### ISSUE TITLE
Finish callback on ESC key should pass skipped as true

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#100]
When leaving the tour via the ESC key, the callback should either pass that it has been skipped, or that it was left via the ESC key.

`{ type: 'finished', steps: [{...}], skipped: true }`

**Comment by gilbarbara** [comment]
ESC only closes the current step, it doesn't end the tour.
But it should dispatch a callback with type `step:after`..

**Comment by gilbarbara** [comment]
I added an `action` property in the callback response. f5b50f776c6dbe19671f2918d6841ae1a53d5371
So you can skip the tour the user presses esc in your app. But I think that skip must be an explicit user action.
