### ISSUE TITLE
Keyboard focus on tour

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#101]
For accessibility, could there be a focus set on the tour when each step comes into view? That way the first tab a user issues would tab them to the next accessible element in the page (next button, close button, etc.). Currently tabbing just tabs you to the next element under the tour.

**Comment by uwolfer** [comment]
Just in case: When this would be implemented, the joyride would also behave a lot better when used in an app which runs inside an iframe. Scrolling does not work there, but when the "next" button is focused, browsers seem to ensure that it is visible in viewport.

**Comment by gilbarbara** [comment]
@sbrigham 
Let's discuss the changes here.

how do you propose to "lock" the keyboard navigation?

**Comment by sbrigham** [comment]
A good explanation of locking focus is found here: https://accessibility.18f.gov/keyboard/ (number 6)

**Comment by sbrigham** [comment]
@gilbarbara The fix in my original PR did fix the issue. It's uses a HOC that wraps tooltip.
It watches for changes on the propery "target", then re-focuses to the "focusTarget" property.

**Comment by sbrigham** [comment]
I can get it working without recompose.

**Comment by sbrigham** [comment]
As far as the allowKeyboardNavigation property, what was the reason this might be the case? 

> Sometimes you don't want the user to close the tooltip with ESC, this won't change and has nothing to do with accessibility.

Doesn't the close button always show?

**Comment by gilbarbara** [comment]
Yes, using the default styles but some users hide it with custom styling. (I'll not judge since I don't know their needs)

And other times you don't to block the users to close it but you don't want it to be so easy, no matter what the "manual" says. I'm not the accessibility police.

**Comment by sbrigham** [comment]
Yeah that's fair. I see your point. 

My original PR got rid of "keyboardNavigation". In solving this issue https://github.com/gilbarbara/react-joyride/issues/101 it seems the right idea to make it not even be an option? Maybe there could be a new bit added called "escClosesTooltip" or something like that?

**Comment by gilbarbara** [comment]
I'm not sure I understood.

Do you mean the `keyboardNavigation` prop? This controls whether the user can use `esc, space bar, return` to advance the tour or close the current tooltip and it's not related to this issue at all.

I could update the name in V2 but I won't remove the functionality. If you have a suggestion for a new name let me know but it shouldn't include "ESC" in it.

You can see the code [here](https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/index.jsx#L781)

**Comment by gilbarbara** [comment]
Yeah, I see your point and I'll have to remove the `keyboardNavigation` prop to have these changes done properly.
However there a couple of gotchas:

I'm in the process of refactoring this module and the Tooltip/Beacon will be handled by another package: [react-tooltips](https://github.com/gilbarbara/react-tooltips). I'll definitely add this behavior to it. Or if you are willing to help there, it will be great.

And I don't want to add new breaking features until that process is finished because the current code is super bloated and easy to break. And I definitely don't have time or disposition to handle changes in both versions right now.

I'm adding this issue to the V2 [feature log](https://github.com/gilbarbara/react-joyride/issues/291)

**Comment by gilbarbara** [comment]
@sbrigham I'm releasing 2.0 soon and I've added a focus manager that hopefully will fix these issues. You can try it with: `npm i react-joyride@next`

**Comment by sbrigham** [comment]
@gilbarbara Awesome. I'll try it out. Thanks!

**Comment by richardaum** [comment]
> @gilbarbara The fix in my original PR did fix the issue. It's uses a HOC that wraps tooltip.
> It watches for changes on the propery "target", then re-focuses to the "focusTarget" property.

Which change are you talking about? I'd like to have it, because I don't need to focus on the tooltip.
