### ISSUE TITLE
Problems with chrome dark mode

### ISSUE THREAD

**Issue by devcer** [gilbarbara/react-joyride#1015]
## 🐛 Bug Report

The arrow color is not aligning with the dark mode.

## To Reproduce

* Open `chrome://flags` in chrome browser
* Enable `Auto Dark Mode for Web Contents` and relaunch your browser
* Open react-joyride website https://react-joyride.com/
* Click on `Start`
* On Step 2 you will see the arrow of the popover in white color
<img width="637" alt="Screenshot 2024-03-26 at 1 19 31 PM" src="https://github.com/gilbarbara/react-joyride/assets/3799600/559166f5-b092-4c44-9f61-4cf6622b3241">

## Expected behavior

The arrow should have been in dark color along with the popover

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.
* You can try this on official website. https://react-joyride.com/

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
Hey @devcer 
I would say it's an issue with their override. Maybe they should consider SVG elements as well. I don't know how they are doing since the tooltip style still uses a white background.
Since the colors are customizable, I don't want to hardcode a selector for this.
