### ISSUE TITLE
Walkthrough Restart [only on mobile -> safari]

### ISSUE THREAD

**Issue by Shivamk99** [gilbarbara/react-joyride#1030]
## 🐛 Bug Report

As the walkthrough gets started, if I scroll in between the walkthrough then It gets re-started even though I have added disableScroll prop. 

## To Reproduce

code:
` <Joyride
        continuous
        run={true}
        steps={steps}
        callback={handleJoyrideCallback}
        disableCloseOnEsc={true}
        disableScrolling={true}
        hideCloseButton
        showSkipButton
        locale={{ last: 'Exit' }}
        spotlightPadding={10 }
        styles={{
          options: {
            zIndex: 10000,
          },
        }}
      />`
      
      
> video:

https://github.com/gilbarbara/react-joyride/assets/50996696/fe589c39-29cf-41c7-872d-e2af179d62b6

## Expected behavior

Then walkthrough should not get re-started when I scroll in between steps.

**Comment by gilbarbara** [comment]
Hey @Shivamk99 

As mentioned in the issue template, the only way to debug it properly is with a reproduction example.

> ## Link to repl or repo (highly encouraged)
> Please provide a https://codesandbox.io/ demo or similar.
> Issues without a reproduction link are likely to stall.
