### ISSUE TITLE
Overlay is not full height

### ISSUE THREAD

**Issue by GabiLlvs** [gilbarbara/react-joyride#1031]
## 🐛 Bug Report

When you zoom I'm having this weird bug where I scroll down and the overlay sets amid the background color and the normal page size
![image](https://github.com/gilbarbara/react-joyride/assets/100242809/aafebe1a-cdd1-4d7e-9516-31007b943661)

## Link to repl or repo (highly encouraged)
This is are my styles:

```tsx
const joyrideStyles = {
	options: {
		zIndex: 10000,
		primaryColor: theme.palette.primary.dark,
		disableScrolling: true,
		textColor: '#1E1E1E',
	},
	buttonNext: {
		backgroundColor: theme.palette.primary.dark,
		color: '#1E1E1E',
	},
	buttonBack: {
		// backgroundColor: theme.palette.warning.dark,
		color: '#1E1E1E',
	},
	overlay: { 
		height: '100vh'
	},
};
```

**Comment by gilbarbara** [comment]
Hey @GabiLlvs 
Can you try v2.8.2 and let me know if it works for you?

**Comment by gilbarbara** [comment]
And remember to remove the `overlay.height` from the styles. 
The height is set dynamically, so it has no effect.

**Comment by gburatti** [comment]
@gilbarbara. I have the same problem, tried with v2.8.2 and overlay.height removed. Still no luck.

@GabiLlvs I had a similar problem caused by my app having body height 100% of viewport and letting the content scroll inside. I managed to solve this by using

```
	overlay: { 
		height: document.body.scrollHeight
	},
```

**Comment by gilbarbara** [comment]
@gburatti 
Having a custom scroll element (in your case, the body) is difficult to support since there are so many ways people can do it.

The [function](https://github.com/gilbarbara/react-joyride/blob/main/src/modules/dom.ts#L22) I use to get the document height includes the `body.height`, so I can't know what's going on with a reproducible example.

**Comment by gilbarbara** [comment]
Hey @mtr1990 

Can you please post a minimal reproducible example on codesandbox or stackblitz?

**Comment by mtr1990** [comment]
Hi @gilbarbara 

You an check : 

https://codesandbox.io/p/devbox/elated-hofstadter-gwjt2g?file=%2Fsrc%2FBasic%2Findex.tsx%3A30%2C14&workspaceId=5ba1f6d5-7206-4894-9388-5f8eabfc1fff

Please check file : `src/Basic/styles.css`

```css
html,
body {
  height: 100%;
}
```

**Comment by Yash-pede** [comment]
> @gilbarbara. I have the same problem, tried with v2.8.2 and overlay.height removed. Still no luck.
> 
> @GabiLlvs I had a similar problem caused by my app having body height 100% of viewport and letting the content scroll inside. I managed to solve this using
> 
> ```
> 	overlay: { 
> 		height: document.body.scrollHeight
> 	},
> ```
> 
> Hope this helps.


I have same problem and the `document.body.scrollHeight` is not working for me nor the [https://github.com/gilbarbara/react-joyride/issues/1031#issuecomment-2130063435](url)
can anybody please help 
![Screenshot_20240527_011524](https://github.com/gilbarbara/react-joyride/assets/116386431/039d31fc-a8f2-4745-ba45-bbc5d810fd6d)

**Comment by gilbarbara** [comment]
Hey @Yash-pede 

Can you please post a minimal reproducible example on stackblitz or codesandbox?

**Comment by zhuhang-jasper** [comment]
Im having this problem too. Im not using any custom scollbar, yet the overlay height is not taking the whole page when scroll.

**Comment by pj-reversebits** [comment]
I'm experiencing a similar issue where the element does not consistently stick to the target, and its height does not fit the screen. As a result, both horizontal and vertical scrollbars appear.

<Joyride
        callback={handleCallback}
        disableOverlayClose
        disableCloseOnEsc
        continuous
        run={run}
        stepIndex={stepIndex}
        steps={steps}
        scrollDuration={500}
        spotlightPadding={5}
      />
      
      
Using inbuilt tooltipComponent of the library still gets the issue. Also I debug about the css, no any CSS is overriding or affecting this.


@gilbarbara please open this issue

**Comment by gilbarbara** [comment]
Hey @pj-reversebits 

This seems like a different problem.
Please open a new issue with a minimal reproducible example.

**Comment by pkalani1999** [comment]
> @gilbarbara. I have the same problem, tried with v2.8.2 and overlay.height removed. Still no luck.
> 
> @GabiLlvs I had a similar problem caused by my app having body height 100% of viewport and letting the content scroll inside. I managed to solve this using
> 
> ```
> 	overlay: { 
> 		height: document.body.scrollHeight
> 	},
> ```
> 
> Hope this helps.

this is very helpfull thanks ☺️
