### ISSUE TITLE
Not working in the production mode. 

### ISSUE THREAD

**Issue by yashnerkar** [gilbarbara/react-joyride#1038]
## 🐛 Bug Report

In production, the React Joyride tour is not functioning correctly, causing the following error: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')`.

## To Reproduce

1. Implement a tour using React Joyride in a separate `tour.tsx` component.
2. Import and use the `tour.tsx` component in other components as needed.
3. Build the application for production.
4. Deploy and run the production build.

## Expected behavior

The React Joyride tour should function as expected in production, similar to its behavior in the development environment, without throwing any errors.

## Link to repl or repo (highly encouraged)
Locally Build - 
[Loom video](https://www.loom.com/share/509515a8dfd643169eef9c08b1fa5150)

**Comment by gilbarbara** [comment]
Are you using next.js?
Try adding a [`use client`](https://nextjs.org/docs/app/building-your-application/rendering/client-components) in your tour component before all the imports.
Or setting [`swcMinify: false`](https://nextjs.org/docs/architecture/nextjs-compiler#minification) to your next.js config.

**Comment by yashnerkar** [comment]
Thanks @gilbarbara ! It worked well.
