### ISSUE TITLE
esc key issue

### ISSUE THREAD

**Issue by haoweih** [gilbarbara/react-joyride#104]
is it possible to switch the keyboard event handler to use keyup instead of keydown?

react bootstrap is using keyup for closing its modal with esc key.

When used with joyride (and configured esc to stop joyride), the esc keypress used to stop joyride will also close the next modal being opened. 

a e.stopPropagation is also needed in joyride's onKeyboardNavigation() to help this situation.

Thanks

-- update --
It seems keyup is not needed, just need the e.stopPropagation after this line
https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Joyride.jsx#L436

**Comment by gilbarbara** [comment]
hey,

I don't think this approach will work in the current version since I added the keyboard listener on Joyride mount, esc wouldn't work anywhere else as long it is mounted.
Any other ideas?
