### ISSUE TITLE
without joyride__beacon tour open  tour defaulty

### ISSUE THREAD

**Issue by tayloraucoin** [gilbarbara/react-joyride#1041]
### Discussed in https://github.com/gilbarbara/react-joyride/discussions/1006

<div type='discussions-op-text'>

<sup>Originally posted by **Manoj-1024** February 26, 2024</sup>
can anyone help me out!  joyride__beacon should not be there direct open dialog</div>

`autoStart` no longer available and is essential for UX requirements.

Thank you for your contributions!

**Comment by gilbarbara** [comment]
Let's continue in the discussion, there's no need to open an issue.
