### ISSUE TITLE
Tooltip drop-shadow not working in edge browser and IE

### ISSUE THREAD

**Issue by Nic128** [gilbarbara/react-joyride#105]
These line do not render in edge and IE.

````
-webkit-filter: drop-shadow(-1px -2px 3px rgba(0, 0, 0, 0.3)) drop-shadow(1px 2px 3px rgba(0, 0, 0, 0.3));
filter: drop-shadow(-1px -2px 3px rgba(0, 0, 0, 0.3)) drop-shadow(1px 2px 3px rgba(0, 0, 0, 0.3));
````

I am trying to find alternatives, but box-shadow only applies to the tooltip rectangle and not the arrow. Tried applying a border, no luck either. It's very hard to edit the arrow svg.

**Comment by gilbarbara** [comment]
I couldn't find a way to add a proper shadow to IE.
If have any ideas reopen this. Thanks
