### ISSUE TITLE
Optional type of `run` prop instead of required

### ISSUE THREAD

**Issue by stud-mai** [gilbarbara/react-joyride#1060]
## 🐛 Bug Report

It is written in file of types' definitions that `run` property has default values. In [documentation](https://docs.react-joyride.com/props) it is said that the only required prop is `step`
https://github.com/gilbarbara/react-joyride/blob/c6c7bd7b4a6f68e8ba009083d825673b47196cb2/src/types/components.ts#L179

## Expected behavior

`run` prop should be optional https://github.com/gilbarbara/react-joyride/blob/c6c7bd7b4a6f68e8ba009083d825673b47196cb2/src/types/components.ts#L181

**Comment by gilbarbara** [comment]
Fixed in 2.9.0

Thanks
