### ISSUE TITLE
hideCloseButton property is not working

### ISSUE THREAD

**Issue by stoefln** [gilbarbara/react-joyride#1073]
## 🐛 Bug Report

If I set hideCloseButton={true}, the closeButton is still visible.
I tried to set it in the step, but also as part of the react props. It doesn't show any effect.
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/709f2da2-513e-4808-a6fe-2d39e8c93716">

## To Reproduce

Just set hideCloseButton={true} on the joyride component

## Expected behavior

The "Close" button should be hidden

## Link to repl or repo (highly encouraged)

[Codesandbox](https://codesandbox.io/p/devbox/sharp-ritchie-mvy74j?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0gdos8j00073b6kjl9tzu8z%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0gdos8j00023b6k3x4g95vc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0gdos8j00043b6k0hp976ww%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0gdos8j00063b6kwgxidpl8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0gdos8j00023b6k3x4g95vc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0gdos8j00013b6k04vbwaux%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0gdsq3m00373b6kpnmn2t3b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A51%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A51%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FBasic%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0gdos8j00023b6k3x4g95vc%2522%252C%2522activeTabId%2522%253A%2522cm0gdsq3m00373b6kpnmn2t3b%2522%257D%252C%2522cm0gdos8j00063b6kwgxidpl8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0gdos8j00053b6kv2kwikjk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm0gdos8j00063b6kwgxidpl8%2522%252C%2522activeTabId%2522%253A%2522cm0gdos8j00053b6kv2kwikjk%2522%257D%252C%2522cm0gdos8j00043b6k0hp976ww%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0gdos8j00033b6k5kolmr1s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522cm0gdos8j00043b6k0hp976ww%2522%252C%2522activeTabId%2522%253A%2522cm0gdos8j00033b6k5kolmr1s%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by gilbarbara** [comment]
Hey @stoefln 

This prop is for the "X" button in the top right.
The only way to remove the primary button is by using a custom tooltip.
