### ISSUE TITLE
Tooltip not focused after build but focused in dev mode

### ISSUE THREAD

**Issue by rickerp** [gilbarbara/react-joyride#1076]
## 🐛 Bug Report
I'm having an issue when my application is built (`next build`) that the tooltip in the joyride isn't focused (check image below):
<img width="337" alt="image" src="https://github.com/user-attachments/assets/cdc0f008-c945-4e65-83a8-027981ae4598">
But when running the application in dev (via `next dev`) it is showing correctly (focused):
<img width="337" alt="image" src="https://github.com/user-attachments/assets/db499ee1-b931-4ef8-b073-0bda1b6512a9">

### Code
This is the joyride usage (sorry atm I cannot give more code details):

```
<div ref={setContainerEl} className={classes.container}>
      ...
      {runTour && (
        <Joyride
          steps={tourSteps}
          callback={handleJoyrideCallback}
          continuous
          showProgress
          showSkipButton
          styles={{
            options: {
              arrowColor:
                theme.palette.type === 'dark'
                  ? theme.palette.primary.main
                  : theme.palette.primary.dark,
              primaryColor:
                theme.palette.type === 'dark'
                  ? theme.palette.primary.main
                  : theme.palette.primary.dark,
              backgroundColor: theme.palette.text.primary,
              textColor: theme.palette.background.paper,
            },
          }}
        />
      )}
    </div>
```
Here is the next configuration:
```
/** @type {import("next").NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  output: 'standalone',
  env: {
  ...
  },
};

module.exports = nextConfig;
```

**Comment by gilbarbara** [comment]
Hey @rickerp 

As mentioned in the issue template, `Issues without a reproduction link are likely to stall.`.

Anyway, I'm not sure what you mean by "focused". Are you talking about the buttons in the footer?
The second image looks like the tooltip is dimmed, which isn't how it's supposed to work.

**Comment by rickerp** [comment]
Hey @gilbarbara 

Sorry, I switched the images (it's fixed now). In the first image, the tooltip is _unfocused_ which means I can't click on it or in the next and skip buttons because only the target element is focused. The second image is how it was supposed to be.

PS: I still couldn't do a minimal reproducible app with this issue. I will share it eventually if I can.

**Comment by gilbarbara** [comment]
Hey @rickerp 
Since many users use the library with next.js and have never reported this problem, I think this might be an implementation problem rather than something with the library.
Inspect the markup to see what's in front of the tooltip and blocking the clicks. Try changing the zIndex.
