### ISSUE TITLE
step.showProgress does not show progress

### ISSUE THREAD

**Issue by EliasVal** [gilbarbara/react-joyride#1079]
## 🐛 Bug Report

After `2.9.0`, and setting each step's `showProgress` to `true`, the progress still does not show.

## To Reproduce

Upgrade the package to `2.9.0` or later, set `showProgress` to true for the steps, and run the joyride.

## Expected behavior

For the `next` button to show the progress of the current joyride.

## Link to repl or repo

This is even reproduced in the docs page.

## Current workaround

`Array.map()` the steps of your joyride, setting the `step.locale.next` to include the `index + 1` and the length of your steps array.

**Comment by gilbarbara** [comment]
Hey @EliasVal 

Fixed in v2.9.2
