### ISSUE TITLE
beacon offsetX config not include in downloaded sourcecode

### ISSUE THREAD

**Issue by Yogi-Jiang** [gilbarbara/react-joyride#108]
Hi, I download version 1.4.7, found that the source code not include the offsetX when calculating the plament.x.How can I fixed it ?
![2016-08-09 9 57 26](https://cloud.githubusercontent.com/assets/10647827/17502190/7ae9fe2a-5e18-11e6-9fc7-489597b449a5.png)
PS:
It seems that the package.json file didn't include the npm package nested-property that help calculating the offsetX

**Comment by gilbarbara** [comment]
Please try version 1.4.8 and reopen this issue if it's not fixed.
Thanks
