### ISSUE TITLE
Calling handlers.next() does not immediately block spotlight interaction on current step

### ISSUE THREAD

**Issue by davidshumway** [gilbarbara/react-joyride#1083]
## 🐛 Bug Report

Calling handlers.next() does not block double-clicking on spotlight. Calling handlers.next() should immediately block spotlight interaction on current step.

## To Reproduce

Create a button and put it in the spotlight. On button click, call handlers.next() to move the spotlight to the next step. Add another div elsewhere, such that the spotlight moves to somewhere besides the button. Double-click the button and notice that the spotlight allows for multiple clicks on the button before the tour moves to the next step.

As an aside, the prop `scrollDuration` does not affect this issue, i.e., setting `scrollDuration={0}` does not change the identified spotlight behavior.

## Expected behavior

After a single call to handlers.next(), the spotlight for the current (now last) step should be deactivated. Further clicks and other interaction (mouseover, mouseout) should not be passed to elements in the spotlight. At present, there is a short delay where it's possible to continue interacting with elements in the (closing) spotlight.

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash

System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) [--] CPU @ 2.30GHz
    Memory: [--] GB / [--] GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.20.4 - /usr/bin/node
    npm: 10.7.0 - /usr/bin/npm
  npmPackages:
    react-joyride: ^2.9.2 => 2.9.2

```

**Comment by gilbarbara** [comment]
Hey @davidshumway 

The library isn't aware of what's showing or happening in the elements in the spotlight.
You can disable your button after the first click.
