### ISSUE TITLE
overlay must mouse over to render

### ISSUE THREAD

**Issue by vhphuc0240** [gilbarbara/react-joyride#1088]
## 🐛 Bug Report

Hi, i use this library to create a guide on my react app. But when the component change, the guide tour does not work. I must mouse over to change the overlay. This is the video to see example: https://go.screenpal.com/watch/cZQTfmVSafJ 

## To Reproduce
thIs is code i use to setup with GuideTourContent component is my custom component :
<Joyride
      steps={guideSteps.map(step => ({
        disableBeacon: true,
        hideFooter: true,
        ...step,
        content: (
          <GuideTourContent
            {...{
              ...step,
              isControlledGuide,
              currentStep: stepIndex,
              totalSteps: totalStep || guideSteps.length,
              onNext: () => setStepIndex(prev => prev + 1),
              onBack: () => setStepIndex(prev => prev - 1),
              onSkip: () => setRun(false)
            }}
          />
        )
      }))}
      callback={handleJoyrideCallback}
      continuous={false}
      debug
      run={run}
      showProgress
      scrollOffset={200}
      scrollDuration={0}
      stepIndex={stepIndex}
      spotlightPadding={0}
      disableOverlayClose
      disableCloseOnEsc
      disableScrollParentFix
      styles={{
        options: {
          zIndex: 100
        },
        buttonClose: {
          display: 'none'
        },
        tooltip: {
          padding: 0,
          borderRadius: 16
        },
        tooltipContainer: {
          textAlign: 'unset'
        },
        tooltipContent: {
          padding: 0
        },
        spotlight: {
          borderRadius: 8
        },
        overlay: {
          height: document.getElementById('app').offsetHeight
        }
      }}
    />

## Expected behavior

overlay show right away i change the content of target element

## version
3.0.0-4
## Repo
https://codesandbox.io/p/sandbox/6tnnh8

**Comment by vhphuc0240** [comment]
@gilbarbara i already use floaterProps: { eventDelay: 0 } but it does not work

**Comment by gilbarbara** [comment]
Hey @vhphuc0240 

First of all, version 3 isn't ready to use. Use 2.9.2 instead.

The spotlight is only calculated when the step is mounted, so if you change the dimensions of it while the step is showing, you could probably send a resize event to update it.

`window.dispatchEvent(new Event("resize"));`

**Comment by vhphuc0240** [comment]
@gilbarbara Thanks for reply. How to "send a resize event to update it" as you mention. Can you give me some example for it?

**Comment by gilbarbara** [comment]
Do you have a listener for the radio buttons onChange?
Use the dispatchEvent code inside the listener. If you have the `run` prop in the component, check if it is running before executing the code.
