### ISSUE TITLE
Test timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by arbersokoli** [gilbarbara/react-joyride#1089]
## 🐛 Bug Report

Getting the following error:
4) [webkit] › standard.spec.tsx:22:5 › should run the tour ───────────────────────────────────────

    Test timeout of 10000ms exceeded.

    Error: Screenshot comparison failed:

      Test timeout of 10000ms exceeded.

## To Reproduce

npm run e2e

## Expected behavior

The timeout needs to be increase from 10 * 1000 to 20 * 1000 for slower computers. It works for me with 20 * 1000.

**Comment by gilbarbara** [comment]
Hey @arbersokoli 

This isn't a bug with the library, just the development environment.
You can change it locally and ignore it.
