### ISSUE TITLE
Error when adding an element dynamically

### ISSUE THREAD

**Issue by tomascharad** [gilbarbara/react-joyride#109]
If an element of the joyride selectos is added after Joyride has started. At the moment of adding it I receive an error.

For example, if you have an element that has not been created when the Joyride started, if the user performs an action that makes the element to be displayed again. Then the error is thrown.

```
Joyride.js:43 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

<img width="752" alt="screen shot 2016-08-10 at 4 15 43 pm" src="https://cloud.githubusercontent.com/assets/1534092/17569410/0bfce4e2-5f16-11e6-9938-9f4249ae8b58.png">

I have debugged, and the variable `el` is `".joyride-tooltip"`.

Is there any quick workaround that you can think about? 

UPDATE:

Ok I just seen this: 

> Only start the tour after all target elements (or at least the first step) are rendered in the page.

How can I handle this situation?

**Comment by friendOfOurs** [comment]
I had a similiar issue and solved it by adding the step for the initially non-existant element dynamically only **after** the element has been created (or displayed in my case). I keep the steps in state and in the callback of `setState` I perform check if new steps have been added and reset/start joyride accordingly.  Works pretty well :)

**Comment by gilbarbara** [comment]
I think it's fixed now.
