### ISSUE TITLE
Overlay flickering on delayed setStepIndex due to being unmounted

### ISSUE THREAD

**Issue by marcus-wishes** [gilbarbara/react-joyride#1091]
## Overlay Flickering on Delayed setStepIndex
During the tour I mount a complex modal component for one step in a controlled joyride instance.
I use a state to set the component to be mounted in the *step:before* type callback. When I immedietly update the stepIndex the new step does not find the target, as the component did not mount yet. 

```ts
// doesn't work, the step doesn't find the right target (it works with simple components, like a button in my example below)
if (type === "step:after") {
    setComponentVisible(true);
    setStepIndex(prev => prev+1);
}
```
So I use flushSync to ensure that the modal with the complex content it mounted. I cannot do this during rendering, therefore I add a setTimeout - but the unmounting of the overlay results in a flickering:
```ts
// does work, but flickers
if (type === "step:after") {
    setComponentVisible(true);
    setStepIndex(prev => prev+1);
}
```
## Links:

Code sandbox:
https://codesandbox.io/p/sandbox/d7lys7

Here as repo:
https://github.com/marcus-wishes/react-joyride-problem-showcase

## Expected behavior
I would like to avoid the unmounting of the overlay between the steps which causes the flickering.

This works if in the *hideSpotlight()*-method in the Overlay.tsx does not react on the *LIFECYLCE.INIT* and *LIFECYCLE.COMLPETE* states.

I modified the react-joyride code and added a prop named *keepOverlayMountedBetweenSteps*, which defaults to false, but when set to true, it does not add the *LIFECYLCE.INIT* and *LIFECYCLE.COMLPETE* to the check im **hideSpotlight()** in the *Overlay.tsx*.
I don't know if this would be an acceptable PR or if this is use case if too niche, but it would certainly help in my case.

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash
 System:
    OS: Linux 6.11 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
    Memory: 43.44 GB / 62.60 GB
    Container: Yes
    Shell: 5.2.32 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 20.17.0 - /etc/profiles/per-user/markus/bin/node
    npm: 10.8.2 - /etc/profiles/per-user/markus/bin/npm
  npmPackages:
    react-joyride: ^2.9.2 => 2.9.2 

```

**Comment by gilbarbara** [comment]
Hey @marcus-wishes 

I'm actively working on the new major version, in which I'll change the default to render the Overlay at all times while it's running and only hide with beacons.

I'll change it by the end of the week.
You can try it with the branch `next`, but be advised that more breaking changes are coming.

**Comment by marcus-wishes** [comment]
Hi,
thank you for your quick reply.

I am looking forward to try out the new version. And thank you for your work and support on this package.
