### ISSUE TITLE
Content not rendered when built and deployed

### ISSUE THREAD

**Issue by samirmsallem** [gilbarbara/react-joyride#1092]
## 🐛 Bug Report

The content of the tour stays empty when I build and deploy the application to my staging environment. However, it does work locally without any problems.

## To Reproduce

- Test locally with yarn. Execute yarn run dev while dev being: `"dev": "PORT=8089 cross-env NODE_OPTIONS=--openssl-legacy-provider preact watch" `
- --> Works good
- Build docker image with built application using yarn run stage, while stage being: `"stage": "NODE_ENV=staging cross-env NODE_OPTIONS=--openssl-legacy-provider preact build",`
- Deploy and run. Everything of the application works fine, however joyride tour is displayed with correct steps and buttons but no content is visible

## Expected behavior

Content should be visible since ReactNode is the given type for content.

## Link to repl or repo (highly encouraged)

Unfortunately project is too complex, however here are some screenshots:

<img width="813" alt="image" src="https://github.com/user-attachments/assets/4b29f826-23ff-43ab-a5bc-de2c7157c6b0">
<img width="521" alt="image" src="https://github.com/user-attachments/assets/d9281033-299a-43e1-8834-9fcfc0c07f7a">

Exemplary step definition of my steps array:
`{
    target: 'body',
    placement: 'center',
    content: (<OnboardingDialog heading="Header" text="Content" mode={1} />),
    locale: {
      skip: <strong aria-label="skip">Nein danke</strong>,
      next: 'Ja, unbedingt!',
    },
  },`

--> As you can see in the screenshot, the `<strong>` is not working. This used to work in version 2.8.2, I updated to 2.9.2 to see if it can resolve my error but it brought up this error as well. The issue with `<strong>` is appearing both locally and on staging deployed.

When I am using just plain text and title for content and title like 'Test' it works perfectly fine. It seems that it only has problems rendering/parsing the component. When I directly put the <div> into the content parameter it still does not work on staging. However for local development everything works like a charm. 

Is there a difference between how joyride content is treated between yarn watch and yarn build?

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash
  System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 62.95 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.3.0 - /opt/homebrew/bin/node
    npm: 10.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
  npmPackages:
    react-joyride: ^2.9.2 => 2.9.2 

```

**Comment by gilbarbara** [comment]
Hey @samirmsallem 

It's impossible to debug it without being able to run the code, but since it's working on development, it is most likely a problem within your app.
Also, Preact isn't officially supported, so there is little to do here.

Good luck

**Comment by samirmsallem** [comment]
Hi @gilbarbara, 

thank you for your answer. I understand your viewpoint and also the fact that there is not much to do in regards to preact. 
To whoever who might stumble upon this in the Future: I was able to resolve this issue by creating a customTooltip instead of just passing JSX in the content prop of the step. Then in the CustomTooltip i added my additional content besides`step.content`.
