### ISSUE TITLE
React Joyride skips beacon lifecycle if default stepIndex not 0

### ISSUE THREAD

**Issue by mauserez** [gilbarbara/react-joyride#1095]
When I set continuous=true, run = true and stepIndex!=0.
It start with tooltip lifecycle.
How i can avoid it ?

**Comment by gilbarbara** [comment]
Hey @mauserez 

Are you sure you don't have `disableBeacon` on your first step?

**Comment by mauserez** [comment]
Ofc. Now i create controlled joyride with custom callback.
But i have a situation.

When i use ReactQuery with delay data.
I dont have elements at render.
And cant use stepIndex with non existing element.
Now i use hard useEffect hook with ObserverMutation to tour-data attribute element.

Mb u have a simpliest decision how to detect delayed existing of elements

**Comment by gilbarbara** [comment]
You could control the `run` prop and ensure that you have the data before starting or restarting the tour.
it could be on a hook or the callback.
