### ISSUE TITLE
The spotlight has a position calculation error

### ISSUE THREAD

**Issue by xyyit9** [gilbarbara/react-joyride#1098]
## 🐛 Bug Report

The tooltip can be positioned accurately, but the spotlight position is wrong. The phenomenon is as follows

![image](https://github.com/user-attachments/assets/bd76ec44-41f1-4017-a1d9-497a70de2793)

## To Reproduce

1. In the third step, you can see that the entire document is scrolled.
![img_v3_02g0_883a1185-aa23-40c8-9d5d-fc1a58bf42hu](https://github.com/user-attachments/assets/f1e7630f-cb85-4337-af1f-f3ffaba3db76)

2. In the fourth step, the sidesheet is opened. There is also a scroll bar in the sidesheet, but it does not scroll.
![img_v3_02g0_513143e1-4769-496c-b2ac-f2fc52a3ebhu](https://github.com/user-attachments/assets/b8725dcb-5b38-41f6-a770-ad426db5aa2f)

I debugged the problem and found that it was caused by this line of code.
```
// https://github1s.com/gilbarbara/react-joyride/blob/main/src/modules/dom.ts
export function getElementPosition(element: HTMLElement | null, offset: number, skipFix: boolean): number {
   // ...
    if (!parent.isSameNode(scrollDocument())) {
      top += scrollDocument().scrollTop;
    }
  }

  return Math.floor(top - offset);
}
```
The parent of element is shown in the figure, which satisfies the condition of !parent.isSameNode(scrollDocument()). The scroll of html scrolled in the third step, so scrollTop = 1058.5, which caused the error in the calculation of the final top value.
![img_v3_02g0_16428bfc-8eac-43f8-8e79-0a05ae28adhu](https://github.com/user-attachments/assets/0803f27a-d828-443e-978c-d0046629009f)
![img_v3_02g0_5cb77d5e-c2d6-4a0b-95fe-d2b1bcd77chu](https://github.com/user-attachments/assets/6a7b61c0-27da-41d8-a21f-694b43647e9b)

## Expected behavior

When the ducument scrolls, the spotlight position is calculated correctly

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
Hey @xyyit9 

I need a minimal reproducible example to see the error and understand what is happening.
Or you can submit a PR with a fix.

**Comment by xyyit9** [comment]
Hello~ @gilbarbara  Hello, I'm glad to hear from you.Thanks again for providing a useful package.  I'm sorry that I didn't give an example before. Now I wrote an example to show such a scenario. Looking forward to your reply~   https://codesandbox.io/p/devbox/dry-sunset-cz9y6v

**Comment by xyyit9** [comment]
@gilbarbara  Hello, I am a newbie on GitHub, I want to confirm, have you seen the example I wrote? I am not sure if you have received the message, because the issue still shows need example, I don't know how to remove this label. Looking forward to your reply😄   my example： https://codesandbox.io/p/devbox/dry-sunset-cz9y6v

**Comment by andrei8788** [comment]
I have the same issue. Is there a quick fix, perhaps?

**Comment by andrei8788** [comment]
I noticed that I get this bug with fixed elements on the page, such as the header and sidebar, when the scroll is not at the very top position

**Comment by andrei8788** [comment]
Solved this issue by using scroll to top in callback handler

**Comment by andrei8788** [comment]
I would also like to add that in my case the comment above solved the problem without blocking the scroll (overflow: 'hidden' for body). After blocking the scroll everything worked just as well.

**Comment by xyyit9** [comment]
@andrei8788 Hello, may I ask about your method for more detail? Are you setting document.scrollingElement.scrollTop = 0 in the callback? If you could provide some examples code, that would be even better.

**Comment by andrei8788** [comment]
My case is a bit unconventional. I need to jointly control the state of not only joyride steps (there is an additional modal display), but also automatically skip joyride steps if any element is missing. 
For steps other than target and content, I have set the settings:
```
{ 
   ...,
   placement: 'auto',
   disableScrolling: true,
   disableBeacon: true,
}
```
When using joyride steps and locking scrolling, I additionally use the logic in useEffect, where I look for the desired element and if it is present, I do 
```
setTimeout(() => {
     element.scrollIntoView({ behavior: 'smooth', block: 'center' })
})
```
If not, I move on to the next or prev step.
Accordingly, I keep the target and index values in the state, scrollTop is not used.  This works well for me. 

Before scroll locking, I had to use scrollTop = 0 logic for fixed elements that were always in the visible area.

**Comment by andrei8788** [comment]
@xyyit9 
My solution won't work for you. I've looked at your code. As far as I know, Joyride calculates the scroll position relative to the body. You have a separate Drawer that has internal scroll content. Joyride probably does not support this. I apologize if I misled you. Did not fully understand your situation.
Perhaps you can help in some way @gilbarbara.

**Comment by xyyit9** [comment]
@andrei8788 Thank you very much for your solution. It really gave me some ideas. I also tried to solve my problem in your way, but I found that my scenario was more complicated and it was really impossible to solve it.
 I am still troubled by this problem recently. What's more unfortunate is that I also found new problems at the same time. Although I disabled all scroll configurations, unexpected scrolling still occurred on the document. These problems are really difficult for me to solve. @gilbarbara Can you help me look at these problems? Thank you very much

**Comment by gilbarbara** [comment]
Hey @xyyit9 
Can you try this updated package before I merge the changes?

`npm i https://pkg.csb.dev/gilbarbara/react-joyride/commit/d709f73b/react-joyride`
Or whatever package manager you use...

**Comment by xyyit9** [comment]
hi @gilbarbara I am glad to get your reply. But after I tried your commit, I found some new errors.😭 There was no problem when I used 2.9.2. So your commit cannot be merged into master yet，which may introduce new problems.
The phenomenon of 2.9.2.
the phenomenon of commit.

**Comment by gilbarbara** [comment]
Hey @xyyit9 
So, is it a problem in the sidesheet again? Are there other problems?
Do you have steps outside the sidesheet, and are they working correctly?
Please update your example to include all the problems, and I'll take a look.

**Comment by xyyit9** [comment]
@gilbarbara 
1. It's a problem in the sidesheet. But it works well in version 2.9.2. 
2. yes，I have steps outside the sidesheet, they are working correctly.
 I will provide you with a complete example after I finish my urgent work.
In addition, I have another question, why is document.documentElement still scrolling after setting {disableScrollParentFix: true} and setting document.documentElement.scrollTop = 0; in the callback? Which method does the scrolling?

**Comment by gilbarbara** [comment]
You probably want the `disableScrolling` prop in the `step`.
The `disableScrollParentFix` prop just tries to handle bad styling, such as the content being taller than the body.

The callback is usually called after everything has happened, and you can't change the internal behavior. So, setting the scrollTop doesn't have the desired effect.

**Comment by xyyit9** [comment]
@gilbarbara  I want full control over the scrolling, but I find that it still scrolls unexpectedly. Do you have any idea which method does the scrolling? This will help me tremendously.
![image](https://github.com/user-attachments/assets/cb8f3fba-37cf-45b4-9b89-9e210477af27)
![image](https://github.com/user-attachments/assets/02cc9628-e850-4396-b02b-b5e55b789789)


My code is as follows:
1. Joyride props
```
<Joyride
        disableScrolling
        disableScrollParentFix
        scrollToFirstStep={false}
        disableCloseOnEsc
        disableOverlayClose
         // ....
/>
```
2. callback
```
  const handleJoyrideCallback = async (data: CustomCallBackProps): Promise<void> => {
       // ....
      document.documentElement.scrollTop = 0;
      if(finishedStatuses.includes(status)){
          //...
      }else if (element && action === ACTIONS.START && (type === EVENTS.TOUR_START || type === EVENTS.TOUR_STATUS)) {
      const isVisible = isInViewport(element);
      if (!isVisible) {
        const parent = scrollParent(element);
        if (parent) {
          const offsetTop = element?.offsetTop - parent?.offsetTop;
          parent?.scrollTo({
            top: offsetTop,
            behavior: 'smooth',
          });
        }
        const time = 500;
        await new Promise<void>((resolve, reject) => {
          setTimeout(() => {
            console.log(`callback START TOUR_START 等待了${time}ms`);
            resolve();
          }, time);
        });

        setRun(true);
      }
    }

**Comment by xyyit9** [comment]
> You probably want the [disableScrolling](https://docs.react-joyride.com/step) prop in the `step`. The `disableScrollParentFix` prop just tries to handle bad styling, such as the content being taller than the body.
> 
> The callback is usually called after everything has happened, and you can't change the internal behavior. So, setting the scrollTop doesn't have the desired effect.

@gilbarbara  I have also disabledScrolling for each step. Can you tell me which function inside scorll the document.scrollElment?

**Comment by gilbarbara** [comment]
Sure, it's the `scrollTo` in the modules/dom.ts

**Comment by gilbarbara** [comment]
However, there are some caveats. 
Even with `disableScrolling`, if the target is outside the viewport, the browser will "scroll" to it as the beacon/tooltip gains focus.

**Comment by gilbarbara** [comment]
@xyyit9 

Please try using this version and tell me if it makes any difference.
`npm i https://pkg.csb.dev/gilbarbara/react-joyride/commit/4d7dde80/react-joyride`

**Comment by xyyit9** [comment]
@gilbarbara 
Good news! It works! The document has no scroll. The bad news is that the spotlight calculation is wrong. No matter parentScroll is set or not, the position will be calculated incorrectly.
![image](https://github.com/user-attachments/assets/04d870c9-6ba7-4dc3-a62c-0fb0288da769)

**Comment by xyyit9** [comment]
@gilbarbara  Oh sorry, I made a mistake, this commit is correct https://pkg.csb.dev/gilbarbara/react-joyride/commit/4d7dde80/react-joyride. 
I still used the previous commit https://pkg.csb.dev/gilbarbara/react-joyride/commit/d709f73b/react-joyride, and I found that removing the previous commit, the position calculation is correct.

Due to my local environment, I can only pull the code locally and use the built dist file, so I just mistakenly brought the previous commit

**Comment by xyyit9** [comment]
@gilbarbara hi， I verified again today that this commit can solve my all scroll problem. https://pkg.csb.dev/gilbarbara/react-joyride/commit/4d7dde80/react-joyride
And because I se've set document.documentElement.scrollTop = 0;  so when in the sidesheet, the position  of spotlight calculation is also right. 
Thank you so much!!   and when you merge it into master and release a new version. let me know that~

**Comment by xyyit9** [comment]
@gilbarbara Hi~ Can you merge it into master and release another version this week? Thank you very much for your help

**Comment by xyyit9** [comment]
@gilbarbara hello~  Our requirements cannot be put online now. This matter is very urgent. Can you release a test package version that only includes this commit https://github.com/gilbarbara/react-joyride/commit/4d7dde80307531efb56981554ea67a2a84da949a?   thank you very much

**Comment by gilbarbara** [comment]
Released as [2.9.3](https://github.com/gilbarbara/react-joyride/releases/tag/v2.9.3)
Thanks

**Comment by gilbarbara** [comment]
Hey @xyyit9 
I can't. The release is for every library user, not just for you.
The last test version I sent you contained both commits and you said it was ok.

Anyway, have you tried [this](https://github.com/gilbarbara/react-joyride/discussions/1051#discussioncomment-10036055)?

**Comment by xyyit9** [comment]
@gilbarbara

**Comment by xyyit9** [comment]
@gilbarbara hi~ In my previous verification, I replied that https://github.com/gilbarbara/react-joyride/commit/d709f73bd7708fe4f8a47c3d665247ba77283db8 will cause other errors instead. So only this commit https://github.com/gilbarbara/react-joyride/commit/4d7dde80307531efb56981554ea67a2a84da949a can be merged.
I understand that this package is not just for me, but if the verification is not OK in my scenario, it will also be a problem in other people's scenarios.
I just hope that npm can fix the bug and become better.
![image](https://github.com/user-attachments/assets/74cf585e-5850-41a2-a641-735df7338ce3)

**Comment by gilbarbara** [comment]
Hey @xyyit9 

The library worked well for everyone, just not for your case. This [pkg.csb.dev/gilbarbara/react-joyride/commit/4d7dde80/react-joyride](https://pkg.csb.dev/gilbarbara/react-joyride/commit/4d7dde80/react-joyride) includes both commits. I thought the second build, including the previous commit, fixed the problem...

Did you try the fix I mentioned?

**Comment by xyyit9** [comment]
@gilbarbara  I‘m sorry for the misunderstanding. 
1. I was just worried that you misunderstood my verification results and might affect other people's use. Now I hear that other people are working well, that's great!  I will carefully identify the problem in my case.
2. I tried the fix you mentioned, but it didn't help.

**Comment by gilbarbara** [comment]
@xyyit9 
Are you disabling the scroll? At the component level or individual steps?
If you are, does it still try to scroll?
I'm trying to replicate a similar scenario in the demo, but it appears to work.

**Comment by mostafamohamedaly** [comment]
@gilbarbara Hello, I do believe I have the same issue as @xyyit9, but with react-bootstrap modals. The issue got introduced for me in the newer version (2.9.3). The spotlight is not aligned with the target at all if disableScrollParentFix={true} if disableScrollParentFix={false} its fine, but I want it to be true so I don't lock the page scrolling.

![Screenshot 2024-11-24 171427](https://github.com/user-attachments/assets/a8d28aad-31e0-4dc9-9f3e-300d3ad6c197)
