### ISSUE TITLE
Is there a react-joyride.d.ts file?

### ISSUE THREAD

**Issue by subashbhujel** [gilbarbara/react-joyride#110]
https://github.com/DefinitelyTyped/DefinitelyTyped doesn't have it. :(

**Comment by gilbarbara** [comment]
Not yet. I'm planning a new version (2.0) that will have a solid api and I'll definitely make a definition file.

**Comment by subashbhujel** [comment]
Thanks @gilbarbara for a quick response. Any ETA on when can we expect 2.0? 
*excited*

**Comment by Mosho1** [comment]
Someone seems to have made one, available through @types

**Comment by gilbarbara** [comment]
@Mosho1 I couldn't find it.

**Comment by Mosho1** [comment]
https://www.npmjs.com/package/@types/react-joyride
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-joyride
