### ISSUE TITLE
When the page has a scroll bar, the spotlight position is calculated incorrectly

### ISSUE THREAD

**Issue by codingLeee** [gilbarbara/react-joyride#1105]
![image](https://github.com/user-attachments/assets/1a2751ee-dfaf-45ca-88a0-c85f89dd92f8)
![image](https://github.com/user-attachments/assets/aca3ef09-b264-4741-bc31-6b18b07ff7d3)

sandbox：https://codesandbox.io/p/sandbox/flamboyant-david-ykxtny?workspaceId=a12641fd-00e9-4601-8b94-f23ecb706115

**Comment by gilbarbara** [comment]
Hey @codingLeee 
Do you mean horizontal scroll?
Yeah, it's not supported.

**Comment by codingLeee** [comment]
> Hey @codingLeee Do you mean horizontal scroll? Yeah, it's not supported.

OK, thanks
