### ISSUE TITLE
Incompatibilité avec react-dom et Next.js 15

### ISSUE THREAD

**Issue by safiatou78** [gilbarbara/react-joyride#1108]
Je rencontre une erreur avec `react-joyride` version 2.9.2 sur Next.js 15 et React 18. L'erreur se produit lors de la tentative de compilation avec le message suivant :
Cela est dû au fait que `react-dom` a supprimé certaines méthodes, comme `unmountComponentAtNode` et `unstable_renderSubtreeIntoContainer`, dans ses dernières versions.

J'ai essayé d'installer `react-joyride` avec la version la plus récente, mais le problème persiste.

**Comment by gilbarbara** [comment]
Salut @safiatou78 

Voulez-vous dire React 19? Vous pouvez essayer la version @next

`npm i react-joyride@next`

**Comment by Gherdty** [comment]
Merci beaucoup! This worked for me 👍 Nice work
