### ISSUE TITLE
`@gilbarbara/types` dependency missing from `next`

### ISSUE THREAD

**Issue by aaron-hutton** [gilbarbara/react-joyride#1109]
## 🐛 Bug Report

A `devDependency` on `@gilbarbara/types` was added in the `next` version. This breaks the types as they depend on it, but the package is not installed by default as it's a `devDependency` not a full `dependency`.

A temporary workaround is to directly install the types package.

## To Reproduce

Use typescript with `next` version

## Expected behavior

The types package needs to be promoted to a full dependency or needs to be removed by the bundler (somehow).

**Comment by gilbarbara** [comment]
Hey @aaron-hutton 

Fixed in 3.0.0-7
Thanks
