### ISSUE TITLE
How to hide tooltip?

### ISSUE THREAD

**Issue by namratanakhale** [gilbarbara/react-joyride#1110]
## How to hide tooltip?

For some step i want to hide tooltip and just want to highlight along with onclick is it possible?

**Comment by gilbarbara** [comment]
Hey @namratanakhale 

It's not possible.
The whole idea behind this library is to highlight and explain features sequentially.
How would you navigate if you don't have a tooltip (and a button to go next)?

However, you could use a controlled tour with the `run` and `stepIndex` props. This would stop the tour before the tooltip is shown and restart it when the user clicks something in the app.
Check the [Controlled example](https://codesandbox.io/p/devbox/github/gilbarbara/react-joyride-demo?file=%2Fsrc%2FControlled%2Findex.tsx) for more information.
