### ISSUE TITLE
joyride:parseSteps

### ISSUE THREAD

**Issue by jjordy** [gilbarbara/react-joyride#116]
Hey man love the library. Its working really well for me. I was wondering if its possible to supress your warning for the target not being mounted. This is pretty helpful most of the time but when i run my test it goes nuts because i mostly use shallow rendering so im not actually mounting child components. Im sure there is a way for me to suppress this in phantom or karma but i wanted to see if you had intended to have it targeted by the debug flag as well.

Thanks,

Jordy

**Comment by gilbarbara** [comment]
Done! 👍

**Comment by nicmesan** [comment]
@jjordy I am trying to test my component using shallow rendering, but it's not possible since I cannot use ref method inside Joyride component and thus not able to call `this.joyride.parseSteps`. How were you able to achieve this?

Thanks in advance!

**Comment by IanVS** [comment]
As of version 1.8.0, it's no longer necessary to parse steps before providing them to joyride!  :-D  Try to just pass them in directly.
