### ISSUE TITLE
Potential README documentation typo

### ISSUE THREAD

**Issue by mrsteele** [gilbarbara/react-joyride#117]
The API discusses `this.refs.addTooltip(data)`, however I believe it is supposed to be `this.refs.joyride.addTooltip(data)` like the others.

I'm creating a pull request as well to fix / better explain where the issue exists.

**Comment by gilbarbara** [comment]
Removed string refs.
Fixed in d833b6ddf531c81072ca0346f1ddb28558ad5447

Thanks
