### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by lightninglu10** [gilbarbara/react-joyride#119]
Does this have an autostart feature? On page load, automatically start the tour without having to hover/click the beacon?

**Comment by gilbarbara** [comment]
Yeah. When you call `..joyride.start()` you can pass a boolean to starts the tour with the first tooltip opened.

**Comment by lightninglu10** [comment]
I tried this but it doesn't work.

Do you mean if I call `..joyride.start(true)` then it on page load, the tour will start without me touching anything?

**Comment by lightninglu10** [comment]
Oops just kidding, this works.

**Comment by AviRoy1988** [comment]
Where to put this block of code (joyride.start()) to start the tour automatically

**Comment by gilbarbara** [comment]
Hey @AviRoy1988 
this issue is 4 years old...
Check the [docs](https://docs.react-joyride.com/) for the current version
