### ISSUE TITLE
Page reloads on tooltip click

### ISSUE THREAD

**Issue by johanneserber** [gilbarbara/react-joyride#120]
Hi,

I am using react-joyride in an application with hash history. Now because the tooltip buttons are using an a tag with href=# the page reloads when you click on next step or any other link.

Am I missing something that prevents the page from reloading?

Why did you choose <a> tags instead of <span> tags for the links? Maybe this could be changed to prevent the issue?

Thanks in advance,
Johannes

**Comment by gilbarbara** [comment]
hey,
You are the first person with this problem.. Maybe something is hijacking document clicks? the click handlers call `preventDefault` and `stopPropagation`...

I'm sure what you mean by tags..

**Comment by johanneserber** [comment]
Thanks for your answer. 

I meant a tags and span tags. (Should not have used html markup in the comment.) Span tags will resolve this problem of native browser behaviour (no prevent default needed), you only need some CSS to have a pointer cursor. But there might be other reasons why you chose a over span.

Anyway, if nobody else has this problem it might not be necessary to change it. Will check where else the problem can come from.

**Comment by erwan** [comment]
Hi,

I'm having a similar issue in an application with a router catching event very early (at the capture phase on the `body`). So indeed hijacking document click, however being a router it will only act and stop events that appear to be navigation-related (hence the `a` tags).

Is there any chance you would accept a pull request that replaces `<a href="#"` by a simple `<span>` tag? Is there any reason why keeping an `a` tag is important?

**Comment by erwan** [comment]
I have it ready in a branch BTW: https://github.com/erwan/react-joyride/tree/nohref
