### ISSUE TITLE
Is it possible to start at a particular step in the list of steps?

### ISSUE THREAD

**Issue by vning93** [gilbarbara/react-joyride#127]
For example...

```
const steps = [{a: 1}, {b: 2}, {c: 3}]
this.joyride.start(2) // This should start at the second step {b: 2}
```

Is this possible?

**Comment by gilbarbara** [comment]
Nope, not possible. You could change your steps and reset the tour or something.

[s]

**Comment by vning93** [comment]
Got it, thanks. That's what I'm doing right now.

**Comment by pociej** [comment]
Thats very bad. Real scenario i have tutorial with navigation between steps ( ability to go back). User closed the browser by accident and then relaunched the app. I would like to start the app exactly at point of tutorial that user left and still have ability to navigate back. Above shows that this case is not handleable.
