### ISSUE TITLE
Add custom action button

### ISSUE THREAD

**Issue by msalsas** [gilbarbara/react-joyride#129]
Hi, I wonder if there is any way to add a "More info" button with a link. If not, there could be a `showCustomButton` prop, and `locale` prop could have a `custom` property for the custom button text. The `callback` prop could be executed also when the custom button is clicked with `type` set to `'custom'` or `'customButtonClicked'`. In this way, I could redirect the user to a custom page, as if it was a link. What do you think?

**Comment by gilbarbara** [comment]
Why not add that in the tooltip body? You can use html there.
There's not much room left in the footer to allow custom buttons in mobile screens.

**Comment by msalsas** [comment]
That could do the trick. Thanks

**Comment by IanVS** [comment]
Hm, it seems less-than-ideal to have to code up a button as a string.  For example, I want my custom button to dispatch a redux action, which is going to be non-trivial to implement.  Furthermore, some room for the footer still remains even if all elements are hidden, putting the button in a slightly different place than it would be if it were actually in the footer.  

My use case is that I want to hide all the default buttons and replace them with my own for a particular tooltip.  Running out of room will not be a problem for me, so it would be great to be able to add a custom button as requested in this issue.  Any chance you'll reconsider?
