### ISSUE TITLE
Call events prior to triggering next step

### ISSUE THREAD

**Issue by vning93** [gilbarbara/react-joyride#133]
Hi,

Is it possible to call a chain of actions, perhaps to open up dropdowns and other UI elements before the next tooltip is rendered? I ask because the selector element for the next tooltip is bound to an element within the dropdown that needs to be rendered first.

Thanks,
Vince

**Comment by gilbarbara** [comment]
Hey, I've refactored the callback system.
I think you could stop the tour on `step:before` and start it again after the render is done.
Let me know..

**Comment by vning93** [comment]
Great, thank you I will try this out!

**Comment by Pinch1A** [comment]
Does it work ? any example of it ?
