### ISSUE TITLE
Steps randomly need a redraw 

### ISSUE THREAD

**Issue by jducro** [gilbarbara/react-joyride#135]
On some first loads, I end up with missing Next button text and closing arrow
<img width="482" alt="screen shot 2016-10-25 at 14 37 24" src="https://cloud.githubusercontent.com/assets/898196/19688432/9cc61a0c-9ac1-11e6-9846-02ab67fa7393.png">

If you open the inspect tools or refresh the page everything is back to normal.

**Comment by gilbarbara** [comment]
weird, I'll try to reproduce. If you find out the cause let me know

**Comment by gilbarbara** [comment]
Can you please try 1.6.0 and let me know if you still have problems?
