### ISSUE TITLE
Tooltips are not showing

### ISSUE THREAD

**Issue by xrado** [gilbarbara/react-joyride#136]
I get the overlay over selected element, but the tooltip is not shown. I've inspected the html and it's there, just -1000px and opacity:0. Interesting is that if I resize a window, tooltip appears.

Any idea what might be wrong?

**Comment by gilbarbara** [comment]
Hey,

Do you have a public demo or something?

**Comment by xrado** [comment]
no sorry, now I've tried v1.4.8 and works fine (tooltip appears), but in v1.5.0 and v1.5.1 don't. Both tested in latest chrome and safari. But I've just find out that with v1.4.8 overlay have wrong position in safari.

**Comment by xrado** [comment]
I'll describe what happens. I have two steps. Bacon appears, I click on it, overlay appears, but no tooltip. Then if I resize a window, tooltip appears. Clicking next, moves overlay to next element and again no tooltip, resizing then help again to make it visible.

**Comment by xrado** [comment]
see #138

**Comment by gilbarbara** [comment]
merged
