### ISSUE TITLE
[feature request] add this.joyride.next()

### ISSUE THREAD

**Issue by IanVS** [gilbarbara/react-joyride#140]
It would be great to be able to advance the tour by means of an arbitrary user action.  For instance, the tour may ask the user to click a button, and when they do so, we would like to consider the step finished and move on to the next step.  I believe `this.joyride.next()` could be added to increment the step index, just as if the user had pressed `next` in continuous mode or `close` in single mode.

It should also allow incrementing the step even if `this.joyride.stop()` has been called to "pause" the tour, I think.

Would you consider adding this to the API?

**Comment by IanVS** [comment]
@gilbarbara I'd be willing to work on this if it's something you'd consider merging.

**Comment by IanVS** [comment]
@gilbarbara I need to add this for my own purposes and I haven't heard from you so far, so I went ahead and submitted a PR.  Hope you don't mind.

**Comment by gilbarbara** [comment]
I'll check those PRs soon.
Sorry, I had a busy week with this black friday shit.

**Comment by IanVS** [comment]
Awesome, I totally understand.  Thanks for giving an update!
