### ISSUE TITLE
Is the demo running an older version?

### ISSUE THREAD

**Issue by IanVS** [gilbarbara/react-joyride#141]
I'm noticing that my steps with right/left position are top-aligned to their target elements, but the steps in the demo are more vertically centered on the target.  I found a commit which [seems to have changed this](https://github.com/gilbarbara/react-joyride/commit/c6e2c9527ccebc4a74e450e3efc8b945ec6e5b07), but that would mean the demo is not up-to-date.  Is that the case?

**Comment by gilbarbara** [comment]
I'm not sure, I will take a look asap and update if needed
