### ISSUE TITLE
Saucelabs not running in CI

### ISSUE THREAD

**Issue by IanVS** [gilbarbara/react-joyride#143]
All of the recent PRs seem to be failing in CI because saucelabs is not running:

```
Sauce Labs Authentication Error.
You used username 'None' and access key 'None' to authenticate, which are not valid Sauce Labs credentials.
```

(for example: https://travis-ci.org/gilbarbara/react-joyride/builds/177077303)

**Comment by gilbarbara** [comment]
Yeah, it appears to have a limitation for PRs, I'll check it.
