### ISSUE TITLE
Add stylesheet using CSS custom-properties

### ISSUE THREAD

**Issue by IanVS** [gilbarbara/react-joyride#144]
I work at a company which would really like to use this library, and we will want to customize the appearance of the tooltips. However, we use postcss and upcoming CSS features like custom-properties instead of Sass.  I know that we could use the compiled stylesheet from `lib`, but your `.scss` stylesheet has a lot of logic which depends on the variables, and overriding the compiled styles will be difficult and fragile.

I'd like to suggest adding another option for a customizable stylesheet, which uses only actual draft CSS specifications.  [CSS Custom-Properties](https://drafts.csswg.org/css-variables/) allow us to use variables natively in CSS, and can be easily overridden by consuming apps.  They already have [pretty good browser support](http://caniuse.com/#feat=css-variables), and can be turned back into "normal" css by those of us using [cssnext](http://cssnext.io/).

I think that adding such a stylesheet would increase the reach of this package to developers not using Sass, and will also help to "future-proof" with actual CSS features (much like we use Babel for new JS features).

I have a PR ready-to-go which implements and documents this approach, but am opening this issue first as requested in your contributing guidelines.

**Comment by gilbarbara** [comment]
Hey,

Looks good, but can you please create a new markdown `CSSNext.md` file for the CSSNext options and instructions? Just add a link to it in the README, `Alternatively, there is a version of the stylesheet using CSSNext syntax ... [link].`

Thanks

**Comment by gilbarbara** [comment]
I ended using styles in JS for the default elements but also added support for custom tooltip and beacon components.
It's already on `npm i react-joyride@next`

[s]
