### ISSUE TITLE
Make hole a "real" hole in the overlay

### ISSUE THREAD

**Issue by IanVS** [gilbarbara/react-joyride#148]
My use case involves prompting the user to take some action within my app, like clicking a button in order to move to the next step of the tour.  Because of that, I need to allow hover states and click handling to pass through the hole in the overlay, but be blocked everywhere else.  I have a working prototype and would be willing to submit a PR if you're agreeable to the idea, @gilbarbara.

**Comment by shashanka-wings** [comment]
I have same use case. How can I use this fix? Thanks.

**Comment by IanVS** [comment]
I'm waiting to hear from @gilbarbara before submitting a PR to this project, but if you'd like to test it out, you could use my fork: https://github.com/nutshellcrm/react-joyride.  Although, I'll have to warn you that's a little risky because I'm not necessarily following semver on that fork, so I wouldn't recommend using it in production.  That said, you could fork this project yourself and make the same changes I did in https://github.com/nutshellcrm/react-joyride/pull/5.

**Comment by gilbarbara** [comment]
I would like to see it running before considering the merge. Can you apply this to the demo?

**Comment by beaesguerra** [comment]
I also have the same use case. I checked out the proposed solution and it looked good! This feature would be very useful. Any progress on applying it to the demo? @IanVS

**Comment by IanVS** [comment]
@beaesguerra I've been working on other areas of the react-joyride code lately which I need to get functioning before I can use this library, but I do intend to try adding it to the demo.  I'll do my best to prioritize it since it seems it would be useful for others.
