### ISSUE TITLE
Remove Beacon

### ISSUE THREAD

**Issue by etshi** [gilbarbara/react-joyride#15]
I would like to ask is it possible to remove the beacon? 
For example if the joyride tooltip is closed in the middle of the steps the beacon doesn't show and the next time the joyride is triggered it starts from the beginning.

**Comment by gilbarbara** [comment]
hey,

I think that would defeat the whole tour flow. Can you give me a practical example? 
You could try enabling `joyrideShowSkipButton` option. (available in version 0.6.7) Maybe it will fulfill your needs?

**Comment by etshi** [comment]
Thank you. you can close

**Comment by gilbarbara** [comment]
:+1:
