### ISSUE TITLE
logger called with wrong parameters

### ISSUE THREAD

**Issue by jjhale** [gilbarbara/react-joyride#166]
In Joyride.jsx#parseSteps this.logger is called with a string as the second argument instead of a list. That string gets "applied" to the logger function resulting in:

`Uncaught TypeError: CreateListFromArrayLike called on non-object`

Problem line:
`this.logger('joyride:parseSteps', 'Target not rendered. For best results only add steps after they are mounted.', s);`

Fix:
`this.logger('joyride:parseSteps', ['Target not rendered. For best results only add steps after they are mounted.', s]);`

**Comment by IanVS** [comment]
I would actually suggest fixing this like: https://github.com/nutshellcrm/react-joyride/commit/da915e7274cd4ee3b400ca5dd6af27cd029d1f64.  Forcing messages to be wrapped in an array is a bit clunky.

I haven't had any luck having pull requests reviewed on this project, unfortunately.
