### ISSUE TITLE
[bug] Callback still fires after finish

### ISSUE THREAD

**Issue by karolselak** [gilbarbara/react-joyride#172]
That's crazy bug... I've written a simple callback function logging received argument. And I discovered with wonder, that after finishing the ride, my ALL other system actions started firing this callback. It's fired still with the same object:
`{
    action: 'next',
    type: 'finished',
    ... }`
What's more strange, callback becomes sensitive for my actions only after finishing the ride - before everything was ok.

**Comment by IanVS** [comment]
What version are you using? I don't understand the problem. It sounds like you are getting the "finished" callback when the joyride finishes? That is what should happen. Maybe you can share a small bit of code to help explain?

**Comment by karolselak** [comment]
I'm using version 1.7.0. The problem is that after finish callback becomes "glued" to my system and fires when I do some other actions (supported by Redux), i.e. hover on some object od click some button. I looked to your code and I suspect that function `componentWillUpdate` of `Joyride`component still can be fired after ride finish and it triggers the callback every time the component is rerendered.

**Comment by IanVS** [comment]
Ah, thanks, I think I understand now.  I'll take a look this evening.

**Comment by gilbarbara** [comment]
Fixed in e54250b46873aedc5313b6239e4735155c81b7e2
Please try v1.8.1
