### ISSUE TITLE
this.joyride.reset() doesn't reset index.

### ISSUE THREAD

**Issue by GusRuss89** [gilbarbara/react-joyride#177]
I'm trying to make my joyride tour available on a button click, but can't get it to work more than once (once the tour is finished it can't start again).

I've found that `this.joyride.reset()` is not changing the index back to zero.

The following code

    console.log(this.joyride.state);
    this.joyride.reset(true);
    console.log(this.joyride.state);

produces

    Object {action: "next", index: 6, isRunning: false, isTourSkipped: false, shouldRedraw: true…}
    Object {action: "next", index: 6, isRunning: false, isTourSkipped: false, shouldRedraw: true…}

Looking at the code I can't figure out _why_ it isn't resetting properly, so there's a chance I'm missing something but I can't figure out what.

**Comment by IanVS** [comment]
I assume you're on the latest version, `1.7.0`, correct?

That does seem odd, I'll look into it ASAP.  Thanks for the report!

**Comment by GusRuss89** [comment]
Yes `1.7.0`. Thanks.

**Comment by gilbarbara** [comment]
I think I know what happened, the `defaultState` got mutated.
I'll submit a commit fixing it later tonight.

**Comment by gilbarbara** [comment]
Please try 1.8.0 and reopen if it ain't fixed.
Thanks.
