### ISSUE TITLE
Allow touch events in overlay hole

### ISSUE THREAD

**Issue by IanVS** [gilbarbara/react-joyride#178]
Currently, we rely on mouse events to enable clicking inside of an overlay hole. That means that touches will not work.  We should also enable touch events.

**Comment by gilbarbara** [comment]
I'll try to add a touchstart event to identify real touch screens and add a handler to it.

**Comment by IanVS** [comment]
Actually, when I simulate a mobile phone or "laptop with touch" in chrome, the app already works how it is.  

It seems that the order of events (at least in the chrome emulator) is:

- touchstart
- touchend
- mousemove (which changes pointer-events)
- mousedown
- mouseup

I wonder if there are actually any problems on real devices.  Can anyone try and confirm?

**Comment by gilbarbara** [comment]
I don't think real touch screens have mouse events at all.

**Comment by IanVS** [comment]
According to [Touch and Mouse](https://www.html5rocks.com/en/mobile/touchandmouse/#toc-together) from html5rocks, mouse events are still fired, in the order which I determined.  It goes on to mention some other possible differences, but I think it's worth actually hearing about a real problem on a touch device before deciding this is an actual bug.  We have a touchscreen Windows 8 box at the office, I'll try it out next time I'm there.

**Comment by gilbarbara** [comment]
Oh Jesus, Windows. ✝

**Comment by IanVS** [comment]
I just tested on a real touch screen, and touching the element in a hole works just fine!  🎉

**Comment by gilbarbara** [comment]
Yay! 👍
