### ISSUE TITLE
stepCallback doesn't work/seems unimplemented

### ISSUE THREAD

**Issue by jmrog** [gilbarbara/react-joyride#18]
Even though I assign a function to `stepCallback`, the function never seems to be called. Looking through the source, I don't see any spot where it would be. Is calling this method intentionally unimplemented at the moment? If so, it would be good to mention that in the docs. If not, then there's a different problem.

I'd be happy to submit a PR either way.

**Comment by gilbarbara** [comment]
It's back on [0.7.1](https://github.com/gilbarbara/react-joyride/releases/tag/0.7.1).

cheers
