### ISSUE TITLE
Ride doesn't work when some `text` field is an empty string and there's no warning

### ISSUE THREAD

**Issue by karolselak** [gilbarbara/react-joyride#180]
I've had a situation that package was not working and I realised that was caused by empty string in `text` field in one of my steps. I think that some error or warning would be helpful in such situations, or simply steps with plain strings could be ignored.

**Comment by IanVS** [comment]
I actually don't see why the `text` needs to be a required field at all.  I'm going to submit a PR that removes that limitation.

**Comment by gilbarbara** [comment]
@IanVS why not? I'm not sure I get it..

**Comment by gilbarbara** [comment]
Fixed in 5c968513aabad4f240a1eec477ba4077bef8ddaa
It will be on 1.8.2
