### ISSUE TITLE
Events disabled when tooltip overlaps target hole

### ISSUE THREAD

**Issue by xveganxxxedgex** [gilbarbara/react-joyride#182]
If you have a step that targets a large element at the top of the page, the tooltip overlaps the target hole area, which has the pointer-events disabled (I think as part of the feature to click actions in the hole itself). Would there be a way, or would it make sense, to only add the pointer-events removal if a prop was set on the step itself to allow click events within the target? In the screenshot below, none of the items in the tooltip (the x close, skip and next buttons) are clickable.

![screen shot 2017-01-10 at 10 53 16 am](https://cloud.githubusercontent.com/assets/4555168/21820059/102ecba4-d723-11e6-8e52-60566a9b9cc4.png)

**Comment by beaesguerra** [comment]
I also ran into this problem. A fix for this would be greatly appreciated!

**Comment by IanVS** [comment]
This is fixed in [1.8.2](https://github.com/gilbarbara/react-joyride/releases/tag/1.8.2)
