### ISSUE TITLE
Question: how to handle `this.joyride`?

### ISSUE THREAD

**Issue by karolselak** [gilbarbara/react-joyride#185]
I have a problem with using API of the package - although there're many methods described in README file, I cannot use them until I can handle the object with some variable. Please explain me how to get it at least with global variable. And I think it should be explained in README too.

**Comment by gilbarbara** [comment]
I'm not sure I understand your issue..

Did you add a ref to the Joyride component like this?
```javascript
<Joyride ref={c => (this.joyride = c)} ... />
```

**Comment by karolselak** [comment]
Hm, I was thinking I had checked this, but I hadn't - yes, it works, I'm sorry. And maybe that's good idea to explain in README why is that fragment important.
