### ISSUE TITLE
Restart with autorun

### ISSUE THREAD

**Issue by karolselak** [gilbarbara/react-joyride#188]
How to restart ride with autorun with API? This doesn't work, I don't know why:
`    this.refs.joyride.reset();`
`    this.refs.joyride.start(true);`

**Comment by IanVS** [comment]
Did you try `this.refs.joyride.reset(true);`?

**Comment by karolselak** [comment]
I wrote that I want to run it with autorun. I'm sorry, I meant autostart of course - I want to run it without showing the beacon first. Unfortunately that sequence also doesn't work:
    `this.refs.joyride.reset(true);`
    `this.refs.joyride.start(true);`

**Comment by IanVS** [comment]
`reset(true)` should be enough. If it's not, it's a bug.

**Comment by karolselak** [comment]
I think I'm not understood. It works, but not in the way I want. I can only say that I want to start it again, but I have no ability to specify, how I want to do that - that I want to do that with an `autorun` option. In normal `start` method I have that option, but in `reset` I haven't. Possible solution could be adding second option to `reset` method - it could look like `reset(restart, autorun)` or something like that.

Or maybe there's some another way to achieve it, but I can't find it. For me that's very strange that I can neither write synchronous code like running `reset` first and `start` next nor achieve it with putting some callback to `reset` function.

**Comment by IanVS** [comment]
I think I see what you are saying now.

If you would like to avoid seeing a beacon, you can set the `autoStart` prop of `<Joyride />` to `true`, like: `<Joyride autostart={true} />`

Will that work for you?

**Comment by karolselak** [comment]
I have that option set, but it works only for the first start. When I'm restarting ride, it's ignored.

**Comment by IanVS** [comment]
That sounds like a bug, then.  We'll investigate it.  Thanks!

**Comment by karolselak** [comment]
Thank you too :)
