### ISSUE TITLE
README: why `ref={c => (this.joyride = c)}`?

### ISSUE THREAD

**Issue by karolselak** [gilbarbara/react-joyride#196]
Is there some reason for inserting `ref={c => (this.joyride = c)}` to the `Joyride` component instead of plain `ref='joyride'`? For me both versions works the same, but the second one is more clear and understandable.

**Comment by IanVS** [comment]
The way of using refs that is recommended by React for the last few versions is the [callback ref](https://facebook.github.io/react/docs/refs-and-the-dom.html#the-ref-callback-attribute) (`ref={c => (this.joyride = c)}`).  String refs are discouraged, and may be deprecated in the future.  The react docs have this note:

>If you worked with React before, you might be familiar with an older API where the ref attribute is a string, like "textInput", and the DOM node is accessed as this.refs.textInput. We advise against it because string refs have some issues, are considered legacy, and are likely to be removed in one of the future releases. If you're currently using this.refs.textInput to access refs, we recommend the callback pattern instead.

Another nice thing about callback refs is that you do not need to use `reactDom.findDOMNode`, and in fact that API is also [discouraged](https://github.com/yannickcr/eslint-plugin-react/issues/678#issue-165177220).

If you have any other questions, feel free to ask.  You can also ask questions like this in our [gitter channel](https://gitter.im/gilbarbara/react-joyride).
