### ISSUE TITLE
overlay and tooltip placement issue

### ISSUE THREAD

**Issue by freefire8** [gilbarbara/react-joyride#198]
![bugjoyride](https://cloud.githubusercontent.com/assets/13870349/22145179/8b550318-df00-11e6-8212-cdb8e89e9bdc.jpg)

I got a problem of placement. there's a sharepoint menu banner on the top, and i think eveything is moved by the size of this banner. Any idea of a workaround?

**Comment by IanVS** [comment]
I think this is probably the same issue as https://github.com/gilbarbara/react-joyride/issues/124.  We don't have a workaround so far, but we will work to solve the problem.
