### ISSUE TITLE
v1.9.1 $joyride-close-image breaking compiled stylesheet

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [gilbarbara/react-joyride#202]
I spent most of the day today debugging styling issues with my project. I finally figured out that the latest changes to react-joyride's react-joyride.scss (specifically, the stylesheet changes) are to blame. 

It looks like @gilbarbara fixed the $joyride-close-image variable issue an hour after creating the 1.9.1 tag. But he never created another tag after the fix.

@gilbarbara please create another tag off of master to address this issue. Thanks!

**Comment by gilbarbara** [comment]
That's not the case.
You can check the [commits](https://github.com/gilbarbara/react-joyride/commits/master) to see that 1.9.1 was pushed after the changes in the main scss file.
I'll try to update the demo and try to reproduce.

**Comment by IanVS** [comment]
It looks like there were a few scss changes in https://github.com/gilbarbara/react-joyride/commit/fe8d045ffdd1765a03d72be3e74dc6f4228537bb.

**Comment by gilbarbara** [comment]
@IanVS just linting

**Comment by cah-alexsukhodolsky** [comment]
![error](https://cloud.githubusercontent.com/assets/12052245/22351053/da690992-e3db-11e6-97ae-91bbdd9a5b59.png)

**Comment by gilbarbara** [comment]
alright, I'll fix that now.

**Comment by cah-alexsukhodolsky** [comment]
This issue can be resolved by creating another tag.

**Comment by gilbarbara** [comment]
I know.

**Comment by cah-alexsukhodolsky** [comment]
Thanks

**Comment by gilbarbara** [comment]
v1.9.2 is published.
Sorry about that, Chrome is very forgiving and I was tired.
