### ISSUE TITLE
allowClicksThruHole isn't working in Mobile Safari (and iOS Chrome)

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-joyride#204]
the mousemove event isn't being triggered at all.

@IanVS I think is extremely important for all the features to work in all supported browser. Maybe if the user wants to use allowClicksThruHole, the overlay won't close the step by default?

**Comment by IanVS** [comment]
Doh, that's no good.  Yeah we should definitely try to get it working in as many browsers as possible.   I don't quite understand your suggestion, though.  

Out of curiosity, does the target you're tapping on have a click handler?  According to one [old article](http://sitr.us/2011/07/28/how-mobile-safari-emulates-mouse-events.html) I found,

>Mobile Safari will only produce mouse events when the user taps on a clickable element, like a link. You can make an element clickable by adding an onClick event handler to it, even if that handler does nothing. On tap Mobile Safari fires the events mouseover, mousemove, mousedown, mouseup, and click in that order

**Comment by gilbarbara** [comment]
@IanVS 
The mousemove listener needs to be triggered to change the `pointer-events` property for the overlay, right? And that is only needed to close the tooltip by clicking it.
But if the user really wants to draw attention to the hole, clicking on the overlay to close it maybe isn't a good thing.. So if `allowClicksThruHole` is enabled the overlay click event won't work at all.

About you question, it is a proper anchor with an onClick handler. [demo](https://github.com/gilbarbara/react-joyride/blob/demo/app/scripts/components/Panels.jsx#L79).
And that article is ancient! :)

**Comment by IanVS** [comment]
>The mousemove listener needs to be triggered to change the pointer-events property for the overlay, right?

Yes.

>And that is only needed to close the tooltip by clicking it.

Not necessarily.  In my own use case, the button is part of my app and actually does things within the app.  One of the side effects of the button is to advance the `stepIndex` of the joyride (if one is active).

>So if allowClicksThruHole is enabled the overlay click event won't work at all.

That's right, I don't want the overlay click event when there are clicks (or taps) in the hole.  `allowClicksThruHole` essentially turns the hole into a _real_ hole (or at least that's the goal).  The app underneath works as it normally does, but all around the hole, the overlay is active.

I tried the demo on an Android, and so far the taps work correctly to advance the joyride.  I'll have to do some research about iOS to see what's going on there.

**Comment by gilbarbara** [comment]
I have an iPhone 7 and a Samsung S7 here plus browerstack. Safari and Chrome on iOS don't work with the button in the hole in the demo.

**Comment by IanVS** [comment]
Yeah I see that on my iPad as well.  Need to figure out why… and if it's possible to fix.

**Comment by IanVS** [comment]
So, it seems like it does have to do with iOS's goofy rules about when to emulate mouse events.  Here's a [slightly less ancient](http://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html) article from Peter-Paul Koch which also talks about it.  I think what is happening, is that webkit looks at the touch target (the hole), checks to see if it meets its criteria, finds that it doesn't, and cancels the mouse events.  I did what PPK suggested, and added an empty `onClick` handler to the hole, and it starts to work in mobile Safari.  PR coming soon.

**Comment by gilbarbara** [comment]
Merged! 👍

**Comment by ravicious** [comment]
Has something changed in the browsers since January? I can reproduce the problem with react-joyride 1.0.1 and on current versions of Chrome (59.0.3071.102) and Safari on iOS.

**Comment by IanVS** [comment]
I just tested in chrome 59.0.3071.115 and it's working fine for me.  Maybe something is not configured correctly.  Are you able to share your code?

**Comment by ravicious** [comment]
Hmm, I'm able to share only the Joyride setup. Nothing too fancy. I replaced the actual values with foo/bar just to show how I have this organized in the real app.

<details>

```javascript
<Joyride
  steps={[
    {
      selector: '.foo',
      title: 'Foo Bar',
      text: <div><p>Foo</p> <p>Bar</p> <input readOnly value="Baz" /></div>
    },
  ]}
  run={props.foo}
  autoStart
  locale={{ next: 'Got it!', close: 'Got it!' }}
  allowClicksThruHole
  holePadding="14"
/>
```
</details>

**Comment by ravicious** [comment]
Turns out [FastClick](https://github.com/ftlabs/fastclick) somehow prohibited the clicks to go through the hole. The bug doesn't happen if I don't attach the FastClick handler.

To be honest, we already had problems with FastClick in our project, namely with [tapping on labels](https://github.com/ftlabs/fastclick/issues/60), so I think I'll just remove FastClick altogether.

**Comment by IanVS** [comment]
Ah!  Thanks for reporting back.
