### ISSUE TITLE
Allow components to be passed to steps

### ISSUE THREAD

**Issue by Mosho1** [gilbarbara/react-joyride#206]
I would like to be able to pass a `component` prop instead of `text` in a step, to render that instead of an html string as the content of the step. I could make a PR.

**Comment by brandonmp** [comment]
This is already a feature. It's pretty straightfowrad, but you can take a look at [this example](https://github.com/gilbarbara/react-joyride/blob/demo/app/scripts/components/Charts.jsx) to see it in action.

**Comment by gilbarbara** [comment]
Added to the README. I need to change the step's key `text` to `content`...
