### ISSUE TITLE
Alignment issues  

### ISSUE THREAD

**Issue by AlmogRnD** [gilbarbara/react-joyride#207]
I'm getting wired alignment issues within my app which is responsive. It looks like the overlay is pushing height and then the overlay objects get missed aligned attached screenshots. Any idea what might be causing this? 

![1](https://cloud.githubusercontent.com/assets/169507/22717464/5e4658c4-edef-11e6-8691-2eadada98efd.png)

**Comment by styks1987** [comment]
https://github.com/gilbarbara/react-joyride/issues/124
