### ISSUE TITLE
Fix Repositioning of Tooltips on Resize

### ISSUE THREAD

**Issue by jmrog** [gilbarbara/react-joyride#21]
@gilbarbara, in my PR #20, I mentioned that I was having some issues with positioning of elements in the joyride. After doing some investigating, it seems that the check at line 193 in the most recent version (https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Mixin.js#L193) prevents visible tooltips from updating their position when the window is resized. As far as I can tell, the check that prevents this was initially added in commit 9f932e94eaa9467a3bf41341736e1cb3dfc5036e ("fix autorun"). Whenever the tooltip has an X position that is greater than -1, it gets the `animate` class via props. But `calcPlacement` does not reposition any element that both has the `animate` class and has an X position greater than -1, with the result that tooltips never reposition themselves. 

Changing line 193 so that it only checks if `step` exists (which is what it used to do before 9f932e94eaa9467a3bf41341736e1cb3dfc5036e) seems to fix this issue. Did you make the change in 9f932e94eaa9467a3bf41341736e1cb3dfc5036e in order to prevent updating state too frequently on resizing?

**Comment by jmrog** [comment]
Just to add: if you go to your demo, open a tooltip, and then resize the window, you can see the behavior I'm talking about (no positioning). The demo works with the changes from PR #22 incorporated, though.

**Comment by gilbarbara** [comment]
hey @jmrog 
Yeah, I've added those checks to prevent too many state changes but I forgot to test the resizing afterwards..
I've copied your changes locally and will test some more.

**Comment by gilbarbara** [comment]
@jmrog 
I'm thinking about just leave the debouncing callback implemented without a flag to turn it off.
And setting a minimum 50 to a `resizeDelay` option.

Thoughts?

**Comment by gilbarbara** [comment]
@jmrog Pushed 0.7.4 to npm
Thanks
