### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by vget98** [gilbarbara/react-joyride#210]
Is is possible to run multiple instances of react-joyride at the same time? Would they always have to be on the parent App.js component or could a separate instance be run on another child component of App.js?

**Comment by hew** [comment]
@vget98 Yes you can. They run in isolation. 

I've actually found this to be way easier to maintain in some ways. But less dry.

**Comment by vget98** [comment]
If I had another instance of joyride running on one of the child components would that cause problems  since it is not on the parent App.js?

**Comment by vget98** [comment]
I am getting alignment issues where the tooltip shows all the way to the far left of the target element.

**Comment by IanVS** [comment]
It's difficult to troubleshoot without an example.  Are you able to provide a reproducible case?

We do still have some issues with alignment if you have `position: relative` elements (https://github.com/gilbarbara/react-joyride/issues/124).  Or, it could be that the joyride itself is inside a parent which has a padding or margin set.

**Comment by vget98** [comment]
Thanks a lot IanVS looks like the problem was that the Joyride was inside a parent with styles already so I would get alignment issues.

**Comment by vhermecz** [comment]
@vget98 could you rename the ticket to something more descriptive? e.g.: "support for multiple instances in parallel". (It is annoying  to need to open from a search list because "Questions" does not really give away much. thx
