### ISSUE TITLE
how to add synchronous steps inbetween tour steps?

### ISSUE THREAD

**Issue by brandonmp** [gilbarbara/react-joyride#211]
I'd like to perform trivial actions inbetween steps, like opening drawers or clicking buttons. 

I know I can call `this.joyride.next()` programatically, which I believe was added to enable controlling the tour from outside the tooltip.  

But is there a clean way to use it to add actions in-between steps?

**Comment by IanVS** [comment]
I think you can probably accomplish what you want.  Can you hop in the [gitter room](https://gitter.im/gilbarbara/react-joyride) and chat about it?

**Comment by brandonmp** [comment]
just to add a little more, here's something I'm trying now:

```
class MyTour extends React.Component{
// ... constructor etc

 handleStep =  ({ type, index, step }) => {
    console.log(`***Parsing step ${index} of type ${type}`)
    if (type === 'step:after' && index === 0) {
      const btn = document.querySelector('#placesButton > button')
      console.log("CLICK", btn)
      if (btn) btn.click()
    }
    return
  }

  render() {
    return (
      <Joyride
        ref='joyride'
        autoStart
        showOverlay
        steps={tourSteps}
        resizeDebounce
        showStepsProgress
        showSkipButton
        callback={this.handleStep}
        type={'single'}
        run={true} 
        debug={true}
      />
    )
  }
}
```

The handler should call a `click` method on the target `DOM` node after step 0 completes.  The `console.log` fires, and the `click` method works in my Chrome Console, but when I try to do it in Joyride, the button doesn't seem to get clicked.

**Comment by brandonmp** [comment]
sure thing, thanks!

**Comment by brandonmp** [comment]
to recap from gitter chat, this looks like it's possible.  basically:  connect the `run` prop to state,then in `callback`,  hook a `setState({run: false})` call to `step:after`. Then do what you have to do, and set `run:true` when you're done. Something like this (h/t @IanVS for the snippet)

```
render() {
return (
<Joyride 
    stepIndex={this.state.joyrideStepIndex}
    run={this.state.isJoyrideRunning}
    callback={this.handleJoyrideCallback}
    {…otherProps} />
)}

handleJoyrideCallback(event) {
    if (event.type === ‘step:after’ && event.index === 0) {
        this.setState({
            isJoyrideRunning: false,
            joyrideStepIndex: event.index,
        });
        // Do your sync things, at the end of which do another setState to turn `isJoyrideRunning` back to `true`
    } else if (event.type === ‘step:after’) {
        this.setState({joyrideStepIndex: event.index});
    }
}
```

**Comment by BOOSTOProtocol** [comment]
the next function seems to be gone in the new version. What is the alternative way of calling .next for the new version?

**Comment by gilbarbara** [comment]
@BOOSTOProtocol check the controlled example in the demo.
