### ISSUE TITLE
Issue with arrow repositioning

### ISSUE THREAD

**Issue by vget98** [gilbarbara/react-joyride#212]
`<Joyride
          ref={ref => this._idleJoyride = ref ? ref : null}
          disableOverlay={false}
          run
          locale={{ close: 'Close', last: 'Done' }}
          showOverlay={false}
          steps={idleJoyrideSteps}
          tooltipOffset={0}
          type={'single'}
          callback={this.joyrideCompleteCallback.bind(this)} />`

this is my joyride but whenever I start the tour the tooltip arrow that is pointing to the center of the element sudden jumps all the way to the left.

**Comment by vget98** [comment]
#111 
I have tried the possible hacky solutions from the issue but still no good

**Comment by gilbarbara** [comment]
Are you using v1.4.7? Can you try 1.10.1?

**Comment by gilbarbara** [comment]
¯\_(ツ)_/¯
