### ISSUE TITLE
Joyride positioning to the right of parent element, not on top

### ISSUE THREAD

**Issue by johnnyji** [gilbarbara/react-joyride#213]
Hi there!

I've run into an issue using Joyride. I'm setting the joyride element in a sidebar component, so that when a form open, there's a walkthrough on the form.

However, instead of overlaying the beacon and tooltips on top of the form (as it does when I use it on the dashboard), it instead offsets the joyride content to the right.

Is there any reason why this would be happening? Not sure if this is a bug or not.

PS, thanks for the amazing library!

![screen recording 2017-02-27 at 03 42 pm](https://cloud.githubusercontent.com/assets/8540601/23385272/bfb7d056-fd03-11e6-905d-416b83f99995.gif)

**Comment by kirstu** [comment]
I'm experiencing the same problem with React Material UI tab component

**Comment by LucasBassetti** [comment]
Hi,

I'm using [inspinia](https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S) template and I'm getting a similar problem

![image](https://user-images.githubusercontent.com/1014326/29372527-caf7baae-8281-11e7-80ca-b649d335697f.png)

The joyride should select the search input field.

Any solution?

**Comment by gilbarbara** [comment]
yeah, you should use `isFixed`
