### ISSUE TITLE
Beacon wrongly placed when its target element is inside a bootstrap modal

### ISSUE THREAD

**Issue by jothi-pyt** [gilbarbara/react-joyride#217]
Hi,

I am trying to use this amazing tour guide plugin in my project. In relative elements am not facing any issues. 

Inside bootstrap modal its relocation to somewhere to the bottom. Am trying to point the change button in the header top. Any suggestions?

![screen shot 2017-03-07 at 9 19 42 pm](https://cloud.githubusercontent.com/assets/23206756/23664539/d965479e-037b-11e7-9eac-87e56171e6e1.png)

**Comment by IanVS** [comment]
is the modal a fixed position?  If so, are you using the `isFixed` property on the step?

**Comment by jothi-pyt** [comment]
@IanVS Thanks for the response. Here the step config am using,

`{
     title: 'Action title',
     text: 'Replace this activity with other options available here',
		selector: '#activity-details-change',
		position: 'bottom',
		type: 'hover',
		isFixed: true,
	}`

**Comment by ddeath** [comment]
@jothi-pyt if you want you can test my repo (add to npm) 

    "react-joyride": "ddeath/react-joyride#fixed-positioning-and-overlay",

There is applied a fix and created PR to this repo in #229

**Comment by gilbarbara** [comment]
This will be fixed in V2
