### ISSUE TITLE
Tooltip not showing. Opacity: 0

### ISSUE THREAD

**Issue by mlukaszczyk** [gilbarbara/react-joyride#218]
Hey there,

we are adding react-joyride to our app but it seems that there´s an issue similar to https://github.com/gilbarbara/react-joyride/issues/136. 

The tooltip is positioned correctly but the opacity is set to 0. Probably an issue with the css animation.

Did anyone encounter similar problems with react 15.4.2 and joyride 1.10.1?

Thanks,

Michael

**Comment by undershot** [comment]
Maybe screen width is smaller than joyride-tooltip element width (with its paddings). I met this issue only with screen width < 330px (iPhone 5). And I have next solution: clear all paddings in .joyride-tooltip
`.joyride-tooltip {
		filter: none !important;
		padding: 0
}`
So in my case it works perfect.

**Comment by mlukaszczyk** [comment]
Hey @undershot, the resolution was actually full HD. I will try the padding fix though.

**Comment by mlukaszczyk** [comment]
Unfortunately, this did not work. Does someone else have an idea?

**Comment by karmajunkie** [comment]
I'm seeing the same behavior... possible some kind of init animation isn't running?

**Comment by jayhack** [comment]
I had a slightly different fix that lead to a solution: explicitly set the width to something that will fit on your screen, e.g.

`const steps = [
  {
    ...
    style: {
      width: '200px',
      },
    ...
  }
]`
