### ISSUE TITLE
Beacon OffsetY Does Nothing

### ISSUE THREAD

**Issue by hew** [gilbarbara/react-joyride#221]
`beacon: { offsetY: val }` - does nothing regardless of value
`beacon: { offsetX: val }` - adjusts appropriately

Can't provide a reproducible repo at this time.

**Comment by djkirby** [comment]
@hew I ran into some similar behavior, and looking in the code it looks like it's doing a check to only apply `offsetY` if the `position` starts with `top` or `bottom`. May be why you're not seeing any change, if your position is not starting with one of those.

**Comment by andrewabogado** [comment]
@hew any luck on this? Can't seem to make offsetY to work as well.

**Comment by michaelmitchell** [comment]
Some problem here

**Comment by gilbarbara** [comment]
You do this with the step's offset option in V2.
You can try it with `npm i react-joyride@next`
