### ISSUE TITLE
stepIndex doesn't appear to work

### ISSUE THREAD

**Issue by brandonmp** [gilbarbara/react-joyride#223]
Setting `stepIndex` to, say, `3` in[ the demo](https://github.com/gilbarbara/react-joyride/blob/master/demo/src/App.jsx) doesn't seem to affect the starting step. Checking `react devtools` show that Joyride recognizes its `props.stepIndex` as `3`, but seems to have no effect.

**Comment by re8260** [comment]
+1

**Comment by IanVS** [comment]
Sorry, but I'm not sure exactly what you're saying.  Can you give a bit of an example with some code?

**Comment by PeterAronZentai** [comment]
@IanVS - he says that the `stepIndex` parameter isn't working - setting it to whatever value does not have effect.

**Comment by michaelmitchell** [comment]
yup seeing the same problem

**Comment by gilbarbara** [comment]
This will be fixed in V2 with controlled/uncontrolled tours

**Comment by piotr-cz** [comment]
There is a check in `componentWillReceiveProps`, but in `componentDidMount`.
Maybe this issue should be left opened until it's fixed or implemented in v2

**Comment by piotr-cz** [comment]
It seems that stepIndex use is fixed by changing `&&` to `||` at [line 176](https://github.com/gilbarbara/react-joyride/blob/1.11.1/src/scripts/index.jsx#L176) and commenting out [line 222](https://github.com/gilbarbara/react-joyride/blob/1.11.1/src/scripts/index.jsx#L222), but this may break other scenarios

**Comment by nadim** [comment]
In V2 the stepIndex parameter is ignored on tour start. Is there a way to start on a specific step without patching the src?
