### ISSUE TITLE
disableOverlay does not work every time

### ISSUE THREAD

**Issue by ddeath** [gilbarbara/react-joyride#225]
In my case I am able to click on everything behind overlay even when the disableOverlay is true.

The problem is that ".joyride-overlay" has zero height as far as I discovered it is because of this code:
[https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Tooltip.jsx#L527](https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Tooltip.jsx#L527)

which use document.body.clientHeight which has unstable results.

The solution appears to be implementing code from this SO answer:
[http://stackoverflow.com/a/11077758/2599892](http://stackoverflow.com/a/11077758/2599892)

Which use code from jquery function.

The second "bug" which makes disableOverlay to not work is on here:
[https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Tooltip.jsx#L119](https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Tooltip.jsx#L119)

The removing of the event listener is not enough because property `mouseOverHole` can be set to the true from previous step. So we need to reset it to the `false`

**Comment by tomkdgun** [comment]
Hi, Looks like fix is ready, but delivery was postponed, because of Travis issue, not related with the fix it self. When the fix can be delivered ?

**Comment by ddeath** [comment]
@tomkdgun I would say that this repo is half dead. So I would not be waiting for this to be merged any time soon.

**Comment by gilbarbara** [comment]
Fixed in [v1.11.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.11.0)
