### ISSUE TITLE
Jenkins builds fails because of missing dependency

### ISSUE THREAD

**Issue by ddeath** [gilbarbara/react-joyride#228]
Hi there,
when I created PR I noticed that builds are failing.
After a while of investigation I found out that you are using:

    "image-webpack-loader": "^3.2"

That library released a new version 3.3.0. Because of the rule in package.json after:

    npm install

it installs 3.3.0 - but in that version they removed dependency `file-loader` but in demo you are relying on it when importing images.

So the solution is to use strictly 3.2 version or add own dependency of `file-loader`

**Comment by gilbarbara** [comment]
Fixed in [v1.11.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.11.0)
