### ISSUE TITLE
Offer some troubleshooting tips when the getting started does not work

### ISSUE THREAD

**Issue by AddictArts** [gilbarbara/react-joyride#23]
Hi, thanks for this excellent mixin. followed the getting started and I don't see any beacon. I added the css and the mixin plus the call to joyrideAddSteps. Thanks for any help you can offer.

**Comment by gilbarbara** [comment]
Hey,

You can call `joyrideSetOptions` during `componentWillMount` with debug set to `true`.

The step's selector you pass to `joyrideAddSteps` needs to be rendered on the document for it to work..

**Comment by jmrog** [comment]
"The step's selector you pass to joyrideAddSteps needs to be rendered on the document for it to work."

Is this documented anywhere? I ran into this same issue when initially getting started with the joyride plugin. 

It would actually be good to have an example/demo of using the joyride in a larger controller view with subcomponents. The current demo is not very "React" because it is all basically rendered in one giant component. Getting the joyride to work among subcomponents that might or might not render was/is more complicated (but it's also part of what got me to contribute some to this project! :smile: ).

**Comment by gilbarbara** [comment]
@jmrog Yeah this isn't properly explained in the README. I'll add it.

However, I'm trying to find time to refactor it as a component instead of a mixin, that's why I haven't done a new demo yet..
But I'll definitely re-code the demo with child components.

**Comment by AddictArts** [comment]
Thanks @jmrog  and @gilbarbara. I did figure out that my first problem was that the step selector had not rendered, so it was not in the dom. Debugging showed that when it performed the element.querySelector(). Now my problem is the style property top is not calculated properly for the beacon and tooltip. Looking at what I can do to fix that. Any hints or suggestions on that are greatly appreciated. Thanks again.

**Comment by gilbarbara** [comment]
@AddictArts That's hard to help without seeing it. Do you have an online demo?

[s]

**Comment by gilbarbara** [comment]
I've added a note about rendered elements in the readme and improved the debug logging with warnings for the "unmounted" steps.

@jmrog I refactored the demo with child components and an explicit flow to add steps asynchronously.

**Comment by AddictArts** [comment]
@gilbarbara Thanks for the support and I am working on the online demo, it is up, but I encountered an issue. I will add a comment when it is fixed. What I am working on is at http://sri-save.github.io/react-components

**Comment by AddictArts** [comment]
@gilbarbara I fixed the page issue I ran into, so now it is kinda working. The tooltip is not positioned right. My guess is it is something with the position calculation. Thanks for any help. Please see http://sri-save.github.io/react-components

Be sure to click simulate at the bottom once you open the demo. You will then see the beacon.

**Comment by gilbarbara** [comment]
@AddictArts I think it's a problem with that gh theme's css.
If you inspect the elements you will see that the `<body>` has 0 height as well the `.wrapper` element.
All sort of position hacks and it styles entire selectors like `header` and `footer`.

[s]
