### ISSUE TITLE
Error: npm run build:demo 

### ISSUE THREAD

**Issue by sharma-varun** [gilbarbara/react-joyride#231]
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:demo"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-joyride@1.10.1 build:demo: `NODE_ENV=production webpack --config demo/config/webpack.build.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-joyride@1.10.1 build:demo script 'NODE_ENV=production webpack --config demo/config/webpack.build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-joyride package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production webpack --config demo/config/webpack.build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-joyride
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-joyride
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

Whenever I tried to build the demo, I get this error and also when I run "npm start" I get the bundle.js file

**Comment by pomelo-nwu** [comment]
I have also encountered the same problem

**Comment by ddeath** [comment]
@sharma-varun hi the quickfix for this is `npm install --save file-loader` and then it should run. For more info see #228

**Comment by sharma-varun** [comment]
Cool, thanks it work!!
