### ISSUE TITLE
The hole does not resize if the target element change size

### ISSUE THREAD

**Issue by ddeath** [gilbarbara/react-joyride#232]
This is problem for example when you have forms which have validation. When the error is show, the hole is not resizing so you can not fill the fields.

The normal state of the form
![image](https://cloud.githubusercontent.com/assets/2537379/25559078/7c3d9c14-2d34-11e7-83bb-e623cb57eb7f.png)

Form with the errors:
![image](https://cloud.githubusercontent.com/assets/2537379/25559085/99a9b7c4-2d34-11e7-866d-dc538a4814eb.png)

Expected behavior is that the hole would change it size.

**Comment by gilbarbara** [comment]
This is not something I would work on. You could use a overflowed container for the form.
