### ISSUE TITLE
Allow overriding hole positioning styles

### ISSUE THREAD

**Issue by jeffbowen** [gilbarbara/react-joyride#234]
I'm trying to start off my tour with a modal more or less. It would be nice to do that within react-joyride. Right now, I just attach the first step with the `body` selector and hide the arrow like so:

    style: {
      arrow: {
        display: 'none'
      }
    }
The only problem is the overlay hole is the size of `body`. I'd like to manually override the hole's `width` and `height` for this step like so:

    style: {
      hole: {
        width: 0,
        height: 0
      }
    }
However, when `stepStyle.hole` and `styles.hole` are merged ([here](https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Tooltip.jsx#L354-L355)), since `styles.hole` is last, its values overwrite those of `stepStyles.hole`. What would you think about reversing them so that the hole's `top`, `left`, `width`, and `height` could be overridden?

**Comment by jeffbowen** [comment]
I can submit a PR if that sounds like a good idea.

**Comment by jeffbowen** [comment]
Tried it out and that doesn't do the trick. Don't want to override too many things to make it work. Is there a better way? Worth adding this functionality?

**Comment by gilbarbara** [comment]
Can you please provide a demo? Not sure how this would work.
Feel free to re-open when you do.
