### ISSUE TITLE
How to set autoScroll option in joyride 

### ISSUE THREAD

**Issue by sahithiWS** [gilbarbara/react-joyride#237]
I tried setting scrollToSteps:true but it does not seem to work
I am using react-joyride version 1.5.2
I am trying to achieve to scroll to the steps automatically in a long page
Can some one please let me know if this is achievable through this joyride or should we handle at our end

**Comment by pedroabreu** [comment]
What do the debug messages say ?

**Comment by sahithiWS** [comment]
There are no messages as such i was trying to set 
 <Joyride ref={c => (this.joyride = c)}
                steps={this.state.steps}
                showOverlay={true}
                callback={this.tourCallback}
                scrollToSteps = {true}
                />
but nothing seems to be getting effected
we have upgraded react-joyride 1.10.1 but no luck in scrolling to the steps
do we have any documentation to achieve this scrolling to the steps , if so can you please share

**Comment by gilbarbara** [comment]
Fixed in [v1.11.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.11.0)
