### ISSUE TITLE
Internet Explorer 11 - A valid react element must be returned

### ISSUE THREAD

**Issue by scrambled2k3** [gilbarbara/react-joyride#238]
I am getting this error when loading the Joyride component using IE11.  Everything works fine in Chrome, Safari and Edge though.

```
SCRIPT5022: Joyride.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

Joyride: 1.10.1
React: 15.5.4

**Comment by jjordy** [comment]
@scrambled2k3  did you find a solution to this?? I just ran into the same issue.

**Comment by scrambled2k3** [comment]
unfortunately no

**Comment by jjordy** [comment]
@scrambled2k3 Ill let you know what I find.

**Comment by lukaszlipinski** [comment]
+1 works fine everywhere beside IE11

**Comment by TheDolo** [comment]
+1

**Comment by AndrewStobie** [comment]
Did anyone ever find a solution to this? I'm still having this same problem.

**Comment by AndrewStobie** [comment]
I had some success updating my babel-core and probably more specifically to react 15.5 and it seemed to work that way. If I figure out the exact fix I'll let you know.

**Comment by gilbarbara** [comment]
In production builds too or just in development?
The demo works for me in IE11. It does not work for you?

Can you please provide a demo?
Feel free to re-open when you do.

**Comment by mchlltt** [comment]
👋  In case anyone happens on this issue, I wanted to post the fix that I found. This issue in the React repo addresses the issue more generally: https://github.com/facebook/react/issues/8379. The short version, as best I can explain it: React and ReactDOM were loading before babel-polyfill, which led to React's and/or ReactDOM's function for testing the validity of an element not being transpiled properly. Moving babel-polyfill to the first item in my webpack configuration ensured that React and ReactDOM were transpiled properly. The Joyride component is now correctly identified as a valid React element, and the tour is now behaving as expected in IE11, as well as Chrome, Firefox, and Safari.

**Comment by mbm-rafal** [comment]
@mchlltt THANK YOU! You saved my production!
