### ISSUE TITLE
Joyride hangs in Safari

### ISSUE THREAD

**Issue by billytianlan** [gilbarbara/react-joyride#239]
In Safari 10 on MacOS Sierra clicking next in joyride causes the beach ball to come up. After about 10 seconds the next step appears. Anyone have experience with this?

Edit:

Looks like the issue is that we have some selectors that are not on the page yet, this is actually intentional on our end. Not seeing any problems with Firefox, Chrome or Safari 9. 

Edit 2:

Seems only able to reproduce on Safari 10.0.x

**Comment by billytianlan** [comment]
Looks like the issue is that we have some selectors that are not on the page yet, this is actually intentional on our end. Not seeing any problems with Firefox, Chrome or Safari 9.

**Comment by jbduzan** [comment]
Do someone have news about this bug ?
I also experience this bug in safari 10.x, but it seems to happen even when my selector are already on the page.

**Comment by gilbarbara** [comment]
Can you please provide a working demo?
Feel free to re-open when you do.

**Comment by catamphetamine** [comment]
In our case Joyride hangs on unmounting: it reaches 100% CPU when navigating away from the page.
