### ISSUE TITLE
Make inactive tab active when the step arrives. 

### ISSUE THREAD

**Issue by preeti2904singh** [gilbarbara/react-joyride#243]
Hi I am not sure is this a right place to ask doubts but a help would be appreciated. I have two tabs in a page. When I click on start tour icon, the tour starts, I want to make the second tab active when the tooltip hovers on it, and show the tooltip in hidden elements of that particular tabs page which is active? Is it possible?

**Comment by PeterMerkert** [comment]
Yes, that's possible. But you need to manually intervene the joyride callback and check where it is at. Just before you enter the step where you want to highlight something in the new tab, you need to change the React state of the tab container to have your wishes tab active.
Then, the page will be rerendered and the prior hidden elements are visible. Then you can select them as usual with CSS selectors in joyride.

Example for a callback for you:
```
tourCallBack(data) {
    if (data.type === 'step:before' && data.step.selector === '.StepSelector') {
      this.tabContainer.activeTab = 1;
    } else if (data.type === 'finished') {
      // reset the active tab
      this.tabContainer.activeTab = 0;
    }
  }
```

**Comment by gilbarbara** [comment]
Yeah, this should be done with callbacks.
I'll try to improve it in V2
