### ISSUE TITLE
Fully Customizing the CSS in Joyride

### ISSUE THREAD

**Issue by sharma-varun** [gilbarbara/react-joyride#244]
Hi,  I want to add custom CSS to my Joyride. I am using SCSS in my project. Is there a way I can style properties like **font-size**, I see there are properties for background-color, color which I can pass to as objects, but I'm unable to to modify font-size or font-type inside my tooltip.

**Comment by wildlingjill** [comment]
I was able to make CSS changes by using the joyride selectors, e.g. .joyride-tooltip, in my SCSS file.

I've changed z-index, box-shadow etc., so it should be easy enough to change things like font-size and -type using the joyride element selectors in your normal SCSS file.

**Comment by gilbarbara** [comment]
This can be done passing `style` options to the step.

**Comment by reywright** [comment]
@gilbarbara I wanted to ask a question but didn't want to open a ticket. How is the CSS for Joyride working? It seems like there is some joyride chrome element, which knocks out the color of the overlay in general? And I'm not able to find the main overlay color anywhere in my Chrome inspector. Can you point me anywhere that has a general explanation?

**Comment by wildlingjill** [comment]
I might be able to help with this - do you mean the grey page overlay that comes on when you're running a joyride walkthrough? You can change it using the `.joyride-hole` CSS selector - the whole overlay is actually just a box-shadow around whatever your focus element is, so you can change the color of that shadow with CSS.

**Comment by reywright** [comment]
@wildlingjill thanks! Yeah I was literally sitting there being like... where does this overlay color come from, it's "literally" not defined. This is a brand new technique, never seen something like this before. Thanks.

**Comment by wildlingjill** [comment]
No problem! I had the same issue, it took me quite a while to figure out where it was coming from. Good luck with whatever you're building!

**Comment by sohedev** [comment]
check the link below it was useful for me  for some style props you wanna use
https://codepen.io/arielcavalcante/pen/YzzoaZK
