### ISSUE TITLE
Step `position` properties not being set

### ISSUE THREAD

**Issue by alexander-daniel** [gilbarbara/react-joyride#245]
Hello! Perhaps I am doing something wrong, but this is what I am noticing:

My step object sets `position: "top"` but no matter what, the component seems to be rendering with `"bottom"`. Has anyone else experienced this? I cannot seem to modify the position because of this.

![screen shot 2017-06-07 at 12 33 13 pm](https://user-images.githubusercontent.com/5408720/26889968-e9e2f6f8-4b7d-11e7-80b3-d957b242f74d.png)

Appreciate any help in advance, looking forward to continuing to use this component.

**Comment by gilbarbara** [comment]
I think this is done to prevent the tooltip to render outside the viewport.
Try [v1.11.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.11.0) and let me know.

**Comment by alexlukelevy** [comment]
I'm still seeing the same issue in 1.11.0.

**Comment by gilbarbara** [comment]
I need some code to identify if it's a bug.
