### ISSUE TITLE
JoyRide only once: for the first time

### ISSUE THREAD

**Issue by balrajhariharan** [gilbarbara/react-joyride#249]
I would like to have this feature that the joyride runs only for the first time. or probably when I click a demo button. Please help

**Comment by zzhcch** [comment]
@balrajhariharan  i think you need the `this.joyride.reset(restart)` to repeat your feature

**Comment by IanVS** [comment]
You would need to set some kind of flag either in a database or in localstorage or some other method, in order to determine when to start the joyride or not.

**Comment by PeterMerkert** [comment]
Yes, there is no way around the database flag. I also implemented it like that. Then on startup I check if the flag is set, and if not, I do `this.joyride.setTour(...)`.

**Comment by flieks** [comment]
@PeterMerkert so you save IP in database or user login ? I think it's way easier to save something in localstorage..
I think starting it without user consent is bit hard. Using the glowing ball indicator is not. Is the ball in the package ?

**Comment by PeterMerkert** [comment]
@flieks : We have user logins. So, we can save it on server side. Otherwise obviously local storage is the way to go! So, maybe I would then just use cookies to store a flag 👍 :-)

**Comment by gilbarbara** [comment]
I think this is best to be done in the app's code using the callback.
If you don't need a tour don't render the component! :)

**Comment by linonetwo** [comment]
How to know joyride has been done? What's the callback?

**Comment by linonetwo** [comment]
Use this:

```js
<Joyride
            steps={addFieldGuideSteps}
            callback={({ status }) => {
              if (([STATUS.FINISHED, STATUS.SKIPPED] as string[]).includes(status)) {
                window.localStorage.setItem('tutorial2Passed', 'true');
                setTutorial2Passed(true);
              }
            }}
            showProgress
            showSkipButton
            spotlightClicks
            continuous
            styles={{
              options: {
                zIndex: 1100,
              },
            }}
          />
```
