### ISSUE TITLE
Tooltip is blinking on slow devices

### ISSUE THREAD

**Issue by vladimirivanoviliev** [gilbarbara/react-joyride#250]
As we test our app against slow android devices, we observed that the tooltip is blinking (showing and hiding), most probably due to repositioning of the element on page scroll. After some investigation it appears that the drop shadow applied by the filter CSS property is causing it (fyi):
```
+.joyride-tooltip {
+    filter: none !important;
+    -webkit-filter: none !important;
+}

```

**Comment by gilbarbara** [comment]
Good to know. Thanks
