### ISSUE TITLE
Alignment issues when not using isFixed

### ISSUE THREAD

**Issue by bayweiheng** [gilbarbara/react-joyride#252]
Dear gilbarbara,

Firstly, thanks for this amazing library. I'm encountering this issue where a step with isFixed set to true gives the below (i.e. works properly),

![image](https://user-images.githubusercontent.com/24561788/28122846-f9b1549a-6751-11e7-8558-a7e691872d12.png)

but without isFixed results in weird positioning of the tooltip/overlay. However, I would not like to have to use isFixed, as the overlay will not center around the div element properly upon scroll. Please help! Thank you!

![image](https://user-images.githubusercontent.com/24561788/28122871-0861c286-6752-11e7-8e40-76c6a01c074f.png)

**Comment by eternal-echoes** [comment]
The code is at https://github.com/raynoldng/nusmods/tree/development

**Comment by IanVS** [comment]
@bayweiheng this is likely because you have fixed elements on the side and top.  There have been other issues related to this here as well, and if you search and find them you can probably find some solutions.  Sorry I can't give too much guidance other than that at this time.

**Comment by gilbarbara** [comment]
This will be fixed in V2
