### ISSUE TITLE
Prevent closing

### ISSUE THREAD

**Issue by rafaelgrilli92** [gilbarbara/react-joyride#253]
Is there any option to avoid users closing the guide? 

I tried to find here in the repository and on google but I didn't find anything. 

For now, I just changed the CSS to do not display the 'X'. But I think that it could have some better way to do it.

Thanks!

**Comment by gilbarbara** [comment]
I will add global styles to next version besides individual steps.

**Comment by gilbarbara** [comment]
This will come in V2 soon.
You can try it with `npm i react-joyride@next`

**Comment by snazzypants** [comment]
@gilbarbara can you elaborate on how to do this? I am trying to get rid of the close button (x) but can't figure it out. Thanks

**Comment by nbdn** [comment]
You can hide the close button (x) through the styles prop : 
```
styles={{
  buttonClose: {
    display: "none"
  }
}}
```
