### ISSUE TITLE
Scrolling to the appropriate hidden target in panels with custom scrolling

### ISSUE THREAD

**Issue by sharma-varun** [gilbarbara/react-joyride#254]
Hi,
I'm trying to achieve auto scroll for hidden icons for Joyride.
For e.g: If we see the DEMO of joyride it auto scrolls to the target, here we can see at the bottom there is a scrollable table (Task Panel). 
I have similar table in the app i'm working what i'm trying to achieve to scroll to the elements and then show the tooltip (e.g: Completed task: "fix error on sales page" row from the demo) 
Currently it just hover over it and shows the tooltip message but the icon is still hidden, is there a way to make this work?

**Comment by gilbarbara** [comment]
Can you please provide a working demo?
Feel free to re-open when you do.
