### ISSUE TITLE
table column as step selector?

### ISSUE THREAD

**Issue by bdkent** [gilbarbara/react-joyride#257]
I want to select a table column, but I don't seem able to use a selector to multiple elements: only the first one is selected when the beacon is clicked and the tooltip comes up.

For example:
```
<table id="myTable">
  <tr>
    <td>...</td>
    <td class="my-column">...<td>
    ...
  </tr>
  <tr>
    <td>...</td>
    <td class="my-column">...<td>
    ...
  </tr>
  ...
</table>
```
and
```
{
  title: "...",
  text: "...",
  selector: "#myTable td.my-column",
  ...
}
```

Is this possible with `react-joyride`?

**Comment by mergebandit** [comment]
Under the hood joyride appears to be using `document.querySelector`, which only returns the first element that matches the selector(s).

So it doesn't look like this is possible.

**Comment by gilbarbara** [comment]
Yeah, a step is coupled with a single selector.
You could add `nth-child` or some other matcher in your selector.

**Comment by berabhishek** [comment]
Its been three years, any solution or workaround for this?

**Comment by gilbarbara** [comment]
@berabhishek 
Yes, using a [nth selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type).
