### ISSUE TITLE
`Array.prototype.includes` and `String.prototype.includes` aren't supported in all browsers

### ISSUE THREAD

**Issue by kartikluke** [gilbarbara/react-joyride#258]
There are a few places where this can be replaced with `indexOf` to improve compatibility.

**Comment by kartikluke** [comment]
https://github.com/gilbarbara/react-joyride/blob/b9de3c6b9a47419186ae74929524f126650aed56/src/scripts/Joyride.jsx#L817
https://github.com/gilbarbara/react-joyride/blob/b9de3c6b9a47419186ae74929524f126650aed56/src/scripts/Joyride.jsx#L871
https://github.com/gilbarbara/react-joyride/blob/b9de3c6b9a47419186ae74929524f126650aed56/src/scripts/Joyride.jsx#L874

**Comment by gilbarbara** [comment]
Fixed in [v1.11.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.11.0)
