### ISSUE TITLE
Add additional options for closing tooltips and allowing interactions

### ISSUE THREAD

**Issue by jmrog** [gilbarbara/react-joyride#26]
Currently, the joyride plugin always includes an overlay element (which can either be made invisible or not), and the overlay itself has a 'close' click handler that makes the tooltips close if you click anywhere on the overlay (effectively, anywhere on the screen other than the tooltip itself). The result is that tooltips sometimes get closed before a user reads them -- e.g., because the user clicks somewhere else on the screen and doesn't expect the tooltip to close unless he/she actually clicks the 'x' to close it. It would be nice to allow users of this plugin the option of setting things up so that there is no overlay element, meaning that the user can still interact with other parts of a page without closing the tooltip. It would also be nice to allow users to set things up so that the only thing that closes a tooltip is explicitly clicking on the 'x' (or the "next" or "skip" buttons, etc.). @gilbarbara, any thoughts about this?

I've implemented this locally in my own fork because I needed there to be no overlay and I needed the tooltips to close only when the 'x' was clicked, so I'm happy to submit a PR or discuss code.

**Comment by jmrog** [comment]
Actually, in case it's worth discussing, here's a relevant commit from my fork that does something like this: https://github.com/jmrog/react-tooltipper/commit/f62ba5bdba08f85f44838aafd26585aeafbe1d46 (the implementation in react-joyride would have to be somewhat different, as my fork doesn't provide any discrete joyride functionality; it's a pruned down version that is meant for showing discrete, disconnected tooltips or beacons)

**Comment by gilbarbara** [comment]
hey @jmrog 
I think this is great and I'll implement both options.
I start using discord last week and they had a similar approach to what you're suggesting and it was a great ux..

Have you seen this [reactiflux](http://join.reactiflux.com/) server? Some good channels.

**Comment by jmrog** [comment]
:+1: 

Sounds good. I've been on reactiflux, but when it was on Slack, so I haven't tried out discord yet. I'll check it out this morning!

**Comment by gilbarbara** [comment]
@jmrog I fixed this issue in [0.7.6](https://github.com/gilbarbara/react-joyride/releases/tag/0.7.6)
Let me know if this works for you.
