### ISSUE TITLE
The demo site doesn't run joyride

### ISSUE THREAD

**Issue by goodbomb** [gilbarbara/react-joyride#261]
Just FYI, I went to https://gilbarbara.github.io/react-joyride/ but nothing happens. I would've expected a demo of joyride in action.

**Comment by townmulti** [comment]
![image](https://user-images.githubusercontent.com/10806345/29637506-ec1962a8-8819-11e7-9b7d-b89afa38c177.png)


You have to click the beacon to activate it.
