### ISSUE TITLE
Simplify advancing tour when allowClicksThroughHole enabled

### ISSUE THREAD

**Issue by jeffreyscarpenter** [gilbarbara/react-joyride#262]
Following up on the conversation on #189. The behavior I'm looking for is to allowClicksThroughHole so that the user can navigate through the app using the elements exposed through the holes, but with also advancing the tour to the next step. 

I see from the demo code that you can modify the callbacks for the elements exposed through the hole to advance the tour manually, I was hoping to do this without spreading knowledge of the tour throughout my application.

**Comment by gilbarbara** [comment]
Do you mean multiple holes?
Maybe it will be better to turn off the overlay if you need to access multiple parts of your app's UI?
