### ISSUE TITLE
Starting the Joyride after a delay, is not working

### ISSUE THREAD

**Issue by hkedia321** [gilbarbara/react-joyride#264]
I want to set the `run` attribute to `true` when an ajax call is completed. But the joyride is not starting.
Here is the code:
`<Joyride
    autoStart={true}
    ref="joyride"
    steps={steps}//defined
    run={this.state.isTourOpen}
    type="continuous"
/>
`
The variable this.state.isTourOpen is initially false. When the ajax request is completed, it is set to true. But the Joyride is not starting.

**Comment by gilbarbara** [comment]
Please turn on `debug={true}` on your installation and make sure you have valid steps.
