### ISSUE TITLE
Can't use React component in tooltip text, only in steps

### ISSUE THREAD

**Issue by michaelatmender** [gilbarbara/react-joyride#265]
Using 1.10.1. I can use a React component as the text value of a step, but not as a single tooltip using addTooltip method.

In browser console I see `Uncaught Error: Objects are not valid as a React child `

**Comment by gilbarbara** [comment]
Can you please post an example?

**Comment by vkoudela** [comment]
I've (probably) ran into same problem. Error message from console is: `Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}).`

I'm using 1.10.1 on React ^16.1.0. I'm getting this error only on IE11 (Win 8.1).

**Comment by jschendzielorz** [comment]
I've the same problem. 
I define steps like this
```javascript
{
 title: '',
 text: (
  <div>
   Some text
   <ul>
    <li>Some text</li>
    <li>Some text</li>
   </ul>
   Some text
  </div>
 ),
 selector: 'div.searchbar',
 position: 'right',
 trigger: 'div.searchbar .helpIcon img',
}
```

and add it via api like this
```javascript
 this.joyride.addTooltip(item)
```

I'm using 1.11.* on React 15.4.*

**Comment by stillesjo** [comment]
Here's a codesandbox-project that shows the problem:

https://codesandbox.io/s/xly3kwml3o

**Comment by gilbarbara** [comment]
Hey,

yeah, it's known limitation that I'll address in V2 but I'll remove standalone tooltips in favor of [react-tooltips](https://github.com/gilbarbara/react-tooltips).
Can you please try it?
