### ISSUE TITLE
Autoscroll doesn't accommodate for fixed top header navbar

### ISSUE THREAD

**Issue by AnnekaSillitoe** [gilbarbara/react-joyride#266]
We have a fixed navbar at the top of our screen, and scrolling to our next step which is now up the screen and under the navbar means only some of the dialog is highlighted instead of the full box. Is there a way to override the highlighted area with CSS so that we can move it down? Or add in that the page scrolls fully back to the top before selecting the next item in the joyride?

**Comment by Aiso786** [comment]
I had the same issue, i've added this in my css file:

.joyride-hole, .joyride-beacon {
    margin-left: -230px;
    margin-top: -50px;
}

**Comment by agroves333** [comment]
+1

**Comment by PeterMerkert** [comment]
I had the same issue and encountered that by using: `scrollOffset: 200`

**Comment by gilbarbara** [comment]
Please try [v1.11.0](https://github.com/gilbarbara/react-joyride/releases/tag/1.11.0) and let me know if it works.

**Comment by AnnekaSillitoe** [comment]
@gilbarbara this didn't seem to make a difference for our step. We have added some code that moves us from the bottom of a scrolled page to where we need to be at the top:

```
if (result.index === 5) {
      window.scrollTo(0, 0);
}
```

It would highlight the correct thing, but this would still be behind our fixed nav bar and wouldn't scroll the page to display the item correctly.

**Comment by gilbarbara** [comment]
I need to see some code about the scroll.

About the fixed nav, this is probably a z-index issue. Try to load the Joyride before the nav and you could force a higher z-index for it in your setup.

**Comment by gilbarbara** [comment]
@AnnekaSillitoe I need to see some code about the scroll.

About the fixed nav, this is probably a z-index issue. Try to load the Joyride before the nav and you could force a higher z-index for it in your setup.

**Comment by afrancht** [comment]
Hi @gilbarbara,

Thank you so much for this resource!

This doesn't resolve the issue as the scrolling still leaves the component behind the navbar.

![image](https://user-images.githubusercontent.com/19917183/120393956-66f5e100-c2f8-11eb-93ea-3b4dc13f141d.png)

**Comment by orszaczky** [comment]
This is still an issue in v2.3.2

**Comment by joshsny** [comment]
Yeah +1 for this issue, a topOffset param would be really helpful! Trying to figure out a hack for this right now. Thanks for all the amazing work you have done @gilbarbara!

**Comment by joshsny** [comment]
After diving into the code I can see this is available with the `scrollOffset` parameter. Not sure how I missed that in the docs!
