### ISSUE TITLE
Warning after last step

### ISSUE THREAD

**Issue by norama** [gilbarbara/react-joyride#267]
There is a warning after pressing "Last" on last step:
```
Did not provide a step object.
```

Call stack:
```
componentDidUpdate -> getScrollTop -> getStepTargetElement(step=undefined) -> checkStepValidity(step=undefined)
```

In my code I am using a workaround to overcome this:
```
const checkStepValidity = Joyride.prototype.checkStepValidity;
Joyride.prototype.checkStepValidity = (step) => {
	if (!step) { // skip logging for undefined step (after last)
		return false;
	}
	return checkStepValidity(step);
};
```

But I would suggest to avoid calling these methods with `step=undefined` after  pressing "Last" on last step.

**Comment by wwarme** [comment]
I'm having the same issue. I'm not changing my steps at all, they are even allocated in joyrides props but checkStepValidity still fails. 

It renders my tutorial unusable, it can only be ran once. I can not restart it without reloading my site. What am I missing here?

**Comment by wwarme** [comment]
Ah I see Joyride.reset() does the trick here... Sorry.

**Comment by gilbarbara** [comment]
Please provide a working demo and feel free to re-open

**Comment by jayphelps** [comment]
@gilbarbara the demo inside this repo actually reproduces it as well when you enable `debug: true`.

![image](https://user-images.githubusercontent.com/762949/32519386-705fb53e-c3c1-11e7-8667-ae41b6021815.png)

I took a crack at fixing it, but it looks like several places are relying on this behavior right now. `toggleTooltip`, `componentWillUpdate`, `componentDidUpdate` maybe more.
