### ISSUE TITLE
Way to disable the display of close button?

### ISSUE THREAD

**Issue by SamSunani** [gilbarbara/react-joyride#271]
Is there a way I can disable the close button on the tooltip? I have tried to edit the scss file and tried to set the opacity to 0 in the props, but it does not seem to be working.

![image](https://user-images.githubusercontent.com/15188782/31142711-f1bafc54-a82f-11e7-874f-f9c721ebb56b.png)

**Comment by SamSunani** [comment]
Apologies, just fixed it through the props.

**Comment by dhaneshKatre** [comment]
@SamSunani  Which prop did you change in order to do that ?

**Comment by GlisboaDev** [comment]
@dhaneshKatre  you can use this to disable it:
```
<Joyride
styles={
            {
              buttonClose: {
                display: 'none',
              },
            }
          }
```

**Comment by dhaneshKatre** [comment]
Oh, cool! Thanks a lot! @GlisboaDev
