### ISSUE TITLE
Make a Material-UI IconMenu open within the joyride?

### ISSUE THREAD

**Issue by jduncanRadBlue** [gilbarbara/react-joyride#272]
I'm very new to react-joyride, and so far, it is awesome!

We are trying to create a walkthrough for our site which contains a lot of material-ui components.  Is there a way to have one of the steps in the joyride, open up a material-ui IconMenu and show the options?  If I try and put the selector as the IconMenu's menuitem, I get an error that the target was not mounted.

Thank you in advance for any advice!

**Comment by gilbarbara** [comment]
Not sure how to achieve this. Let me know if you find a way to do it.

**Comment by alexlukelevy** [comment]
If you are using Redux to control UI state, then you could dispatch an action when this step of the tour begins.
```

function Tour({ openMenu }) {
  return (
    <Joyride
      run
      callback={(event) => {
        if (event.type === 'step:before' && event.step.title === 'myStep') {
          openMenu(); // dispatch action in container
        }
      }}
    />
  );
}
```
