### ISSUE TITLE
Steps is wrong when click Next then Enter from keyboard

### ISSUE THREAD

**Issue by nighttiger1990** [gilbarbara/react-joyride#273]
example:
1. Step 1 is on screen.
2. I click 'next button' with mouse
3. Step 2 is on screen.
4. I press 'enter' from keyboard 
5. Step 4 is on screen.

Problem is Step 3 not showing. Is this bug or my wrong config?

**Comment by wildlingjill** [comment]
I saw the same problem - if you start from step 1 and hit enter, it shows each step; but if you click 'Next' first on any of the preceding steps, then hit the enter button, it skips 2 at a time.

**Comment by nighttiger1990** [comment]
Yes, and problem is using mouse then using keyboard. The step will be confused. I just clicked 'Back' with mouse then 'Enter' with keyboard and same problems

**Comment by gilbarbara** [comment]
This is fixed in V2.
You can try it with `npm i react-joyride@next`
