### ISSUE TITLE
Button inside button not working in Firefox. Please change default Button to Div

### ISSUE THREAD

**Issue by nighttiger1990** [gilbarbara/react-joyride#274]
I searched my problems and got this.
https://stackoverflow.com/questions/26517121/element-inside-button-does-not-fire-click-event-in-firefox
Please changes  all default `<button>` to `<div>` tag in all 'LOCALE' props.
Im got problems when customize them on FireFox. Inside button won't fire event
Example in my below code: `skip_not_remind` function wasn't fire in FireFox

`locale={{skip:(<div className='joyride-tooltip__button'>`
`<span className='joyride-tooltip__button joyride-tooltip__button--secondary'>Skip </span>`
`<button onClick={this.skip_not_remind} className='joyride-tooltip__button joyride-tooltip__button--primary'>Skip and not remind again</button>)`
`</div>}}`

**Comment by gilbarbara** [comment]
The code passed to the `locale` will be rendered inside a button.
Feel free to suggest how it would work without losing the ability to pass a simple string to it.
