### ISSUE TITLE
Pass stepIndex to reset()

### ISSUE THREAD

**Issue by heynah** [gilbarbara/react-joyride#275]
I would like to call `reset()` with a stepIndex param. 

Uses would be to only ever show the welcome message once, or to start users at different steps based on who they are / where they are in the joyride. 

Is there a way to achieve this behaviour already?

**Comment by gilbarbara** [comment]
You could filter your steps before passing them to Joyride and start from there.

Anyway, I'll deprecate all methods in V2 and `steps` will be handled differently.
