### ISSUE TITLE
Avoid changing step when action is empty

### ISSUE THREAD

**Issue by qgadrian** [gilbarbara/react-joyride#276]
Hi all, first thank you for this library!

I'm having a problem where the Joyride is used in a parent component that eventually might call render method.

The problem is that when that happens, Joyride is automatically changing to next step.

This is the data received in the callback prop when the Joyride's parent is re-rendered:

`{action: "", index: 1, type: "step:after", step: {…}}`

And the data when the button is clicked, as you already know:

`{action: "next", index: 1, type: "step:before", step: {…}}`

It is possible ignore an empty action for Joyride?

The workaround here is reset Joyride (I'm currently re-rendering with the remaining steps), but it's not ideal as the next step is showing before the reset, looking really bad.

Regards!

**Comment by gilbarbara** [comment]
Can you provide a demo?
