### ISSUE TITLE
step option "text" as a function

### ISSUE THREAD

**Issue by jakub-gawlas** [gilbarbara/react-joyride#278]
Hi folks 😃 

Would be nice to pass step option `text` as a function, where first parameter will be a joyride context.

It could be used this way:
```js
{
   ...
   text: (joyride) => <Tooltip progress={joyride.getProgress()} />
   ...
}
```

What do you think?

Cheers :clinking_glasses:

**Comment by gilbarbara** [comment]
I don't understand what you are proposing. Can you please elaborate?
