### ISSUE TITLE
Optional selector

### ISSUE THREAD

**Issue by 5an1ty** [gilbarbara/react-joyride#279]
If no selector give, just show the step in the middle of the screen. This way our first step could be something like:

step 1) floating in the middle of the screen "Hello, let's give you a tour"
step 2) info of a specific element
step 3) ...

**Comment by monsieurnebo** [comment]
That's a good idea!

**Comment by gilbarbara** [comment]
It's possible to use the `center` placement in V2.
If you don't have a target selector (for scrolling) just use the `body`.

`npm i react-joyride@next`

[s]

**Comment by keul** [comment]
Using `body` and `center` works until you have a short page. When the page is long you can obtain a bearer somewhere below the fold.

**Comment by gilbarbara** [comment]
@keul Yeah, but this library can't change the app styling. If you don't have space, there's no magic.

**Comment by keul** [comment]
@gilbarbara sure, my intention was to say this is not a silverbullet solution but just enough for most usecases.
Wanted to highlight that original request was (probably) a little different, like a modal fixed at the center of the viewport or something like that.
