### ISSUE TITLE
Function to close the joyride

### ISSUE THREAD

**Issue by etshi** [gilbarbara/react-joyride#28]
Is there a function similar to `this.joyrideStart()` but to stop/close the joyride ?

**Comment by gilbarbara** [comment]
you could use `joyrideReplaceSteps` with a empty array or maybe turn on the `showSkipButton` option.

**Comment by etshi** [comment]
Thanks for your help. appreciate your prompt response.

I am already using `joyrideReplaceSteps` which does the trick, I was just wondering if there is a function or another way which I have missed or not stated in the guide. So you may close this issue.

**Comment by gilbarbara** [comment]
@etshi I'm refactoring this to be a component instead of mixin so the API will change soon.
Tell me more about what you are thinking about this functionality..
It will kill the whole tour or just pause it? Why would you kill it?

[s]

**Comment by etshi** [comment]
>It will kill the whole tour or just pause it? Why would you kill it?

I am looking for something to reset it to it's initial state

**Comment by etshi** [comment]
In my case I am using it in an App where it should be displayed in certain pages only. So in case I transition from a page where it is displayed to a page where it should not be displayed I need Something to kill/reset it.
