### ISSUE TITLE
Distribute unminified version as `main`

### ISSUE THREAD

**Issue by jayphelps** [gilbarbara/react-joyride#280]
Any objections to distributing the unminified version as the default for package.json `"main"` Bundlers like webpack won't pass-along source maps of dependencies by default, without something like [source-map-loader](https://github.com/webpack-contrib/source-map-loader), which [requires forking/ejecting from create-react-app](https://github.com/facebookincubator/create-react-app/pull/2355).

Noticed this because I'm trying to debug an issue related to joyride but it's very hard to figure out if it's my app (probably) or joyride itself.

***

Thanks for maintaining this library btw. It's awesome 🚀

**Comment by gilbarbara** [comment]
Hey,
Yeah, I can refactor the build process to transpile the individual files to `/lib` without uglifying and remove the source-map.

Thanks! :)

**Comment by gilbarbara** [comment]
@jayphelps Fixed!
Let me know if it worked.

[s]

**Comment by jayphelps** [comment]
@gilbarbara works perfectly. Thank you much! 🕺
