### ISSUE TITLE
Can't resolve 'prop-types' (production deploy)

### ISSUE THREAD

**Issue by Emeroj** [gilbarbara/react-joyride#285]
Hello there!

I've been successfully using react-joyride in the development environment. Great library!

However, when deploying to Heroku it appears to be unable to find the package 'prop-types'. I've checked the package.json in react-joyride and the 'prop-types' package is definitely in there. I'm deploying with webpack and an express server.

Below are my errors from the attempted deploy through heroku cli:

`remote:        ERROR in ./~/react-joyride/es/index.js`
`remote:        Module not found: Error: Can't resolve 'prop-types' in `
`'/tmp/build_0a778da283b714fe52935e1859f26089/node_modules/react-joyride/es'`
`remote:        @ ./~/react-joyride/es/index.js 14:0-35`
`remote:        @ ./app/containers/CableListener.js`
`remote:        @ ./app/containers/App.js`
`remote:        @ ./app/config/routes.js`
`remote:        @ ./app/index.js`
`remote:        @ multi whatwg-fetch babel-polyfill ./app/index.js`
`remote:`
`remote:        ERROR in ./~/react-joyride/es/Beacon.js`
`remote:        Module not found: Error: Can't resolve 'prop-types' in '/tmp/build_0a778da283b714fe52935e1859f26089/node_modules/react-joyride/es'`
`remote:        @ ./~/react-joyride/es/Beacon.js 10:0-35`
`remote:        @ ./~/react-joyride/es/index.js`
`remote:        @ ./app/containers/CableListener.js`
`remote:        @ ./app/containers/App.js`
`remote:        @ ./app/config/routes.js`
`remote:        @ ./app/index.js`
`remote:        @ multi whatwg-fetch babel-polyfill ./app/index.js`
`remote:`
`remote:        ERROR in ./~/react-joyride/es/Tooltip.js`
`remote:        Module not found: Error: Can't resolve 'prop-types' in ` `'/tmp/build_0a778da283b714fe52935e1859f26089/node_modules/react-joyride/es'`
`remote:        @ ./~/react-joyride/es/Tooltip.js 12:0-35`
`remote:        @ ./~/react-joyride/es/index.js`
`remote:        @ ./app/containers/CableListener.js`
`remote:        @ ./app/containers/App.js`
`remote:        @ ./app/config/routes.js`
`remote:        @ ./app/index.js`
`remote:        @ multi whatwg-fetch babel-polyfill ./app/index.js`

I get the feeling that it may be to do with babel?? There is another package installed that removes "unnecessary" prop-types from production:
`babel-plugin-transform-react-remove-prop-types`

Could it be possible that this package is disrupting the imports of 'prop-types' for Tooltip.js, index.js and Beacon.js?

I'm fairly new to development, so I may be way way off the mark.

Is this enough information to diagnose?
Any help appreciated!

**Comment by gilbarbara** [comment]
@Emeroj `prop-types` is a [peerDependency](https://docs.npmjs.com/files/package.json#peerdependencies), so you probably need to install it in your project.
Try `npm install --save prop-types` and let me know if it works.

**Comment by Emeroj** [comment]
@gilbarbara thanks for the tip, yes that worked. 

prop-types is listed as a dependency in the react-joyride `package.json`, so shouldn't that be installed as part of that? Or is my understanding of how dependencies work incorrect?

Really love the library mate. Looks awesome. Great user experience.

**Comment by gilbarbara** [comment]
hey

`prop-types` is listed in both **peerDependencies** (you need to install in your project) and **devDependencies** (it will only install in development mode).

The only 2 **dependencies** are "nested-property" and "scroll" and they will be installed in your project since this library need them to work.

Yeah, it's a bit complicated at first. :)
