### ISSUE TITLE
Possibility to use in React Native project

### ISSUE THREAD

**Issue by eugene-zheng0208** [gilbarbara/react-joyride#286]
I imported the package into my RN project but seems to be not working at all.
I want to know exactly how we can use the package in RN project.
Thank you

**Comment by gilbarbara** [comment]
I don't think that's possible since this library relies on the DOM but I never tried.
Let me know if it works for you.

**Comment by eugene-zheng0208** [comment]
Unfortunately, not worked for react-native.
I hope you could by any change make another version for react-native.

**Comment by bryantobing12** [comment]
any recommendation what lib to use for react native?
