### ISSUE TITLE
SCSS - File to import not found or unreadable: ~react-joyride/lib/react-joyride.

### ISSUE THREAD

**Issue by Vadorequest** [gilbarbara/react-joyride#287]
I tried using (as the doc states) in my `index.scss`:

`@import '~react-joyride/lib/react-joyride'`

But I got the following error (using create-react-app):

```
{
  "status": 1,
  "file": "/home/vadorequest/www/student-loan-simulator/src/index.scss",
  "line": 3,
  "column": 1,
  "message": "File to import not found or unreadable: ~react-joyride/lib/react-joyride.\nParent style sheet: /home/vadorequest/www/student-loan-simulator/src/index.scss",
  "formatted": "Error: File to import not found or unreadable: ~react-joyride/lib/react-joyride.\n       Parent style sheet: /home/vadorequest/www/student-loan-simulator/src/index.scss\n        on line 3 of src/index.scss\n>> @import '~react-joyride/lib/react-joyride';\n   ^\n"
}

npm ERR! Linux 4.13.0-17-generic
npm ERR! argv "/home/vadorequest/.nvm/versions/node/v6.12.0/bin/node" "/home/vadorequest/.nvm/versions/node/v6.12.0/bin/npm" "run" "build-css"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! student-loan-simulator@0.1.0 build-css: `node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the student-loan-simulator@0.1.0 build-css script 'node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the student-loan-simulator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs student-loan-simulator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls student-loan-simulator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vadorequest/www/student-loan-simulator/npm-debug.log

```

I loaded the file differently using `@import '../node_modules/react-joyride/lib/react-joyride';` in my `index.scss` file and it compiled correctly. Maybe the doc should provide that alternative? I don't really understand how works the path with the `~`.

**Comment by Vadorequest** [comment]
Great "plugin", The doc isn't so easy to read IMHO, I first thought the setup was way more complicated than it actually is. Kinda reluctant to jump in, but it went fine.

```
    <Joyride
          locale={{
            back: (<span>Retour</span>),
            close: (<span>Fermer</span>),
            last: (<span>Finir</span>),
            next: (<span>Suivant</span>),
            skip: (<span>Ignorer</span>),
          }}
          showOverlay={true}
          showSkipButton={true}
          showStepsProgress={true}
          type={'continuous'}
          steps={[
            {
              title: 'Title1',
              text: `Text1`,
              selector: '#recommended-header',
              position: 'top',
            },
            {
              title: 'Title2',
              text: `Text2.`,
              selector: '#simulated-header',
              position: 'top',
            },
          ]}
          run={true}
          autoStart={true}
          debug={false}
        />
```

This is one very simple example, that doesn't rely on `ref`, or nested components or anything, and it works almost perfectly. Maybe worth adding such a simple example to the doc? Or a very simple demo project, yours is very complicated due to the many options. (awesome to see what features it has to offer, but hard to dive in when looking for simple use case)

I noticed a strange behavior with scrolling, it doesn't work the first time, and it scrolls when we leave the tour (shouldn't IMO). Maybe a side effect of not using `ref`? No idea. But I found a workaround anyway.

**Comment by gilbarbara** [comment]
Hello,
`create-react-app` doesn't support SASS by default, did you eject it?
It might be a problem your setup since I got this working in many projects with webpack. This is an [comment](https://github.com/webpack-contrib/css-loader/issues/12#issuecomment-41940311) explaining the use of `~`.
You can read more about it in the webpack [documentation](https://webpack.js.org/configuration/resolve/) for module resolution.

**Comment by gilbarbara** [comment]
I'll refactor the README and the examples for V2.

 - You don't need to set props with the same value as the default, such as `showOverlay` or `debug`
- If you pass the steps before they are rendered, the first scrolling will not occur since the target isn't positioned yet. If it works in the demo, it's probably an issue with your implementation.

**Comment by Vadorequest** [comment]
You can add SCSS support without ejecting. Unsure about SASS, but SCSS works fine.

Scrolling worked fine when using the "tour" mode and not "standalone".

**Comment by rodrigobacelli** [comment]
Little late:

Try adding `--importer=node_modules/node-sass-tilde-importer` to your `build-css` task (do not forget to install [`node-sass-tilde-importer`](https://www.npmjs.com/package/node-sass-tilde-importer))
