### ISSUE TITLE
next() is a reserved keyword

### ISSUE THREAD

**Issue by cjtafoya** [gilbarbara/react-joyride#289]
Started having issues in production with Joyride. When inspecting the react element, it appears the `next()` function call is actually trying to use the Object constructor as its prototype. Believe this is because `next()` is a reserved keyword. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/next

**Comment by gilbarbara** [comment]
Hello,

Next isn't a reserved word. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
The link you posted is about the prototype of generators which isn't used in Joyride.

If you could create a simple [create-react-app](https://github.com/facebookincubator/create-react-app) setup and still encounter this error, feel free to re-open and post a link to it.
