### ISSUE TITLE
Styling for last step

### ISSUE THREAD

**Issue by etshi** [gilbarbara/react-joyride#29]
Is there a way to change styling of tooltip for only last step.

In my case I would like the step button to not show in the last step but show on all other steps.
I also would like to give the last button a different colour.

Is that possible.

**Comment by gilbarbara** [comment]
hey!
I just published version 1.0 that adds custom styling for tooltips and other improvements.
But it is a major refactor with breaking changes and now it requires React 0.14

I'll add a few other styling options for hiding elements later.. If you have other suggestions, please let me know.

cheers

**Comment by etshi** [comment]
Really nice job

**Comment by gilbarbara** [comment]
@etshi Thanks! :+1: 
Styling options for the button added in 1.0.1
