### ISSUE TITLE
Component as `text` not working

### ISSUE THREAD

**Issue by consultwithmike** [gilbarbara/react-joyride#290]
I wanted to embed a Component as the `text` property for a step. Based on the code, it looks like this is quite possible. However, I've only been able to get this to work with inline JSX.

## Working Example

```
{
  title: 'Some Title',
  text: (<div>Some text.</div>),
  selector: ':some_selector',
  position: 'top',
  style: {
    mainColor: '#ff00ff',
    beacon: {
      inner: '#CB3CFF',
      outer: '#CB3CFF'
    }
  }
}
```

## Failing Example

```
import MyComponent from "../components/joyride/MyComponent";

...

{
  title: 'Some Title',
  text: MyComponent,
  selector: ':some_selector',
  position: 'top',
  style: {
    mainColor: '#ff00ff',
    beacon: {
      inner: '#CB3CFF',
      outer: '#CB3CFF'
    }
  }
}
```

Is there a reason that the inline JSX is working but referencing a Component is not? I've tried exporting a standard Component as well as a functional component - neither work.

**Comment by gilbarbara** [comment]
Hey,

You need to pass a `node` to the text prop.
*Anything that can be rendered: numbers, strings, elements or an array (or fragment) containing these types.*
As described [here](https://github.com/facebook/prop-types)

`MyComponent` is a function when you import it, so you to execute it.
<MyComponent /> will do.

**Comment by consultwithmike** [comment]
@gilbarbara my apologies - I should have picked up on that! Thanks for your help and I'm sorry for wasting your time on that one.
