### ISSUE TITLE
disableOverlay:true disables hole:click event

### ISSUE THREAD

**Issue by darrenmerrett** [gilbarbara/react-joyride#292]
I want to disableOverlay but I want to catch the hole:click event.

I don't want people to be able stop the tour, hence disableOverlay, but I also want to catch the hole:click event so I can disable an alert telling them to finish the tour first.

**Comment by gilbarbara** [comment]
Since you don't want to use the overlay, you don't get a hole. ¯\_(ツ)_/¯

You could just simply add an event listener on the element you want people to use to advance and call `.next()` on it. Since there's no overlay, you can interact with all elements in the page.

**Comment by darrenmerrett** [comment]
I meant the option disableOverlay, "disableOverlay {bool}: Don't close the tooltip on clicking the overlay. Defaults to false".

I want to disable clicking on the overlay, but this also disables clicking on the hole.
