### ISSUE TITLE
disableOverlay:true disables hole:click event

### ISSUE THREAD

**Issue by darrenmerrett** [gilbarbara/react-joyride#293]
I want to disable the click on overlay by using disableOverlay "disableOverlay {bool}: Don't close the tooltip on clicking the overlay. Defaults to false", but I want to catch the hole:click event.

I don't want people to be able stop the tour, hence disabling click on the overlay, but I also want to catch the hole:click event so I can disable an alert telling them to finish the tour first.

**Comment by gilbarbara** [comment]
duplicate
