### ISSUE TITLE
Outstanding issues

### ISSUE THREAD

**Issue by darrenmerrett** [gilbarbara/react-joyride#294]
Please can you take a look at this again, it is a genuine issue.

https://github.com/gilbarbara/react-joyride/issues/293

I want to show the overlay, disable the click on overlay but still catch hole:click. Currently disabling click on overlay also disables click on hole.

**Comment by gilbarbara** [comment]
Seriously dude, WTF! Stop opening issues on the same subject.
There's no premium support in open source...

Here's the repo's demo updated to be a mandatory tour: https://1oppqow7l3.codesandbox.io/
And here's the source code: https://codesandbox.io/s/1oppqow7l3

Please stop opening issues about implementation. If you need help try stackoverflow or something.
