### ISSUE TITLE
Is it possible to trigger a beacon in code

### ISSUE THREAD

**Issue by robertzimmerman** [gilbarbara/react-joyride#295]
Hi, I was wondering if its possible to trigger a beacon based on an action through code.

I would like to do the following
example, I have my tour start in an input field, once a value has been entered in the field, another the next tooltip will popup. 

I would really like it if we did not need beacons at all and it would just show tooltip based on actions of the user. Would this be possible with react-joyride.  

Any help will be much appreciated. Thank you

**Comment by robertzimmerman** [comment]
sorry i just read a previous issue with beacons and how to stop the tour.

**Comment by gilbarbara** [comment]
Use tooltips.

I've published a new component that I'll use in react-joyride for that: [react-tooltips](https://github.com/gilbarbara/react-tooltips)

**Comment by toddmedema** [comment]
I'm having the same issue - how to start the tour via code. Unfortunately, @robertzimmerman didn't link to the solution he found, and I'm not sure how using tooltips fixes this (I'm already implementing a custom `tooltipComponent`)

I was hoping that setting run = false until it's triggered, and then flipping it to run = true would auto-start the tour, but that doesn't seem to be working.

For reference, here's my implementation: https://github.com/toddmedema/electrify/blob/master/services/app/src/components/Compositor.tsx#L172

**Comment by toddmedema** [comment]
@gilbarbara am I missing something?

**Comment by gilbarbara** [comment]
@toddmedema I can't say just by looking at the code. Did you get anything in the console? Did you try to enable debug?
Apparently you are starting the tour on the initial render before the steps are mounted. Try to start the tour after the component is mounted.

**Comment by toddmedema** [comment]
I've confirmed that the Tooltip function is only getting called when the first target (#tooltip) exists, via `function Tooltip(props: TooltipProps): JSX.Element { console.log(document.getElementById('topbar') !== null); }`

I tried turning on debug mode - not really sure what to look for, but I don't see any errors. This is what it logs when it loads that first page, before I click on the beacon (clicking on the beacon actually doesn't log anything additional):

```
react-joyride: init
react-floater: init
react-joyride: step:0
```

I'd expect that when step 0 is fired, and the tour is enabled via `run=true`, that the tutorial would start automatically... I'm not sure what else to try. @gilbarbara  Any other suggestions for debugging?

**Comment by gilbarbara** [comment]
@toddmedema No. It's impossible to debug without seeing the code running.

**Comment by toddmedema** [comment]
For future people who find this issue: gil helped me through it via email, I ended up just having to set `disableBeacon: true` on my first step - https://docs.react-joyride.com/step

**Comment by alexpopa-work** [comment]
@toddmedema it's an old comment but it still saves the day. Needed the same thing, turns out that `disableBeacon: true` launches the tour without creating beacons. Exactly what was needed. Thanks.
