### ISSUE TITLE
Cannot render two tooltips against the same selector back-to-back

### ISSUE THREAD

**Issue by consultwithmike** [gilbarbara/react-joyride#297]
For whatever reason, you cannot render two tooltips back-to-back when they leverage the same selector. Here is a [`CodeSandbox` example](https://codesandbox.io/s/r4kqp80o54).

The SASS and styling isn't loaded, but you can see the second tooltip does not show up.

**Comment by gilbarbara** [comment]
I couldn't understand the problem reviewing your demo.

Anyway, you should use pseudo qualifiers to handle elements with the same selector.
`nth-of-type`, `nth-child` or similar.

**Comment by consultwithmike** [comment]
@gilbarbara the problem is that the tooltip is rendered but doesn't show up. I've tracked it down to positioning. In my example I'm dropping the tooltip on the `h2` - how would I use some kind of pseudo-selector on that?

**Comment by gilbarbara** [comment]
add the stylesheet to your demo: `import 'react-joyride/lib/react-joyride-compiled.css';`
It's a front-end component, for god's sake! 😁 

BTW, It's not possible to use the same element for different steps... I don't see the point of having a tour to highlight the same element more than once.

If you had two different elements you could use pseudo selectors to match them in the correct sequence.

If you just need to highlight single elements with a beacon/tooltip, please use [react-tooltips](https://github.com/gilbarbara/react-tooltips)

**Comment by consultwithmike** [comment]
Well, the point would be to joyride the features of an application where the work was done inside of a single element. But, alas, it looks like you're not interested in that use case. So, I guess there's nothing I can do.

Further, sorry I frustrated you over the CSS, sure didn't mean to get things all wound up over this.

Good day.
