### ISSUE TITLE
beacon.offsetX and offsetY only work for certain values of position

### ISSUE THREAD

**Issue by ajprax** [gilbarbara/react-joyride#298]
I'd like to be able to fully control the relative positioning of the beacon, but when I tried using `offsetX` and `offsetY` I found that only one would be respected at a time. I did a little digging in the code and found that `offsetX` is only respected when `position: /^(left|right)/` while `offsetY` requires `position: /^(top|bottom)/`.

If there isn't a technical reason why these constraints are required I'd be happy to work up a pull request to remove them.

**Comment by gilbarbara** [comment]
This will be fixed in V2 since I'll be using a new package to handle the positioning.
