### ISSUE TITLE
[Feature Request] Make Tooltip and Beacon component customizable

### ISSUE THREAD

**Issue by tobilen** [gilbarbara/react-joyride#299]
I am using styled-components in my project, and i'd like to style joyride with it as well.

The easiest way to achieve this would be to make its subcomponents, `Tooltip` and `Beacon` passable as props. This would also open up a useful escape hatch for other kinds of customization.

Example:
```jsx
import Tooltip from 'react-joyride/lib/Tooltip';
import styled from 'styled-components';

const StyledTooltip = styled(Tooltip)`
  background-color: red;
`;

<Joyride
 // ...
  tooltipComponent={StyledTooltip}
/>
```

**Comment by gilbarbara** [comment]
How do you propose to control the tour using custom components?

**Comment by gilbarbara** [comment]
@tobilen👆

**Comment by tobilen** [comment]
For the purpose of wrapping styles around `Tooltip` and `Beacon` components, you can check out the associated PR, and my example above for how to use it.

A nice story to extend this idea, and which hopefully answers your question, would be to make `Tooltip` and `Beacon` be able to receive render props, which would pass all "controls" as arguments. for example: 

```jsx
import Joyride from 'react-joyride';
import Tooltip from 'react-joyride/lib/Tooltip';

const CustomTooltip = (
  <Tooltip
    render={({ onClose, onNext, onPrevious, content }) => (
      <div>
        <button onClick={onClose}>Close Me</button>
        {content}
        <button onClick={onPrevious}>Previous</button>
        <button onClick={onNext}>Next</button>
      </div>
    )}
  />
);

return <Joyride tooltipComponent={CustomTooltip} />;
```

i plan on doing something like this to the version of joyride i forked a couple of days ago, but i'll also create a PR on this one, so you can take a look at the implementation.

**Comment by gilbarbara** [comment]
Yeah, I misunderstood what you tried to do with your PR. I was thinking about a full customization but it was only skin deep, that why I asked this.

IN V2 I will use [react-tooltips](https://github.com/gilbarbara/react-tooltips) to handle the tooltips and all the styling will be done with inline-styles. And that's why I'm not accepting PRs to change the behavior of the current implementation here.

But I'm not sure about the custom render since the user can change all styles with a single object.

**Comment by tobilen** [comment]
Providing a render prop on requires you to know how the component you're passing it to works internally. Including the `styles` object in this case. Thats the downside to providing a great hatch into the presentational logic of your library.

For example, i want my own components (button, tooltip, close icon etc.) to use joyrides logic.

I assume you'll still be wrapping react-tooltip with your own tooltip component to inject default functionality into them (close button, next button etc.). This is great for getting set up quickly. For individualisation, nothing beats render props imo.

**Comment by gilbarbara** [comment]
handled in #304
