### ISSUE TITLE
IE 10 Error

### ISSUE THREAD

**Issue by etshi** [gilbarbara/react-joyride#30]
I am still using version `0.7.6` and getting the following error `Unable to get property 'type' of undefined or null reference` when clicking on next to go from one step to the next. This error only occurs in IE 10, works fine in IE 11, Safari, Chrome , Opera and Firefox.

Did anyone report a similar issue before? Can you recreate the issue in IE10? Or is it something just from my side?

**Comment by etshi** [comment]
I believe that this might be related to that IE 10 does not support `*.dataset`.
[stackoverflow](http://stackoverflow.com/questions/7127896/problem-using-elem-dataset-with-ie-and-jsfiddle)
So If this is the case and there is a quick fix to `v0.7.6`, I would be very grateful.

**Comment by gilbarbara** [comment]
I'm going to test it with all browsers for v1.1 but I don't have plans to continue support for 0.x.

You can load a polyfill for IE <11..
https://gist.github.com/brettz9/4093766

**Comment by etshi** [comment]
Thanks. But Is there noway you can include this polyfill for version 0.7.6. The thing is not all have migrated to react v0.14 yet.

**Comment by gilbarbara** [comment]
Not really. 
You'll need to load the polyfill globally in your html file if some criteria is met.

```
<!--[if lt IE 11]>
    <script src="path/to/html5-dataset.js"></script>
<![endif]-->
```

**Comment by etshi** [comment]
Thanks.
