### ISSUE TITLE
Issue when using nth-child it doesn't work as expected.

### ISSUE THREAD

**Issue by deepu105** [gilbarbara/react-joyride#301]
First of all awesome library guys. thanks.
It seems the selection of element doesn't work as expected when using nth-child. Using a simple `nth-child(2)` works but `nth-child(-n+2)` doesn't work as it still only selects one element.

For example, if I change the step in the demo to below it doesn't work as expected. I was expecting first 2 items to be selected but instead, only first item (the equivalent of `nth-child(1)`) was selected.
```
        {
          title: 'Title only steps — As they say: Make the font bigger!',
          textAlign: 'center',
          selector: '.projects .list > div:nth-child(-n+2)',
          position: 'top'
        }
```

**Comment by gilbarbara** [comment]
Hey,

I'm not sure if I understand what you to do. Do you want to set multiple targets for a single "step"?
It it's that, it will not work.

**Comment by deepu105** [comment]
@gilbarbara I guess I was expecting the CSS selector to work, and in this case, it means yes selecting multiple elements. Thanks for clarifying. Do you have plans for enabling selection of multiple elements?

**Comment by gilbarbara** [comment]
I'll support multiple steps for the same target in V2, in case the user changes the content dynamically but I can't think of a use case for the other way around.
