### ISSUE TITLE
use querySelectorAll to enable selectors with index

### ISSUE THREAD

**Issue by rogeliotg** [gilbarbara/react-joyride#302]
on my code, to discard bad steps selectors I use:
var num =/\[(\d+)\]/.exec(aux[2]);
          var nododom=null;
          if (num) {
            nododom =document.querySelectorAll(aux[2].substring(0, aux[2].indexOf('['))).item(num);
          } else {
            nododom =document.querySelector(aux[2]);
          }
if (nododom)  addStep

I propose a similar approach in library to enable selectors as .menu[1] that now fail.

**Comment by gilbarbara** [comment]
I can't understand the code you posted. 
Why are are adding steps with bad selectors to start with?

**Comment by gilbarbara** [comment]
I'm closing this since I can't choose for the user which selector I should use from the list returned by querySelectorAll.

**Comment by rogeliotg** [comment]
what I proposed is that when the selector end on [3], you use querySelectorAll, and return 3 on resulting list
