### ISSUE TITLE
Provide alternative way to render Joyride via render props

### ISSUE THREAD

**Issue by tobilen** [gilbarbara/react-joyride#304]
As discussed [here](https://github.com/gilbarbara/react-joyride/issues/299#issuecomment-363058651), a [render prop](https://reactjs.org/docs/render-props.html) would provide a great way to modify presentation of joyrides tour steps, for example use your own buttons or tooltip component.

This is how you could potentially use it:
```jsx
import Joyride from 'react-joyride';
import Tooltip from 'react-joyride/lib/Tooltip';

const CustomTooltip = (
  <Tooltip
    render={(tooltipProps, tooltipState) => (<div>
        <span className="custom-header" style={tooltipState.styles.header}>
          {tooltipProps.step.title}
        </span>
      </div>)
    }
  />
);

return <Joyride /* ... other Joyride props */ tooltipComponent={CustomTooltip} />;
```

**Comment by gilbarbara** [comment]
hey,

I use render props in several apps and it's awesome.
However, I can't stop thinking about the shitload of issues from newbies trying to be cool, messing things up and complaining it's a bug... 😩
OSS is a bitch.

**Comment by gilbarbara** [comment]
This will come soon. You can try it with: `npm i react-joyride@next`
