### ISSUE TITLE
Pass ref's as selectors

### ISSUE THREAD

**Issue by tobilen** [gilbarbara/react-joyride#311]
So currently we have the ability to pass xpath selectors to joyride to attach tour steps to certain elements. I'd argue that those are a bit of an anipattern, especially in the react ecosystem, and references are the preferred way of identifying elements within an application.

Seeing as we can pass components for the `text` key, It'd be pretty cool if we could pass references instead of strings in the `selector`:

```jsx
class RefDemo extends React.Component {
    render() {
      const joyrideProps = {
        // ... ,
        steps: [
          {
            text: 'Tooltip Text.',
            selector: this.selectorRef,
          },
        ],
      };

      return (
        <div>
          <Joyride {...joyrideProps} />
          <div ref={c => { this.selectorRef = c; }}>
            Tour Anchor
          </div>
        </div>
      );
    }
  }
```

**Comment by gilbarbara** [comment]
I'm not sure using refs right now is a [good thing]((https://reactjs.org/docs/refs-and-the-dom.html#dont-overuse-refs))...
The ref is only set after the component is mounted and this can get tricky when the component you are trying to use as a ref is nested deep in the tree. 

Your own example wouldn't work because the ref is only set after the component has mounted and it doesn't trigger a new render.

Disabling the tour because a step isn't mounted don't feel like a good idea.
Instead, I was thinking about adding "async" steps that it would wait for a max `timeout` before skipping it.

**Comment by gilbarbara** [comment]
To use refs in a much simpler scenario I had to use a bound class method and trigger a forceUpdate to get it to work.

```jsx
export default class TooltipProxyMode extends React.Component {
  setRef = c => {
    this.target = c;
    this.forceUpdate();
  };

  render() {
    return (
      <div>
        <Target innerRef={this.setRef} />
        {this.target && ( // <- target is only valid in the second render
          <Tooltip
            content="hello"
			target={this.target}
		  />
		)}
	  </div>
	);
  }
}
```

**Comment by gilbarbara** [comment]
@tobilen 
react-tooltips supports `refs` as the target so this will be possible in V2. However, I'm not sure it's a good practice.

The React team is working on a better approach for this problem, so a lot can change.

**Comment by tobilen** [comment]
yeah, the mounting problem definitely exists with refs. given the choice between refs and xpath selectors, im definitely in favor of refs though. especially in joyrides usecase. we always want the selectors to be single-element-identifiers.
The async path might be a good idea, but it would require documentation as well as user maintained code. They'd have to create promises and resolve them upon element rendering.

**Comment by gilbarbara** [comment]
Yes, there's no magic.

**Comment by tobilen** [comment]
people using joyride. there is no reason to ever pass a selector thats not unique on the site.

**Comment by alv22** [comment]
@tobilen Of course there is. Please don't speak for everyone else. For example, my company uses Joyride as a general contexthelp for elements of the GUI. Same type of elements may appear in a bit different contexts on different pages, but the help texts are always the same for each type. Refs wouldn't work at all here, xpath selectors work absolutely perfectly.
