### ISSUE TITLE
mouseOverHole not properly getting set edge case 

### ISSUE THREAD

**Issue by Nicky-P** [gilbarbara/react-joyride#313]
There is a scenario where a user is able to click through the overlay because mouseOverHole is always set to true. 

**Reproduction steps:**
version: 1.11.2

1. Set disableOverlay and showOverlay to true.
2. Create a step that has allowClickThruHole set to true and create the next button so that it is within the hole (this is the set up for the second step in the demo).
3. Create a second step that has allowClickThruHole set to false.
4. When running, click next button within the hole of the first step.
5. Notice that mouseOverHole is never updated and that it is now possible to click through the overlay and interact with components behind it.

**Bug:**
It appears that this bug is occurring because within Tooltip.jsx, componentWillReceiveProps(), the mousemove event listener unsubscribes and the mouseOverHole state is never updated.

**Comment by gilbarbara** [comment]
yeah, the whole `allowClickThruHole` is a big fat hack...
if you can think of a proper way to do it, let me know.

**Comment by Nicky-P** [comment]
For some reason, whenever I make changes to the Joyride source code in the demo, I am not seeing the changes being applied to the demo app.  So I have not had a chance to test this, but continuing with the allowClickThruHole paradigm... I believe the fix would be as simple as adding `this.setState({ mouseOverHole: false });` to componentWillReceiveProps() within Tooltip.jsx.  This way the mouseOverHole state is always getting reset and updated regardless of the event listener.

**Comment by Nicky-P** [comment]
@gilbarbara any update on this?

**Comment by gilbarbara** [comment]
Nope

**Comment by gilbarbara** [comment]
can you try v2 and let me know if it's still a problem?
`npm i react-joyride@next`

**Comment by Nicky-P** [comment]
I was able to test the fix I mentioned above and it works.  I have not had the chance to check if the problem exists in v2.  I will let you know when I get a chance.
