### ISSUE TITLE
Standalone Tooltip Documentation

### ISSUE THREAD

**Issue by mahburg** [gilbarbara/react-joyride#316]
The documentation only barely references the standalone tooltip and the code in the example doesn't make it clear what needs to be done make sure that the tooltip isn't part of the rest of the walkthrough.

**Comment by gilbarbara** [comment]
hey

Standalone tooltips are deprecated and will be removed in the next version.
Please try [react-tooltips](https://github.com/gilbarbara/react-tooltips)

**Comment by mahburg** [comment]
Bummer. But thanks for making the package and the recommendation. And double thank you for the quick reply!
