### ISSUE TITLE
Hole selector is not working

### ISSUE THREAD

**Issue by MichaelA59** [gilbarbara/react-joyride#317]
I am including some CSS styling in my Steps const, pointed at `hole` but nothing seems to work. I thought maybe `width` is a problem but when trying different CSS properties, they also failed to take.

```
const coach_sessionsTab = [
  {
    title: 'Sessions',
    text: 'This is where you will find a full list of all coaches available to work with you',
    selector: '#sessions-tab',
    position: 'right',
    type: 'hover'
  },
  {
    title: 'Session Scheduling',
    text: 'This is where you will find a full list of all coaches available to work with you',
    selector: '#dash-tabs',
    position: 'right',
    type: 'hover',
    hole: {
      width: '20%'
    }
  }
];
```

**Comment by gilbarbara** [comment]
hey

Read the [step-syntax](https://github.com/gilbarbara/react-joyride#step-syntax) carefully. You must pass the `hole` key inside a `style` object.
But messing with the dimension will probably break it.

**Comment by MichaelA59** [comment]
Hey, sorry about that. My post didn't reflect the code I was actually trying, that's on me.

I had the `hole` wrapped in a style object. `width: ` is still not working but other stuff like `backgroundColor` does work...

```
const coach_sessionsTab = [
  {
    title: 'Sessions',
    text: 'This is where you will find a full list of all coaches available to work with you',
    selector: '#sessions-tab',
    position: 'right',
    type: 'hover'
  },
  {
    title: 'Session Scheduling',
    text: 'This is where you will find a full list of all coaches available to work with you',
    selector: '#dash-tabs',
    position: 'right',
    type: 'hover',
    style: {
      hole: {
        backgroundColor: 'red'
        width: '20px'
      }
    }
  },
];
```

@gilbarbara

**Comment by gilbarbara** [comment]
@MichaelA59 Yeah, some styles may be overwritten by the hole's size calc.
Can you explain why would you need to change the hole sizing?
I don't plan to change this behavior but if I could understand what you want...

**Comment by MichaelA59** [comment]
Yea, sure. Basically I have a bunch of pages that are broken up into tabs. Style-wise, the div runs the course of the page really and it has to be like that. I was hoping to first do a `step` showing the whole tab bar and then each individual one. I would like to shorten it to compensate for the fact that it stretches past the relevant data on the page

Here are some SS's to give further detail Thanks

<img width="1436" alt="ex 1" src="https://user-images.githubusercontent.com/21009897/36437918-5e346522-1636-11e8-839c-4c01e5d924ee.png">
<img width="664" alt="ex2" src="https://user-images.githubusercontent.com/21009897/36437919-5e4f8848-1636-11e8-96f1-c818d281e369.png">

**Comment by gilbarbara** [comment]
Yeah, this is an implementation problem and it's probably best to fix instead of hacking the default sizing. Think responsive...
You probably should add a wrapper to this menu that would fill the width but the menu itself should be an inline-block that only uses the required space and not the whole block.

**Comment by MichaelA59** [comment]
Ok, thanks. I will look into that then.
