### ISSUE TITLE
Doesn't scroll long pages correctly

### ISSUE THREAD

**Issue by chadoh** [gilbarbara/react-joyride#32]
First of all, thanks so much for this module! It looks great, and works pretty well! ...up to a point :stuck_out_tongue_closed_eyes: 

[Here's a video of the behavior I'm seeing](http://cl.ly/3f3u1T2K0W40). It's possible I missed setting some option. I hope the fix is that easy!

Description of the problem:

The first two steps of the tour highlight elements that are visible on the page with no scrolling. These are focused and scrolled to and highlighted just fine. It looks awesome!

The last step of the tour highlights an item that's at the very bottom of a long page. This is where things get weird! The `joyride-hole` element is placed perfectly, but it's nowhere close to being in view! Instead, the `joyride-tooltip` is visible, but its placement is _completely_ incorrect. It seems that it's placed at the bottom of the visible portion of the page when scrolled the whole way up, rather than actually down next to the `joyride-hole`.

Here's a low-quality gif, in addition to the high-quality video linked above:

![gif](http://f.cl.ly/items/0N1y0o2x100K08272J2F/Screen%20Recording%202015-11-22%20at%2011.08%20AM.gif)

**Comment by gilbarbara** [comment]
hey, thanks! :)

Do you have a live example of this page?
I already have tested the scroll in a couple of long pages and it worked. I'll take a look at the code again but it's really hard to debug this way.

**Comment by chadoh** [comment]
Great to hear from you so quickly! I can't quite figure out how to get the google auth tokens working in a new staging branch I made, but if you pull down the code at https://github.com/chadoh/life/tree/react-joyride, you should be able to `npm i` and then `npm run start` and check it out at `localhost:3000`. You'll see the tour once you sign in/up.

**Comment by gilbarbara** [comment]
@chadoh found it.
It is an issue with your css, actually. I think normalize.css is setting you `body` to height: 100% which is 100% of your window not the whole rendered document.
You can check it with `document.body.clientHeight` and `document.querySelector('body').clientHeight`
The simplest solution is to set `height: auto;` and `min-height: 100%;` in the file `basics.css`

cheers

**Comment by chadoh** [comment]
:clap: :clap: :clap: Thank you so much! What a nice easy fix!
