### ISSUE TITLE
"Cannot read property 'ease' of undefined" when setting `scrollToSteps` to true

### ISSUE THREAD

**Issue by jmale** [gilbarbara/react-joyride#320]
Version 1.11.2

To reproduce: set `scrollToSteps` to true but don't specify any other scroll props (leave them as the defaults).

You'll then get the above error which I think is thrown from the "scroll" dependency. It looks as though the code which causes this is in `index.jsx` starting line 385:

```
if (isRunning && scrollToSteps && shouldScroll && scrollTop >= 0) {
  scroll.top(getRootEl(), this.getScrollTop());
}
```

The `top` method expects more than two parameters, e.g. it wants a defined `opts` parameter as a third parameter otherwise it blows up.

**Comment by gilbarbara** [comment]
yeah, this was an error with [scroll](https://github.com/michaelrhodes/scroll/issues/9). It was fixed in 2.0.3 and updated in 1.11.3

[s]
