### ISSUE TITLE
Adjust step main container location

### ISSUE THREAD

**Issue by jrpharis** [gilbarbara/react-joyride#321]
It would be nice to be able to offset the main container on a per step basis. Basically have an offsetX and offsetY that would work just like the beacon offset. That way, I could align the main container with certain parts of my own UI. Such as the left side of the step with the left edge of box above it.

![41f3e8236615452999adf9d83e5dd1b8](https://user-images.githubusercontent.com/5515703/36848431-2fc1e408-1d2f-11e8-8921-30c0e847e216.png)

**Comment by gilbarbara** [comment]
Did you try `bottom-left` for the position?
Anyway, V2 will use a different engine for the tooltips using popper.js.
This will make it possible to use a custom offset beside the new placement options, however, this is not something I would work on initially.

**Comment by jrpharis** [comment]
@gilbarbara Ah, I was actually trying `bottom-right`, thinking the `right` was indicating where the container is aligned, I see how that is working now. So `bottom-left` does move the container, but the triangle is no longer centered. We've decided to leave as is for now, but will be interested to see how it can be customized in V2.
