### ISSUE TITLE
Need a better example (Documentation)

### ISSUE THREAD

**Issue by Technologeek** [gilbarbara/react-joyride#322]
Thanks for the beautiful project! I want to integrate Joy-Ride in my web-app desperately but due to poor documentation and limited resources,I don't know how should I start .Some of you might argue that every thing is just straight forward but it doesn't seem as straightforward to me (the readme and the demo source code)
I'm having a single page applications and my parent container has sequence of child components which I want to highlight using JoyRide.Can someone please point me in the right direction ? What should be my arrayOfSteps ? Should be the classes of the elements or just the component name ? Hope someone acknowledges this soon.Thanks!

**Comment by gilbarbara** [comment]
Hello,

I will update the README and the examples for V2 but that will take some time.

- arrayOfSteps is literally an array of step objects. 
- the step selector is a DOM selector.
