### ISSUE TITLE
Show all beacons 

### ISSUE THREAD

**Issue by mplungjan** [gilbarbara/react-joyride#323]
I would like to allow my users to take a tour OR jump straight to the item they need help on.
I had a look to see if the beacons were available in the DOM so just needed to be made visible, but alas (V1) 
I understand that I could have tooltips instead, but would prefer to have only one set of code running. The user could just continue a tour from where they left off or skip the first beacons if not interesting.

![](https://user-images.githubusercontent.com/1433276/37160227-0449665e-22f0-11e8-9d0d-4d21dfce1747.png)

**Comment by gilbarbara** [comment]
You can manage the steps you pass to Joyride by yourself. This module isn't a state manager.
If the user already has completed a step you could simply remove it from the steps for the next time the user tries to get help.

About showing all beacons this will never happen as I explained before.

**Comment by mplungjan** [comment]
That is regrettable. The users are already familiar with the old interface. We would like them to not have to go through the steps they can recognise from previous interface or can guess what is doing.
The first time they visit they could take the tour from wherever they feel uncertain.
Anyway thanks for the communication.

**Comment by nnmer** [comment]
+1 i was also interested to use the tour component in double modes.
1 - as a tour, where steps are chained
2 - show all beacons and that will act as a interactive help
