### ISSUE TITLE
Sliding side bar in step #3

### ISSUE THREAD

**Issue by puffstream** [gilbarbara/react-joyride#324]
Hey everyone,

love the react-joyride library, everything is working perfectly until I need to show a beacon in a sidebar that needs to toggle open first. Any ideas on how I can achieve this with the current library and API?

I thought about setting a timeout and saw the debounce delay options, I just cant seem to get them working, appreciate any replies on this. Thanks!

**Comment by gilbarbara** [comment]
Hey @puffstream 

Maybe you could set up a `callback` and change the `run` prop to `false` when the action type is **step:after** and switch the `run` to true after the sidebar is completely open.

V2 has a fully controlled tour scheme but still isn't documented.

**Comment by puffstream** [comment]
@gilbarbara Okay, thanks! I'll give it a go :)

**Comment by puffstream** [comment]
@gilbarbara Yup, that did the trick! Awesome :D Lovin it :D
