### ISSUE TITLE
spotlight on wrong position

### ISSUE THREAD

**Issue by mike623** [gilbarbara/react-joyride#326]
trying to build up the simplest demo

![screen shot 2018-03-21 at 3 18 35 pm](https://user-images.githubusercontent.com/14008281/37697972-2a1d6f76-2d1b-11e8-9bee-29da21173c51.png)

Here is the [playground](https://codesandbox.io/s/z361o9jwlp)

**Comment by gilbarbara** [comment]
The `H1` margin-top is breaking the `body` viewport.
Remove it with `style={{ marginTop: 0 }}`
