### ISSUE TITLE
Any way to get joyride to navigate a multi-page site?

### ISSUE THREAD

**Issue by macsplan** [gilbarbara/react-joyride#328]
Hi, is there any way to get joyride to navigate a multi-page site?

As in start on the homepage, show all the features of that, then go to the user profile page, tour that then continue to other pages of the site?

**Comment by gilbarbara** [comment]
Not with the current version.
Version 2.x in controlled mode might handle that. You can try it with `npm i react-joyride@next`

**Comment by macsplan** [comment]
Excellent thanks @gilbarbara i'll pull the @next version and try it out. Is v2 nearly done?

**Comment by gilbarbara** [comment]
Check #291 for the progress
