### ISSUE TITLE
V2: No `autoStart` prop 

### ISSUE THREAD

**Issue by pokonski** [gilbarbara/react-joyride#330]
Hey!

First of all thanks for the great library! I just updated to 2.0.0-7 and overall feels and behaves much better (especially on mobile :) )

But there's one issue, it seems the option to autoStart is missing, is it intentional?

Cheers

**Comment by gilbarbara** [comment]
Thanks! :)

Yes, it was removed. Please check the #291 for more information.
I'll add migration instructions before I release V2 officially.

[s]

**Comment by pokonski** [comment]
Great! So the solution for future Googlers: 

Add `disableBeacon: true` to the first step and it will work once again

**Comment by gitowiec** [comment]
Thanks, now I know what beacon is (in this library context) and what it does.
First I thought that I have to pass `floaterProps.autoOpen:true` to make joyride auto start, but no!
It just made worse, passing `floaterProps.autoOpen:true` disables tooltip for every second step (maybe its a bug - I don't know, it's first time I'm using joyride)
