### ISSUE TITLE
JoyrideProps.tooltipOptions does not apply custom options

### ISSUE THREAD

**Issue by djeeg** [gilbarbara/react-joyride#331]
Not sure if this is intentional

I can get StepProps.tooltipOptions to apply custom options

```
	{
		title: "Hi",
		content: (<div>Welcome</div>),
		tooltipOptions: {
			styles: {
				tooltip: {
					zIndex: zIndex.snackbar,
					backgroundColor: 'brown',
				}
			}
		},
	},
```

However if I try JoyrideProps.tooltipOptions, then it doesnt work

```
<Joyride
	tooltipOptions={{
		styles: {
			tooltip: {
				zIndex: zIndex.snackbar,
				backgroundColor: 'brown',
			}
		}
	}}
/>
```

**Comment by djeeg** [comment]
Actually I think you may have fixed this one already

2.0.0-7 getMergedStep doesnt have mergedStyles 
https://unpkg.com/react-joyride@2.0.0-7/lib/index.js

But i see that v2 source now does 
https://github.com/gilbarbara/react-joyride/blob/V2/src/modules/step.js#L95-L101

**Comment by djeeg** [comment]
Been doing some hacking, and I dont think the latest code will merge the tooltipOptions as I thought it would.

Thought, replacing this

> var tooltipOptions = deepmerge(DEFAULTS.tooltipOptions, step.tooltipOptions || {});

With this (mergedStep instead of step)

> var tooltipOptions = deepmerge(DEFAULTS.tooltipOptions, mergedStep.tooltipOptions || {});

Does allows me to set global tooltip styles

**Comment by gilbarbara** [comment]
if you to change the `styles` of the default tooltip UI use `styles` directly, not `tooltipOptions`. V2 uses React Portal so zIndex don't make much sense as it was in the old version.

Anyway, I need an example to make sure we are talking about the same thing, codesandbox or something.

**Comment by djeeg** [comment]
Say I am using custom zIndexs in my app
eg https://github.com/mui-org/material-ui/blob/v1-beta/src/styles/zIndex.js

Totally contrived example
https://codesandbox.io/s/43o5jjr114

First render is with no custom zIndexes
Tooltip is partial hidden under panel

Next uncomment these two lines
Joyride.styles.**overlay**.zIndex + 
step.tooltipOptions.styles.**tooltip**.zIndex
This is rendering okay
(however zIndexes would need to be defined for every step)

Ideally it would be good to set both of these on Joyride component
Joyride.styles.**overlay**.zIndex + 
Joyride.tooltipOptions.styles.**tooltip**.zIndex

Note
Joyride.styles.**tooltip**.zIndex doesnt not go high enough in the dom.
There is one component above` <JoyrideTooltip>` in Step.js, `<Floater>`, which does not accept style overrides

**Comment by djeeg** [comment]
A better demo

https://7kxml7qvm0.codesandbox.io/modal

I believe Material UI uses react-popper for its portals, and sets a z-index on div within the portal
I couldnt see a z-index being set on your react-modal demo

**Comment by gilbarbara** [comment]
Just use `styles` directly, without `tooltipOptions` (which was renamed to floaterProps btw).
```jsx
<Joyride
	styles={{
		options: {
			zIndex: 2000
		}
	}}
/>
```

If you ever want to customize react-floater's styles use like this, but now there's not much to change there...
```js
<Joyride
  floaterProps={{
	styles: {
	  ...
	}
  }}
/>
```

**Comment by djeeg** [comment]
Thanks

(Update the demo for anyone coming looking for how to do this with Material UI Dialog)
https://codesandbox.io/s/3111rvkok5
