### ISSUE TITLE
V2 - tweak for IE11 if still supported

### ISSUE THREAD

**Issue by djeeg** [gilbarbara/react-joyride#332]
Seems like it mostly works in IE11

`style.remove()` is unsupported though
https://github.com/gilbarbara/react-joyride/blob/V2/src/components/Beacon.js#L60

Could be changed to `style.parentNode.removeChild(style);`
https://stackoverflow.com/questions/20428877/javascript-remove-doesnt-work-in-ie

**Comment by gilbarbara** [comment]
You are using a Beta release. There will be problems...

**Comment by djeeg** [comment]
Yeah no problems :smile: , happy to help test or throw together a PR. Its looking really good so far!

**Comment by gilbarbara** [comment]
Did you test it in IE11? Was this the only problem?
I don't plan to support it officially, but if this is the only issue it won't hurt to fix it.

**Comment by djeeg** [comment]
Yep its the only issue that I have found so far.

**Comment by ericnkatz** [comment]
@gilbarbara are these latest changes pulled down when you install @next ? I'm still running into this issue but it looks like the code patch was already put in master.

**Comment by gilbarbara** [comment]
Fixed in `react-joyride@2.0.0-12`
