### ISSUE TITLE
Does React-joyride support multipage tours

### ISSUE THREAD

**Issue by snlhnk** [gilbarbara/react-joyride#333]
The tour we created has 4 steps on page 1, the remaining steps are on page 2.
We are unable to automatically take the tour to page 2 after the 4th step on page 1.

Intro.js has multipage support, does react joyride support it as well, or something we are missing out?

**Comment by gilbarbara** [comment]
I need some code.
Are you using two different instances of Joyride?

**Comment by snlhnk** [comment]
Ours is a single page html application and we use a single instance of joyride.
[1.zip](https://github.com/gilbarbara/react-joyride/files/1889806/1.zip)

**Comment by gilbarbara** [comment]
This probably won't work with the current version.
You can try V2 with `npm i react-joyride@next`. You can read more about it [here](https://github.com/gilbarbara/react-joyride/tree/V2).

Basically, you'll need to stop the tour with `run: false`, load your route and start it again after it's rendered.

**Comment by Rym04** [comment]
Please give us an Example for multipage using. This would be so helpful

**Comment by pcast01** [comment]
This example I came across helped me to use React Router. https://codesandbox.io/s/owQ8Wrk3

**Comment by vegeta123254** [comment]
@gilbarbara , Please give us an Example for multipage using. This would be so helpful

**Comment by gilbarbara** [comment]
hey,

Here is the multi-page tour example: https://codesandbox.io/s/react-joyride-multi-page-tour-f7bkv0

**Comment by gilbarbara** [comment]
hey @Histamina 

Here is the multi-page tour example: https://codesandbox.io/s/react-joyride-multi-page-tour-f7bkv0

**Comment by Histamina** [comment]
> hey @Histamina
> 
> Here is the multi-page tour example: https://codesandbox.io/s/react-joyride-multi-page-tour-f7bkv0

Thank you! : D

**Comment by gilbarbara** [comment]
Hey @AMfalme 
It's on the README, https://codesandbox.io/p/devbox/github/gilbarbara/react-joyride-demo/tree/main/?
