### ISSUE TITLE
v2 - Pass size to Tooltip

### ISSUE THREAD

**Issue by djeeg** [gilbarbara/react-joyride#335]
I want to show the step progress in a custom tooltip (eg Step 1 of 8)

I can get the `index `and `isLastStep`, but I dont seem to be able to get the total step count within the tooltip

Would it be possible to pass the size to the Tooltip here?
https://github.com/gilbarbara/react-joyride/blob/V2/src/components/Step.js#L184

**Comment by gilbarbara** [comment]
Yes, it's the roadmap. #291
