### ISSUE TITLE
First step is shifted off the page but all others are fine

### ISSUE THREAD

**Issue by MichaelA59** [gilbarbara/react-joyride#337]
For some reason, despite having the popup appear to the right and all the rest of my settings, the first step always looks like the screenshot below, but all other are perfectly find and actually highlight the element in question without issue 

<img width="770" alt="example jpyride" src="https://user-images.githubusercontent.com/21009897/38952004-4027c510-4318-11e8-9502-7da63393fc5b.png">

**Comment by gilbarbara** [comment]
Hey,

can you try V2 and let me know if it works?
`npm i react-joyride@next`

**Comment by gilbarbara** [comment]
or for V1...
is this a fixed element? Did you try to set `isFixed` for the step?

**Comment by MichaelA59** [comment]
No, it's `position: relative` and V2 didn't seem to help

**Comment by gilbarbara** [comment]
I can't help without inspecting the code, especially the step selector styles.

You can post an example at https://codesandbox.io/

**Comment by MichaelA59** [comment]
Ok, thank you and I will look into that. While I have you here, it's a side issue but I am trying to think of a way to perform a redirect while maintaining the step count

I have a page with has it's own tabs, that attach a `hash` (#example) to the existing URL. I need to redirect at certain points. Should these all be different sequence of steps with a callback once complete and then to trigger the redirect or is it possible to have a larger sequence of steps be passed to JR and then somehow trigger a redirect while preserving the order and progress made?

**Comment by gilbarbara** [comment]
About your current issue, make sure the step's selector HTMLElement has proper width and height with `.getBoundingClientRect()` or `window.getComputedStyle()`...
Or it's been transformed with css.

What do you mean with redirect? a full page reload or a simple route navigation?
If it's the second you can use a controlled tour with V2. Check out the Basic example callbacks at V2's [demo](https://codesandbox.io/s/2zpjporp4p).

**Comment by MichaelA59** [comment]
Issue is resolved. Had to do with content not being rendering by the time JR was looking for it to highlught
