### ISSUE TITLE
scrollOffset vs Back

### ISSUE THREAD

**Issue by bronsonmt** [gilbarbara/react-joyride#339]
Hello,

I set the ScrollOfset to 60 and  i click next : JoyRide perform scroll to the correct step,
but when i click back, Joyride don't perform the prev Scroll.

**Comment by gilbarbara** [comment]
Can you try V2 and let me know if it works for you?
`npm i react-joyride@next`

V1 won't have any more updates

**Comment by bronsonmt** [comment]
Thx, I have tried with V2, it seems to be better for the positioning but now the Spotlight is behind the main header (the header have a fixed position).
I have looked at the generated HTML (the className joyride-hole seems to works better than the joyride-spotlight for a "fixed" element)

**Comment by gilbarbara** [comment]
Please post an example at codesandbox. I can't help without seeing some code.

**Comment by alex0520** [comment]
Sorry for comment in this old thread, but I have the same issue, I tried the demo and when you press back button, it doesn't scroll to previous step, maybe @gilbarbara can help me? Thanks
