### ISSUE TITLE
[V2] Missing overlay when swapping from center to top

### ISSUE THREAD

**Issue by djeeg** [gilbarbara/react-joyride#340]
Demo: https://codesandbox.io/s/myqwvrx13x

Not sure if its possible to mix 'center' with other placements

If i do the reverse, ie the first step is 'top' and the second step is 'center', then the overlay shows on the first and hides on the second as expected.

**Comment by monsieurnebo** [comment]
Same issue here.

As soon as `placement: center` is involved, the overlay disappears (for other steps too).

Is there any way to fix this?

**Comment by gilbarbara** [comment]
fixed in 2.0.0-10

**Comment by djeeg** [comment]
Thanks its fixed!

**Comment by monsieurnebo** [comment]
That's working fine. Thanks @gilbarbara 👍
