### ISSUE TITLE
"Center" option for step position

### ISSUE THREAD

**Issue by borovik96** [gilbarbara/react-joyride#343]
Sometimes needs to set step position to the center of component. It will be good to have this option

**Comment by gilbarbara** [comment]
It's already available at V2 `npm i react-joyride@next`

**Comment by borovik96** [comment]
Is it alrady possible to use `v2`? Are there some docs for it?

**Comment by gilbarbara** [comment]
Yes, [here](https://github.com/gilbarbara/react-joyride/tree/V2).

**Comment by damndaniel2000** [comment]
Hi, using placement : center just makes a modal in the center of the page even though the target is a specific div. Am i doing something wrong?

**Comment by gilbarbara** [comment]
hey @damndaniel2000 

This is the expected behavior for the `center` placement.

**Comment by damndaniel2000** [comment]
How do i place it in the centre of the target div?

**Comment by steodor** [comment]
@damndaniel2000 did you ever find a way to do that? The spotlight is missing from the DOM on centered steps.
