### ISSUE TITLE
[V2] Controlled joyride become uncontrolled

### ISSUE THREAD

**Issue by Chypa74** [gilbarbara/react-joyride#345]
Hello. I use your react-joyride V2 and I have faced a problem. When I set state at the Component constructor method stepIndex value (ex. `stepIndex: 0`), then I can't control joyride. It becomes impossible to manage its state and behavior.

**Comment by Chypa74** [comment]
It becomes when i do this code
![image](https://user-images.githubusercontent.com/16071062/39397742-0259191c-4b0d-11e8-8805-44ab12c19cf8.png)

**Comment by Chypa74** [comment]
It becomes when I handle callback like this
```
handleJoyrideCallback = (props) => {
    if (props.action === 'update') {
      this.setState(prevState => {
        return {
          ...prevState,
          stepIndex: props.index+1
        }
      });
    }

    if (props.action === 'prev' || 'next') {
      this.setState(prevState => {
        return {
          ...prevState,
          stepIndex: props.index
        }  
      });
    }
}
```

But if I handle like this, then stepIndex are changing normally
handleJoyrideCallback = (props) => {
    // if (props.action === 'update') {
    //   this.setState(prevState => {
    //     return {
    //       ...prevState,
    //       stepIndex: props.index+1
    //     }
    //   });
    // }

    if (props.action === 'prev' || 'next') {
      this.setState(prevState => {
        return {
          ...prevState,
          stepIndex: props.index
        }  
      });
    }
}

Could you explain me why these happen

**Comment by gilbarbara** [comment]
Do you really need to control the index? If so, you need to increment/decrement the index yourself. You can check the Basic demo [here](https://codesandbox.io/s/2zpjporp4p).

Otherwise, do no set the `stepIndex` and let it use the internal sequencer.

**Comment by Chypa74** [comment]
I understand you. But could you explain to me when I press the close button, Joyride does not turn off, but he switches to the next step

**Comment by Chypa74** [comment]
Click on close button)

**Comment by Chypa74** [comment]
Maybe i didin’t explain correctly. I want behaviour like this: 
1. I click on the clise button. 
2. Joyride finished and tooltip hide.  
How I can reproduce this behavior? Via component state (set ‘run’ to false)?

**Comment by gilbarbara** [comment]
If you really want help post an example at codesandbox.
