### ISSUE TITLE
Provide only some options to locale prop

### ISSUE THREAD

**Issue by evansjohnson** [gilbarbara/react-joyride#346]
If I provide the `locale` prop, I currently have to define all of the strings or else they are undefined and will not render any text.  I believe that there should be a line something like `locale = Object.assign({}, defaultProps.locale, locale);`

My use case is that I want to customize the text of the `last` string but feel like I shouldn't have to duplicate the defaults.

If this sounds okay I'd be happy to file a PR!

**Comment by gilbarbara** [comment]
It's fixed on V2.
You can try it with `npm i react-joyride@next`
