### ISSUE TITLE
When 'content' field is react node then app is crashed V2

### ISSUE THREAD

**Issue by borovik96** [gilbarbara/react-joyride#348]
If `content` field in `step` is React node value then app ends to respond, it seems like infinity loop. Only way to close tab from task manager

**Comment by gilbarbara** [comment]
This doesn't seem like a problem with joyride itself. If you try to load this React component by itself it doesn't crash?
You can check the demo and most examples load React components without problems.
Can you post an example in codesandbox?

**Comment by borovik96** [comment]
This is example https://codesandbox.io/s/n49r4kz9lj
It only happens if i generate react component in render method, if it is wrong, how should i dynamicly generate content for steps?

**Comment by gilbarbara** [comment]
The example above didn't crash at all.
It was supposed to?

**Comment by borovik96** [comment]
Sorry, updated example https://codesandbox.io/s/n49r4kz9lj

**Comment by gilbarbara** [comment]
Not sure why this happened, probably a limitation on how the render method handles things.

You can set the steps on the constructor or even outside the React component.

**Comment by borovik96** [comment]
Unfortunately I need do it dynamic, because I have hot loading translation. If I find solution, will post it here

**Comment by gilbarbara** [comment]
It should crash like that, I'm looking into it.

**Comment by NaomiThomson** [comment]
I'm experiencing this problem too using v2. Should I switch to a previous version?

**Comment by gilbarbara** [comment]
fixed in 2.0.0-11
