### ISSUE TITLE
Gray background V2

### ISSUE THREAD

**Issue by borovik96** [gilbarbara/react-joyride#349]
In some blocks i have gray background, but in other blocks with same background colors i don't (see image below), it seems strange. Do you have any idea what may cause this issue?

Without overlay
![image](https://user-images.githubusercontent.com/9018702/39616356-a86c52a4-4f83-11e8-9306-3e39a505b9e7.png)

With overlay
![image](https://user-images.githubusercontent.com/9018702/39616349-9ae8aac4-4f83-11e8-950c-8d1c0295d0ce.png)

**Comment by gilbarbara** [comment]
Please try to update to 2.0.0-10 and let me know if it works

**Comment by gilbarbara** [comment]
It's impossible to know what is going on without seeing some code.

Review your steps and make sure you are not setting options you don't need to.

If you can reproduce this behavior on codesandbox, reopen the issue.

**Comment by michalkow** [comment]
I had the same problem. In my case, it is when using react-joyride on react-table. I think it is a CSS issue.
I managed to replicate error: [https://codesandbox.io/s/o5q6rnrz1q](https://codesandbox.io/s/o5q6rnrz1q)
It is grey in Chrome but displays correctly in Firefox.

**Comment by gilbarbara** [comment]
@michalkow Feel free to submit a PR

**Comment by gilbarbara** [comment]
@michalkow I really can't say. It seems like a weird interaction with form elements. Or the way react-table render things.

**Comment by michalkow** [comment]
I solved it by setting white background on ReactTable, before no background color was set.

**Comment by gilbarbara** [comment]
Nice, I will try to understand if it's a requirement to mix-blend-mode and add to the FAQ.
Thanks
