### ISSUE TITLE
Reset Method

### ISSUE THREAD

**Issue by jerryf196** [gilbarbara/react-joyride#35]
First off i want to thank you for the support and quick fixes. We are using this plugin in a project and so far so good. Another small issue or bug appeared.

When i call the .reset(true) method I get this js error

TypeError: this._renderLayer is not a function

if (restart && this.state.play === restart && this.state.index === 0) {
this._renderLayer();
}

Looks like the _renderLayer() method does not exist.

**Comment by jerryf196** [comment]
Another question:

How can I remove the guide from memory? Basically when I close the modal or switch page I pass an empty array to the addSteps() method. Then I get this js error when I resize the browser:

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

It seems as if it's trying to find the element on the page. Is the reset(true) method best way to do this?

**Comment by gilbarbara** [comment]
Hey, I fixed the `this._renderLayer();` bug in ec0a2f4d6ab15256ee15d6ba14dbf836dd4e0c9c and published as 1.0.5

**Comment by gilbarbara** [comment]
About your problem, I  don't know..
Maybe you should set your `steps` state to an empty array directly. Calling `addSteps` will add it the steps collection, not reset it..

[s]

**Comment by jerryf196** [comment]
I figured it out. Yeah that is exactly what i came up by clearing the array. Thanks! For the fix it works as expected.

Thanks again!
