### ISSUE TITLE
Easy way to replicate V1 Animations

### ISSUE THREAD

**Issue by MichaelA59** [gilbarbara/react-joyride#356]
* Expected behavior

Animations seem a little ridged in this version, but overall it looks a lot better I think. I really liked how the tooltips would animate in a `popup` fashion. I have tried manipulating the actual CSS provided, but it doesn't look like anything is taking. Any ideas?

* React-Joyride version

V2

**Comment by gilbarbara** [comment]
Not sure what you mean by V1 animations. Which moment exactly?

**Comment by MichaelA59** [comment]
The main difference being the following:

### V1
A new tooltip (on initialize or next) will appear in a "bouncing" kind of way. It's a smooth animation/transition

### V2
New tooltips appear in a "Fade In" way, except they seem kind of rigid and not as fluid as V1. 

The example I am trying to demonstrate and be best seen if you have several tooltips opening on the same page without scrolling so that you can see how they flow (this is the scenario for my use-case).

I just want to find a way to include that previous affect
