### ISSUE TITLE
Adding setTimeout to disable buttons

### ISSUE THREAD

**Issue by MichaelA59** [gilbarbara/react-joyride#358]
My Bug:

I am using V1. This only happens in one spot, and I don't know why. In this specific instance, I hit the final step and in my callback, I have a conditional that looks like 
```javascript
if (data.type == 'finished') {
   this.props.advanceJoyRide(data)
}
```
This works just find the previous 2 times it is called. Except on this time, it runs TWICE, each time with identical callback data. I am using this callback to make a `PUT` request to my backend, to update the progress of the users onboarding and this is causing it to advance an additional step. 

Now, I thought, maybe if I put a check before the `PUT` request is run, I can prevent it from running the second time. So I did something like the following

```javascript
this.state = { updating: false }
...
advanceJoyRide() {
  if (!this.state.updating) {
   this.state.updating = true
   API.put(....my put request....)
  }
}
```

Also tried moving that function into _another_ function and using a callback in setState, thinking it would only run once state was set except that doest work either. Looks like

```javascript
this.state = {updating: false}
...

advanceJoyRide() {
 if (!this.state.updating) {
   this.setState({
      updating: true
   }, () => this.updateJR())
}

updateJR() {
 ...my PUT request...
}
```
That callback function, still gets called twice and state is never set for `updating` despite hardcoding the state and trying `this.setState`. As a result, I can't count on this to prevent an additional request.

_However_, and this may be completely off base, but I have noticed, when I move more slowly through the JoyRide, it seems to work correctly. Yea, it doesn't always break and in this case, I am not sure if this is even a likely fix. It may have to do with state being set and getting jumbled in the lifecycle method or something but I am out of ideas...

>Expected behavior

Given the above description, maybe I can add a `setTimeout()` to the tooltips which would disable all of the buttons on the tooltip when it is first rendered and then when the function runs, restore functionality to the buttons and allow the user to proceed.

>React version

^15.6.2

>React-Joyride version

V1

**Comment by gilbarbara** [comment]
sorry, V1 has been deprecated and there's no more support to it as you might have imagined
