### ISSUE TITLE
Mount components during the tour

### ISSUE THREAD

**Issue by sarates** [gilbarbara/react-joyride#362]
>Expected behavior

During the tour we can mount new components and show them in the tour.

>Actual behavior

'Target not mounted ' warning and showed next step.

How I can manage this issue? If I trying to do this with controlled tour and set stepIndex after it loaded - I have such info: `action : start`, `index : 7` (correct), `type : tour:status` and tour doesnt start.

UPD - When I pass all classes to `target` - it start works. (was `.side-bar`, now `.side-bar.open`). Magic.

**Comment by gilbarbara** [comment]
Please check the **Controlled** example in the [demo](https://codesandbox.io/s/2zpjporp4p).
