### ISSUE TITLE
Unexpected behavior using stepIndex with value 0

### ISSUE THREAD

**Issue by keul** [gilbarbara/react-joyride#364]
>Expected behavior

* using `stepIndex={0}` should be handled as a valid numeric value for `stepIndex` but there's a different behavior when using a

>Actual behavior

* using stepIndex={0} will select the first step of a tour (user must click on the button to activate)
* using stepIndex={1} will select the second step of a tour but also start it immediately

>Steps to reproduce the problem

```jsx
          <Joyride
            steps={steps}
            run
            scrollToFirstStep
            disableOverlay
            continuous
            stepIndex={0}
          />
```

Just change `0` to any other value to see the different behavior.

>React version

15.6.2

>React-Joyride version

2.0.0-10

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by keul** [comment]
Can't reproduce anymore with 2.0.0-11 version

**Comment by akilham** [comment]
I get the same thing on 2.0.0-12. I fixed it by setting the disableBeacon property to true on the first step.
