### ISSUE TITLE
No overlay for centered step on Microsoft Edge

### ISSUE THREAD

**Issue by monsieurnebo** [gilbarbara/react-joyride#368]
There is no overlay on **Edge**, for a **centered** step.

The bug can be see on the [official demo](https://2zpjporp4p.codesandbox.io/):

![image](https://user-images.githubusercontent.com/2378274/40242060-e0df483c-5abc-11e8-8cb0-309e4e5069d1.png)

Moreover, it seems that the following style isn't taken on account on Edge:
```js
  spotlight : {
    borderRadius : 0
  }
```

**Comment by monsieurnebo** [comment]
I just discoverd that the same two bugs are observable on **Google Chrome** for **Android**.

**Comment by gilbarbara** [comment]
Feel free to submit a PR

**Comment by gilbarbara** [comment]
I've found the culprit, it's the browser detection function and I'll improve it.

About the `borderRadius` it's a bit weird. I don't think those two browsers need prefixing but I'll dig deeper.

**Comment by monsieurnebo** [comment]
@gilbarbara  If you're having troubles in browser detection, [this resource](https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser/9851769#9851769) is the most reliable we found so far.

You may also take a look on [browserhacks](http://browserhacks.com/), but everything isn't working.

**Comment by gilbarbara** [comment]
Fixed in `react-joyride@2.0.0-12`

**Comment by monsieurnebo** [comment]
Thanks for the fix!

For your information, the over seems to still be invisible on iOS browsers :)

**Comment by gilbarbara** [comment]
@monsieurnebo Oh shit. I'll fix it tonight...

**Comment by gilbarbara** [comment]
@monsieurnebo I'm seeing the bug with Chrome on iOS but Safari looks fine.
Can you confirm?

**Comment by gilbarbara** [comment]
@monsieurnebo fixed in 2.0.0-13

**Comment by monsieurnebo** [comment]
I was encountering this issue on the following iOS browsers: Chrome, Firefox and Opera (but not Safari, you're right).

I will try the fix and keep you informed.

**Comment by monsieurnebo** [comment]
I just tried the `2.0.0-13`:

Browser | Result
--- | ---
Chrome | ✅ 
Firefox | 🔴 
Opera Mini | 🔴

**Comment by gilbarbara** [comment]
@monsieurnebo 
Opera Mini apparently don't behave with the box-shadow hack either. Does it show a gray box or a weak shadow?
Firefox will work with 2.0.0-14

**Comment by monsieurnebo** [comment]
Overlay is now working on both iOS **Firefox** & **Opera Mini** !

Great job 🎉
