### ISSUE TITLE
Scrolling messed up in Firefox?

### ISSUE THREAD

**Issue by chadoh** [gilbarbara/react-joyride#37]
Hello. I see that you closed #27 a while ago, but I've noticed some weird behavior with it. Perhaps it's my fault again, as it was in #32.

The issue is with `position: bottom` tour steps, which [most of mine are](https://github.com/chadoh/entire_life/blob/master/src/utils/tourSteps.js#L8). For these steps, Firefox scrolls the whole way to the top of the page, rather than to the top of the tooltip.

You can see this in action at http://entire.life, by taking the tour in the "Take a Tour" section.

Thanks again for this super beautiful plugin!

**Comment by gilbarbara** [comment]
hey @chadoh !
Did you fix this?

**Comment by chadoh** [comment]
I did not fix it! I got around it, I think I remember, by always using `position: top`

**Comment by chadoh** [comment]
To be clear, that might mean that react-joyride is still broken in this way :smile:

**Comment by gilbarbara** [comment]
I couldn't reproduce this behavior in several tests and nobody else complained so it could be a side effect from your setup. If I get more reports I'll look into it.
👍

**Comment by chadoh** [comment]
:+1:
