### ISSUE TITLE
Unable to reset controlled tour when user skips and wants to retake the tour

### ISSUE THREAD

**Issue by xveganxxxedgex** [gilbarbara/react-joyride#371]
>Expected behavior

If custom logic exists to reset the tour index to 0 when user skips the tour after completing a few steps, it should start at the first step if they try to retake the tour. 

>Actual behavior

The tour continues where it last left off.

>Steps to reproduce the problem

* https://codesandbox.io/s/1z9n1x6rl4
* Go to the Controlled tab
* Take tour until step 3, then click the Skip button on step 3
* Scroll back up to the top and click the Let's Go button to take the tour again
* Tour should be restarted at 0 index, but instead picks up where it left off

>React version

16.3.2

>React-Joyride version

2.0.0

>Error stack

None

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by ragnar-pwninskjold** [comment]
@xveganxxxedgex I have gotten around this issue by placing a key prop on the root component and then increment the key when the skip button is pressed. This forces react to 'reset' the component, which resets the tour state. Not sure if there is a better solution here but it works for me

**Comment by xveganxxxedgex** [comment]
@ragnar-pwninskjold Thanks for the suggestion, I'll give that a try!

**Comment by xveganxxxedgex** [comment]
This solution ended up working for me, so I'm going to close this out. Thanks again @ragnar-pwninskjold

**Comment by mjohnson290** [comment]
@xveganxxxedgex Did you create an event listener on the skip button, or how did you go about making the fix? The problem is there for me when either skipping or finishing the tour.

**Comment by xveganxxxedgex** [comment]
@mjohnson290 In my app, I have a button to start the tour, and each time that's pressed I have a local tourVersion state that I increment. That value is then used as the key I pass to the Joyride component instance. I think just doing that ended up fixing this issue for me

**Comment by mjohnson290** [comment]
@xveganxxxedgex Ahh awesome! Totally works, thanks!

**Comment by mx781** [comment]
@gilbarbara is this the encouraged solution for re-initializing the tour? I am looking to trigger a similar behavior - when user presses skip, I'd like the tour to go to the last step (which says something along the lines of "if you wish to re-initiate the tour, hit this button).
