### ISSUE TITLE
There's a way to act of the Floater size?

### ISSUE THREAD

**Issue by keul** [gilbarbara/react-joyride#372]
>Expected behavior

I'd like to present the first step as a modal (mainly what another user described in #279). So I'm using the 'center' position, which works perfectly for my usecase.

>Actual behavior

The rendered Floater dimension is always narrow, ok for a small tooltip, not good for a lot of text.

I'd like to resize it to a wider dimension.

I tried with `floaterProps` on the step with something as:

          floaterProps: {
            styles: {
              floater: {
                width: '80vw',
              },
            },

This works of the outer container, but the inner div is still 380px.

I'm just wondering if this is an unsupported feature or there's some styles/options combination for doing this.

>React version

15.6.2

>React-Joyride version

2.0.0-11

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by Izhaki** [comment]
I think you need to distinguish between the floater style and the tooltip style - the two are separate. 

We had to change the border radius of the tooltip for a particular step. This does it:

```
        styles:{
          tooltip: {
            borderRadius: 0
          }
        }
```

So I guess this will for for you:

```
        styles:{
          floater: {
            width: '80vw',
          },
          tooltip: {
            width: '80vw',
          }
        }
```
