### ISSUE TITLE
[V2] Can't use multiple instances of Joyride in the same component

### ISSUE THREAD

**Issue by heymaddieh** [gilbarbara/react-joyride#374]
>Expected behavior

I'm trying to use Joyride multiple times on the same component to highlight 3 different features of a product, each with their own set of steps and a beacon for each as well. Each `<Joyride />` has its individual key property.

>Actual behavior

Because I'm having the same problem as [#361](https://github.com/gilbarbara/react-joyride/issues/361) , I'm forced to target the beacon element container by id, and removed the `visibility: hidden;` manually after I have triggered Joyride to run. If I'm trying to use multiple instances of Joyride, I can't target by id, because id's are meant to be unique, so only the first element with an id of `react-joyride:0` is targeted to remove that class. If I remove the class manually from the 2nd instance in the Chrome Dev Tools, I get the expected behavior. 

Is using multiple instances something that is possible or will be in the future? 

>React version

^15.6.2

>React-Joyride version

2.0.0-11

**Comment by gilbarbara** [comment]
The visibility bug is fixed in `react-joyride@2.0.0-12`
Multiple tours support isn't something on my mind, but I never tried. Does it work for you?

**Comment by MarcusJay** [comment]
Multiple tours are very useful for larger, more complex apps. Most users won't sit through 20+ steps, but 2-3 shorter tours are doable for most. I'm using currently using 2, and there are beacon positioning problems, but I'm working around them best I can.

**Comment by dmathisen** [comment]
I know it's been a few years, but I can't find much online or in the documentation. Are multiple tours supported?
Is there any way to have Tour A, Tour B and Tour C, each highlighting different sets of features in an SPA?
