### ISSUE TITLE
Update @types/react-joyride package for the new version

### ISSUE THREAD

**Issue by prawn-cake** [gilbarbara/react-joyride#379]
>Expected behavior

Current version of the `@types/react-joyride` is 1.10.2 which doesn't match the properties of the latest version of the library.

>Actual behavior

Spits out properties errors like `Property X does not exist...`

>Steps to reproduce the problem

Run Joyride with typescript

>React version

16.3.2 + typescript 2.8.3

>React-Joyride version

2.0.0-11

>Error stack

Example:
`TS2339: Property 'continuous' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Joyride> & Readonly<{ children?: ReactNode; }> & R...'.`

**Comment by tibetsprague** [comment]
Any progress on this?

**Comment by prawn-cake** [comment]
Hi @gilbarbara 
Can you point out or help with which package / repo / team should this be addressed?

**Comment by wlindner** [comment]
@prawn-cake I resolved this by uninstalling `@types/react-joyride` and creating a custom type declaration in `@types/react-joyride/index.d.ts` [here's a gist](https://gist.github.com/wlindner/c45daf0f7b94ed0a3f4a1e490b4392d4).

**Comment by prawn-cake** [comment]
Thanks @wlindner.
It would be nice to have official solution though to avoid too many customisations.

@gilbarbara can you take a look at @wlindner solution and may be push it forward if it's sufficient?

**Comment by gilbarbara** [comment]
@prawn-cake It doesn't look right. I don't expose any methods in V2

**Comment by gilbarbara** [comment]
I'll try to add an official package before the final release.
If somebody wants to help, it would be great.

**Comment by prawn-cake** [comment]
@gilbarbara I can help. What do you exactly want me to help with? 
To write type definitions for the public interface of the library?
Do you have any preferences of the contribution process?

**Comment by kdy1** [comment]
I've made a pr.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28585
