### ISSUE TITLE
How to update the `overlay`'s size accordingly

### ISSUE THREAD

**Issue by hjfrun** [gilbarbara/react-joyride#381]
I found in this joyride, the `overlay` and the `hole` can block the click events. But the `overlay` only capture the **original** visible size of the first step, but could never be updated later. This result to some bugs in our app.

(I colored the `overlay` yellow)
![image](https://user-images.githubusercontent.com/4508489/40838850-7c760130-65d2-11e8-9f81-5885c09206da.png)

Then the page content size increase. But the size of the `overlay` stay the same.

**The clickable `shadow`**
<img width="1439" alt="wx20180531-233014 2x" src="https://user-images.githubusercontent.com/4508489/40791667-a0456892-652a-11e8-8bfd-394fbaabb7b3.png">

**Comment by gilbarbara** [comment]
Which version?

**Comment by hjfrun** [comment]
v1.11.4

**Comment by gilbarbara** [comment]
V1 is deprecated. Please try V2
