### ISSUE TITLE
[V2] IE 11 compatibility

### ISSUE THREAD

**Issue by hlehmann** [gilbarbara/react-joyride#383]
In order to make the v2 work in IE 11 I had to use polyfills for : 
- String.prototype.startsWith (core-js/modules/es6.string.starts-with)
- Object.getPrototypeOf (core-js/modules/es6.object.get-prototype-of)
- Element.prototype.remove (https://github.com/jserz/js_piece/blob/master/DOM/ChildNode/remove()/remove().md)

What could be done to avoid this error for others ?

**Comment by gilbarbara** [comment]
The prototype.remove will be updated soon but the rest won't be fixed. If you need to support old browsers you'll need pollyfills
