### ISSUE TITLE
typescript definitions are not up-to-date since rewrite March 1

### ISSUE THREAD

**Issue by emjane** [gilbarbara/react-joyride#384]
>Expected behavior
Typescript properties should be consistent with documentation

>Actual behavior
"selector" is now "target"
"continuous" is now "type"
etc...

>Steps to reproduce the problem
declare selector or continuous properties/ get error that prop does not exist 

>React version
15.6.2

>React-Joyride version
4.11.1

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
duplicate of #379
