### ISSUE TITLE
Cannot override Locale Property on Step

### ISSUE THREAD

**Issue by dzfranco** [gilbarbara/react-joyride#388]
>Expected behavior

The state can override locale property

>Actual behavior

The state renders using either default locale or joyride-level locale.  The problem can be seen on this fork of the sandbox https://codesandbox.io/s/m4pv67zox8 on the first step of the basic tour.

Note that the rest of the properties are being overridden, save for the locale one.

>Steps to reproduce the problem

1. Use the usual Joyride setup
2. In a step add the locale property with the overrides, such as `{ back: 'Atras', close: 'Cerrar', last: 'Finalizar', next: 'Siguiente', skip: 'Saltar' }`
3. Observe the render, it will use the default properties

>React version

16.3.2

>React-Joyride version

2.0.0-11

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
Yeah, you can't set locale on the step.

If need to customize each step radically you probably will need to use your own components with the render props.
