### ISSUE TITLE
Multiple Targets

### ISSUE THREAD

**Issue by LeomarAmiel** [gilbarbara/react-joyride#389]
Hi, 

Using react-joyride 2.0.0-11

Is it possible to add multiple targets in a single step? I want to put multiple spotlights to different components with only one Joyride instance.

**Comment by gilbarbara** [comment]
nope, only a single target per step.

**Comment by jesperlandmer** [comment]
I too had this problem and made an ugly fix to wrap multiple elements into a div and highlighted the wrapped-div if anyone else comes across this problem.

`function wrapMultiElements(steps) {
  steps.forEach((step, index) => {
    if (Array.isArray(step.target)) {
      const classes = step.target;
      const d = document.createElement('div');
      d.id = `step-${index + 1}`;
      d.style.display = 'inline-block';

      classes.forEach((c) => {
        const el = document.querySelector(c);
        const wrapperExists = document.getElementById(d.id);
        if (!wrapperExists) {
          el.parentNode.insertBefore(d, el);
          d.appendChild(el);
        } else if (!wrapperExists.contains(el)) {
          d.appendChild(el);
        }
      });

      steps[index].target = `#${d.id}`;
    }
  });
}`

Now all steps that includes an array of targets will be wrapped.
