### ISSUE TITLE
does not support server side rendering

### ISSUE THREAD

**Issue by thomasjshafer** [gilbarbara/react-joyride#39]
Hey @gilbarbara,

Thanks for this library. It works great, however it does not support server side rendering. It would be totally ok to only show the tooltips on the client. The issue is the library cannot be required on the server due to accessing the `window` object on `require` or `import`.

Thanks,
Thomas

**Comment by gilbarbara** [comment]
Hey,

Yeah, I never tried it on server-side rendering. But I'm not sure how to implement this library without using the DOM.

If you know how to fix it, let me know.

**Comment by thomasjshafer** [comment]
Thanks for the quick response. There isn't really a way to use the library without the dom for parts such as positioning and scrolling. The issue is really that requiring the library tries to access `window`. It would be great to just make sure that window is defined in the initial require. Then it's practically a no-op for server side which should mostly be fine. The library is really great and the demo looks fantastic.

**Comment by gilbarbara** [comment]
hey!
Sorry for the delay, it has been a crazy couple of months!
I've made some tests but some of the modules that I require still uses window..
You could wrap you render block inside a jsdom env so it can use a mocked window object.

```javascript
jsdom.env({
  html: '<!doctype html><html><body></body></html>',
  done: function (err, window) {
    if (err) {
      throw new Error(err);
    }

    global.window = window;
    global.navigator = window.navigator;

    var App = require('./components/App');
    console.log(ReactDOM.renderToStaticMarkup(<App />));
  }
});
```

**Comment by SunyoungKim508** [comment]
@gilbarbara where should I put that code?

**Comment by gilbarbara** [comment]
@SunyoungKim508 
There was an update (433ea7016777f285de764d3c0102b6b5fe265326) to skip the `window` object if it's not available.

If you still need it you could require an external script with Mocha, with `--require path/to/your/require.js` to initialize the jsdom window before running your tests.

**Comment by josebalius** [comment]
@gilbarbara https://github.com/gilbarbara/react-joyride/commit/9640e193a8b17512a71f716d60f08e994a7a40cb this release seems to break with `window` errors again.
