### ISSUE TITLE
Automatically trigger the first tutorial step on componentDidMount

### ISSUE THREAD

**Issue by Zionn13** [gilbarbara/react-joyride#390]
>Expected behavior

I would want to have the option to trigger the tutorial when the page loads,instead of user behaviour and I have found a way to do that by adding an element to the `steps` array

>Actual behavior

When you have an element in your steps array and that element is the first of the array, and said element is not hooked to any DOM element the Joyride automatically triggers the tutorial from the closest element that is hooked to the DOM. Also the `back` button has to be disabled for this use case(disabled for the first step,meaning index 1 instead of 0).

Problem here is that this breaks the `showProgress` counter and it would be nice to have a way to trigger the joyride automatically when a user enters the page

>Steps to reproduce the problem

Just use something like this, and make sure that `.empty-step` class is not assigned to anywhere on the dom.

`
joyrideSteps: [
        {
          target: ".empty-step",
          "content": "This step is here to trigger the tutorial on page load, do not assign it anywhere"
        },
        {
          target: ".first-step",
          "content": "something",
          "placement": "right",
          "event": "hover"
        }
      ],
`

>React version

>React-Joyride version

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by freak3dot** [comment]
I had the same problem.

My solution uses the following two settings together.
1. Use `disableBeacon: true` on all the steps.
2. Use the `run` property on the Joyride React component to run it when the page loads.

I hope this helps. I'm new to this component as well.

**Comment by gilbarbara** [comment]
As @freak3dot said, you need to set `disableBeacon: true` on the first step.

**Comment by mauro-sosa** [comment]
> I had the same problem.
> 
> My solution uses the following two settings together:
> 
> 1. Use `disableBeacon: true` on all the steps.
> 2. Use the `run` property on the Joyride React component to run it when the page loads.
> 
> I hope this helps. I'm new to this component as well.

Excellent

**Comment by gilbarbara** [comment]
Actually, you just need to add `disableBeacon: true` on the first step for continuous tours.
