### ISSUE TITLE
Editing defaultOptions?

### ISSUE THREAD

**Issue by snazzypants** [gilbarbara/react-joyride#391]
>React-Joyride version
2.0.0-11

How can I edit the defaultOptions globally? I understand that I can override any of these by passing props to the component, but there are a few things that I'd like to change globally (such as the default button colors).

**Comment by gilbarbara** [comment]
You can create set a prop `styles` in the Joyride component.

```jsx
<Joyride styles={{ options: { arrowColor: '#f04' } }} />
```

**Comment by Finwenor** [comment]
I would like to set the options once, for all the Joyride components I set in my project. I don't want to set these options on every single instance of Joyride component I put in my code. Is there a way to achieve this? Something like a default props to override?

**Comment by gilbarbara** [comment]
Yeah, several ways, but this doesn't concern this library or any other react components. 

> 'Polluting' the global scope means that you define too many variables that are globally accessible. From a programming perspective, you make it difficult to debug and maintain code when you use global variables.
[How JavaScript variable scoping is just like multiple levels of government](https://www.freecodecamp.org/news/how-javascript-variable-scoping-is-just-like-multiple-levels-of-government-d7ddabc49bf1/#:~:text='Polluting'%20the%20global%20scope%20means,when%20you%20use%20global%20variables.)

You can create a styles constant in your app (config.ts?), import it, and set it in the props, for example.
