### ISSUE TITLE
Use locale for beacon's title (open) to be able to translate it

### ISSUE THREAD

**Issue by Betree** [gilbarbara/react-joyride#392]
>Expected behavior

By specifying the key `open` in the `locale` object, we should be able to see the translation for beacon's title.

>Actual behavior

Beacon cannot be translated

![image](https://user-images.githubusercontent.com/1556356/41530903-df65178c-72f1-11e8-8880-d7ced7837761.png)

>React-Joyride version

`2.0.0-11`

**Comment by gilbarbara** [comment]
Fixed in `react-joyride@2.0.0-12`
