### ISSUE TITLE
beaconComponent works only when defining it inside step object

### ISSUE THREAD

**Issue by joakimgrr** [gilbarbara/react-joyride#395]
>Expected behavior

In the examples this works:

```
state = {
    beaconComponent: props => <Beacon {...props} />,
    run: true,
    steps: [ ... ]
}
```

>Actual behavior

In my testings the top level beaconComponent is ignored but works when defined like this:

```
state = {
    run: true,
    steps: [
        {
            beaconComponent: props => <Beacon {...props} />,
            ...
        }
   ]
}
```

>React version

16.3.2

>React-Joyride version

2.0.0-11

This might be just a misalignment between the docs and actual behaviour since the 2.0 version is used. If so I'll gladly try to help updating the docs.

**Comment by gilbarbara** [comment]
I'm not sure I understood this correctly since the `Custom` example sets the `beaconComponent` at the tour level and it's working.
Are trying to override this props in the step too?

Please post an example at codesandbox.
