### ISSUE TITLE
Calling joyride.back() triggers the callback with action="next" in V1

### ISSUE THREAD

**Issue by DamianDobrev** [gilbarbara/react-joyride#396]
Hi, I've been trying to use react-joyride for a multi-page tour. I've noticed a bug with the actions callback in v1.

When going back using the `joyride.back()` method, the callback's action prop value is "next" instead of "back", opposite to what the documentation says. This makes it very difficult to track which way we're navigating in step:after. I've tried putting using various props for Joyride and for the steps in order to spot the bug, but it was always there.

Here're some console.logs from the callback function when clicking next:
```
step: {action: "next", index: 3, type: "step:after", step: {…}}
step: {action: "next", index: 4, type: "step:before", step: {…}}
step : {action: "next", index: 4, type: "tooltip:before", step: {…}}
```

Thus the expected behavior for "back" is that the data passed in the callback would be:
>Expected behavior
```
step: {action: "back", index: 4, type: "step:after", step: {…}}
step: {action: "back", index: 3, type: "step:before", step: {…}}
step: {action: "back", index: 3, type: "tooltip:before", step: {…}}
```

>Actual behavior
```
step: {action: "next", index: 4, type: "step:after", step: {…}}
step: {action: "next", index: 3, type: "step:before", step: {…}}
step: {action: "next", index: 3, type: "tooltip:before", step: {…}}
```

>Steps to reproduce the problem
1. Create a Joyride component as you normally would with `callback={handleCallback}`

2. Create 2 steps:

step 1: In "text" should contain:
```
const nextButton = <button onClick={() => this.joyride.next()}>Next</button>
```
step 2: In "text" should contain:
```
const backButton = <button onClick={() => this.joyride.back()>Back</button>
```

3. Add function `handleCallback = (param) => console.log('step param: ', param)` 

3. Click Next to go to step 2

4. [Clear log and] click Back to go back to step 1

5. Check the log and notice that "action" prop of the parameter passed to `handleCallback` is "next"

>React version
15.6.2

>React-Joyride version
1.11.4

>Error stack
No error, just incorrect behavior.

P.S. In V2 the problem does not exist when changing the step index to switch the step.

**Comment by gilbarbara** [comment]
V1 won't get any further updates.
