### ISSUE TITLE
Console warning - overlay not mounted?

### ISSUE THREAD

**Issue by jazzdragon** [gilbarbara/react-joyride#397]
I'm getting this error in the console:
index.js:2178 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the Overlay component.

>Expected behavior

I expect to not get the error... :)

React version: 16.0.0
React-Joyride version: 2.0.0-11

>Error stack

![image](https://user-images.githubusercontent.com/5546798/42386526-9db49edc-80f4-11e8-9922-30e2d57d3686.png)

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
Please post an example in codesandbox

**Comment by codehtmai** [comment]
I'm getting this also. It's worth noting that it only showed up after I switched Joyride to a controlled component.

**Comment by SlowFamily** [comment]
Getting duplicate error as well with 2.0.0-15. Only seems to occur for me in mobile when step event is "hover". Setting event to "click", which is the actual event with a touchscreen, seems to resolve the issue.
