### ISSUE TITLE
Spotlight on safari rendered as grey box

### ISSUE THREAD

**Issue by parlux** [gilbarbara/react-joyride#399]
Spotlight elements render with a grey background. Found on Safari 11.1.1 and mobile safari iOS 11.4.

It appears the `mix-blend-mode` isn't working as expected, although it is supported by safari ¯\_(ツ)_/¯.

>Steps to reproduce the problem

Can be seen in the demo, https://2zpjporp4p.codesandbox.io/ on desktop and mobile safari

>React-Joyride version

2.0.0-11

**Comment by Chypa74** [comment]
@parlux try to change z-index for overlay, floater element (tooltip and arrow) and spotlight. For help check this style document: [style.js](https://github.com/gilbarbara/react-joyride/blob/3e08384415a831b20ce21c8423b6c271ad419fbf/src/styles.js)

**Comment by parlux** [comment]
@Chypa74 cool thanks, it almost worked! In the demo setting the overlay `z-index` to less than 50 fixed it.

However my use case has a fixed navbar on the page, which seems to break it again :(. I've saved a [modified version of the demo](https://codesandbox.io/s/nw4x92jr4l) with a fixed navbar, and regardless of `z-index` combinations, I can't get it to render without a grey box for the spotlight.

Strangely toggling the overlay's `mix-blend-mode` or `z-index` off then on using safari devtools gets the spotlight to render correctly.

Feels like there is something strange going on. The same demo works fine in chrome and firefox.

**Comment by gilbarbara** [comment]
> Strangely toggling the overlay's mix-blend-mode or z-index off then on using safari devtools gets the spotlight to render correctly.
> Feels like there is something strange going on. The same demo works fine in chrome and firefox.

Yeah, I'm getting the same behavior and it feels like a bug in Safari.  
I'm trying to find out why.

**Comment by gilbarbara** [comment]
Fixed in `react-joyride@2.0.0-12`

**Comment by z496090280** [comment]
> 固定于`react-joyride@2.0.0-12`

"react-joyride": "2.7.2-0",This problem still exists

**Comment by z496090280** [comment]
> Fixed in `react-joyride@2.0.0-12`

"react-joyride": "2.7.2-0",This problem still exists

**Comment by gilbarbara** [comment]
Hey @z496090280 
Please refer to this [comment](https://github.com/gilbarbara/react-joyride/issues/467#issuecomment-452881947)

If you still have problems after setting the background, open a new issue.
