### ISSUE TITLE
re-implement as a higher-order component

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-joyride#4]
https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775
https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by gilbarbara** [comment]
:+1:

**Comment by IanVS** [comment]
Hi, can you explain why you closed this issue?  I'm just getting started using this library, and a HOC seems like the perfect fit for it.

**Comment by gilbarbara** [comment]
The first version was a mixin for `React.Class`, this current version closed this
