### ISSUE TITLE
Some examples?

### ISSUE THREAD

**Issue by zalmoxisus** [gilbarbara/react-joyride#40]
First, thanks for the library, it looks awesome! I'd like to see the sources of the demo in order to understand better how to use it.

Is it possible to use only tooltips, so to import them from from `react-joyride/lib/scripts/Tooltip`, or we still need the main component to be rendered? It would be great to have an example of using standalone tooltips.

**Comment by gilbarbara** [comment]
Hello @zalmoxisus,

Thanks! :)

The demo source is in another branch: [demo](https://github.com/gilbarbara/react-joyride/tree/demo)

You'll have to import the whole package even if you are using only standalone tooltips.
Most of the work is done in the main component and it just call Tooltip for display.

[s]

**Comment by zalmoxisus** [comment]
Thanks a lot for the clarification!
