### ISSUE TITLE
HandleKeydown for TAB key is throwing exception

### ISSUE THREAD

**Issue by ravsom** [gilbarbara/react-joyride#400]
>Expected behavior
No error/exception should be thrown/raised

>Actual behavior
Exception is raised

>Steps to reproduce the problem
* Invoke a step
* hit tab key

>React version
16.4.1

>React-Joyride version
2.0.0-11

>Error stack
handleKeyDown@webpack:///../node_modules/react-joyride/es/index.js_+_1_modules?:1245:5\n","message":"event is not defined"

*If you are having UI issues, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
Couldn't reproduce this.
Which browser?

**Comment by ravsom** [comment]
i suspect it is this part of the code - 

`function handleKeyDown(e) {
  if (!modalElement) {
    return;
  }

  if (e.keyCode === TAB_KEY) {
    interceptTab(modalElement, event);
  }
}`

in scope.js

**Comment by gilbarbara** [comment]
> Thanks for the wonderful library.

🎉

It's fixed and it will be published in the next release

**Comment by Whyves** [comment]
I just realized that tabbing works during the steps but as soon as the tour ended, tabbing is not working in my page anymore. I'm on Chrome. Would that be related to this problem?

**Comment by ravsom** [comment]
We're seeing this problem as well - but it doesn't get resolved with the fix provided for the problem mentioned here.

The tabbing does get broken after the tour ends.
