### ISSUE TITLE
Need help. Unexpected behaviour. Popup fails to load, entire page locks.

### ISSUE THREAD

**Issue by dcworldwide** [gilbarbara/react-joyride#403]
Using latest 1.x. I'm really stuck. I can't figure out a customer issue. 

I have a customer using chrome  67.0.3396.99 (Official Build) (64-bit). When they load our app, the popup doesn't render clearly and the page is locked. In the screen, the popup isn't visible, but it should be. You can see the popup background has blurred out the app. 

<img width="530" alt="popuperror" src="https://user-images.githubusercontent.com/4898751/43045861-931902d0-8e03-11e8-81a7-f3492b85f4aa.png">

**Comment by dcworldwide** [comment]
Also no errors in the logs. Very odd.

**Comment by gilbarbara** [comment]
1.x is deprecated, no more support.

That said, it might be an extension or something. Ask him to try it in a incognito window.

**Comment by dcworldwide** [comment]
Because we couldn't find a solution we ended up removing joyride. Excited to retry 2.x. happy to test
