### ISSUE TITLE
Disable finish button

### ISSUE THREAD

**Issue by DonHarishAxe** [gilbarbara/react-joyride#404]
>Expected behavior
I need to have a walkthrough where there is only one step. I don't want the finish button, instead I have set the timeout directly.

>Actual behavior
There is no way to disable the finish button.

>Steps to reproduce the problem

>React version

>React-Joyride version
v2

>Browser name and version

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
You can use your own components if you need to change core functionality.
Check the `Custom` example in the demo.
