### ISSUE TITLE
Custom `tooltipComponent` doesn't receive all relevant props.

### ISSUE THREAD

**Issue by MilllerTime** [gilbarbara/react-joyride#405]
>Expected behavior

In the [Step object doc](https://github.com/gilbarbara/react-joyride/blob/master/docs/step.md), there are a number of useful properties that can be set to alter the tooltip, such as `hideBackButton` and `showSkipButton`. I would expect these to be provided to a custom `tooltipComponent` so that it can replicate the standard behavior.

>Actual behavior

The props I mentioned above are not provided to a custom tooltip, so it's not possible to, for example, hide the back button per step when using a custom tooltip.

A quick test reveals that as of v2.0.0-13, the following props are provided to the custom tooltip component:

- backProps
- closeProps
- primaryProps
- skipProps
- content
- continuous
- index
- isLastStep
- locale
- setTooltipRef
- size
- title

`title` and `content` from the step definition are there, but not other step features like `hideBackButton`. I checked if `backProps` contained a `visible` property or similar, but it does not. It would be great if all step properties were provided to custom tooltips. Thanks!

>React-Joyride version

2.0.0-13

**Comment by MilllerTime** [comment]
There is also no style information passed to the custom tooltip. I realize it's not as critical that style attributes like background color are passed though, since you can already render the custom tooltip in any way. However, it's not possible to change the width of the tooltip on a per-step basis without passing through some of the styles. Changing the width on different steps is a great feature of the default tooltip, and I'd like to have that ability with custom tooltips as well. I have a tour in particular that would benefit from this. The other style information would be a nice to have, too.

Is there any reason why style data is **not** being passed to custom tooltip components?

**Comment by gilbarbara** [comment]
The idea behind the custom tooltip is that you decide what to show or not..
I won't change the render props that are currently being passed down but I could add some other pieces.
Passing the step besides the render props would work for your needs?

**Comment by MilllerTime** [comment]
> Passing the step besides the render props would work for your needs?

Yeah, if all step data is accessible, that would be great!

> The idea behind the custom tooltip is that you decide what to show or not..

I hear you on this. However, I'd like to avoid having a `<TooltipWithBackButton>`, `<TooltipWithoutBackButton>`, `<TooltipNarrow>`, `<TooltipWide>`, etc. I could create a higher-order component to produce these variants on the fly. It's just that you already have a documented approach to customizing the default tooltip, and I'd like my custom tooltip to be a drop-in replacement without requiring other changes and a different API.

**Comment by gilbarbara** [comment]
I'm not sure what to say. The idea of custom tooltips is to give flexibility to users...

**Comment by gilbarbara** [comment]
Fixed in 3135983ff1db708a4f2efe712576a6cc6ec353fc
