### ISSUE TITLE
Can we change taget in controlled joyride?

### ISSUE THREAD

**Issue by DonHarishAxe** [gilbarbara/react-joyride#406]
>Expected behavior
I have a case where in the same step I need to change the content and target after a few seconds. I have written a custom tooltip component for the content manipulation but I'm unable to change the target. Any idea on how to do it?

>Actual behavior
Unable to change target dynamically within controlled joyride.

>Steps to reproduce the problem

>React version
v2

>React-Joyride version

>Browser name and version

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by MilllerTime** [comment]
Any reason this has to be a single step? It would be much simpler if it was two sequential steps. Each would have its own target and content. You could switch between them programmatically by changing the `stepIndex` value you pass to <Joyride>.

**Comment by DonHarishAxe** [comment]
Yeah. I agree that it would be really simple if they were two separate steps. But the situation demands us to do some animation within the same step while pointing to a different target. Is there not any way to do it?

**Comment by gilbarbara** [comment]
Nope, the steps are immutable.

**Comment by MilllerTime** [comment]
Well, there's the answer.

You can still work around this by using two steps. The content of the second step would run the animation you need. You could create a custom component to perform the animation on mount, and use it as the content of the second step. This way you have a simple tooltip component, and the animation complexity lies within the content itself.

**Comment by DonHarishAxe** [comment]
No it's not the content change that's causing the issue. It's the target that should change on a timeout. But I think it's impossible to change the target within the same step. Correct me if I'm wrong.

**Comment by MilllerTime** [comment]
Based on the response above, you cannot change the target. But, you can change the step. Using two steps,  you can set two targets. You can switch to the second step with a timeout, and the content of the second step runs your animation.

It would flow like this:

1. Create a controlled `<Joyride>` component, where you control the `stepIndex` via external state.
2. Start the tour, and the first step is displayed.
3. Queue a timeout that increments the `stepIndex`. This causes step 2 to display automatically, pointing at the new target.
4. Your animation runs as a result of step 2 being displayed.

**Comment by DonHarishAxe** [comment]
Yeah I got your point. With two steps, things are clear, I think I should probably do the same. I just checked with the relevant folks and they don't have a problem in doing it in two steps if it's really hard to implement it within the same step. Will go ahead with the two steps approach. Thanks for your suggestions! Closing this issue as well.
