### ISSUE TITLE
Strange behavior of Skip & Close link

### ISSUE THREAD

**Issue by a5his** [gilbarbara/react-joyride#408]
>Expected behavior
While clicking `Skip` I should move to next step.
While clicking 'Close` i.e. `X` link, it should exit.

>Actual behavior

While clicking `Skip` it exits.
While clicking 'Close` i.e. `X` link, it moves to next step.

>Steps to reproduce the problem
You can follow your demo version to verify this bug. I am adding the screenshot along with this.

![bug-joy-ride](https://user-images.githubusercontent.com/330362/43257815-84e27918-90f0-11e8-9b08-cfb37785d66e.gif)

>React version
Version: `^16.2.0`,

>React-Joyride version
Version: `^2.0.0-13`

>Browser name and version
Chrome - Version 67.0.3396.99

>Error stack (if available)
Nothing

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
That's the expected behavior and not a bug.
If you want to change it, you can try the controlled mode and/or a custom tooltip to handle the actions by yourself.
