### ISSUE TITLE
Show tooltip right away instead of showing the beacon

### ISSUE THREAD

**Issue by xwkuang5** [gilbarbara/react-joyride#409]
Hi, thanks for the awesome library for creating a tutorial workflow!

I was wondering if there's a way to force the user to take the tutorial by showing the tooltip right away instead of showing only the beacon and allowing the user to decide whether he/she wants to click on it or not. 

Can someone provide an example of how to do this?

Thanks!

>React version
16.4.1

>React-Joyride version
2.0.0-13

>Browser name and version
Google Chrome

**Comment by matheusmr13** [comment]
I was having this same issue. How I solved it:

```
class MyTutorial extends Component {
  constructor(props) {
    super(props);
    this.joyrideRef = React.createRef();
  }

  componentDidMount() {
    setTimeout(() => {
      this.joyrideRef.current.setState({ lifecycle: 'tooltip' });
    });
  }

  render() {
    return (
      <Joyride
        ref={this.joyrideRef}
       ...
      />
    );
  }
}
```

It works but doesn't seem like the best solution. Maybe some prop to not render a beacon and force tooltip?

**Comment by gilbarbara** [comment]
You can use `disableBeacon` in the [step](https://github.com/gilbarbara/react-joyride/blob/master/docs/step.md).

**Comment by tarjei** [comment]
@gilbarbara  disableBeacon is just for 2.x, right? Also, when will you release 2.0?

**Comment by tarjei** [comment]
For  1.x the escape hatch is: `this.joyrideRef.setState({ shouldRenderTooltip: true })`

**Comment by BhumiSalat** [comment]
disableBecon prop is not shown i use this version "react-joyride": "^2.3.1",
