### ISSUE TITLE
stepCallback invoked incorrectly

### ISSUE THREAD

**Issue by rubengrill** [gilbarbara/react-joyride#41]
- The stepCallback is invoked when the tooltip is opening (the doc says when completed)
- The stepCallback is also invoked when the tooltip is closing, but for the next step!
  When the next step is opened, the callback is invoked again.

Can be reproduced with at least 2 steps.

**Comment by Keats** [comment]
That would be because of those lines: https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Component.js#L483-L489

That should be done in that function https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Component.js#L430 from a quick look

**Comment by gilbarbara** [comment]
hey,
I'll take a look at this this weekend.

**Comment by gilbarbara** [comment]
Fixed 5c9f6291ef26a28a5ae510da7f9da9f4528c2b52

Thanks
