### ISSUE TITLE
Why close button's size units are tied to px? Why ? Why ?

### ISSUE THREAD

**Issue by harshad521** [gilbarbara/react-joyride#410]
I want to provide the svg's width and height in rem/em. But it seems from the styles prop we are only allowed to give absolute values and the suffix of 'px' will be appended to it.

https://github.com/gilbarbara/react-joyride/blob/72fae22b81b73784efdf5c8ee85968b9ddac0454/src/components/Tooltip/CloseBtn.js#L14
https://github.com/gilbarbara/react-joyride/blob/72fae22b81b73784efdf5c8ee85968b9ddac0454/src/components/Tooltip/CloseBtn.js#L15

**Comment by gilbarbara** [comment]
I changed the behavior in 2.0.0-14
