### ISSUE TITLE
mix-blend-mode and body background

### ISSUE THREAD

**Issue by smashercosmo** [gilbarbara/react-joyride#411]
Just want to note here that mix-blend-mode is buggy in Chrome when background is applied to body element. See the [demo](https://codesandbox.io/s/1z5xqrowp7). To fix that, you need to apply white background to html element. Here is the relevant [stackoverflow question](https://stackoverflow.com/questions/46358881/why-dont-css-blend-modes-work-when-applied-against-the-document-body). May be worth adding to readme. P.S. Thx for the awesome lib)

**Comment by gilbarbara** [comment]
Thanks, That's good to know!
A quick search on the topic will find this issue.
