### ISSUE TITLE
Option to remove delay between steps

### ISSUE THREAD

**Issue by smashercosmo** [gilbarbara/react-joyride#412]
In my project I decided to remove mix-blend-mode solution and use box-shadow solution for all browsers, because I want to have full control over overlay background, so I changed overlay and spotlight styles to
```js
const styles = {  
  overlay: {
    backgroundColor: 'transparent',
    mixBlendMode: 'unset',
  },
  spotlight: {
    backgroundColor: 'transparent',
    boxShadow: `0 0 0 9999px rgba(0, 0, 0, 0.5), 0 0 15px rgba(0, 0, 0, 0.5)`,
  },
}
```
But now I have another problem. Because of the delay between steps, I can see very annoying blinking, when steps are removed and appended to DOM. Is there a way to remove this delay?

**Comment by gilbarbara** [comment]
I really can't say without seeing an example.

**Comment by mmd550** [comment]
I have this problem too. These blinks happen in projects main codesandbox too. 
https://codesandbox.io/p/devbox/github/gilbarbara/react-joyride-demo/tree/main/?file=%2Fsrc%2FApp.tsx

**Comment by gilbarbara** [comment]
Hey @mmd550 
Does the blinking happen in the  built [demo](https://react-joyride.com/)
Because the codesandbox runs in the `dev` environment with the `StrictMode` wrapper, so it's expected.

**Comment by davidshumway** [comment]
There seems to be a delay because I'm able to double-click the spotlight, call handlers.next() on the first click, and the second click goes through on the spotlight even though the spotlight should be on a different area of the screen.
