### ISSUE TITLE
Custom spotlight styling for individual steps

### ISSUE THREAD

**Issue by DonHarishAxe** [gilbarbara/react-joyride#413]
>Expected behavior
Need to set border radius for spotlights per step

>Actual behavior
Unable to find a way to do it

>Steps to reproduce the problem

>React version

>React-Joyride version
v2

>Browser name and version

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by MilllerTime** [comment]
Yeah, this would be a nice feature to document. It might even make a good high-level option. Anyways, if you dig in [styles.js](https://github.com/gilbarbara/react-joyride/blob/3e08384415a831b20ce21c8423b6c271ad419fbf/src/styles.js) (as the docs recommend) you can see how all the internal styling works. 

To set a custom border radius, use the following code. Note that you can also use the `customStyles` object on a per-step basis to change the border radius between different steps if needed.

```javascript
const customStyles = {
  spotlight: {
    // Set your border-radius here!
    borderRadius: 100
  }
};

<Joyride
  styles={customStyles }
  // ...other joyride props
/>
```

**Comment by gilbarbara** [comment]
Yep, changing the styles will do!

**Comment by admehta01** [comment]
I'm getting an error when trying this w/ TypeScript ("@types/react-joyride": "2.0.0") and the latest version as of today.

[ts] Type '{ spotlight: { borderRadius: number; }; }' has no properties in common with type 'StepStyles'.

index.d.ts(173, 5): The expected type comes from property 'styles' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Joyride> & Readonly<{ children?: ReactNode; }> & Readonly<Props>'

Any ideas?
