### ISSUE TITLE
[Feature request]: stepID as prop instead of stepIndex

### ISSUE THREAD

**Issue by nthgol** [gilbarbara/react-joyride#414]
I created a joyride. Then I decided I wanted to add a step to the beginning of the joyride.

I've done a lot of 'side-effects' on my steps. For example, in `handleJoyrideCallback`, I have conditionals like `if(index===2) { //send an email }`.

By adding a step, I've got to go in and modify all the indices. 
If steps was a key-value object rather than an array, Joyride could accept a stepID instead. 
Thanks

**Comment by nthgol** [comment]
It looks like you can pass arbitrary props into each step and that will be passed into `handleJoyrideCallback`, so i'll pass an ID

**Comment by gilbarbara** [comment]
😉
