### ISSUE TITLE
Tab doesn't work after tour ends

### ISSUE THREAD

**Issue by ravsom** [gilbarbara/react-joyride#418]
>Expected behavior
Tab key should continue to work

>Actual behavior
Tab doesn't work

>Steps to reproduce the problem
Start a tour with at least 1 step
Close the tour
Click the TAB key on the browser

>React version
16.4.1

>React-Joyride version
2.0.0-14

>Browser name and version
Chrome -  68.0.3440.84

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by Whyves** [comment]
Thanks @ravsom , should add the removeScope() function in a componentWillUnmount handler do the trick?
