### ISSUE TITLE
Trying to bold certain words in the string

### ISSUE THREAD

**Issue by nickbae91** [gilbarbara/react-joyride#42]
Hey,

So I'm trying to bold certain words within a string in the Tour popovers. Is there a way to do this?

**Comment by Keats** [comment]
Use html tags ( https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Tooltip.js#L238 )

**Comment by nickbae91** [comment]
Thanks so much! I know it must've been an obvious answer, but it isn't for new coders like myself! I think it may be a good idea to a sentence of this in the documentation to make sure we know what's possible or not.

But amazing project you got going here! Thanks again!

**Comment by Omobayode6** [comment]
I am also facing this issue but the link you provided is not going.

Someone should please help

**Comment by gilbarbara** [comment]
Hey @Omobayode6 
You can use JSX in the step's `content`.
Check the [docs](https://docs.react-joyride.com/step#options)
