### ISSUE TITLE
Why string concatenation is used instead of doing it in JSX way? why? why?

### ISSUE THREAD

**Issue by ppandatw** [gilbarbara/react-joyride#421]
Apart from this line everything of 'locale' object can be a react node. Can you please use _span_ or something for concatenation?
Also update the type of 'locale's fields to React.Node from string. 
https://github.com/gilbarbara/react-joyride/blob/72fae22b81b73784efdf5c8ee85968b9ddac0454/src/components/Tooltip/Container.js#L33

**Comment by gilbarbara** [comment]
¯\_(ツ)_/¯
