### ISSUE TITLE
Clicking next button skips beacon

### ISSUE THREAD

**Issue by CharlesBradshaw** [gilbarbara/react-joyride#425]
I want some way of telling Joyride that for a specific step, the beacon should show before the modal and overlay. Sometimes I want the next button to take me to the next step but sometimes I want to let the user explore before going to the next step without having to x out of the current modal. Currently setting disableBeacon to false doesn't force the next beacon to show. 

I figure that this isn't an actual but so I haven't included any code, but if disable Beacon is intended to force the beacon to pop up before the next step then I'll get together some code.

**Comment by gilbarbara** [comment]
You can set `continuous` to false. Or if you complete control you can use `stepIndex` and control the tour by yourself.
Check the demo.
