### ISSUE TITLE
Beacon not moving with target component

### ISSUE THREAD

**Issue by j0o009k** [gilbarbara/react-joyride#429]
>Expected behavior
The beacon to follow whatever component it is attached to.

>Actual behavior
The beacon stays static even after the component refreshes.

>React version
15.6.2

>React-Joyride version
2.0.0-13

I am using Joyride as a tutorial for different widgets on a dashboard. Each widget has its own tutorial, and Joyride component associated with it. When a widget is dragged and dropped to a not spot on the dashboard, the beacon does not move with it but stays stationary until you scroll in the widget. 

Is there a way to update the position of the beacon when its target component updates?

**Comment by gilbarbara** [comment]
It's impossible for me to know what's going on without seeing some code...
You could dispatch a scroll or resize event after the user moves the widget around.
