### ISSUE TITLE
Position not working for continuous mode

### ISSUE THREAD

**Issue by nickbae91** [gilbarbara/react-joyride#43]
So I'm specifying different positions for steps in _continuous mode_ (an extremely common use case for a tool like this) and it doesn't seem to be working. Specifically, only the position for the first step seems to go through, and that first step's position somehow "overrides" the subsequent steps (e.g. if I specify 'bottom' for the firs step's position, it appears in 'bottom' for all latter steps, regardless of which position I had specified).

However, when I do this for "single" mode, they do appear in the positions I have specified.

**Comment by Keats** [comment]
Can confirm this, going to try to have a look at the code to see what happens

**Comment by gilbarbara** [comment]
Hello @Keats ! :)

**Comment by gilbarbara** [comment]
Fixed 8f59777b406938dcd17b3525fc25485a2d5c5b64

Thanks!

**Comment by nickbae91** [comment]
Hey,
So I think that issue triggered another issue - now the Tour is not working at all... This is what I see in the console:

![image](https://cloud.githubusercontent.com/assets/12439968/14408329/72229c18-fead-11e5-898f-0f20534d0adc.png)

**Comment by nickbae91** [comment]
Hey,

I really hope I'm not being annoying here! Just wanted to point out that the position works correctly, but now the overlay is not working for 'continuous' mode. I know it's not something on my end, as I'm testing the same code in the previous version and current version of react-joyride.

**Comment by nickbae91** [comment]
**Update: **I narrowed down the issue to be the "stepCallback" function, and not the overlay. My overlay was dynamic depending on which step the Tour was at, so I could detect this.

It is not being called every time the "Next" or "Back" button is pressed, but only called when the "X" button is pressed in the Step Popover.
Perhaps a bit too early to close this...?

**Comment by gilbarbara** [comment]
@nickbae91 You're not been annoying at all! :)

Please try 1.3.1 and let me know.
If the problems still persists, please open a new issue.

Thanks

**Comment by nickbae91** [comment]
Thanks a lot! It works perfectly now!
