### ISSUE TITLE
auto tour

### ISSUE THREAD

**Issue by charan-r** [gilbarbara/react-joyride#431]
>Expected behavior
need to show all tooltip automatically with some time intervel

>Actual behavior
There is no prop or step for this auto tour

>Steps to reproduce the problem

>React version

>React-Joyride version

>Browser name and version

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
You can achieve that with the controlled mode, check out the demo example.
