### ISSUE TITLE
Showing beacon on page start without need to hover or click

### ISSUE THREAD

**Issue by engmagdy87** [gilbarbara/react-joyride#434]
>Expected behavior
Showing beacon on page start without need to hover or click

>Actual behavior
must click or hover

>Steps to reproduce the problem

>React version
16

>React-Joyride version
2

>Browser name and version
chrome

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
Use `disableBeacon` on the first step.
You can read about step's options [here](https://github.com/gilbarbara/react-joyride/blob/master/docs/step.md).
