### ISSUE TITLE
Using CSS Selector for target doesn't select multiple elements

### ISSUE THREAD

**Issue by gitowiec** [gilbarbara/react-joyride#444]
>Expected behavior

One can query multiple elements that react-joyride highlights (eg table column with `td:nth-child(n)`) 
Readme.md says
> target {Element|string} - required
> The target for the step. It can be a CSS selector or an HtmlElement directly (but using refs created in the same render would required an additional render afterwards).
So I just thought....

>Actual behavior
If developer defines step's target as multiple elements CSS Selector only first element from group is used

**Comment by gilbarbara** [comment]
target must be a single element.
