### ISSUE TITLE
Highlight Spotlight not correct after scrolling

### ISSUE THREAD

**Issue by lightninglu10** [gilbarbara/react-joyride#448]
>Expected behavior

The highlight to highlight the correct element, even after scrolling.

>Actual behavior

The highlight spotlight is highlighting the wrong element. So what's going on is if I don't scroll at all, and then run through the joyride, then the correct element is highlighted. But if I scroll any amount, the wrong element gets highlighted. It looks like something to do with the highlight component using a different scroll from my scrolling (window vs. body??).

<img width="289" alt="screen shot 2018-12-04 at 10 25 38 am" src="https://user-images.githubusercontent.com/2453737/49464177-1052cf00-f7af-11e8-94fa-e8691cb662d7.png">

>React version

"react": "^0.14||^15.5.4||^16.1.1",

>React-Joyride version

"react-joyride": "^2.0.0-15",

**Comment by gilbarbara** [comment]
This will be handled in #376

**Comment by shakefish** [comment]
> Expected behavior

The highlight to highlight the correct element, even after scrolling.

> Actual behavior

The highlight spotlight is highlighting the wrong element. So what's going on is if I don't scroll at all, and then run through the joyride, then the correct element is highlighted. But if I scroll any amount, the wrong element gets highlighted. It looks like something to do with the highlight component using a different scroll from my scrolling (window vs. body??).

<img width="797" alt="image" src="https://user-images.githubusercontent.com/44423943/169488113-2b8d0afe-f550-4d21-9a46-75e98aa2cf5a.png">

> React version

"react": "18",

> React-Joyride version

"react-joyride": "^2.4.0",

**Comment by gilbarbara** [comment]
hey @shakefish 

Do you have a reproduction you can share, like Codesandbox? Issues without a reproduction link are likely to stall.
