### ISSUE TITLE
show a list as a step content

### ISSUE THREAD

**Issue by Ganjdast** [gilbarbara/react-joyride#449]
>Expected behavior

>Actual behavior

>Steps to reproduce the problem

>React version

>React-Joyride version

>Browser name and version

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by Ganjdast** [comment]
Hello, I was wondering if it's possible to pass html list <ul> to step contetnt config?

**Comment by gilbarbara** [comment]
Yes, using css selector.

**Comment by Ganjdast** [comment]
I'm sorry , I did'nt understand . you mean pass a css selector to content ? like this  {content : css selector}?

**Comment by Ganjdast** [comment]
could you give an example?

**Comment by gilbarbara** [comment]
Like this?

```js
{
  target: 'ul li:nth-of-type(1)',
  content: 'This is my super awesome feature!'
}
```

Or do you want to use the list item innerHTML as content? If that's the idea, what is the point of having a tooltip showing the same content of the target?
