### ISSUE TITLE
Can we have a feature to play/pause the joyride with some time interval so that it plays continuously ?

### ISSUE THREAD

**Issue by choudharypravesh03** [gilbarbara/react-joyride#450]
>Expected behavior

>Actual behavior

>Steps to reproduce the problem

>React version

>React-Joyride version

>Browser name and version

>Error stack (if available)

*If you want to get this issue fixed quickly, make sure to send a public URL or codesandbox example.*

**Comment by gilbarbara** [comment]
Yes, you can control the tour status using [props](https://github.com/gilbarbara/react-joyride/blob/master/docs/props.md).

**Comment by choudharypravesh03** [comment]
I dont want to click on next button to play the joyride. It should play automatically. Can we do that ?

**Comment by gilbarbara** [comment]
Not sure what you meant...
The user cannot decide when he wants to advance? It should appear and automatically move to the next without reading it? 😫
