### ISSUE TITLE
Overlay flashes between steps in legacy browsers.

### ISSUE THREAD

**Issue by kristof01** [gilbarbara/react-joyride#452]
>Expected behavior

No flashes nor blinking between steps in Edge nor IE.

>Actual behavior

There is a very noticeable flash between every step where the overlay disappears and reappears in Edge and IE.

>Steps to reproduce the problem

You can see this problem even in the demo:
[demo](https://codesandbox.io/s/2zpjporp4p)

>React version

16.4.1

>React-Joyride version

2.0.0-15

>Browser name and version

IE 11 and Edge 42.17134.1.0

**Comment by kristof01** [comment]
Hi, can someone take a look at this issue?

Thx!

**Comment by gilbarbara** [comment]
@kristof01 Feel free to submit a PR
