### ISSUE TITLE
Add a threshold for the arrow positioning to avoid clashing with the border-radius

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-joyride#453]

**Comment by marcindabrowski** [comment]
Is the same case as in #352? If yes, please fix it, because I'm getting the same issue.

**Comment by gilbarbara** [comment]
Feel free to submit a PR

**Comment by marcindabrowski** [comment]
I've just created the sandbox demo to illustrate the problem.
https://codesandbox.io/s/p3635wm587

**Comment by gilbarbara** [comment]
@marcindabrowski Feel free to submit a PR

**Comment by marcindabrowski** [comment]
OK, I will try, but maybe you can give me a clue where to fix it?
I'm not sure is it a problem with react-floater or with the joyride.
Where in joyride code do you compute the position of floater?

**Comment by gilbarbara** [comment]
hey!

The whole beacon/tooltip positioning is done by popper.js in react-floater, including the arrow.
Check out https://github.com/gilbarbara/react-floater/blob/master/src/components/Floater/Arrow.js

**Comment by marcindabrowski** [comment]
I've issued PR #471.

**Comment by gilbarbara** [comment]
@marcindabrowski GitHub already notified me...
