### ISSUE TITLE
Improve typescript typing

### ISSUE THREAD

**Issue by thomasviaud** [gilbarbara/react-joyride#455]
Hello,

I was wondering why in type definitions (`types/index.d.ts`) there is a Locale interface :
```
export interface Locale {
  back?: string;
  close?: string;
  last?: string;
  next?: string;
  skip?: string;
}
```
but it is not referenced anywhere else and locale props are defined as : `locale?: object;`

I also found strange that some onClick props are typed as string.

Thank you.

**Comment by gilbarbara** [comment]
Why? No reviewers, probably! 😃

**Comment by thomasviaud** [comment]
Alright, i'll try submit a PR asap

**Comment by gilbarbara** [comment]
I already fixed, thanks!

**Comment by thomasviaud** [comment]
Thank you !

**Comment by gilbarbara** [comment]
I'm gonna publish V2 today so I am reviewing everything (again)
