### ISSUE TITLE
Use different elements for the tooltip and the spotlight

### ISSUE THREAD

**Issue by marcindabrowski** [gilbarbara/react-joyride#468]
## 🚀 Feature Idea

Add new property to step named ie. `tooltipSelector` which will be used to position tooltip around another element that highlighted one.
At default when this property is not present it will work as now, and position tooltip around element pointed by `selector`.

## Motivation

Sometimes it is needed to position tooltip somewhere inside highlighted element.
Such approach will give more control where tooltip is placed.
Proposed solution should be easy to implement, and won't complicate API.

I think similar idea was introduced in #199, but was not continued.

## Example

I want to highlight large page element, but want to position tooltip around concrete element.
Using current position options it is impossible.

**Comment by gilbarbara** [comment]
I'm not sure I understand what you are proposing.
Anyway, feel free to submit a PR with examples and tests.

**Comment by marcindabrowski** [comment]
After looking into code, I've created PR #472 and added prop named `spotlightTarget`.
