### ISSUE TITLE
Beacon unable to scroll down on mobile devices

### ISSUE THREAD

**Issue by sach2211** [gilbarbara/react-joyride#47]
On mobile devices, 

1. Beacon is not coming at the correct place. If the div to which step is attached is not in the current view of mobile device, beacon does not cause the page to scroll automatically and attaches itself to some random div at the bottom of current view.

2. The position of beacon and tooltip is not perfect. 

Looks like there is some error with the way, how document height is calculated

**Comment by gilbarbara** [comment]
hey,

I just published 1.3.4 that attempts to fix this issue. Let me know if it works for you.

**Comment by sach2211** [comment]
Yeah , that fixed it . :+1:
