### ISSUE TITLE
React 15.6 and Joyride@2.0.2

### ISSUE THREAD

**Issue by romanlex** [gilbarbara/react-joyride#475]
I'm trying run project with react@15.6.2 and react-joyride@2.0.2
I see this error
![image](https://user-images.githubusercontent.com/3369304/51472010-52e56080-1d89-11e9-8ca7-39bba8e20863.png)
```
Failed prop type: react__WEBPACK_IMPORTED_MODULE_0___default.a.createRef is not a function
    in Joyride
```

I this file https://github.com/gilbarbara/react-joyride/blob/master/src/modules/propTypes.js#L52 I see what used React.createRef without check

**Comment by gilbarbara** [comment]
Fixed in 512737d23e7fbea9c6af3795fae5417eeb008dd1 (2.0.3)
