### ISSUE TITLE
spotlightPadding wrong type

### ISSUE THREAD

**Issue by ljordhen** [gilbarbara/react-joyride#476]
I think it's supposed to be number.

https://github.com/gilbarbara/react-joyride/blob/ef156aa2b533b5737d3b8955c1326353f8f78891/types/index.d.ts#L144

**Comment by gilbarbara** [comment]
Number or string

**Comment by gilbarbara** [comment]
Fixed in 512737d23e7fbea9c6af3795fae5417eeb008dd1
