### ISSUE TITLE
More strict types for "styles" Joyride's and JoyrideStep's prop

### ISSUE THREAD

**Issue by sigo** [gilbarbara/react-joyride#480]
## 🚀 Feature Idea

I think that `styles` property passed to `Joyride` and `JoyrideStep` components should be more strict than `any object`.

## Motivation

Better type checking.

## Example

```
const steps = [
    {target: "#root", content: "Lorem ipsum dolor sit amet.", styles: {{color: "#333"}}}
];

const MySteps = () => <Joyride steps={steps} styles={{color: "#666"}} />;
```

**Comment by sigo** [comment]
I can make simple PR. Based on documentation, there's only 2 places, where developer can pass `styles` prop.

**TypeScript**

- https://github.com/gilbarbara/react-joyride/blob/master/types/index.d.ts#L82
- https://github.com/gilbarbara/react-joyride/blob/master/types/index.d.ts#L147

**propTypes**
- https://github.com/gilbarbara/react-joyride/blob/master/src/components/index.js#L55
- https://github.com/gilbarbara/react-joyride/blob/master/src/components/Step.js#L71

**Comment by gilbarbara** [comment]
Added in 2.0.5
