### ISSUE TITLE
spotlight style won't override the default style

### ISSUE THREAD

**Issue by AE0011** [gilbarbara/react-joyride#489]
custom position style for spotlight won't override the default one
```
 <Joyride
           ...
            styles={{
                spotlight: {
                    position: 'fixed', // default is 'absolute'
                    color:'red',
                }
            }}
 />
```
as u can see in my code at run time position will remain 'absolute' however the color attr will changed

`"react-joyride": "^2.0.5",`

![screen shot 2019-02-24 at 4 53 12 pm](https://user-images.githubusercontent.com/37038198/53299801-bc5b0200-3854-11e9-89cd-364063271a60.png)

**Comment by gilbarbara** [comment]
Hey,

The Spotlight positioning is set [dynamically](https://github.com/gilbarbara/react-joyride/blob/master/src/components/Overlay.js#L160) and you can't override it.
If your target has `position: fixed` the spotlight will use that, otherwise it has to be absolute.

**Comment by AE0011** [comment]
Hi thanks for your response 
In my case i need that spotlight always be fixed ( i implement tour guide in boundary area constant width & height) 
Any way i edited library and changed position of spotlight to fixed! still i think i should be overridable because spotlight view is completely different with the target view and it shouldn't take positioning same as target view.

**Comment by gilbarbara** [comment]
It's impossible to know what is going on without seeing it running.
Can you post an example?
Is your "boundary area" fixed on the page? Does the page have scroll?

**Comment by gilbarbara** [comment]
BTW if you changed the source code directly, it will break when a new version is released and that won't work for new installations or with CI/CD.

**Comment by AE0011** [comment]
Oh i was dealing with this issue all day it's too much code to post :)) however main idea is like this:

I implemented project in size of mobile(400px 800px) so my main div have this boundary (sure it has scroll too). but when i used this useful package every thing worked fine but overlay didn't respect to my main div boundary and all screen got overlay!

So i set boundary to overlay view and 'absolute' position to it and it fixed but the spotlight view was out side the boundary so i needed to set it's position to 'fixed'

Still if u need a full example code let me know maybe there is a simple solution for this :)

**Comment by NikhilAshodariya** [comment]
@AE0011 I am also facing the same issue if you don't mind can you please share the code for it.

**Comment by AE0011** [comment]
@NikhilAshodariya 
I almost forgot about details but this is what i did :

```
node_modules/react-joyride/es/index.js line 1781
position: isFixedTarget ? 'fixed' : 'absolute', => position: 'fixed',
//
"react-joyride": "^2.0.5",
```


```
 <Joyride
            steps={steps}
            continuous
            run={run}
            scrollToFirstStep
            showProgress={false}
            showSkipButton
            styles={{
                overlayLegacyCenter: {
                    backgroundColor: 'red',
                },
                options: {
                    width: screenW * .9,
                    maxWidth: screenW * .9,
                },
                overlay: {
                    height: 'unset',
                    position: 'absolute'
                },
                spotlight: {
                    position: 'fixed',
                    color: 'red',
                },
                spotlightLegacy: {
                    position: 'fixed',
                }
            }}
            locale={locale}
            callback={callBackJoyAction}
            floaterProps={{
                disableAnimation: true,
                styles: {
                    floater: {
                        maxWidth: screenW * .9,
                    },

                }
            }}

        />

```
