### ISSUE TITLE
Anchor Links don't work in Descriptions

### ISSUE THREAD

**Issue by cris7ian** [gilbarbara/react-joyride#49]
Hi, I'm trying to add an anchor link to the description of the tooltip. 

```
For more information click <a href='/how-it-works' target='_blank'>here</a>
````

It's displayed and everything. But the link won't work.

![image](https://cloud.githubusercontent.com/assets/2112370/14642640/da49ce96-0610-11e6-9745-5a659fe95472.png)

It seems as if anchor links in descriptions don't propagate events. I had to add an `onclick` tag with an `window.open`.

**Comment by gilbarbara** [comment]
Fixed in 4ac5850224037703d5ca1207c3423c4cf12fc918 and published as 1.4
Sorry for the delay!
