### ISSUE TITLE
How to use it with multi pages

### ISSUE THREAD

**Issue by congdcit** [gilbarbara/react-joyride#491]
I have multi pages using `react-router`. How to use it? Anyone can help please!

**Comment by gilbarbara** [comment]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [The documentation](https://docs.react-joyride.com/)
- [Our chat on Spectrum](https://spectrum.chat/react-joyride)
- The [react-joyride](https://stackoverflow.com/questions/tagged/react-joyride) tag on [StackOverflow](https://stackoverflow.com/questions/ask)
