### ISSUE TITLE
Jittering message-box when scrolling (some screen widths only)

### ISSUE THREAD

**Issue by cuginoAle** [gilbarbara/react-joyride#493]
## 🐛 Bug Report

When scrolling the page content the message box tries to position itself multiple times on top and left side of the element.
In the demo page this happens only at some resolutions (it shows up around @ 1050 x 800)

## To Reproduce

 see screen-shot

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1298616/53523021-fdb11300-3adb-11e9-9e4e-80956cbaaef2.gif)

**Comment by gilbarbara** [comment]
The positioning is handled by popper.js (via react-floater) so there's not much I can do.
If this is something that affects your app, you should avoid using left/right or disable the flip options
