### ISSUE TITLE
Can't call setState on an unmounted component

### ISSUE THREAD

**Issue by gugiserman** [gilbarbara/react-joyride#494]
## 🐛 Bug Report

I don't see any side-effects in the UI but I always get this error thrown in the console when transitioning to the last step.

```bash
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in JoyrideOverlay (created by JoyrideStep)
    in JoyridePortal (created by JoyrideStep)
    in div (created by JoyrideStep)
    in JoyrideStep (created by Joyride)
```

## To Reproduce

it's a quite simple 3-step tour. We're running Nextjs 7, the component that renders `<Joyride />` with the following steps is placed at the `_app.js`, but no steps are loaded and it doesn't `run` until some time after it's been rendered client-side. It only happens when transitioning to the 3rd step, in which I have to set `run: false`, dispatch a redux action that changes the UI behind it, and set `run: true` back again (being handled with the `callback` prop, it's an uncontrolled flow). It's working pretty well overall.

```js
[
  {
    target: '.tour-step-1',
    content: 'Something',
    placementBeacon: 'right',
    placement: 'left',
  },
  {
    target: '.tour-step-2',
    content: 'Foo',
    placement: 'bottom',
  },
  {
    target: '.tour-step-3',
    content: 'Bar',
    placement: 'right',
    offset: 0,
    spotlightPadding: 0,
  },
]
```

## Expected behavior

No errors thrown.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

```bash
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 5.04 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
```

**Comment by edwinbbu** [comment]
I also faced similar issue. I manually set `run: false` before the component unmounted @gugiserman
