### ISSUE TITLE
Center tooltip while target highlighted

### ISSUE THREAD

**Issue by SamiNami** [gilbarbara/react-joyride#495]
## 💬 Questions and Help

Hi, is it possible to highlight an area with the beacon while having the tooltip centered? How would I go about doing this?

**Comment by gilbarbara** [comment]
Hey,

You mean to show the beacon next to a target but render the tooltip without context? Nope. Wouldn't that be a bad UX, especially on mobile?

**Comment by SamiNami** [comment]
Hi, 

This is what I'm trying to do:

https://www.dropbox.com/s/5z5yh6x7gtm3h1l/Screenshot%202019-03-07%2014.29.36.png?dl=0

**Comment by gilbarbara** [comment]
Yeah, not possible.

**Comment by SamiNami** [comment]
Wrote a custom tooltip for this (in case anyone is looking for a solution)
