### ISSUE TITLE
Hide next button

### ISSUE THREAD

**Issue by ZivJia** [gilbarbara/react-joyride#499]
## 💬 Questions and Help

Just want to know if we have a hideNextButton option somewhere or do I have to wirte my tooltip component in order to do that.

### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [The documentation](https://docs.react-joyride.com/)
- [Our chat on Spectrum](https://spectrum.chat/react-joyride)
- The [react-joyride](https://stackoverflow.com/questions/tagged/react-joyride) tag on [StackOverflow](https://stackoverflow.com/questions/ask)

**Comment by edwinbbu** [comment]
I face the same issue there is no option to hide the next button, but there is option to hide the back button

**Comment by ZivJia** [comment]
@edwinbbu I actually just used the hideFooter instead.

**Comment by edwinbbu** [comment]
@ZivJia I did the same using hideFooter and custom Tooltip. It is better to have option for hiding the next button alone.

**Comment by gilbarbara** [comment]
You can use the `styles` prop for it.

```jsx
<Joyride
  styles={{
	buttonNext: {
	  display: 'none',
	}
  }}
/>
```

**Comment by ZivJia** [comment]
Thank you very much

**Comment by MalikBagwala** [comment]
@gilbarbara This does not work when you want to show the progress. In my case I always want to show the progress but I just want to disable next in certain steps.

**Comment by MalikBagwala** [comment]
> You can use the `styles` prop for it.
> 
> ```js
> <Joyride
>   styles={{
> 	buttonNext: {
> 	  display: 'none',
> 	}
>   }}
> />
> ```

@gilbarbara This does not work when you want to show the progress. In my case I always want to show the progress but I just want to disable next in certain steps.

**Comment by gilbarbara** [comment]
Hey @MalikBagwala 

This issue was about hiding the next button entirely, and it has been closed for three years.
Since then, we have moved these questions to the Discussion board, where the community could help as well,

Anyway, you can read the [docs](https://docs.react-joyride.com/custom-components) on how to use custom components.
