### ISSUE TITLE
How to remove / hide "Close" Button? 

### ISSUE THREAD

**Issue by rahul1si12is035** [gilbarbara/react-joyride#503]
I am using this library in my react app. I do not want to show "Close" button. How to remove / hide "Close" Button? Thanks in advance.

**Comment by edwinbbu** [comment]
You can create a custom Tooltip where you can hide the Close Button (isLastStep prop is provided to check for the last step). There is no props provided by joyride for hiding next/close button @rahul1si12is035

**Comment by gilbarbara** [comment]
@rahul1si12is035 Yes, you can use the `styles` prop. Check the [docs](https://docs.react-joyride.com/styling)

As always, search the issues before posting a new one since this has already been answered.
