### ISSUE TITLE
progress with dots

### ISSUE THREAD

**Issue by glyif-wonder** [gilbarbara/react-joyride#504]
## 🚀 Feature Idea

Instead of having the progress being shown in as like 1/6 in the next button, have the progress be shown with dots.

## Motivation

a different, maybe more elegant way of showing progress

## Example

Something like this:
<img width="438" alt="Screen Shot 2019-04-01 at 11 46 26 AM" src="https://user-images.githubusercontent.com/35234523/55351684-d00d1000-5473-11e9-842a-39666ed36e89.png">

**Comment by gilbarbara** [comment]
Hey,

You can use your [own component](https://docs.react-joyride.com/custom-components) and change the UI to your needs.

**Comment by shurvirarora** [comment]
is there a way to bring progressComponent as a prop to edit the way progress is shown (such as the dots) on react joyride?
