### ISSUE TITLE
Overflow is cancelled, can't scroll, half of page is missing

### ISSUE THREAD

**Issue by shtengel** [gilbarbara/react-joyride#505]
## 🐛 Bug Report

When i put a <Joyride /> tag inside my `render()` function, the page overflow is hidden and then half of my page is cut. (can't scroll down, but if i use "Inspect Source in Chrome" find a element outside the screen and click Scroll Into View then the page does scroll to that element but you cant scroll to top that part is now cut off the page)

without the <Joyride /> tag i still see the page overflow is hidden but the scroll is available and you can scroll down and up

## To Reproduce
npm install react-joyride
add <Joyride /> to one of my Components

## Expected behavior
All page should be accessible and scroll should work

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:
  System:
    OS: macOS 10.14.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 494.78 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.9.4 - ~/Desktop/skywatch_web/node_modules/.bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman

#Fix:
 idk why, but when i add a CSS rule then scrolling is working and the whole page is accessible as it should be.
```
[role=navigation] {
    overflow: auto !important
}
```

**Comment by shtengel** [comment]
when `joyride-overlay` is opened half of my page is still missing, i can't react it , even i set scrollToSteps={true}

**Comment by gilbarbara** [comment]
This is probably a CSS issue with your setup and this library cannot fix these issues by itself.
You can add `min-height: 100vh;` to the `body` tag to see if it fixes your problem.

**Comment by starikcetin** [comment]
Setting `disableScrollParentFix={true}` fixed this for me. But now the highlight is positioned wrong for smaller screens.

**Comment by 100KhanMawaz** [comment]
> min-height: 100vh;

Habibi thank you very much it was a css problem only

**Comment by apcqa** [comment]
Thanks starikcetin was couldn't figure out where the overflow: initals were coming from and messing up my scrolling until I saw this.
