### ISSUE TITLE
typo on readme image

### ISSUE THREAD

**Issue by trphunt** [gilbarbara/react-joyride#506]
Readme.md shows an image which says `Let's beign our journey!` whereas it should read `Let's begin our journey!`

![reactJoyride](https://user-images.githubusercontent.com/30430132/55816029-64ecba80-5abf-11e9-92b2-31454fd601d0.PNG)

**Comment by scottcinatl** [comment]
I have a fix for this on my local branch that is ready for a PR. But I am running into some access rights into trying to push the commit. @gilbarbara, if possible, could you guide me in getting access rights to push to this repo?

**Comment by gilbarbara** [comment]
You can't have access rights. You'll need to fork, edit the files and open a PR.
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by scottcinatl** [comment]
Opened a PR for this issue with #507

**Comment by gilbarbara** [comment]
Fixed
