### ISSUE TITLE
Wrong placement of tooltip

### ISSUE THREAD

**Issue by torchsmith** [gilbarbara/react-joyride#510]
## 🐛 Bug Report

The bug is that the tooltip is placed incorrectly.
![Screen Shot 2019-04-10 at 7 33 30 PM](https://user-images.githubusercontent.com/14154207/55917990-dc0d7600-5bc7-11e9-812c-b2660adf38f7.png)

react-joyride__overlay is also being assigned a height value much higher than the `<body>`

## To Reproduce

```js
// Step inside of a step array given as prop to joyride
{
          target: '#react-tabs-0',
          content: 'This is the home page.',
          placement: 'bottom',
          spotlightClicks: true,
          disableBeacon: true,
          hideCloseButton: true
}

// ReactJoyride component
<ReactJoyride
                steps={this.state.steps}
                run={this.state.run}
                stepIndex={this.state.stepIndex}
                callback={this.handleJoyrideCallback}
                continuous
                disableOverlayClose={true}
                showProgress
                spotlightPadding={10}
                disableCloseOnEsc={true}
                showSkipButton
                locale={{back: 'Back', close: 'Close', last: 'Last', next: 'Next', skip: 'Skip Tutorial'}}
                styles={{
                  options: {
                    arrowColor: '#fff',
                    backgroundColor: '#fff',
                    overlayColor: 'rgba(21,72,159,0.4)',
                    primaryColor: '#00adee',
                    textColor: '#000',
                  }
                }}
              />
```

## Expected behavior

The tooltip should be pointing up at the highlighted area, and should be positioned below the highlighted area.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 16.96 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.1.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
```

Any help would be much appreciated. I spent some time trying to figure this out on my own, but I honestly can't figure it out.

**Comment by Funisaac** [comment]
![Screen Shot 2019-04-10 at 7 42 14 PM](https://user-images.githubusercontent.com/14154207/55918241-c6e51700-5bc8-11e9-97a2-88be4675b77a.png)
This image may help.

**Comment by gilbarbara** [comment]
Post a codesandbox example.

**Comment by Funisaac** [comment]
It would take more time than I have to make a codesandbox replicating this, however I did take a look at the CSS and it is all good CSS.

On a side note that I didn't mention though:
This **was** actually working about 2 weeks ago and there have not been any changes to the layout or CSS of the affected area.

Any thoughts? - I'll try to get a sandbox made up soon.

**Comment by gilbarbara** [comment]
Oh, so it was working and stopped without changing the version?
How can it be a bug with this library?

**Comment by hugobarragon** [comment]
i am having the same problem, i will create a codesandbox link

**Comment by hugobarragon** [comment]
@torchsmith  @gilbarbara 
here is the code box example, tooltip stays to left.
the modal has an opening animation, so i do a timout before setting joyride run
only importing the orignal css
any idea?

[![Edit react-joyrideWithAntdDesign](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-joyridewithantddesign-vhx0o?fontsize=14&hidenavigation=1&theme=dark)

**Comment by torchsmith** [comment]
@hugobarragon that is exactly what was happening to me!

**Comment by hugobarragon** [comment]
I find out that on window resize it fix's, temporary i am doing a setInterval each 250ms to trigger a fake window resize
https://www.loom.com/share/1b01a825d11d4a6aa5a30a31559a94c2

**Comment by gilbarbara** [comment]
@hugobarragon Removing the floaterProps make it work as expected. Is that it?

**Comment by hugobarragon** [comment]
@gilbarbara i dont know, if i resize it fix's, if i remove the disableBeacon it solves to...

**Comment by nixton9** [comment]
@hugobarragon did you find any better way to do it without using setInterval?

**Comment by hugobarragon** [comment]
Nop, that way still does not work  
https://codesandbox.io/s/joyride-bug-on-github-cant-get-a-good-placement-8ur9j?file=/index.js

**Comment by shubhsk88** [comment]
I am facing the same issue, I want to hide the arrow from the tooltip, so I change the floatProps, but then the tooltip's position is weird. if I remove the floatProps it's works fine

**Comment by gilbarbara** [comment]
@shubhsk88 
Please open a new issue with a codesandbox minimal reproducible example.
