### ISSUE TITLE
How can I use getHelpers prop

### ISSUE THREAD

**Issue by sarbjeetsingh** [gilbarbara/react-joyride#512]
Could you please explain getHelpers prop. I want to take user to different route if user skips or closes the joyride.

**Comment by gilbarbara** [comment]
Use the callback instead.

**Comment by sarbjeetsingh** [comment]
@gilbarbara Thanks it worked

**Comment by luisFernandezDevSpark** [comment]
Would still like to see an example of how getHelpers work please!

**Comment by polarstoat** [comment]
If using the callback is always preferred, perhaps `getHelpers` should be deprecated?

Otherwise it seems useful to add further documentation on the usage of `getHelpers`.

**Comment by gilbarbara** [comment]
@polarstoat Feel free to submit a PR

**Comment by Morriz** [comment]
If no example, how else can we trigger a reset from outside of the component?

**Comment by bluepenit** [comment]
In v 2.7.2, overlay click action is same as the close button click.
I'd like to pass to the next step when clicking on overlay.
How can I handle this?

**Comment by andresmarty** [comment]
Having same issue as bluepenit...I have the following scenario:
- When user clicks on overlay tour should end.
- When clicking on last button user should be routed to other page and tour end.

For now I can only make the routing but also when clicking on overlay .

**Comment by bluepenit** [comment]
I have resolved the issue that I met with native javascript addEventListener.
Here is my step:
1. `disableOverlayClose={true}`
2. in callback function, 
```
const joyrideEl = document.querySelector(".react-joyride__overlay");

if (joyrideEl) {
            if (index <= joyrideSteps.length - 1) {
                joyrideEl.addEventListener("click", () => setStepIndex(index + 1));
            } else {
                setStepIndex(0);
                emitDashboardJoyrideEvent({ runDashboardJoyride: false });
            }
        }
```

In the above code, emitDashboardJoyrideEvent function is for run property of Joyride component.

**Comment by davidshumway** [comment]
@Morriz 

https://github.com/gilbarbara/react-joyride/blob/20e3b893ea56f70f08d5e7d6555fc98b5f0dc0ad/test/__fixtures__/Standard.tsx#L54

```python
      <Joyride
        callback={handleJoyrideCallback}
        continuous
        getHelpers={helpers => {
          // do something with helpers
          // e.g., helpers.next() moves ahead one. 
        }}
        run={run}
        scrollToFirstStep
        showSkipButton
        steps={steps}
        {...rest}
      />
```
