### ISSUE TITLE
Restart tour with callback enabled

### ISSUE THREAD

**Issue by nuthinking** [gilbarbara/react-joyride#513]
I'd like to give my users the ability to restart the tour regardless if the tour is currently visible or not.

Because the `stepIndex` is driven by the `callback`, the problem I found is that if I change the `stepIndex` from the outside the `callback` will kind of restore it.
I found on another issue the `joyride.reset()` method but doesn't look like it still exists.

Is there a way to either say the component to reset or to better read the callback so that I can ignore it in the case of a restart? Thanks!

**Comment by gilbarbara** [comment]
Hey,

I'm not sure that I understand your problem.
The `stepIndex` is a variable that you can change anywhere, it doesn't need to be updated only inside the callback.
It can be a component's state key or a plain variable from context/redux.

**Comment by nuthinking** [comment]
I obviously have a conflict between callback and redux. Is there a way to keep redux up-to-date without the callback?

**Comment by gilbarbara** [comment]
No, the only way to communicate with Joyride is with the callback.
I've never implemented it with Redux so I'm not sure what's the proper way to sync them but shouldn't be any different as to sync it with an internal state.
If the tour is running the source of truth is the callback state. If it's not running the callback wouldn't be triggered.

**Comment by nuthinking** [comment]
I will check again the **controlled** example, I might have missed something. Thanks!

**Comment by nuthinking** [comment]
Sorry, I had a look. But if _"the only way to communicate with Joyride is with the callback"_, how do I restart a tour from a UI event outside JoyRide? Is this possible?
