### ISSUE TITLE
Stateless function components cannot be given refs

### ISSUE THREAD

**Issue by nuthinking** [gilbarbara/react-joyride#514]
## 🐛 Bug Report

I recently updated my Joyride library and I started getting the "Warning" in the title. Precisely:

```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `JoyrideBeacon`.
```

## To Reproduce

My custom beacon component is:

```
const Wrapper = styled.button`
  ...
`;

export default class JoyrideBeacon extends React.Component {
  render() {
    return (
      <Wrapper
        key="JoyrideBeacon"
        className="joyride-beacon"
        type="button"
        {...this.props}
      >
        <span className="inner" />
        <span className="outer" />
      </Wrapper>
    );
  }
}
```

And I pass it in this way:

```
<Joyride
            beaconComponent={(props: any) => <BeaconView {...props} />}
```

I use React 16.2.0

Any idea how to fix/suppress this? Thanks!

**Comment by gilbarbara** [comment]
Your BeaconView component needs to support refs...
I can't say from your example what kind of React component it is.

Please refer to React's [docs](https://reactjs.org/docs/refs-and-the-dom.html).

**Comment by nuthinking** [comment]
`JoyrideBeacon extends React.Component`

why wouldn't it "support refs"? Do I need React 16.3?

**Comment by gilbarbara** [comment]
`JoyrideBeacon` is a class component as `(props: any) => <BeaconView {...props} />` is a functional one.
Set your `BeaconView` directly:

```jsx
<Joyride beaconComponent={BeaconView} ... />
```

**Comment by nuthinking** [comment]
I am using TypeScript and the problem is that `"@types/react-joyride": "^2.0.2"` reports the following signature:
`export interface Props {
  beaconComponent?: (renderProps: BeaconRenderProps) => React.ReactNode;`

I suppressed the tslint error, and things work fine, doing:
`<Joyride
            beaconComponent={BeaconView as any}`

anyway, I also get the console warning **"beacon is not a valid DOM element"**. Any idea what this might be? Thanks a lot!

**Comment by gilbarbara** [comment]
It's impossible to know what's happening without running the code.
Please post an example in codesandbox

**Comment by gilbarbara** [comment]
I've updated the custom components props type to be `React.ElementType<T>` where T is their respective props: `BeaconRenderProps` or `TooltipRenderProps`.

People using styled-components should cast `as React.ElementType<XXXRenderProps>`
