### ISSUE TITLE
Typescript error on placement field

### ISSUE THREAD

**Issue by sjgmojica** [gilbarbara/react-joyride#516]
Hi,

Upon checking your source code, I see that you declared placement value but it shows me some ts error even I put the correct value of `placement`.

Thanks

**Comment by gilbarbara** [comment]
Where are you using `placement`? On the step or the component itself?

**Comment by sjgmojica** [comment]
On the step.

**Comment by gilbarbara** [comment]
Yeah, I missed that.
I was reading about it literal inference [here](https://basarat.gitbooks.io/typescript/docs/types/literal-types.html).

One option would be to set it like this:

```tsx
{
 placement: 'bottom' as 'bottom',
}
```

But it is clumsy.
I will read more about it tomorrow and if you have a solution for this, let me know.

**Comment by sjgmojica** [comment]
Ok I see..thanks

**Comment by gilbarbara** [comment]
[Typescript 3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html) introduced **const assertions** that can be used in these situations.

```ts
{
 placement: 'bottom' as const,
}
```
