### ISSUE TITLE
Render tour upon clicking button

### ISSUE THREAD

**Issue by sjgmojica** [gilbarbara/react-joyride#518]
Hi ,

Need help.. I have separate component. I called it product card component where in there is a add button. When I click the add button It will change into quantity box. My app break down when I click the add button. What I want to do is when i click next of the tour then point to add button it shows the tooltip (which is now work) , then click add button shows the quantity box with tooltip. Kindly see attached file. Thanks
<img width="301" alt="Screen Shot 2019-05-24 at 10 49 11 AM" src="https://user-images.githubusercontent.com/14226982/58410636-1f9f3f00-80a5-11e9-9aa2-7bd3d580eba7.png">

**Comment by gilbarbara** [comment]
You'll probably need to use a controlled tour. Check the demo for more information
