### ISSUE TITLE
beacon error if selector has disappeared

### ISSUE THREAD

**Issue by shackbarth** [gilbarbara/react-joyride#52]
Here's what happens: I create a beacon based on some event, but the user ignores my beacon and moves to a different route, in which the selector that the beacon was tied to no longer exists.

Ideally, the beacon would disappear when the user has left the screen in which the beacon is relevant.

But a second problem (easier to fix) is that if the user then clicks the beacon it throws an error.
`Cannot read property 'getBoundingClientRect' of null`
https://github.com/gilbarbara/react-joyride/blob/524125c223bb7bb82315c1970d174795ae82d753/lib/scripts/Component.js#L522

I'd be happy to submit a simple PR to guard against this failure. I don't have any ideas, offhand, how to make the beacon disappear altogether when the user has moved to a different route, which I'd consider to be the more complete solution.

**Comment by gilbarbara** [comment]
hello,

You could replace the steps or reset the tour when a relevant component in unmounted..

I'm refactoring this component and I'll add some extra error handles to it.

**Comment by shackbarth** [comment]
That's a decent workaround to the problem I'm up against, although it'd be ideal if my components didn't necessarily have to be themselves aware of the joyride beacons being attached to them. Thanks for the quick response.

**Comment by gilbarbara** [comment]
Yeah, I'd love to have a cleaner option for these situations but I can't think in a way to watch for changes in the DOM without being too intrusive. If you can think of a better way let me know.

[s]
