### ISSUE TITLE
Not able to reset tour if already taken and want to retake tour

### ISSUE THREAD

**Issue by nikita2423** [gilbarbara/react-joyride#520]
I have a application in which when a new user signed up, it starts the tour to explain the application. It works perfectly fine.
I have also a help button having a functionality to retake the tour
On the first time page loaded, retaking the  tour perfectly fine and if user pressed skip button and want to retake the tour again without loading the page, then it is not working.

Followed the links below:
https://github.com/gilbarbara/react-joyride/issues/371
https://github.com/gilbarbara/react-joyride/issues/354

Didn't find the proper solution to it

**Comment by kotofeyweb** [comment]
Can you share your solution with me please?

**Comment by evenfrost** [comment]
@gilbarbara so, what's the proper way to reset the tour once it is closed?

**Comment by gilbarbara** [comment]
Hey @evenfrost 

Have you checked the [documentation](https://docs.react-joyride.com/props) for the `getHelpers` prop?
It's also in the [demo](https://github.com/gilbarbara/react-joyride-demo/blob/9f0591eba9a4e7f70c9daf91c0d91665f82e2003/src/CustomComponents/index.tsx#L237).
