### ISSUE TITLE
A little bit space on overlay

### ISSUE THREAD

**Issue by sjgmojica** [gilbarbara/react-joyride#521]
Hi,

I want to spotlight exactly on the target but I noticed has a little bit space. kindly see the attached file.

Thanks
<img width="379" alt="Screen Shot 2019-06-04 at 10 12 21 AM" src="https://user-images.githubusercontent.com/14226982/58846295-46ff9880-86b1-11e9-946b-ceb6a372da75.png">

**Comment by gilbarbara** [comment]
Check out styling instructions [here](https://docs.react-joyride.com/styling)

**Comment by gilbarbara** [comment]
Sorry, this padding is on the spotlight and it is calculated in the code and it can't be changed thru styling.
I'll try to add this with styles soon.

**Comment by sjgmojica** [comment]
Ok i will try this.Thanks

**Comment by gilbarbara** [comment]
You can set the `spotlightPadding` to 0 in an individual step or as a prop for all steps.

**Comment by sjgmojica** [comment]
Thanks for the updates :)
