### ISSUE TITLE
disableOverlayClose not working

### ISSUE THREAD

**Issue by owenpearson** [gilbarbara/react-joyride#522]
### Description

I am trying to create a controlled joyride, closely following the example [here](https://docs.react-joyride.com/callback)

## To Reproduce

In the App component (of create-react-app) add the following component state:

    state = {

    run: true,

    steps: [
      {
        target: '#thefirstjoyride',
        content: 'This is something...',
        disableBeacon: true,
        disableOverlayClose: true,
      },
      {
        target: '#viewport',
        content: 'Now drag it over here somewhere...',
        disableBeacon: true,
        disableOverlayClose: true,
      }
    ],
    stepIndex: 0
    }

And add the Joyride component with the following props

        <Joyride
          steps={steps}
          run={run}
          stepIndex={stepIndex}
          callback={this.handleJoyrideCallback}
          spotlightClicks={true}
          disableOverlayClose={true}
        />

Note that I have used the `disableOverlayClose` prop for the Joyride component, and i have tried the override property on each step. The issue still persists if I only use one of these methods.

## Expected behavior

The 'Close' button doesn't appear on my overlays.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 1.40 GB / 7.80 GB
  Binaries:
    Node: 10.15.2 - C:\Program Files\nodejs\node.EXE
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by gilbarbara** [comment]
Hey,

There's no close button on the overlay, just on the tooltip and the `disableOverlayClose` prop has a different functionality: **Don't close the tooltip when clicking the overlay.**

If you want to customize the UI, please follow the instructions [here](https://docs.react-joyride.com/styling).
You have two options: pass a styles prop with your changes or use a custom component.

```jsx
<Joyride
  styles={{
	buttonClose: {
      display: 'none',
    },
  }}
  ...
/>
```
