### ISSUE TITLE
Spotlight does not synchronise with components having position: sticky

### ISSUE THREAD

**Issue by dropbeardan** [gilbarbara/react-joyride#529]
## 🐛 Bug Report

When a Step targets a Sticky component and the user scrolls the page, the spotlight desynchronises with the target (see the repl below)

## To Reproduce

Create a sticky component, target that sticky component using a Tour step.

## Expected behavior

The spotlight should follow the sticky target.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/react-joyride-demo-h8os9

## Likely targets:
https://github.com/gilbarbara/react-joyride/blob/master/src/components/Overlay.js#L166
https://github.com/gilbarbara/react-joyride/blob/master/src/modules/dom.js#L188

**Comment by dropbeardan** [comment]
@gilbarbara There's been a few issues with Spotlight desync, just for my own benefit was there any particular reason you chose the path of maintaining an internal spotlight position on-scoll rather than recalculate position based on target's new position?

**Comment by gilbarbara** [comment]
Hey,

To be simple and avoid expensive calculations.
