### ISSUE TITLE
Language change for next, skip and close button would be great to have.

### ISSUE THREAD

**Issue by NikhilAshodariya** [gilbarbara/react-joyride#530]
## 🚀 Feature Idea

A clear and concise description of what the feature is.
For buttons like next, skip and close button when I change language it does not changes automatically based on browser preference.

## Motivation
Got the idea from project working on .

**Comment by gilbarbara** [comment]
What do you mean by change language, the browser language?
You can customize and change these strings with the `locale` prop.
