### ISSUE TITLE
Joyride with react-select

### ISSUE THREAD

**Issue by Vivek-Nehra** [gilbarbara/react-joyride#531]
When I use joyride on react-select, only the selection part is highlighted and not the dropDown menu .. Can you suggest some way to change the target to dynamically point to dropdown menu as well (as the target is still the same but has expanded further)... Any help is appreciated

**Comment by gilbarbara** [comment]
Hey,

this library wasn't designed with the ability to update the target dynamically.
I can't think in a way to perform what you want.

**Comment by gauravsoti1** [comment]
Facing the same problem. Anyone found a solution?

**Comment by FilipFES** [comment]
Hello everyone, while working on Wizard Walk/ Tutorial on my work I found one solution for the react-select using joyride.

1. FIrst of all,  you need to have a **state for the select opening** that will change _depending on the what step you are on or if you clicking on the react select input._ (I'm saving it in context, so I can access it where my Select component is and where my Joyride component is.
2. **Prefixing** your React-select with **classnamePrefix** will allow you to easily reference the dropdown menu in your joyride component (in my case: wizard-step-2__menu-list is how i'm getting the dropdown menu element and wizard-step-1 for the select input)
3.  Define **menuIsOpen** prop to be toggle the dropdown menu opening. There are two ways to trigger this one: 
- By clicking on the react input (onFocus and onInputChange) and when your joyride step becomes active.
4. In your **Joyride callback** have a logic for toggling the state when going back and fort between states. In my case, logic is this: Open the menu when going next from step 0 and close when going next from step 1. Also open it again if i'm coming back from step 1 to step 0.
5. Last problem I had was reopening the dropdown menu when its already focused, so I inserted "fake" and "invisible" input that i'm focusing on when the action on input change method is 'menu-closed'.

Hope I didn't overcomplicate this one :D. Let me know if you have any questions.

### My Joyride Component:

  const steps = [
    {
      target: '.wizard-step-1',
      title: 'Role selection',
      content: ' The currently selected role is displayed here.',
      disableBeacon: true,
      spotlightClicks: true,
      showButtons: true,
    },
    {
      target: '.wizard-step-2__menu-list',
      title: 'Roles',
      content: 'Select a role from the dropdown list to continue',
      showButtons: true,
      disableBeacon: true,
      spotlightClicks: true,
      placement: 'right'
    },
  ]

  const handleCallback = (event) => {
    const { status, action, index, type } = event;

    if (status === STATUS.FINISHED || status === STATUS.SKIPPED) {
      setActiveWizardWalk(false);
      setWizardStep(0);
    } else if (([EVENTS.STEP_AFTER, EVENTS.TARGET_NOT_FOUND]).includes(type)) {
      if (action === ACTIONS.NEXT && index === 0) {
        setIsGlobalSelectionOpen(true);
      }
      if (action === ACTIONS.NEXT && index === 1) {
        setIsGlobalSelectionOpen(false);
      }
      if (action === ACTIONS.PREV && index === 1) {
        setIsGlobalSelectionOpen(false);
      }

      const nextStepIndex = index + (action === ACTIONS.PREV ? -1 : 1);
      console.log("Next step is", nextStepIndex);

      setTimeout(() => {
        setWizardStep(nextStepIndex);
      }, 200)
    }
  }

  return <Joyride
    steps={steps}
    stepIndex={wizardStep}
    continuous
    showProgress
    showSkipButton
    disableOverlayClose
    disableScrolling
    run={!isLoading && activeWizardWalk}
    callback={handleCallback}
    tooltipComponent={(props) => <Tooltip
      {...props}
      showSkipWizardWalk
      steps={steps}
    />
    }
  />;
}

### My React Select Component: (including "fake" input to focus on)

`     <Select
          value={selectedValue}
          placeholder={'Select role'}
          options={options}
          classNamePrefix='wizard-step-2'
          className='basic-single wizard-step-1'
          onChange={(value, action) => handleJobFilterChange(value, action)}
          isClearable={true}
          styles={customStyles2}
          onInputChange={(options, { action }) => {
            if (action === 'menu-close') {
              setIsGlobalSelectionOpen(false);
              focusRef.current.focus();
            }
          }}
          onFocus={() => setIsGlobalSelectionOpen(true)}
          menuIsOpen={isGlobalSelectionOpen}
        />
        <input ref={focusRef} style={{ position: 'absolute', left: '-9999px' }} />
`
   
### My context where i'm saving the states:
   import { createContext, useContext, useState } from "react"

const WizardWalkContext = createContext();

const WizardWalkUpdateContext = createContext();

export const useWizardWalk = () => {
  return useContext(WizardWalkContext)
}

export const useUpdateWizardWalk = () => {
  return useContext(WizardWalkUpdateContext)
}

export default function WizardWalkProvider({ children }) {
  const [activeWizardWalk, setActiveWizardWalk] = useState(false);
  const [wizardStep, setWizardStep] = useState(0);
  const [isGlobalSelectionOpen, setIsGlobalSelectionOpen] = useState(false);

  return (
    <WizardWalkContext.Provider value={{
      activeWizardWalk,
      wizardStep,
      isGlobalSelectionOpen
    }}>
      <WizardWalkUpdateContext.Provider value={{
        setActiveWizardWalk,
        setWizardStep,
        setIsGlobalSelectionOpen
      }}>
        {children}
      </WizardWalkUpdateContext.Provider>
    </WizardWalkContext.Provider>
  )
}
