### ISSUE TITLE
"open" locale missing from types

### ISSUE THREAD

**Issue by nodeworks** [gilbarbara/react-joyride#533]
## 🐛 Bug Report

The "open" locale is missing from types in index.d.ts

## To Reproduce

Using typescript in your project, add a locale prop to the Joyride component:

`locale={{
  open: 'Start the tour'
}}`

This will produce an error:

```
TS2322: Type '{ open: string; }' is not assignable to type 'Locale'.
  Object literal may only specify known properties, and 'open' does not exist in type 'Locale'.
```

## Expected behavior

Expected not to receive this error

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
System:
    OS: Linux 4.9 Debian GNU/Linux 8 (jessie) 8 (jessie)
    CPU: (5) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 2.85 GB / 11.71 GB
    Container: Yes
    Shell: 4.3.30 - /bin/bash
Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
npmPackages:
    react-floater: ^0.6.5 => 0.6.5
```

**Comment by gilbarbara** [comment]
Fixed in 2.1.1
