### ISSUE TITLE
Customize transition in tour progress

### ISSUE THREAD

**Issue by nomisrevol** [gilbarbara/react-joyride#535]
## 🚀 Feature Idea
With current react-joyride animation for custom component with tooltip, I see it doesn't friendly with user enough, so I think we need to provide users the way to customize it.

## Motivation

To make the transition more friendly with users and smoother (example: fade in/fade out)

**Comment by gilbarbara** [comment]
That's not something I'm considering to work on.
Feel free to submit a PR

**Comment by nomisrevol** [comment]
I think to customize transition is necessary thing that user should be provided someway to control it. I'm not sure I will make a pull request for it, but I will try.

**Comment by gabrielbuzziv** [comment]
At the example page the tour is using a fade between steps, but my tooltips steps kind of jump on screen, how can we change it?

**Comment by gilbarbara** [comment]
Hey @gabrielbuzziv 

Which example? Anyway, there is no fade between steps.
If you are using React's StrictMode, it will mount every component twice, causing the overlay to flick.
This only happens in development mode.

**Comment by johnmema** [comment]
I've been having the flickering while in dev mode too. Is there any way I can see if it doesn't flicker in other modes without going to production?

**Comment by gilbarbara** [comment]
Hey @johnmema 
Did you try removing the StrictMode in development to check if the flickering still happens?
There are several ways to preview your built app, depending if it is client-side or server-side.
