### ISSUE TITLE
How do i access dynamic css properties with React Joyride

### ISSUE THREAD

**Issue by vinikatyal** [gilbarbara/react-joyride#539]
My Css classes are dynamically generated

```
import * as styles from './WalletBarcodeSnapshot.css';

const cx = ClassNames.bind(styles);

<div className={cx('snapshotWrapper')}>
```

My question is how do i use this in the react joyride?

**Comment by gilbarbara** [comment]
You can use [custom components](https://docs.react-joyride.com/custom-components).
There is an example in the [demo](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo) source.

**Comment by vinikatyal** [comment]
@gilbarbara Hi could you point me to the file where you are using it?

**Comment by gilbarbara** [comment]
@vinikatyal The `Custom Component` directory in the demo uses styled-components. But the idea is the same for dynamic CSS classes, you can use anything you like with this approach.

It's up to you.
