### ISSUE TITLE
Can we have two steps targeted at one element - Joyride

### ISSUE THREAD

**Issue by vinikatyal** [gilbarbara/react-joyride#541]
![bar](https://user-images.githubusercontent.com/5568656/63243544-81241380-c278-11e9-8182-b1e8aaf67132.jpg)

Can something like this be implemented in React Joyride with two steps on one target?

**Comment by gilbarbara** [comment]
Hello,

I didn't understand what you want to do with this image.
But yes, you can have two different steps with the same target

**Comment by vinikatyal** [comment]
I mean customize such that we can show two steps above and below the target?

**Comment by gilbarbara** [comment]
You can't do that with this library. Joyride means a tour, sequential steps...
You could display an additional tooltip with [react-floater](https://github.com/gilbarbara/react-floater), the library used to position and render the steps, but that's not good UI.
