### ISSUE TITLE
Warning on click of "Next":: Target not mounted 

### ISSUE THREAD

**Issue by archana-iron** [gilbarbara/react-joyride#543]
I am getting a warning on click of next.

**Warning::**

> Target not mounted {title: "Dynamic To do List", text: "Fully functional widget with working add, delete, refresh and cancel buttons.", textAlign: "left", selector: ".tour-step-2", position: "left", …}

Please provide a solution for this.

**Comment by gilbarbara** [comment]
Your target isn't rendered, so the library skipped it. You must render it before advancing or implement some sort of delayed render. Check the examples in the codesandbox [demo](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo), or search the issues.

**Comment by rfgonzalezweb** [comment]
> Your target isn't rendered, so the library skipped it. You must render it before advancing or implement some sort of delayed render. Check the examples in the codesandbox [demo](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo), or search the issues.

could that be the same reason I'm getting this on Sentry? 
``` 
TypeError <object>.value(react-joyride/src/components/index) Level: Error
Cannot read properties of null (reading 'removeEventListener')
```

**Comment by gilbarbara** [comment]
Hey @rfgonzalezweb 
If you search the code for the library, you'll see that I only use `removeEventListener` on the `window` and `document.body`, so it is not likely to be related to the "Target not mounted" warning.
