### ISSUE TITLE
Problems with mix-blend-mode

### ISSUE THREAD

**Issue by DragonRaider5** [gilbarbara/react-joyride#544]
## 🐛 Bug Report

Using the layover in Chrome over an uneven surface can cause weird looks. This can be a problem for example when you try to display an action button over some cards. The cards need to be visually separated from the background, while the action button needs to be distinct from both.

## To Reproduce

Create some kind of rectangles with a different shade of grey than the background. Now add an element floating above an edge and create a walkthrough step targeting this element.

## Expected behaviour

It creates a clear, highlighted area over the target element.

### With uneven background (card `#ECECE9`, background white)
<img width="93" alt="Uneven Background" src="https://user-images.githubusercontent.com/6208890/64282891-a7bf9b00-cf56-11e9-9133-28bbaf4e3b6c.png">

### Even background (card and background `#ECECE9`)
<img width="97" alt="Even Background" src="https://user-images.githubusercontent.com/6208890/64282933-bd34c500-cf56-11e9-8a3f-bb39f0b0843b.png">

### Workaround
<img width="104" alt="Workaround" src="https://user-images.githubusercontent.com/6208890/64282841-8e1e5380-cf56-11e9-89d9-847e881146a1.png">

I achieved this by using `box-sizing: content-box` and applying  `border-width` matching the positioning of the highlighted area on the overlay (+ making the highlight area straight up transparent).

Would you like me to create a PR with this workaround as an added option? It wouldn't change the structure at all, just some CSS.
Might also fix #411

**Comment by gilbarbara** [comment]
Hey,
I need a codesandbox example to make sure isn't a problem with your setup.
Demo images won't cut it

**Comment by gilbarbara** [comment]
From the images, it appears the problem is with the spotlight positioning and not the mix-blend-mode

**Comment by DragonRaider5** [comment]
Hey,

thanks for your response. In the images you can see it's not about the positioning, as for the first image the rounded corners on the right hand side are missing.

However it is indeed about my setup... I actually just duplicated #411 because I didn't set an explicit color on the background. My bad 😄
