### ISSUE TITLE
Broader Styling options

### ISSUE THREAD

**Issue by borisrorsvort** [gilbarbara/react-joyride#545]
## 🚀 Feature Idea

Allow styles option object to customise every part.
 
## Motivation

It’s a pity that for now you can only change a few styling options. For instance I’d very much like to change the tooltip text alignment.

## Example

use subways to design the part to be changed then merge the two styles, letting yours overwrite the default.

**Comment by gilbarbara** [comment]
Hey,
You can render your own custom tooltip, isn't that enough?

**Comment by borisrorsvort** [comment]
Just to change the text alignement, that would be overkill and less maintainable. It’s just that you already allow some styles to be changed, so why not all? Text alignement seems as valid as text color imho.

Thanks a bunch for the already awesome component btw 👏

**Comment by gilbarbara** [comment]
You can change the alignment using the `styles` prop.
Since this prop will be merged, it will accept additional keys.

```jsx
<Joyride
...
styles={{
  tooltipContainer: {
    textAlign: 'right'
  }
}}
/>
```

Check [styles.js](https://github.com/gilbarbara/react-joyride/tree/master/src/styles.js) for more information.
