### ISSUE TITLE
Restart or continue tour after elements was loaded or changed via ajax

### ISSUE THREAD

**Issue by flushorg** [gilbarbara/react-joyride#546]
Hi, i try to integrate your nice code into my browser extension.
It nearly works fine, but my browser extension (react js) renders some elements into the page (dom tree change), after the user has started this code via click on a button (this takes some seconds). But in the meanwhile my tour ends.
Is there a possibility to wait for my elements or to restart the tour on another stepIndex or something similar?

Thanks a lot and best regards
Matt

**Comment by gilbarbara** [comment]
Yes, you can start Joyride only when your elements are rendered on the screen.
Set the `run` prop to false and change it when it's ready.

https://docs.react-joyride.com/props
