### ISSUE TITLE
react-floater overlay problem if container have overflow : auto

### ISSUE THREAD

**Issue by gabrielsdimeli** [gilbarbara/react-joyride#547]
## 🐛 Bug Report

I have my overlay component inside of a table with overflow auto for responsive but if overflow is activated then the overlay lose reference of the position of the target.

## To Reproduce

Just create a div container with overflow : auto, then inside create an overlay component with or without children, specify some target and try.

## Expected behavior

Don't lose reference of the position of the target setted.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/clever-river-32mtq

**Comment by gilbarbara** [comment]
This issue should be opened in [react-floater](https://github.com/gilbarbara/react-floater) repo.
