### ISSUE TITLE
Incorrect location of popup

### ISSUE THREAD

**Issue by IPWright83** [gilbarbara/react-joyride#549]
## 🐛 Bug Report

The location of one of the messages is incorrect. Strangely this message appeared correctly on a previous step.

## To Reproduce

Using the sample github rep:
`npm install`
`npm start`

1. Click the beacon to open the wizard
2. Notice the location of `Message 3`
3. Continue to `Message 10` - this should have appeared in the same place as `Message 3`.

## Expected behavior

The popup within `Message 10` in appears at the same location as the one with `Message 3` as it uses the same selector.

## Link to repl or repo (highly encouraged)

https://github.com/IPWright83/joyride-bug/blob/master/README.md

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 8.04 GB / 15.79 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by gilbarbara** [comment]
Hey,

You are updating the component state from step 8 and up and that's probably messing with the positioning.
My suggestion is to use the controlled mode and update the stepIndex after your data has changed the graph.
This library uses `popper.js` for positioning and there's nothing much I can do change its behavior.
Let me know if the stepIndex helps.

**Comment by IPWright83** [comment]
Thanks, I'll go have a read and see if I can try that.

**Comment by IPWright83** [comment]
@gilbarbara that seems to fix things - though I've found it a little tricky managing the `stepIndex` manually. Do you have some example rules anywhere on how to handle increment this value? I find I get frequent updates to the callback and the steps just run away with themselves!

Thanks :)

**Comment by gilbarbara** [comment]
Not really. The controlled example in the demo uses `stepIndex` but there's no correct way to do it... 
It's a escape hatch for when your app needs to wait for some asynchronous changes.

[s]
