### ISSUE TITLE
The primary button is not focused by default

### ISSUE THREAD

**Issue by p-himik** [gilbarbara/react-joyride#551]
## 🐛 Bug Report

The primary button is not focused.
I assume that it should be, given [this code](https://github.com/gilbarbara/react-joyride/blob/782fb7340f797d577dac59cac46f818a777808de/src/components/Step.js#L193-L194):
```typescript
this.scope = new Scope(this.tooltip, { selector: '[data-action=primary]' });
this.scope.setFocus();
```

## To Reproduce

You can easily check it at https://react-joyride.com/
Note that the very first step still has focus at its primary button. It seems to be because the target is the body - I have the same behavior in my own project.

## Expected behavior

The primary button should be focused by default at each step.

**Comment by danielimmke** [comment]
@gilbarbara Hello I have a PR in for this if you have a moment to review it
