### ISSUE TITLE
Unable to completely remove the pulsating icon if the user quits the tutorial midway

### ISSUE THREAD

**Issue by arnav13081994** [gilbarbara/react-joyride#555]
Hi,

I am unable to completely remove the pulsating icon that becomes visible once the user quits the tutorial. I understand the icon is maintaining a ref to what the user saw last etc. Is there any way to not affect the functionality and to re-trigger the tutorial without having to click on that icon.

**Note: Even in the demo if you quit the tutorial somewhere in the middle, hitting "Start" will not do anything.**

**Comment by gilbarbara** [comment]
What do you mean by "quit the tutorial"?
Closing a tooltip doesn't end the tour, only the `skip` button does it.
You can have a controlled tour where you are in charge of the complete flow, check the examples.

**Comment by arielcavalcante** [comment]
The pulsating button is referred in the docs as 'beacon', knowing this might help you do what you want.
