### ISSUE TITLE
Steps without targets

### ISSUE THREAD

**Issue by darinrogers** [gilbarbara/react-joyride#564]
## Modal-like steps that don't point to an element

A pattern that's been popping up in some places is to have steps that look more like a modal. These steps don't highlight a particular element, but normally give a general message. 

## Motivation

A product tour might be more helpful if there are slides that give general info, as opposed to highlighting a specific element. This general info can be an overview of what the tour will cover, or just displaying contact info. 

## Example

Take the case of a tour that highlights two elements: a settings menu icon and a user menu icon for logging out. We might instead have 4 steps. Step one would not point to or highlight a specific element. It'd look more like a modal and could have a welcome message and a list of which parts of the app the tour will highlight. Step two would highlight the settings menu icon, as joyride currently works. Step three would highlight the user menu icon, also as joyride currently works. Step four would be another modal-like step which lets the user know that if they have any questions that can contact a support email address.

**Comment by darinrogers** [comment]
It's just been brought to my attention that you can achieve this with a `target` of `body` and a `placement` of `center`. It looks like that's how the demo site handles it. If this is a valid way, should there be a note in the docs?

**Comment by gilbarbara** [comment]
It's already documented [here](https://docs.react-joyride.com/step).

But if you just need centered steps this library would be a huge overhead since it uses popper.js for positioning and it is a huge library...
