### ISSUE TITLE
Joyride props callback lacking differentiation

### ISSUE THREAD

**Issue by darthzeran** [gilbarbara/react-joyride#565]
My code in my Joyride callback says
```
callback={(e: CallbackProps) => {
				if (EVENTS.STEP_AFTER, EVENTS === e.type	) {
				    //Progress to the next Step
                                    console.log('Step Updates')
                               }
			}
```
But when I run it (with debugging mode on or off it doesnt matter)
I notice that the react-floater initializes, and then the react-joyride step initializes.
But my console log is logging 2 times per step update.
And all my step update consists of is incrementing the step by 1.

Is there a way to differentiate between floater and joyride props?

**Comment by gilbarbara** [comment]
Hey,

The callback in the Joyride component is only triggered by its state changes.
Can you provide a working example at codesandbox or similar?
