### ISSUE TITLE
Using react-joyride in a functional component

### ISSUE THREAD

**Issue by groundswel** [gilbarbara/react-joyride#566]
Hello,

I am trying to use joyride in a functional component . Here is a snippet from the component. However when I run it nothing happens and I dont see any error either

```
var steps = [
      {
        target: '.my-first-step',
        content: 'This is my awesome feature!',
      },
      {
        target: '.my-other-step',
        content: 'This another awesome feature!',
      },
    ]


                return (
                        <div id="container1">
                                <p>
                                {appname}
                                </p>
                                <Joyride steps={steps} />
                                <SubscriptionStatusBar appname={appname} />
                                PMValue
                        </div>
                        )

     
```

**Comment by gilbarbara** [comment]
hey,

Set the `debug` prop to `true`. It might show something.
The targets are rendered?

Please provide a https://codesandbox.io/ demo or similar.

**Comment by paulbutcher** [comment]
I'm experiencing the same problem. Sandbox: https://codesandbox.io/s/fragrant-star-b5tcc

**Comment by gilbarbara** [comment]
@paulbutcher 

You are rendering a Paragraph with ID but setting the target to a className.
Change the target to `#target1` instead and it will work.

PS: to get the spotlight to work you'll need to set the parent component to a color, preferably the body. That's how the mix-blend-mode works.

**Comment by paulbutcher** [comment]
D'oh! Thanks @gilbarbara (and blush).

**Comment by gilbarbara** [comment]
@paulbutcher It happens! 😀
