### ISSUE TITLE
Issue related to input focus in react joy ride

### ISSUE THREAD

**Issue by aqeeljaved88** [gilbarbara/react-joyride#567]
I have been facing issue using react joyRide. Explaining the problem in points below if some one can help please.

- I have an input in a dialog where user enter task name and create a task.
- When i run joyRide reach the point where spotlight is on the input field in dialog.
- All click events work on any thing which comes under the spotlight e.g. input label, input tooltip etc...
- But clicking on input does not get a focus and it seems like a disabled input where as input is not disabled and both focus and blur events are logged in console.
- Unfortunately A very strange behavior take place, When click outside browser and click back on input and focus works.

Can you guys please help me out with this.?

**Comment by gilbarbara** [comment]
Hey,

Please provide a https://codesandbox.io/ demo or similar.
Issues without a reproduction link are likely to stall.

**Comment by delewis13** [comment]
+1 on this issue

In my case, using Material-UI library with a TextField input inside a Dialog component. The problem does not occur with TextFields not in a Dialog component.

Additional notes:
- Overlay is false
- Using controlled mode
- What appears to trigger the problem is the re-rendering of the joyride tooltip. 
e.g. if I have a joyride tooltip open, then open my dialog I can interact with the text-field just fine. The element only becomes non-interactive when I trigger a joyride re-render [e.g. by incrementing the step programatically].

Will attempt to create a minimal demo over the weekend, though if you have any bright ideas @gilbarbara can give it a shot prior to that.

Thank you for this fantastic library :)

**Comment by delewis13** [comment]
Hi @gilbarbara please find demo:

https://codesandbox.io/s/react-joyride-bug-x4dv3

Cheers :)

**Comment by bychrisme** [comment]
https://github.com/gilbarbara/react-joyride/issues/567#issue-573967552

i had the same problem

**Comment by akashahmad** [comment]
@gilbarbara I am also having this issue.

**Comment by MateenCode** [comment]
@gilbarbara  I'm also facing this issue and there doesn't seem to be work around either.

**Comment by MateenCode** [comment]
> Hi @gilbarbara please find demo:
> 
> https://codesandbox.io/s/react-joyride-bug-x4dv3
> 
> Cheers :)

Hey @delewis13  in you demo is says if you put a setTimeout on the input field it would work but I don't see that happening

**Comment by delewis13** [comment]
> > Hi @gilbarbara please find demo:
> > https://codesandbox.io/s/react-joyride-bug-x4dv3
> > Cheers :)
> 
> Hey @delewis13 in you demo is says if you put a setTimeout on the input field it would work but I don't see that happening

Hmm strange. I can't reproduce there either - can't remember how I did it at the time.

Regardless, I made another codesandbox example that demonstrates how I'm currently working around it in my app:
https://codesandbox.io/s/react-joyride-bug-delay-input-render-4qudr?file=/src/App.js

It works by delaying the rendering of the `<Dialog />` component till after the joyride step has incremented.

**Comment by gilbarbara** [comment]
hey @delewis13 

I've tried to remove the tab scope from this library and it didn't have any effect with your example.
My next guess was to look at the `material-ui` docs and I've found this: https://material-ui.com/api/unstable-trap-focus/
Setting the `disableEnforceFocus` on the Dialog fixed the input problem with focus.

I'm not sure it is the best approach, however, it goes to show this isn't a problem with this library per se, but a more complex interaction between modals, portals, and dialogs that I can't really fix for all.

**Comment by gilbarbara** [comment]
@aqeeljaved88 I don't if you are using the same library for the dialog, but you can try that if you use material-ui, or re-open this issue with a codesandbox example.

**Comment by gilbarbara** [comment]
@bychrisme @akashahmad @MateenCode 

Without more information like which library are you using or a codesandbox example, I can't help you.
"I'm having the same problem" doesn't mean much.

If you are using material-ui, you might try the option I've mentioned above or you can open an issue for your specific case.

**Comment by hewseph** [comment]
I'm having the same problem 1 and a half years later. My target element on the step is a `<form>...</form>`. I enabled spotlightClicks. And I am using a normal generic input that I styled. I cannot focus the input on clicks.

**Comment by dexterarmy** [comment]
i am also having the same issue, the input TextField is not focussing

**Comment by vlad-shulzhenko** [comment]
> i am also having the same issue, the input TextField is not focussing

I have the same @gilbarbara

**Comment by gilbarbara** [comment]
To anyone re-using this closed issue: without a minimal reproducible sandbox, there's nothing I can do to help...

**Comment by vlad-shulzhenko** [comment]
> > Hi @gilbarbara please find demo:
> > https://codesandbox.io/s/react-joyride-bug-x4dv3
> > Cheers :)
> 
> Hey @delewis13 in you demo is says if you put a setTimeout on the input field it would work but I don't see that happening

This one is reproducable @gilbarbara. Have the same problem

**Comment by gilbarbara** [comment]
Hey @vlad-shulzhenko 

Setting the `disableEnforceFocus` on the Dialog fixes the problem, as I mentioned in this [comment](https://github.com/gilbarbara/react-joyride/issues/567#issuecomment-742809507)
