### ISSUE TITLE
Steps with isFixed are not scrolled into view if they went out of view due to steps next to it.

### ISSUE THREAD

**Issue by ngmgit** [gilbarbara/react-joyride#570]
## 🐛 Bug Report

When setting `isFixed` option to true for a step and if the target element for that step gets out of the view when progressing in tour to the steps next to it, scrolling the target element of fixed step into view doesnt work when getting back by pressing the back button.

## To Reproduce

* Add steps and set one of the step with `isFixed` set as true.
* At least one of the steps next to this fixed step should scroll the page leading to the above fixed step to go out of view.
* Get back to this out of view `isFixed` step by pressing back button the element is not scrolled into view.

## Expected behavior

I expect that the `isFixed` step should be scrolled into view if it gets out of view and if its already in view `isFixed` functionality should work as is.

## Link to repl or repo (highly encouraged)

Will add the link here once codesandbox starts working fine.

**Comment by gilbarbara** [comment]
Hey

That's not how it works.
Your step needs to be fixed (using CSS) and the flag `isFixed` on the step configuration is only used to tell the Joyride that your step should be treated as fixed. This library won't change the positioning for you.
