### ISSUE TITLE
Next page

### ISSUE THREAD

**Issue by Maxim1905** [gilbarbara/react-joyride#571]
How to use joyride when switching to another page? I want the tour to continue after the transition

**Comment by gilbarbara** [comment]
Hey,

You'll need a controlled tour. Check the Controlled example in the demo [source code](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo)

**Comment by Maxim1905** [comment]
Will the program wait for the transition to another page and continue execution, or do you need to write an address check to continue the tour?

**Comment by gilbarbara** [comment]
Nope, you control the flow of the tour.

You can use a MutationObserver or some state/location change you have in your app to tell the tour to continue when the transition is complete.
