### ISSUE TITLE
Parent with visibility: hidden causes all children to be unusable for guided tours

### ISSUE THREAD

**Issue by SibrenTalens** [gilbarbara/react-joyride#573]
## 🐛 Bug Report
Elements of which one of the parents has the visibility: hidden style set, will be excluded from the guided tour, even if a more direct parent has visibility: visible set.

## To Reproduce
Add a step in a guided tour with the target being an element whose parent has visibility: hidden, but the element itself has visibility: visible.

## Expected behavior
Since the element is visible on the page, I expect to be able to add a guided tour step to it.

## Link to repl or repo (highly encouraged)
https://codesandbox.io/s/adoring-lake-wtyc5

See step 3, it is skipped and a 'Target not visible' warning is logged to the console, even though the target is visible.

I think I have a fix in [my fork](https://github.com/gilbarbara/react-joyride/compare/master...SibrenTalens:master)

## Run `npx envinfo --system --binaries --npmPackages react-floater`
```bash
  System:
    OS: Linux 5.5 Fedora 30 (Workstation Edition) 30 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 3.81 GB / 31.36 GB
    Container: Yes
    Shell: 5.0.11 - /bin/bash
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.4 - ~/<projet directory>/node_modules/.bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.11.0/bin/npm
```

**Comment by gilbarbara** [comment]
Hey @SibrenTalens 

Isn't that an anti-pattern?

I feel like this shouldn't be handled by this library.
And the fix you've mentioned is a breaking change.
