### ISSUE TITLE
Custom style for spotlight, width or height not accepted.

### ISSUE THREAD

**Issue by jephjohnson** [gilbarbara/react-joyride#576]
Various styles are not accepted for spotlight when integrating into a step.

When implementing the following below. A style like 'width' or 'height' is not accepted, but margin is?

The only work around I found was to manipulate through JS depending on the indexed step.

```
{
	content: "my content",		
	placement: 'left',
	target: '.header-icon',
	title: 'my title',
	offset: 90,
	styles: {
	    spotlight: {
	      marginLeft: '-87px'
	      height: '300px', <----- height wont take
	      width: '200px' <----- width wont take
	    },
	 }
	}

```

Workaround:
```
...
const checkIndex = (index === size - 1);
const el = document.querySelector('.react-joyride__spotlight');

if(el && checkIndex) {
      el.style.width = '300px';
      el.style.height = '210px';
    }
...
```

**Comment by gilbarbara** [comment]
Hey

Yes, these attributes are calculated dynamically.

**Comment by jephjohnson** [comment]
> Hey
> 
> Yes, these attributes are calculated dynamically.

Having the option to to pass in a value to a prop would be be useful...

**Comment by gilbarbara** [comment]
@jephjohnson Feel free to submit a PR!

**Comment by ruthchemla** [comment]
https://github.com/gilbarbara/react-joyride/blob/0f0dfe0e57c1a5211a8f077603071181782f3fe9/src/components/Overlay.js#L117

could this consider a solution? 
adding this line at the end will override the dynamic calc attributes

```
return {
      height: Math.round(elementRect.height + spotlightPadding * 2),
      left: Math.round(elementRect.left - spotlightPadding),
      opacity: showSpotlight ? 1 : 0,
      pointerEvents: spotlightClicks ? 'none' : 'auto',
      position: isFixedTarget ? 'fixed' : 'absolute',
      top,
      transition: 'opacity 0.2s',
      width: Math.round(elementRect.width + spotlightPadding * 2),
     + ...(isLegacy() ? styles.spotlightLegacy : styles.spotlight),
    };
```
