### ISSUE TITLE
Target not mounted

### ISSUE THREAD

**Issue by R-D-P** [gilbarbara/react-joyride#577]
I am using react.Lazy to dynamically import components.
Due to this react joyride skips the step since the target has not been mounted yet.

When I import the components the usual way, it works fine.

Is there any timeout I could add so that react joyride waits for the component to render instead of just skipping it.

**Comment by gilbarbara** [comment]
hey,

You can use the controlled mode and change steps manually when you are ready.
Check the [demo](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo) and read about `stepIndex` in the [docs](https://docs.react-joyride.com/props)

You can use a mutation observer to handle that or do it manually.

[s]

**Comment by gilbarbara** [comment]
@nadeem-preplaced 

https://codesandbox.io/s/github/gilbarbara/react-joyride-demo/tree/main

Or https://github.com/gilbarbara/react-joyride#development

**Comment by PandaTryingCoding** [comment]
Hello there!

Even i got into a similar kind of problem where the target was not getting mounted as I was now using two queries to render the components on my page, the best solution I found out was to wait until the loading of both the queries was done and then run the Joyride
