### ISSUE TITLE
Warnings to upgrade. Seeing Warning: componentWillMount has been renamed

### ISSUE THREAD

**Issue by sueyee** [gilbarbara/react-joyride#580]
## 🐛 Bug Report
We are using react version 16.10.2.

We are seeing warnings:
Warning: componentWillMount has been renamed, , and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. 

Load web page and you can see these warnings in the developer tools, console.

Warnings are displayed for componentWillMount, componentWillReceiveProps, componentWillUpdate

Will you be upgrading the code to add the prefix, "UNSAFE_" ?

Will you be upgrading to handle react version 17 ?

**Comment by gilbarbara** [comment]
hey,

Which version of this library are you using?
2.0 and up do not use `componentWillMount`.
Please upgrade!
