### ISSUE TITLE
Tooltip surfacing

### ISSUE THREAD

**Issue by Maxim1905** [gilbarbara/react-joyride#581]
I have the appearance of a tooltip accompanied by a jitter and every time it appears from the upper left corner. Now I turned it off floaterProps = {{
         disableAnimation: true
       }} How can I change the appearance animation?

**Comment by gilbarbara** [comment]
hey,

There's no way to customize the animation.
Feel free to submit a PR to [react-floater](https://github.com/gilbarbara/react-floater) repo to add this customization

[s]
