### ISSUE TITLE
Tooltip component only excepts string 

### ISSUE THREAD

**Issue by jephjohnson** [gilbarbara/react-joyride#582]
## 🐛 Bug Report

When passing in an external component for a custom tooltipComponent it throws the error below.

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: <Tooltip />. Did you accidentally export a JSX literal instead of a component?`

I am aware I can import my custom tooltip and pass it in with the following approach below but this fails when addiontional props are needing to be passed in.

```
...
<Joyride
        continuous={true}
        run={state.run}
        tooltipComponent={Tooltip} <-------This method can not accept custom props types.
        hideBackButton={false}
        showProgress={true}
        steps={Steps}
        callback={handleJoyrideCallback}
        scrollOffset={500}
        stepIndex={stepNumber}
      />
...
```

## To Reproduce

Create a separate component outside of your joyride setup and pass the component to the tooltip.

**Main.js**

```
...
<Joyride
        continuous={true}
        run={state.run}
        tooltipComponent={<Tooltip endTour={endTour}/>} <-------Fails
        hideBackButton={false}
        showProgress={true}
        steps={Steps}
        callback={handleJoyrideCallback}
        scrollOffset={500}
        stepIndex={stepNumber}
      />
...
```

**Tooltip.js**
```
...
const Tooltip = ({ continuous, index, step, size, backProps, closeProps, primaryProps, tooltipProps, endTour }) => {
   return (
      <div {...tooltipProps}>
        {step.title && <h2>{t(step.title)}</h2>}
        {step.content}
        ....
          <BootstrapButton onClick={endTour}>End</BootstrapButton>
        )}
        .....
      </div>
    );
  };
 export default Tooltip;
```
  

## Expected behavior

Allow a component with custom prop types be passed to the tooltipComponent. 

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
Hey,

Yeah, this is expected.

Both `beaconComponent` and `tooltipComponent` expect a React component (class or forwardRef) that will be called with the tooltip props and ref.

What are you trying to achieve with the `endTour` prop? You can use the skipProps to end a tour...

**Comment by jephjohnson** [comment]
'endTour' is a function that lives on my root.

```
const endTour = () => {
    setStepNumber(0);
    dispatch(actions.setRun(false));
    dispatch(actions.setJoyRideShow(false));
    dispatch(actionMenu.setShowEllipsis(false));
  };
```

**Comment by gilbarbara** [comment]
You can use the skip props and listen for the skip action in the callback and dispatch your actions there.

**Comment by gilbarbara** [comment]
Anyway, feel free to submit a PR

**Comment by jephjohnson** [comment]
Haven't tested but say
`<BootstrapButton {...skipProps} >End</BootstrapButton>`

and in my root 
```
if (action === 'skip') {
      setStepNumber(0);
    dispatch(actions.setRun(false));
    dispatch(actions.setJoyRideShow(false));
    dispatch(actionMenu.setShowEllipsis(false));
}
```
Should do it?

**Comment by gilbarbara** [comment]
@jephjohnson Yeah, I think so.

Check the Controlled [demo](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo?file=/src/Controlled/index.tsx) if you need a detailed example.
