### ISSUE TITLE
problem when tour starts and changes component path

### ISSUE THREAD

**Issue by kheker** [gilbarbara/react-joyride#583]
I have the joyride as provider to the entire app and when I use it in one component and when I start the tour and close after going through the first step, close it and move to another component, the joy does not work again.
this is my code 
`import React, { createContext, useCallback, useMemo, useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import Joyride, { EVENTS } from 'react-joyride';
export const helperDataAttr = 'data-helperjoy';
// eslint-disable-next-line no-unused-vars
export const AppHelpersContext = createContext({ refresh: (helperData) => { }, helperDataAttr });
AppHelpersContext.displayName = 'AppJoyHelpersContext';
export const AppHelpersContextProvider = AppHelpersContext.Provider;
export const AppHelpersContextConsumer = AppHelpersContext.Consumer;

function onShowed(seriesID) {
  let appShowedHelpers = JSON.parse(localStorage.getItem('appShowedHelpers'));
  if (!appShowedHelpers)
    appShowedHelpers = {};
  appShowedHelpers[seriesID] = true;
  localStorage.setItem('appShowedHelpers', JSON.stringify(appShowedHelpers));
}

function AppHelpersProvider({ children }) {
  const [renderingHelperData, setRenderingHelperdata] = useState({});
  const [run, setRun] = useState(false);
  const onRefresh = useCallback((helperData) => {
    setRun(false);
    setRenderingHelperdata(helperData);
  }, []);
  const joyHelpersContextValue = useMemo(() => {
    return { refresh: onRefresh, helperDataAttr };
  }, []);
  const steps = useMemo(() => {
    return Object.keys(renderingHelperData).map((helpDataID) => {
      const helpDataItem = renderingHelperData[helpDataID];
      return {
        target: `[${helperDataAttr}="${helpDataID}"]`,
        ...helpDataItem
      };
    });
  }, [renderingHelperData]);
  useEffect(() => {
    setRun(steps.length > 0);
  }, [steps]);
  const handleJoyrideCallback = (data) => {
    const { status, type, step } = data;
    if (type === EVENTS.STEP_AFTER) {
      onShowed(step.serieID);
      //setRun(false);
    }
  };
  return (
    <AppHelpersContextProvider value={joyHelpersContextValue}>
      <Joyride steps={steps}
        continuous={true}
        run={run}
        callback={handleJoyrideCallback}
        disableOverlayClose={true}
        styles={{
          options: {
            zIndex: 1000,
            arrowColor: '#e3ffeb',
            primaryColor: '#f57c00',
          }
        }} />
      {children}
    </AppHelpersContextProvider>
  );
}
AppHelpersProvider.propTypes = {
  children: PropTypes.oneOfType([PropTypes.node, PropTypes.element]).isRequired
};
export default AppHelpersProvider;`

`import { useEffect, useContext, useMemo } from 'react';
import shortid from 'shortid';
import { AppHelpersContext } from '../components/appHelpersProvider.jsx';

export function makeHelpers(helperDefs) {
  return function useHelpers() {
    const { refresh: refreshHelp, helperDataAttr } = useContext(AppHelpersContext);
    const [helperElementProps, helperData] = useMemo(() => {
      const helperElementPropsRes = {};
      const helperDataRes = {};
      Object.keys(helperDefs).forEach(defKey => {
        const helperID = shortid.generate();
        helperElementPropsRes[defKey] = { [helperDataAttr]: helperID };
        helperDataRes[helperID] = helperDefs[defKey];
      });
      return [helperElementPropsRes, helperDataRes];
    }, [helperDefs]);
    useEffect(() => {
      const appShowedHelpers = JSON.parse(localStorage.getItem('appShowedHelpers'));
      if (appShowedHelpers) {
        const pasosFaltantes = Object.keys(helperData).filter(key => {
          const caminoComponente = helperData[key].serieID;
          return (caminoComponente in appShowedHelpers);
        });
        if (pasosFaltantes.length > 0) {
          pasosFaltantes.map((x) => delete helperData[x]);
        }
      }
      refreshHelp(helperData);
    }, [refreshHelp, helperData]);
    return helperElementProps;
  };
}`
this way it works like "makeStyles" from material-ui,for all the components and the previously used ones are transferred to a blacklist

**Comment by gilbarbara** [comment]
Hey,

Please use the templates to create issues, there is some information that's needed. Library and node version, OS, etc.

Also, issues without reproducible code (codesandbox) are likely to stall.

**Comment by gilbarbara** [comment]
But this doesn't seem to be a bug with the library itself but instead a problem with your implementation.

You can try the Spectrum [chat](https://spectrum.chat/react-joyride) to get help from other users.
Anyway, without a codesandbox it's a impossible to know what's happening.

[s]
