### ISSUE TITLE
Tooltip wrong postion on antd column header 

### ISSUE THREAD

**Issue by hugobarragon** [gilbarbara/react-joyride#588]
## 💬 Questions/Help  

Hello, I am having an issue and I can't seem to find the solution.  
The problem, even with all stock from antd design, when I apply joyride step to column header, the tooltip always gets its position wrong, even without any styles.  
I created a reproduction link on codesandbox.  

[![Edit react-joyrideWithAntdDesignTable](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-joyridewithantddesigntable-nvu0v?fontsize=14&hidenavigation=1&theme=dark)

**Comment by gilbarbara** [comment]
Hey,

The `.ant-table-body` changes the overflow and this breaks the positioning. 
There's nothing this library can't do to override that...
