### ISSUE TITLE
RTL Language Localization + Next button + Progress = Parentheses Display Issue

### ISSUE THREAD

**Issue by b-zurg** [gilbarbara/react-joyride#591]
## 🐛 Bug Report

For RTL languages, the localization + step # in the "next" button does not display correctly.

## To Reproduce

Create a page whose direction  is RTL and who has a joyride with ` showProgress={true}` and a locale object e.g. `{next: "بعد"}`

Start the tutorial, and observe the first  pop up.

## Expected behavior

Expected the next button to render as it would in an LTR language but reversed.

Instead it looks like this:

![image](https://user-images.githubusercontent.com/57298613/88394055-6aab0400-cdc7-11ea-84ae-a8b3ea0889f6.png)

Taking a look at the dom is interesting: 

```html
<span>بعد (1/9)</span>
```
What we need is
```html
<span>(بعد (1/9</span>
```

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 3.37 GB / 15.96 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
```

**Comment by gilbarbara** [comment]
Hey @b-zurg 

I can't see the difference between your two examples. For me, it looks the same, sorry.

Anyway, You can use a custom tooltip component with the `tooltipComponent` prop if the default behavior doesn't suit your needs.

[s]

**Comment by GhrezaKh74** [comment]
I resolve this problem with add Bottom code to base css file when use rtl Mode
`.react-joyride__tooltip{
  float: left !important;
}`
