### ISSUE TITLE
Placement can't be a string

### ISSUE THREAD

**Issue by FlorianRuen** [gilbarbara/react-joyride#595]
## 🐛 Bug Report

I want to use the react-joyride, so I use the npm install to get it, and I follow all the steps inside the readme.
For the steps, I import them from another file (located in /app/shared/onboarding/steps.ts)

For every steps where I add a placement: "center", I got the following error in my terminal:

```
TS2322: Type '({ content: string; placement: string; target: string; } | { target: string; content: string; })[]' is not assignable to type 'Step[]'.
  Type '{ content: string; placement: string; target: string; } | { target: string; content: string; }' is not assignable to type 'Step'.
    Type '{ content: string; placement: string; target: string; }' is not assignable to type 'Step'.
      Types of property 'placement' are incompatible.
        Type 'string' is not assignable to type 'Placement'.

Version: typescript 3.0.1, tslint 5.11.0
```

## To Reproduce

Just import the library, initialize the tour with at least one step that use the placement

## Expected behavior

The steps is well placed but due to this error, my npm test doesn't works perfectly.

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```
  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
    Memory: 3.00 GB / 15.47 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.17.0/bin/npm
  npmPackages:
    react-floater: ^0.7.2 => 0.7.2 
```

**Comment by FlorianRuen** [comment]
Up, someone have a solution on this issue ?
I've done all my Onboarding process, and I need to deploy this, but this error cause my a Pipeline failed.

**Comment by gilbarbara** [comment]
Hey

This is a typescript error not this library...

**Comment by FlorianRuen** [comment]
To answer this, I found a way to solve this:

`placement: 'center' as placement`

just import the {placement} from react-joyride
