### ISSUE TITLE
Joyride skips steps with placement: "center"

### ISSUE THREAD

**Issue by davidhennemann** [gilbarbara/react-joyride#596]
## 🐛 Bug Report

Sometimes it handy to have a step in the joyride tour, which does not highlight any element, but just appears in the middle. One can achieve this by using:
```js
{
      target: "body",
      content: "test",
      placement: "center"
}
```
Unfortunately there seems to be a bug, with using this instruction. If a joyride tour has multiple steps with `placement: "center"` and one is clicking `Next` after the first step, it will just skip all steps afterwards and will only start running normally the step *after* a step without `placement: "center"`.

E.g. 

1. step w/  `placement: "center"`
2. step w/ `placement: "center"`
3. normal step highlighting something in the DOM (w/o `placement: "center"`)
4. any step (centered or normal) **<-- Joyride will jump until here**

## To Reproduce

Please take a look at this code sandbox. The behaviour described above is reproduced there. The tour will instantly jump to step 4. If one removes  `placement: "center"` it will work flawlessly (but obviously without the centered tooltip...)

https://codesandbox.io/s/wizardly-star-qmi96

## affects version

most recent release `2.2.1`

**Comment by gilbarbara** [comment]
hey @davidhennemann 

I think it's a problem with the callback logic in your example.
If you remove the `stepIndex` from the Joyride component, the tour works as expected.
Generally, you don't need to mess with the `stepIndex` unless you really need to control the tour flow by yourself.
