### ISSUE TITLE
Wrong position of spotlights if the page is zoomed on mobile

### ISSUE THREAD

**Issue by vladarsky** [gilbarbara/react-joyride#598]
## 🐛 Bug Report

At first, I would like to thank you @gilbarbara for the very useful library. You did a great job! It has a lot of advantages yet a few flaws. The most critical one for us is the positioning of spotlights. It's getting wrong if you zoom the page on mobile. Unfortunately, we have to disable an education on mobile because of that.
![Image from iOS (1)](https://user-images.githubusercontent.com/12588568/92142948-42c6ab80-ee1d-11ea-8cf7-7686253e49ed.png)

## To Reproduce

Just try it on demo. Zoom the page and scroll around. The position of spotlights will become wrong.

## Expected behavior

The position of spotlights is correct or allowed to be handled outside of the library context.

## Link to repl or repo (highly encouraged)

https://react-joyride.com/

**Comment by gilbarbara** [comment]
Hey @vladarsky 

Thanks!
But this isn't something it is on my radar since it's the first time someone mentions it...

Feel free to submit a PR

**Comment by AbramovichCp** [comment]
face same problem

**Comment by lcoalves** [comment]
Same problem.

**Comment by podlesny** [comment]
Hi @gilbarbara

I hope this message finds you well. I've been using Joyride for onboarding, and it has been incredibly helpful for our project. Thank you for creating such a valuable tool.

Recently, I encountered an this issue related to the zoom-in-out in the library, and I noticed that it has been reported on the GitHub repository, and I would like to kindly request your assistance in resolving it.

The zoom-in-out functionality is essential in a lot of web apps, including our case, and having it work smoothly would greatly improve the user experience. If there's any way you could consider fixing or providing guidance on this issue, it would be greatly appreciated by the community of users.

Thank you for your time and consideration

Best wishes
Max

**Comment by gilbarbara** [comment]
Hey @podlesny 
Thanks!

I'm finishing the TS migration of the source code, and I don't have time to work on that right now.
Feel free to submit a PR.

**Comment by nechaido** [comment]
@gilbarbara Hi. Our team has recently faced the issue as well.

We could dedicate a developer to fix the issue if you could provide a few pointers on what and where to look for.
