### ISSUE TITLE
When using tooltip component and want to stop joyride for validation, how can I stop the animation to the next step?

### ISSUE THREAD

**Issue by WeronikaWeglinska** [gilbarbara/react-joyride#599]
## 💬 Questions and Help

I have a situation when I am using tooltip component and I want to wait for user action, so I am doing some validation. Let's say I have an input in step 3 and I want to stop the tour until user types in email address and after they do I want to continue to step 4.

What I am doing at the moment is sth like this:

```
if (index === 4) {
    const element = document.querySelector(`${STEPS[3].target}`);
    const inputValue = element.value;
    if (!inputValue || !EMAIL_PATTERN.test(inputValue)) {
      dispatch({ type: "STOP" });
    }
  }
```

This works fine validation wise, but because I have scrolling container and step 4 is on top of the page while step 3 is on the bottom, I will see the page scrolling to the top before user can enter email.

The issue I see here is that if I try to stop the tour on index 3 it won't show the step itself.

I will be really grateful for help.

**Comment by gilbarbara** [comment]
hey @WeronikaWeglinska 

Check the controlled mode in the demo, you can control the tour flow by yourself

**Comment by WeronikaWeglinska** [comment]
Hi, yes, thanks for your reply. I am using now controlled mode with the 
```
    disableBeacon: true,
    disableOverlayClose: true,
    spotlightClicks: true,
```
and React.createContext(), when I can dispatch joyride actions, like waiting for the element and dispatch restart from next step. It kinda works, but seems a bit hacky in a way. It would be great if there was a demo showing navigation to another page when tour waits for element to show and it's controlled from different components (but it's just a suggestion, would be nice to see for best practices). 
I will close this issue.

**Comment by gilbarbara** [comment]
@WeronikaWeglinska In the controlled demo, the menu opening stops the tour and restart it after the animation is complete. Is the same principle.

How are you going to wait for the navigation to complete would be different for every app so I don't think there is a correct way to do it.
