### ISSUE TITLE
Accessing getPopper breaks overlay and lifecycle

### ISSUE THREAD

**Issue by JustAskMarina** [gilbarbara/react-joyride#600]
## 🐛 Bug Report

I'm using Joyride in controlled mode and trying to access the Popper instance to force update of the position when window resize occurs.
I have some logics changing the flow if media query changes, I've managed to make the switch almost smooth but in some edge cases I would like to force an update, but simply using the getPopper to log Popper breaks almost everything.

This is what I get logging without the getPopper in place, navigating to the second step, no media query related logic triggered

![Immagine 2020-10-01 162124](https://user-images.githubusercontent.com/44635556/94823199-e0ed6780-0403-11eb-83a6-d0cdae531dd3.png)

and this is what I get with the same code, same steps, but with getPopper uncommented

![Immagine 2020-10-01 162059](https://user-images.githubusercontent.com/44635556/94823492-3295f200-0404-11eb-9072-cd55afd295ca.png)

## Run `npx envinfo --system --binaries --npmPackages react-floater`

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 9.27 GB / 15.85 GB
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - ~\Documents\xxxxxxxx\node_modules\.bin\npm.CMD

```bash

```

**Comment by gilbarbara** [comment]
hey @JustAskMarina 

I'm not sure I understand you are trying to do, please post a codesandbox example.
