### ISSUE TITLE
Overlay height causing scroll issue

### ISSUE THREAD

**Issue by feebabs** [gilbarbara/react-joyride#603]
I had an issue where the overlay height was being set incorrectly causing a scroll issue within my site during the tour. I fixed the issue by setting the `.react-joyride__overlay` height to `100% !important`. However, this will break on any change you put out that changes the classname. I was wondering if it would be possible to get the overlayHeight as a style option similar to the overlayColor so changes won't break my override.

**Comment by jalejandro0211** [comment]
same here

**Comment by gilbarbara** [comment]
hey @feebabs 

That's weird since height usually doesn't work with percentages...
Can you set up a codesandbox?

**Comment by feebabs** [comment]
Height usually doesn't work with percentages, but from what I can tell the tour is trying to get the actual height of the item shown in the tour step, but my site layout has a fixed header and footer with scrolling content. This is causing the overlay to add random height below the fixed layout. Looking at the code, setting the overlay height to `100vh` would probably work better in my instance. Either way, it would be nice to be able to set this via style options rather than override via the CSS class.

**Comment by gilbarbara** [comment]
@feebabs 

You can override the Overlay styles. 

```typescript
<Joyride styles={{ overlay: { height: '100%' } }} />
```

**Comment by feebabs** [comment]
Adding an inline works too, I'm just not a huge fan of inline styles and figured having an option similar to the other style options would be a good way of handling it. Thanks!

**Comment by gilbarbara** [comment]
@feebabs What do you with "other style options"?

**Comment by feebabs** [comment]
In your [styling documentation](https://docs.react-joyride.com/styling), you have a special `options` object inside the `styles` prop. I was hoping to be able to add an `overlayHeight` key/value pair to this object so that the code would be something like

```
styles={{
    options: {
      ...
      overlayHeight: `100vh`,
      ...
    },
}}
```

rather than adding the overlay above the styles like this

```
styles={{
  overlay: { height: '100vh' }, // Fix for random scroll issue
  options: {
      ...
    },
}}
```

Honestly, it's not a huge deal though. Minimal risk doing it the latter way.

**Comment by GabiLlvs** [comment]
When you zoom I'm having this weird bug where I scroll down and the overlay sets amid the background color and the normal page size
![Captura de pantalla 2024-05-17 153514](https://github.com/gilbarbara/react-joyride/assets/100242809/1938df99-c75b-4b3f-a28a-1c455ea94201)
May you help me?
  const joyrideStyles = {
    options: {
      zIndex: 10000,
      primaryColor: theme.palette.primary.dark,
      disableScrolling: true,
      textColor: '#1E1E1E',
    },
    buttonNext: {
      backgroundColor: theme.palette.primary.dark,
      color: '#1E1E1E',
    },
    buttonBack: {
      // backgroundColor: theme.palette.warning.dark,
      color: '#1E1E1E',
    },
    overlay: { height: '100vh' },
  };

**Comment by Jonojono06** [comment]
https://github.com/gilbarbara/react-joyride/issues/603#issuecomment-2118179277

I'm having the same issue. Any fix for this or help with this? Thanks

**Comment by GabiLlvs** [comment]
still strugling :(

**Comment by Ziang-Wang** [comment]
> When you zoom I'm having this weird bug where I scroll down and the overlay sets amid the background color and the normal page size ![Captura de pantalla 2024-05-17 153514](https://github.com/gilbarbara/react-joyride/assets/100242809/1938df99-c75b-4b3f-a28a-1c455ea94201) May you help me? const joyrideStyles = { options: { zIndex: 10000, primaryColor: theme.palette.primary.dark, disableScrolling: true, textColor: '#1E1E1E', }, buttonNext: { backgroundColor: theme.palette.primary.dark, color: '#1E1E1E', }, buttonBack: { // backgroundColor: theme.palette.warning.dark, color: '#1E1E1E', }, overlay: { height: '100vh' }, };

I'm having the same issue.
