### ISSUE TITLE
showCloseButton prop is not passed down into react-floater

### ISSUE THREAD

**Issue by mbrochh** [gilbarbara/react-joyride#604]
Congrats to this fantastic library! It's a real joy to use, pun intended ;)

## 🐛 Bug Report

It seems that not all props are passed down into floaterProps? I'm on version `2.2.1`

## To Reproduce

I have mounted Joyride like this:

```
<Joyride floaterProps={ { showCloseButton: false } } /> 
```

When I open the tooltip, I can still see the close button.

When I use auto-completion in VSCode and write `floaterProps={{}}` VSCode shows me that only the following options: `disableAnimation`, `options`, `styles` and `wrapperOptions`. These seem to be significantly less options than what react-floater actually offers, according to their documentation.

## Expected behavior

I would expect the Close button in the tooltip to be invisible.

**Comment by gilbarbara** [comment]
hey @mbrochh 

Thanks! :)

The close button is rendered by react-joyride, react-floater only takes care of the positioning of the tooltip.

You can use your own UI for the tooltip, check the [docs](https://docs.react-joyride.com/custom-components) for custom components.
