### ISSUE TITLE
Joyride Works fine in google chrome, but in I.E 11 multiple issues

### ISSUE THREAD

**Issue by caiosamarone** [gilbarbara/react-joyride#607]
I've made my joyride component, and its working fine in chrome and firefox. But when I open it with edge, all the overlays became messed up, doesnt highlight the right places.

**Comment by caiosamarone** [comment]
<img width="564" alt="I E" src="https://user-images.githubusercontent.com/23369193/100012838-ade7a480-2db2-11eb-8ecf-37d1d7f1bdb8.PNG">

**Comment by caiosamarone** [comment]
and chrome (working fine)  : 
<img width="896" alt="chrome" src="https://user-images.githubusercontent.com/23369193/100012908-c788ec00-2db2-11eb-8776-77d4dfb36814.PNG">

**Comment by caiosamarone** [comment]
I think, the problem its in the transition between the steps... but how to fix it ?

**Comment by gilbarbara** [comment]
hey @caiosamarone 

There's no official support for legacy browsers.

Did you include the scrollingelement polyfill?

[s]
