### ISSUE TITLE
Support for different scrolling containers

### ISSUE THREAD

**Issue by Nic128** [gilbarbara/react-joyride#61]
Usually, the joyride instance is made for scrolling the body. I have the following situation. I render a popup, then I use joyride on some elements within the popup.

It mostly works, with a few exceptions. I block the body scroll when opening the popup, then I use a scroll within that popup as needed. The auto scroll is made for document.body only. Making the scroll target configurable would be nice.

This next issue has me a bit stumped. I don't render the popup within the same div as the joyride instance. So, when I scroll, it doesn't follow the target because of the different scroll containers. I thought, maybe if I render a joyride instance within the popup, it could work. But since there are relative positions in the popup, the calculations from _calcPlacement come out wrong.

Making the auto scroll configurable is easy, but playing with positions inside a container that's not targeting the body is way too hard. Do you have any suggestions?

**Comment by gilbarbara** [comment]
hey,

Not really, I never though of using this module in such way.
Feel free to submit a PR if you need this.

**Comment by zeroasterisk** [comment]
I too would like this... I'm happy to make a PR if you want... My plan would be to replace most instances of `document.body` with a function `getRootContainer()` which returns a configured root, if one exists, otherwise returns `document.body`... reasonable?

**Comment by gilbarbara** [comment]
Hello @zeroasterisk 
It sounds simple in theory but I don't have tests yet so it would need a working demo for this new functionality.
