### ISSUE TITLE
Potential highlighting issue

### ISSUE THREAD

**Issue by zahir-koradia** [gilbarbara/react-joyride#620]
Hello.

First of all thank you for the wonderful library. It's been a pleasure to work with. 

I've come across something, that is potentially a bug and wanted to check if this is indeed the case. I've implemented a rather simple tour with the following steps:

```
const defaultTourSteps = [
      {
        target: '[data-tour="begin-up-learn-session"]',
        disableBeacon: true,
        content: (
          <span>
            Welcome to Up Learn! Here&apos;s a quick tour to show you how things work. <br /> <br />
            You can press the &apos;Begin Up Learn Session&apos; button and Up Learn&apos;s intelligent algorithm will
            take you to the lesson or activity that will increase your grade most effectively
          </span>
        ),
      },
      {
        target: '[data-tour="recall-practice"]',
        isFixed: true,
        content: 'You can practice recalling definitions here',
      },
      {
        target: '[data-tour="practice-exam-quiz"]',
        content: 'Practice exam-style quiz questions here',
      },
      {
        target: '[data-tour="practice-exam-paper"]',
        content: "When you're ready to do a practice exam paper, you can find them here",
      },
      {
        target: '[data-tour="sections"]',
        content: 'An overview of the whole course, and your progress',
        placement: 'top',
      }
    ];
```

In the last step here, the look of the highlighted area is different across Chrome and Firefox. I've attached the screenshots here. Happy to add more information if it's useful.

![Chrome](https://user-images.githubusercontent.com/1875683/102811841-f1d3c680-43bd-11eb-8169-f3d354e59da8.png)
![Firefox](https://user-images.githubusercontent.com/1875683/102811845-f1d3c680-43bd-11eb-8ba2-361270bc1c12.png)

**Comment by gilbarbara** [comment]
hey @zahir-koradia 

Thanks!

Which versions of Chrome and Firefox?

You should have fulfilled the required info in the issue template...

> Please provide a https://codesandbox.io/ demo or similar.
Issues without a reproduction link are likely to stall.
