### ISSUE TITLE
error:target_not_found event not been triggered

### ISSUE THREAD

**Issue by jibin2706** [gilbarbara/react-joyride#627]
## 🐛 Bug Report

`error:target_not_found` event is not getting trigger when first element of the step is not present in the dom. Also the same issue occurs when your start `run` prop and the next element is not found.

## To Reproduce

- First element should not to present in the dom.

## Expected behavior

`error:target_not_found` error should be thrown

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/peaceful-wind-mzc79?file=/src/App.tsx

Issues without a reproduction link are likely to stall.

**Comment by gilbarbara** [comment]
This event isn't triggered in the controlled mode since the step won't be updated automatically and the callback would be dispatched multiple times.
