### ISSUE TITLE
IE9 support

### ISSUE THREAD

**Issue by vdzundza** [gilbarbara/react-joyride#63]
How to fix working at IE9 ?

**Comment by gilbarbara** [comment]
Does it work on IE 10?

**Comment by Yuripetusko** [comment]
I would prefer not to have support for < IE11. The percentage is too low and it will make code/css bloated to support it.

**Comment by gilbarbara** [comment]
I'll not support IE9 and below.

**Comment by topher515** [comment]
If someone finds this through Google. FYI: All I had to do to do to get Joyride to work with IE10 was to add a `dataset` polyfill, e.g., https://www.npmjs.com/package/element-dataset
