### ISSUE TITLE
You can change routes/click outside the beacon

### ISSUE THREAD

**Issue by iamalextodoran** [gilbarbara/react-joyride#637]
Start the tour -> the beacon appears -> click anywhere outside the beacon (you can change routes/open menus/etc.)

Is there any way to disable clicking outside of it? Or a way to cancel the tour if the user clicks outside the beacon?

**Comment by gilbarbara** [comment]
hey @iamalextodoran

This library doesn't know what's happening in the rest of your app, so it can't control its own status in these conditions
