### ISSUE TITLE
Tooltips do not work outside of a tour

### ISSUE THREAD

**Issue by jchristman** [gilbarbara/react-joyride#64]
As far as I can tell, [state.position](https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Component.js#L641) is never set, which makes the [tooltip rendering break](https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Tooltip.js#L187). I think if you just remove the line from the Component.js, everything will work.

**Comment by gilbarbara** [comment]
hey @jchristman 
I'm not sure if get it.. Do you have an example?
The demo isn't working for you?

**Comment by jchristman** [comment]
I'm not currently home so I can't pull up my code, but I was getting an error where the position variable was undefined and so it could not set the opts.positionBaseClass because the opts.positionClass was undefined. opts.positionClass is set from props.position, which was also undefined. props.position was set on the line from the first link, where state.position is undefined. As far as I can tell, position is never set anywhere in the code as a state variable, which is why it is undefined. When I was debugging, currentastes.position (from the first link) was already correctly set to the variable I passed to this.refs.joyride.addTooltip. When I get home, I will paste some more things in here, but the default behavior seems broken...

**Comment by gilbarbara** [comment]
wow, I can't understand this bunch of code.
Is the demo working for you?

**Comment by jchristman** [comment]
After examining, it appears as though in order for tooltips to work, there have to be steps in the joyride. After the weekend, I will make a minimalistic repo that demonstrates tooltips breaking when there are no steps yet added.

The real question is: are tooltips supposed to be able to be independent of a joyride? Because I can't seem to be able to get them to work independently.

**Comment by Yuripetusko** [comment]
It might be related to this, if I set step as `Object {position: "left", selector: ".faq-sidebar", text: "Multi Page Tour!"}` then `this.props.step.position` will be `undefined` inside of `Tooltip` component

![screenshot 2016-06-15 18 05 04](https://cloud.githubusercontent.com/assets/666169/16089576/b761ec5c-3323-11e6-8fff-aa21219696cf.png)

**Comment by Yuripetusko** [comment]
Actually it doesn't matter if position is set to left or bottom, could it be related to the fact that I set steps as array with only 1 item? `[{position: "left", selector: ".faq-sidebar", text: "Multi Page Tour!"}]`

**Comment by Yuripetusko** [comment]
Looks like in my case `_calcPlacement` never fired so `state.position` is undefined

**Comment by Yuripetusko** [comment]
Ok sorry, my issue was that I was firing `joyRide.start()` twice

**Comment by jchristman** [comment]
@gilbarbara, I have narrowed down the issue to what I was really seeing: if there are no steps in the joyride OR if the joyride is not started, then the tooltip fails. Because of this line: https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Component.js#L130. I can build a minimum working example if you would like, or I can submit a pull request which makes it so that tooltips can be used outside of a joyride.

Thoughts?

**Comment by gilbarbara** [comment]
@jchristman I'm refactoring the tooltip and I'll fix this.

**Comment by gilbarbara** [comment]
@jchristman I've fixed this in 1.4
Sorry for the delay.
