### ISSUE TITLE
Problems with overlay after scrolling from initial viewpoint.

### ISSUE THREAD

**Issue by kfbow** [gilbarbara/react-joyride#65]
The problems are (1) you can click through the overlay to something like a link hidden underneath when scrolling from the initial viewpoint. The overlay should be intercepting that and not trigger the link, even when scrolled down. (2) when you scroll down and click on the overlay, joyride should become disabled. It doesn’t. It only becomes disabled if you click inside the part of the overlay visible before you scroll down.

If you could give me some pointers on where to look we might be able to fix it and submit a patch as we need this for our project.

**Comment by gilbarbara** [comment]
Do you have an example?

**Comment by kfbow** [comment]
@gilbarbara When scrolled down I can check the boxes underneath the overlay and clicking doesn't stop the tutorial. http://recordit.co/CFGVwACyB2

**Comment by gilbarbara** [comment]
Hey
That's weird  since the overlay appears to be above your content and would catch the click.
I have no idea how to debug this since I can't reproduce..
