### ISSUE TITLE
Invalid prop type 'string' listed for offset property in step documentation

### ISSUE THREAD

**Issue by stefanelsat** [gilbarbara/react-joyride#651]
## 🐛 Bug Report

In [step documentation](https://docs.react-joyride.com/step) the type of the `offset` property should be `number` instead of `string`, as this type is required by ReactFloater.

## To Reproduce

Define some tour steps and pass `offset: '0'` as param, for instance:
```javascript
const TOUR_STEPS = [
  {
    target: '.selector',
    content: 'Some content for my step',
    title: 'Super cool step',
    offset: '25' // <--- invalid type string, should be number instead
  }
```
Produces following error in console:
```bash
index.js:1 Warning: Failed prop type: Invalid prop `offset` of type `string` supplied to `ReactFloater`, expected `number`.
    in ReactFloater (created by JoyrideStep)
    in JoyrideStep (created by Joyride)
    in div (created by Joyride)
   ...
```

**Comment by gilbarbara** [comment]
Updated in c33746d542fd8203d2e85ed07a0c07753c3cc86f
