### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by emreesirik** [gilbarbara/react-joyride#655]
## 🐛 Bug Report

React gives error in strict mode. 

<img width="1326" alt="Screen Shot 2021-03-10 at 14 38 49" src="https://user-images.githubusercontent.com/7847917/110623734-56791300-81ae-11eb-9644-afa7c1442859.png">

**Comment by gilbarbara** [comment]
@emreesirik 
This library doesn't use findDOMNode.

The error that you attached apparently came from the [react-resize-detector](https://www.npmjs.com/package/react-resize-detector) library...
