### ISSUE TITLE
TypeError Invalid parameter: element must be an HTMLElement

### ISSUE THREAD

**Issue by Prateek-Singhdeo** [gilbarbara/react-joyride#657]
## 🐛 Bug Report

I am getting the following error in react-joyride custom implementation. 
"TypeError
Invalid parameter: element must be an HTMLElement".

Please find the below sandbox link.

https://codesandbox.io/s/react-joyride-forked-zy1su?file=/CustomComponents/index.js

## To Reproduce

Go to the custom component option in the above sandbox and once you start the tour can see the error.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/react-joyride-forked-zy1su?file=/CustomComponents/index.js

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
hey @Prateek-Singhdeo 
I haven't used the sandbox you forked for a long time. Where did you find it?
If you the demo linked here in the repo it will use the new one...
https://codesandbox.io/s/github/gilbarbara/react-joyride-demo
