### ISSUE TITLE
[Feature Request] Add callback for when a user clicks outside of the tutorial

### ISSUE THREAD

**Issue by kfbow** [gilbarbara/react-joyride#66]
We'd like to call `disableJoyride()` if a user clicks outside of the tutorial, instead of just going to the next step.

**Comment by gilbarbara** [comment]
hey,
What do you mean by "outside"? Anywhere else but the beacons?
You could watch for those clicks and call `this.refs.joyride.stop()` or something like it?

**Comment by gesposito** [comment]
Yeah I guess it's outside the tooltip (and hole?)

**Comment by kfbow** [comment]
@gilbarbara so are you saying add an `onClick()` to the overlay surrounding the tutorial? The greyed out space?

**Comment by gilbarbara** [comment]
Added in 1.4
Thanks

**Comment by stanislav-grin** [comment]
Hi
Sorry, I didn't understand - how can now I stop tour when clicking outside of tooltip?
