### ISSUE TITLE
using with boostrap-tabs

### ISSUE THREAD

**Issue by lsentkiewicz** [gilbarbara/react-joyride#67]
This library is really great, but I have one issue.

I am using react-boostrap and I try to make a tour between tabs.
I change the active tab in the `stepCallback` function, but tooltip is not displayed correctly.
I guess it's because the `stepCallback` is invoked right after the tooltip is displayed and the target UI element is not visible yet.

This issue could be solved if you add a new callback `beforeStepCallback()` or  add custom handlers for `next` and `prev` buttons.

**Comment by gilbarbara** [comment]
I'll add this functionality soon

**Comment by gilbarbara** [comment]
I've refactored the callbacks and added a step:before in e5a36e2cba35e196f727ca0762001c1b71db36a3
Try 1.4
