### ISSUE TITLE
QUESTION: Exposing reset and parseSteps functions

### ISSUE THREAD

**Issue by Yuripetusko** [gilbarbara/react-joyride#68]
Hi, I want to do `addSteps` and `reset` from redux acitions, is there a way of exposing these methods somehow (i.e. `import {parseSteps, reset} from 'react-joyride'`) instead of having them on JoyRider instance and having to use `this.refs` all the time ?

**Comment by gilbarbara** [comment]
Not yet. I'm in the process of rewriting it but no release time yet.

**Comment by stinoga** [comment]
@Yuripetusko Did you get this working with redux actions at all? Wanting to go down the same road...

**Comment by Yuripetusko** [comment]
Hi @stinoga I chose hopscotch in the end, and yes I integrated it with redux, getting initial object of all tours from firebase, then on componentWIllReceiveProps I compare router pathname, if it changed, I check if I have tour that should start on current pathname, and initialize it, saving currentStep onNext in redux etc etc
