### ISSUE TITLE
Joyride breaks responsive tables

### ISSUE THREAD

**Issue by danielrollenmillernovacode** [gilbarbara/react-joyride#689]
## 🐛 Bug Report

Hi, I really like this project so far for the ease of use while also providing enough functionality and customizability for my current use case. Unfortunately I encountered a minor issue:  
When using the bootstrap table-responsive class on a table with a certain minimum width, it will get horizontally scrollable on smaller displays. I understand that joyride is not perfectly usable with this type of table, however, I think we should at least expect that it does not break the responsiveness of the table. But that's how it currently seems to be. 

Before starting a tour my responsive div wrapping the table element looked as follows:
`<div class="table-responsive mt-2"><table>....`
table-responsive will set the following css properties to make it horizontally scrollable if required: 
`.table-responsive {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
}`

Upon starting a tour an element style will be added to the div which then looks as follows:
`<div class="table-responsive mt-2" style="overflow: initial;"><table>....`
Obviously the overflow: initial will overwrite the overflow-x: auto property and therefore break the table. There is an easy fix by adding !important to the overflow-x property, however, I think it'd be best if the element style is not added at all or removed afterwards. 

Paste the results here:
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 4.54 GB / 15.36 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD

Thanks in advance and keep safe and healthy,
Daniel

**Comment by gilbarbara** [comment]
hey @danielrollenmillernovacode 

Did you try setting the `disableScrollParentFix` prop?
https://docs.react-joyride.com/props

**Comment by danielrollenmillernovacode** [comment]
@gilbarbara Thanks for the fast reply!
That works great and doesn't break the table anymore!
Do you have any idea how we could scroll such a table horizontally?
 
Also I am wondering what else this prop may influence now and what the original purpose or issue for the fix causing this behavior was? Everything still seems to behave as intended in my joyride tours, so I assume it was some corner case?

**Comment by gilbarbara** [comment]
@danielrollenmillernovacode 

There's no functionality for horizontal scrolling. There was a PR for it some time ago but it added too much complexity and nobody voted for it.

The prop just adds the overflow property... There were several issues with positioning, especially with content that didn't fill the whole page height and the overlay/tooltip didn't render correctly.
This fix is being used for a couple of years and apparently, it doesn't have a negative impact. 🤷🏻‍♂️
