### ISSUE TITLE
QUESTION: Change 'next' 'last' labels

### ISSUE THREAD

**Issue by Yuripetusko** [gilbarbara/react-joyride#69]
i am doing multi-page tours, so onCallback I do stop() router.push, and then on new page I am replacing steps and doing .start() again, is there a way to change button label to `next` instead of `last` even if it is last item in current steps sequence?

**Comment by Yuripetusko** [comment]
I can see that i can use `locale` attribute, but that doesn't really fit my situation, I want to specifically tell joyRide when to use which label, like a property on `step` object maybe

**Comment by kfbow** [comment]
@Yuripetusko You could add a custom parameter to the step where you want the `locale` to change for example:
`title: 'Welcome', text: 'welcome', selector: '#welcome', position: 'top', last: 'true'`
Then create a state object for `locale` and then use the `stepCallback` joyride prop and write a function along the lines of
```
stepCallback(step: Object) {
        if (step.final) {
            this.setState({
                joyrideLocale: {
                    back: 'Back', close: 'Close', last: 'Last', next: 'Last', skip: 'Skip',
                },
            });
        }
}
```

**Comment by Yuripetusko** [comment]
@kfbow it's not the prettiest solution, but I can work with that! thanks 👍

**Comment by kfbow** [comment]
Agreed :P just one of doing it I guess.
