### ISSUE TITLE
Is there a way to specify order of steps?

### ISSUE THREAD

**Issue by vincentchin** [gilbarbara/react-joyride#70]
Hi, I just installed this and started trying to implement into my app. Since my app flow isn't as linear as the example, I'm trying to trigger the steps in a specific order (I'm using reflux). I know in the example, the steps are added in whichever order the components are mounted. I was wondering if there's another way to add steps other than using `componentDidMount` or maybe even hook up `this.props.addSteps` to an action.

For example if I had something like this,
```
<Component1 addSteps={this.addSteps} />
<Component2 addSteps={this.addSteps} />
<Component3 addSteps={this.addSteps} />
```
How would I get `<Component2 />` to trigger it's beacon first? 

Thanks!

**Comment by andreadelrio** [comment]
@vincentchin did you figure out how to do this?

**Comment by vincentchin** [comment]
@andreadelrio I think what I ended up doing was just specifying the `steps` prop on init which may not be the best way to do it depending on your usage.

**Comment by andreadelrio** [comment]
@vincentchin cool, thanks for your reply!
