### ISSUE TITLE
Using joyride in preact causes an error after completing the first step

### ISSUE THREAD

**Issue by IgnusG** [gilbarbara/react-joyride#702]
## 🐛 Bug Report

Providing an array of at least 2 steps to Joyride while using Preact causes an exception to be thrown after the first step is completed.

## To Reproduce

Environment:  
Preact `10.5.13`  
Joyride `2.3.0`

1. Provide at least 2 steps to Tour
2. Click on first beacon and close tooltip
3. Click on second beacon -> crash

<details>
<summary>Error Stack</summary>
<pre>
Invalid parameter: element must be an HTMLElement
new Scope
https://cvm6g.csb.app/node_modules/react-joyride/es/index.js:1119:11
JoyrideStep.componentDidUpdate
https://cvm6g.csb.app/node_modules/react-joyride/es/index.js:1773:22
JoyrideStep.eval
https://cvm6g.csb.app/node_modules/preact/dist/preact.module.js:237:13
</pre>
</details>

## Expected behavior

Don't crash.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/trusting-surf-cvm6g?file=/src/index.tsx:0-116

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
  System:
    OS: Linux 5.4 Arch Linux
    CPU: (16) x64 Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz
    Memory: 46.45 GB / 50.02 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.asdf/installs/nodejs/14.15.1/bin/node
    npm: 6.14.8 - ~/.asdf/installs/nodejs/14.15.1/bin/npm
```

Original Discussion https://github.com/gilbarbara/react-joyride/discussions/701

**Comment by gilbarbara** [comment]
hey @IgnusG 

Preact isn't supported.

**Comment by IgnusG** [comment]
Hey @gilbarbara. I figured. I still think that this is either A happening because preact is doing something that react isn't or B that this library (or one of it's dependencies) is doing something that breaks this compatibility. If it is the latter this might lead to problems with future react versions anyway. If it's the former, I guess there's nothing for this library to do

**Comment by gpfunk** [comment]
@IgnusG 

I ran into this as well, ended up grabbing the element directly, rather than using the tooltip ref (which seemed like it wasn't being set in time and was causing the error) 

```
const tooltip = document.getElementById(`react-joyride-step-${index}`);

this.scope = new Scope(tooltip, { selector: '[data-action=primary]' });
```
