### ISSUE TITLE
Trying to upgrade to 2.1.1

### ISSUE THREAD

**Issue by mgw-sbex** [gilbarbara/react-joyride#705]
### Discussed in https://github.com/gilbarbara/react-joyride/discussions/704

<div type='discussions-op-text'>

<sup>Originally posted by **mgw-sbex** June 26, 2021</sup>
We cannot use the latest due to dependecies. It seems that 2.1.1 would work. When I install it, it does not create anything in [build-dir]/node_modules/react-joyride/lib/react-joyride. We used to import like this:

@import '~react-joyride/lib/react-joyride';

Now that is failing:
ERROR in ./node_modules/css-loader??ref--3-2!./node_modules/postcss-loader/lib??ref--3-3!./node_modules/sass-loader/lib/loader.js??ref--3-4!./sass/app.scss
Module build failed:
@import '~react-joyride/lib/react-joyride';
^
      File to import not found or unreadable: ~react-joyride/lib/react-joyride.
      in /Users/......./client/web/shows/jimmy/sass/app.scss (line 29, column 1)
 @ ./sass/app.scss 4:14-189
 @ ./app/index.js
 @ multi babel-polyfill whatwg-fetch ./app/index.js

Can you explain what should be done in this case? Many thanks</div>

**Comment by gilbarbara** [comment]
Read the migration guide.
https://docs.react-joyride.com/migration
