### ISSUE TITLE
not work with {position: 'fixed'}?

### ISSUE THREAD

**Issue by realbugger** [gilbarbara/react-joyride#71]
Just started playing with react-joyride and really liked it. However, I found that whenever I change a component's inline style to `{position: 'fixed'}`, the corresponding step will become `undefined`. Did I miss something or this is the expected behavior?

**Comment by gilbarbara** [comment]
can you give me an example?

**Comment by realbugger** [comment]
Here is a simplified version of what I have. With `position: 'fixed'`, Joyride doesn't seem to be able to find the element, and the corresponding step become `undefined`. Once I remove `position: 'fixed'`, or change it to other values (like `relative`, `inline`, etc.), Joyride would be able to find the element.  
```
import React, { Component} from 'react';
import Joyride from 'react-joyride';

const joyrideSteps = [
  {
    title: 'test step',
    text: 'test step',
    selector: '.test-step',
    position: 'bottom'
  }
];

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      joyrideSteps: []
    };
  }

  componentDidMount() {
    this.joyrideAddSteps(joyrideSteps);
  }

  joyrideAddSteps(steps) {
    let newSteps = steps;

    if (!Array.isArray(newSteps)) {
      newSteps = [newSteps];
    }

    if (!newSteps.length) return;

    this.setState(currentState => {
      currentState.joyrideSteps = currentState.joyrideSteps.concat(this._joyride.parseSteps(newSteps));
      return currentState;
    });
  }

  render() {
    const {joyrideSteps} = this.state;
    return (
      <div>
        <div className="test-step" style={{position: 'fixed', top: 100, left: 100, width: 50, height: 50}}>
          Test div
        </div>
        <Joyride
          ref={ref => this._joyride = ref ? ref : null}
          debug={false}
          steps={joyrideSteps}
          type={'continuous'}
          showOverlay />
      </div>
    );
  }
}

```

**Comment by Yijianc** [comment]
I got the same problem with `position: 'fixed'` elements.
I found nothing in `joyride.parseSteps(newSteps)` when next step is attached to `position: 'fixed'` elements. Are there any suggestions to handle this issue except changing the `position` value?
Thks a lot in advance.

**Comment by TroutZen** [comment]
Also have the problem with position fixed elements. 

1) i.e. sidebar is fixed, main-content is scrollable
   - if selector is within fixed sidebar
         - scrollToPosition is calculated incorrectly
         - scroll within main-content also scrolls beacon/tooltip (beacon/tooltip not 'anchored' to element)

2) Sometimes it seems parseSteps does not return the steps

**Comment by krstffr** [comment]
I also have this problem.

Maybe add some "isFixed" property to each step, and if true then position the step using position: fixed.

**Comment by IanVS** [comment]
Closed by https://github.com/gilbarbara/react-joyride/pull/165
