### ISSUE TITLE
[API Proposal] Container Syntax

### ISSUE THREAD

**Issue by jchristman** [gilbarbara/react-joyride#73]
@gilbarbara: I have an idea for a syntax that would make this library a bit simpler to use and remove the need to listen to React lifecycle methods at all, following a syntax that is popular for containers these days. I will expound on this below, but **my main question is this: would you like me to do this in a separate package that references this one, or submit a pull request that adds the feature directly to your repo?**

Proposal: Add standard container syntax support that would pass necessary functions as props.

Here is what the container syntax may look like.
```js
import {JoyrideContainer} from 'react-joyride'; // Or another npm module if that is better
import {App} from './App.jsx';

// Make this be either an object or a function that receives props and could make the options dynamic
const options = {
    debug: false,
    type: 'continuous',
    showSkipButton: true,
    showOverlay: true,
    stepCallback: () => null,
    completeCallback: () => null,
    autorun: true
}

export default JoyrideContainer(options)(App);
```

This container will create a single Joyride prop that is passed to the component being contained (App in the above example):
```js
props.Joyride === {
    addStep,
    addTooltip,
    start,
    stop,
    reset
}
```

These could be used in the component like so:
```jsx
// App.jsx
import React from 'react';

// Note that we don't need selector anymore because we are calling the function with the DOM
// element as the first argument
const mainStepOptions = {
    title: 'New API for Joyride',
    text: '<h2 style="margin-bottom: 10px; line-height: 1.6">Now you don\'t need selectors!</h2>Because we are calling the addStep method with a DOM element as an argument!',
    position: 'bottom',
    event: 'hover',
    style: {
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        borderRadius: 0,
        color: '#fff',
        mainColor: '#ff67b4',
        textAlign: 'center',
        width: '29rem'
    }
}

class App extends React.Component {
    componentDidMount() {
        this.props.Joyride.start();
    }

    render() {
        const {props} = this;
        return (
            <div>
                <Header Joyride={props.Joyride}/>
                {
                    props.Joyride.addStep(
                        <div className='main'> 
                            Some stuff goes here in the main section.
                        </div>
                    , mainStepOptions )  // This will return the div with all of the appropriate bindings on it
                }
                <Footer Joyride={props.Joyride}/>
            </div>
        )
    }
}

export default App;
```

Does that API sound like something you're interested in supporting? Or should I just make my own npm module that wraps around yours?

**Comment by gilbarbara** [comment]
hey

How would you pass multiple steps with a container? Or have multiple parallel tours?
I think it is ok using this inheritance for packages like `react-router` or `redux` but what would be the benefits here?

**Comment by gilbarbara** [comment]
@jchristman Let me know if you still want to pursue this path.

cheers
