### ISSUE TITLE
Callback being called twice when leaving step with target:"body", placement:"center"

### ISSUE THREAD

**Issue by wbolduc** [gilbarbara/react-joyride#739]
https://codesandbox.io/s/amazing-fermi-en5xo?file=/src/Tour.js

This is a fork of the demo branch with a simple reproduction.
Notice the inclusion of Tour.js

I'm not totally sure if this has anything todo with this being controlled.

The tour should start automatically and walk you through the bug

The callback being called twice makes it hard to call imperative code during a step and for this usecase I cannot use the functional style for it

**Comment by ZeCarlosCoutinho** [comment]
Not sure if this adds something important or not, but when the first step is `{ target: 'body', placement: 'center' }`, it shows the 1st step straight away, without having to click any beacon before.

Not sure if this is intentional or not, but it was not what I was expecting.

**Comment by ZeCarlosCoutinho** [comment]
When the component is uncontrolled, the callback is called once, as supposed.
However, the beacon still does not show if the 1st step is `{ target: 'body', placement: 'center' }`

**Comment by gilbarbara** [comment]
@ZeCarlosCoutinho 
Sorry for the late reply.

If the target is the `body` and since it occupies the whole page there's no place to add a beacon
