### ISSUE TITLE
Any way to position tooltip in a center.

### ISSUE THREAD

**Issue by Yuripetusko** [gilbarbara/react-joyride#74]
I want to position some tooltips/steps in a center of the screen (like modals). I know tooltips without selector are not allowed, but even if I will put my whole page as selector, I could center it if there was an option like `position: 'center'`

**Comment by gilbarbara** [comment]
I'm not sure if like this. Why not use modals?

**Comment by hew** [comment]
This would actually be nice.

**Comment by IanVS** [comment]
This seems somewhat similar to what I proposed in https://github.com/gilbarbara/react-joyride/issues/199#issuecomment-275158578.

**Comment by hew** [comment]
Would you be willing to accept a pull request for centering? It's weird that you cannot do it currently.
