### ISSUE TITLE
Border is not covering the arrow

### ISSUE THREAD

**Issue by TarekArar** [gilbarbara/react-joyride#748]
## 🐛 Bug Report

I need to apply a border to the tooltip and when I try with custom components the border is only applied to the snippet but not to the arrow.

## To Reproduce

![Screenshot at 2021-10-06 09-11-51](https://user-images.githubusercontent.com/36131347/136165976-f3437867-cb7b-4f56-8065-3728b80f0c1c.png)

## Expected behavior

Border cover arrow too.

**Comment by gilbarbara** [comment]
hey @TarekArar 

The tooltip, including the arrow, is rendered by [react-floater](https://github.com/gilbarbara/react-floater) but there's no support for setting the border in the arrow in it.

**Comment by TarekArar** [comment]
@gilbarbara I think it would be better to add support for border to the arrow.
