### ISSUE TITLE
React joyride breaks antd table horizontal scroll

### ISSUE THREAD

**Issue by josh231101** [gilbarbara/react-joyride#750]
## To Reproduce

1. Create an antd table that exceeds its width and force it to scroll on horizontal view.
2. Add a card from joyride into a column
3. You will see that scroll is not anymore and the table breaks its width,
## Expected behavior
Not breaking the table

### Steps to reproduce
1. Open sandbox live on new tab
2. Shrink tab to see the normal ant-design scroll x behaviour
3. Once the react joyride points to the antd column it'll break

Sandbox: https://codesandbox.io/s/basic-usage-antd-4-17-0-alpha-5-forked-rhgni?file=/index.js

**Comment by josh231101** [comment]
> Anyway, if you search the issues/PRs for this repo you will see that this feature was rejected twice, so I'm not considering a new PR for it.

Wym? The table is breaking its horizontal scroll

**Comment by josh231101** [comment]
**SOLUTION**
Solved using `disableScrollParentFix` as true.
Check -> https://docs.react-joyride.com/props

**Comment by bertyhell** [comment]
For me disableScrollParentFix didn't work

but i found a different workaround, which might be usefull for other people coming across this issue:

Add a callback to joyrider, so you can listen to start and stop events
then add a class to the body: interactive-tour--in-progress
```javascript
		<Joyride
			steps={mapSteps(tour.steps)}
			callback={handleJoyrideCallback}
		>
```

```javascript
	function handleJoyrideCallback(data) {
		if (data.action === 'start') {
			document.body.classList.add('interactive-tour--in-progress');
		}
		if (data.action === 'stop' || data.action === 'close' || data.status === 'finished') {
			document.body.classList.remove('interactive-tour--in-progress');
		}
	}
```

Then you can disable the horizontal scrolling elements in css while the tour is ongoing:
```css
.interactive-tour--in-progress	.c-my-scrolling-component {
	overflow-x: hidden;
	overflow-y: hidden;
}
```

**Comment by arndom** [comment]
For me, the `disableScrollParentFix`  alone didn't work.
The CSS above didn't work as well.

What worked was also `disabling scrolling` and using a `custom scrolling hook`

```jsx
 <Joyride
     // . . . other required and optional props
     disableScrollParentFix
     disableScrolling
  >
```

```jsx
import { useCallback, useEffect } from "react";
import { Step } from "react-joyride";

const useDemoScrollIntoView = (
  steps: Step[],
  stepIndex: number,
  run: boolean
) => {
  const scrollToElement = useCallback((element: Element) => {
    const scrollIntoViewOptions: ScrollIntoViewOptions = {
      behavior: "smooth",
      block: "center",
    };

    element.scrollIntoView(scrollIntoViewOptions);
  }, []);

  useEffect(() => {
    // stepIndex can equal steps.length because its needed to end the demo tour
    // It is a conditional here because there will be no step based on that stepIndex
    if (stepIndex < steps.length && run) {
      const step = steps[stepIndex];
      const selector = step.target as string;
      const element = document.querySelector(selector);

      if (element) {
        scrollToElement(element);
      }
    }
  }, [run, scrollToElement, stepIndex, steps]);
};

export default useDemoScrollIntoView;
```

**Comment by BhandarkarPawan** [comment]
> For me, the `disableScrollParentFix` alone didn't work. The CSS above didn't work as well.
> 
> What worked was also `disabling scrolling` and using a `custom scrolling hook`
> 
> ```js
>  <Joyride
>      // . . . other required and optional props
>      disableScrollParentFix
>      disableScrolling
>   >
> ```
> 
> ```js
> import { useCallback, useEffect } from "react";
> import { Step } from "react-joyride";
> 
> const useDemoScrollIntoView = (
>   steps: Step[],
>   stepIndex: number,
>   run: boolean
> ) => {
>   const scrollToElement = useCallback((element: Element) => {
>     const scrollIntoViewOptions: ScrollIntoViewOptions = {
>       behavior: "smooth",
>       block: "center",
>     };
> 
>     element.scrollIntoView(scrollIntoViewOptions);
>   }, []);
> 
>   useEffect(() => {
>     // stepIndex can equal steps.length because its needed to end the demo tour
>     // It is a conditional here because there will be no step based on that stepIndex
>     if (stepIndex < steps.length && run) {
>       const step = steps[stepIndex];
>       const selector = step.target as string;
>       const element = document.querySelector(selector);
> 
>       if (element) {
>         scrollToElement(element);
>       }
>     }
>   }, [run, scrollToElement, stepIndex, steps]);
> };
> 
> export default useDemoScrollIntoView;
> ```

Awesome! This is exactly what I wanted, worked for me.
