### ISSUE TITLE
Props - hideCloseButton not generic

### ISSUE THREAD

**Issue by cbaum86** [gilbarbara/react-joyride#751]
### Issue
The documentation states that a prop of `hideCloseButton` can be set on the `Joyride` component, however this does not work and can only be implemented on each individual `Step`.

### Expected
I would expect to be able to apply this prop generically to hide the close button on all steps without having to set individually.

### Reproduction

1. Using the library [code sandbox](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo?file=/src/Basic/index.tsx) - the basic will do in this case.
2. Paste the following prop into the Joyride component - `hideCloseButton={true}`

### Screenshot
![Screenshot 2021-10-21 at 08 52 01](https://user-images.githubusercontent.com/11979763/138234836-a00ea47d-d73e-496c-99d5-feeb98b9a7a7.png)

**Comment by hewilliam** [comment]
+1 also disableScrolling prop isn't working on step level too.
