### ISSUE TITLE
_getElementDimensions didn't check the null "el" 

### ISSUE THREAD

**Issue by dreamershl** [gilbarbara/react-joyride#76]
after init the library, I get the following errors when resize the windows 

![image](https://cloud.githubusercontent.com/assets/1271739/16168614/3a60c3a8-3540-11e6-9b20-121d8b68598d.png)

**Comment by gilbarbara** [comment]
Let me know if this got fixed in 1.4.1
[s]

**Comment by dreamershl** [comment]
yes the exception is solved. but got another issue, after activate the tips, (the popup window is shown), if resize the window, the overlay layer won't change the size accordingly. Through the debugger, I find this div width isn't adjusted. not sure the width should be '100%' instead of the fix number. 

    <div class="joyride-hole chrome" style="top: -5px; left: -5px; width: 929px; height: 991px;"></div>

![image](https://cloud.githubusercontent.com/assets/1271739/16565506/39f55b10-4240-11e6-87e3-fe20b9400937.png)
