### ISSUE TITLE
Tour opens drawer component, but can't find target until it mounts. 

### ISSUE THREAD

**Issue by showduhtung** [gilbarbara/react-joyride#763]
## Expected behavior

Expected to be able to run the tour through any component in the application, including unmounted components. Expect to be able to open, for example, a drawer and then append the next step to it. 

Here's a codesandbox to reproduce-
https://codesandbox.io/s/react-joyride-drawer-bug-gk8kf?file=/src/Tour.jsx

I was able to get something by adding a useEffect listening to the drawer open method, but it never appended correctly. A possible solution could be then to add a dependency variable to wait for.

**Comment by gilbarbara** [comment]
hey @showduhtung 

This is not a bug, the standard tour wouldn't wait for elements.
You can use the controlled mode for that. Check out the [examples](https://codesandbox.io/s/github/gilbarbara/react-joyride-demo?file=/src/Controlled/index.tsx)

**Comment by showduhtung** [comment]
I find this a little confusing because the docs references that using stepIndex makes joyride a controlled component:
```
stepIndex {number}
Setting a number here will turn Joyride into controlled mode.
```
And as you can see from the code sandbox example above, it also uses controlled mode. So I'm a little confused at what you mean

**Comment by showduhtung** [comment]
I'm finally figuring out how this controlled thing works, I wish it was a little more clear in the docs that for a controlled unmounted component, you have to stop the run, mount the correct component, and then finally you can attach the step to the component. The examples are great, but the docs don't explain this behavior that well. And I feel like I could still have a misunderstanding somewhere.

**Comment by gilbarbara** [comment]
@showduhtung 
Feel free to update the docs, it's open-source after all! :)

**Comment by showduhtung** [comment]
true true true true true true, fair point. reversed uno'd me to put my money where my mouth's at
