### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by valtism** [gilbarbara/react-joyride#772]
## 🐛 Bug Report

This is coming from the `react-floater` dependency. I can see that that package has been updated https://github.com/gilbarbara/react-floater/issues/83 so we just need to update the dependency here.

**Comment by gilbarbara** [comment]
You can use a polyfill for it...

There are a few breaking changes in the updated react-floater package, so it's not that simple to do it

**Comment by valtism** [comment]
Oh, I never even thought of using a polyfill. That's actually a good idea for now.

**Comment by lisandro52** [comment]
Can you give an example on how to do this?

I'm running an NX project with Typescript, and I can't find a way to define a global `global` variable. I've tried importing a JS file with a `var global`, I've tried the `polyfill.ts` that comes with the project, but that always throws and error that `global` is not defined, even though it's defined on the previous line...

**Comment by sam17896** [comment]
Any plan to update react-floater to integrate breaking change in near future.

**Comment by danyi1212** [comment]
For anyone encountering it using vite, [this solution worked for me](https://github.com/react-simple-code-editor/react-simple-code-editor/issues/86#issuecomment-1450137826)

**Comment by shiranZe** [comment]
Is there a plan to update the `react-floater` dependency to prevent this issue?
