### ISSUE TITLE
Cannot read properties of undefined (reading 'isSameNode')

### ISSUE THREAD

**Issue by tt-anil** [gilbarbara/react-joyride#783]
## 🐛 Bug Report

If you use the controlled mode and the target is found but disappears before the step is completed, the tour crashes with the error message `Cannot read properties of undefined (reading 'isSameNode')`.
As far as I have seen, there is no designated way to prevent this in controlled mode, is there?

## To Reproduce

Open the code sandbox, wait 3 seconds until the target disappears and then try to continue the tour.

## Expected behavior

There should be a way to jump to the next step if the target disappears before the current step is finished.

## Link to repl or repo (highly encouraged)

https://codesandbox.io/s/react-joyride-issamenode-fysy4o?file=/src/index.js

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
  System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 735.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.4.1 - /opt/homebrew/bin/npm
```

**Comment by gilbarbara** [comment]
hey @tt-anil 

You have control of the `steps` so if you need to remove an element, update the steps before removing it.

**Comment by lidorbt-esggo** [comment]
same issue here
I'm using multi-routes tour and once I'm using controlled mode (and sending stepIndex) the tour crashes after changing route (due to elements unmount)

**Comment by enesozturk** [comment]
Hey there, this issue still appears. It can even be reproduced in you CodeSandbox `Multi Router` example: https://codesandbox.io/s/github/gilbarbara/react-joyride-demo?file=/src/MultiRoute/index.tsx

Steps to reproduce:

- Start the tour.
- Go to Route A
- When in Route A, click `Home` on the navbar.

It'll throw the same error.

@gilbarbara. I didn't went deep in the codebase to investigate. Did you have proper solutions or any reason why we get this?

**Comment by enesozturk** [comment]
Edit: Oh I cannot reproduce it now, not good
