### ISSUE TITLE
Event 'step:before' won't fire if the target does not yet exist

### ISSUE THREAD

**Issue by luciddr34m3r** [gilbarbara/react-joyride#784]
## 🐛 Bug Report

I'm building a tour that integrates with react-router-dom that spans multiple pages. In order to navigate between pages, I capture the 'step:before' event, and if it requires a specific route, I load that route in that step. This should allow the DOM to populate with the elements required for the next step. Instead, Joyride fires 'error:target_not_found', preventing me to load the DOM element that has the appropriate target.

## To Reproduce

1. Create a function that makes a DOM element with a specific ID
2. Create a step that references that id
3. Call the function from 1 during the 'step:before' event
4. Notice an error is raised

## Expected behavior

The step:before event should always fire before testing to see if the necessary DOM element has been loaded. This allows controlled Joyride components that rely on dynamic DOM elements to execute that work in the before step.

I think that the validation of the dom element should only be necessary on the tooltip update event.

**Comment by gilbarbara** [comment]
hey @luciddr34m3r 

You could stop the tour, wait for the page to load, and start it again with the next stepIndex when the element is available.

**Comment by luciddr34m3r** [comment]
Seems undesirable. If there is an event that is supposed to fire before the step is processed, isn't that where the preparation for the step should take place?

If you allow the before even to fire without the dom element, it give you an opportunity to do any work necessary. Stopping and restarting the tour would require you to handle a huge number of edge cases. Whereas by allowing the before event to not require the target to exist, you can always do all of the pre-work in the before block.

As it stands, I'm doing route navigation after the previous step with a next action and after the next step if there's a previous action.

It seems that the purpose of the before and after steps are to do prep and cleanup, wouldn't it follow that some of that work might be creating and destroying the target dom element?

**Comment by gilbarbara** [comment]
It's a matter of interpretation...

The `step:before` action checks if the target is present before rendering the beacon/tooltip and it won't wait for the target to be present anyway.

The controlled mode was added exactly for these edge cases.

**Comment by luciddr34m3r** [comment]
I definitely see what you are saying, but wouldn't it be more intuitive to fire the callback with the `step:before` event, check for the presence of the target after the callback completes, and then throw an error if the target doesn't exist at that time?

I get that controlled mode is for these more advanced cases, but this is pretty similar to `componentWillMount` functionality, and I would expect to be able to prepare the DOM when this event fires rather than after the previous step concludes.

**Comment by dcworldwide** [comment]
I also agree, that the user should be able to define a callback, so that the transition between step before and step after does not occur until the step before callback is fired. Allowing for the developer to inject async behaviour (such as route navigation) before the library attempts to attach the step to the DOM.

**Comment by daveidivide** [comment]
I agree, this would seem much more intuative for how it works.

I'm having a bit of a nightmare at the moment creating a custom hook for our UI Library package that uses react-joyride.

Storing the state in context and passing it around is working, but a bit clunky.

Appreciate gilbarbara has built the `run` prop into it, which should work just fine.

But same as everyone else, took me a while to realise that `step:before` isn't an async function where we can await dom elements.
