### ISSUE TITLE
placement property not working.

### ISSUE THREAD

**Issue by billie-lee** [gilbarbara/react-joyride#787]
## 🐛 Bug Report

Hi, I tried using placement property for the steps, but every time i used it it's giving me this error. It says Types of property placement are incompatible.

S2769: No overload matches this call.
  Overload 1 of 2, '(props: Props | Readonly<Props>): ReactJoyride', gave the following error.
    Type '({ title: string; content: Element; locale: { skip: Element; }; target: string; styles: { options: { width: number; }; }; placement: string; position?: undefined; } | { content: Element; ... 5 more ...; placement?: undefined; })[]' is not assignable to type 'Step[]'.
      Type '{ title: string; content: Element; locale: { skip: Element; }; target: string; styles: { options: { width: number; }; }; placement: string; position?: undefined; } | { content: Element; ... 5 more ...; placement?: undefined; }' is not assignable to type 'Step'.
        Type '{ title: string; content: JSX.Element; locale: { skip: JSX.Element; }; target: string; styles: { options: { width: number; }; }; placement: string; position?: undefined; }' is not assignable to type 'Step'.
          Types of property 'placement' are incompatible.
            Type 'string' is not assignable to type '"center" | "auto" | Placement | undefined'.
  Overload 2 of 2, '(props: Props, context: any): ReactJoyride', gave the following error.
    Type '({ title: string; content: Element; locale: { skip: Element; }; target: string; styles: { options: { width: number; }; }; placement: string; position?: undefined; } | { content: Element; ... 5 more ...; placement?: undefined; })[]' is not assignable to type 'Step[]'.

and this is my set up for my steps:

[
    {
      title: "Welcome!",
      content: <h2>Let's begin our journey!</h2>,
      locale: { skip: <strong aria-label="skip">S-K-I-P</strong> },
      target: 'body',
      styles: {
        options: {
          width: 300,
        }
      },
      placement: 'center',
    },
    {
      content: <h2>Sticky elements</h2>,
      target: '.application-list',
    }]

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.20 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    npm: 8.5.5 - /opt/homebrew/bin/npm
  npmPackages:
    react-floater: ^0.8.0 => 0.8.0

**Comment by victorgunta** [comment]
Use it like this:|

placement: 'center' as const,
