### ISSUE TITLE
react-floater use nested-property@1.0.1 in that version 0.7.3 

### ISSUE THREAD

**Issue by AndreyMartinez** [gilbarbara/react-joyride#793]
## 🐛 Bug Report

Right now the nested-property library is used in react-floater in version 0.7.3
as you can see below
```
└─┬ react-joyride@2.4.0
  ├── nested-property@4.0.0
  └─┬ react-float@0.7.3
    └─┬ tree changes@0.5.1
      └── nested-property@1.0.1
```
That dependency has security problems.
in react-floater 0.8.0 this problem is solved by not using the dependency.
It is possible to do an update with this.

## Expected behavior

it's possible update this library. 

thank you soo much

**Comment by gilbarbara** [comment]
Fixed in 2.5.0
Thanks
