### ISSUE TITLE
Tour not scrolling to view the next component

### ISSUE THREAD

**Issue by s-pcode** [gilbarbara/react-joyride#796]
## 🐛 Bug Report

The tour initialization is correct and it works as expected for 1st 3 steps as all the components are in the viewport. But the 4th step is regarding the component which is not visible and here the problem arises that the tour does not scroll the page to bring that component into view. I followed the exact steps mentioned in the docs and also the code is similar to the demo.

## To Reproduce

Steps to reproduce the behaviour:

## Expected behaviour

When the component is not in view the tour should scroll the page to bring that component into view.

## Link to repl or repo (highly encouraged)

https://stackblitz.com/edit/nextjs-m696rr?file=pages/_app.js

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.24 GB / 15.83 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
```

I'm using nextjs and material UI. I'm not able to figure out the issue for 2 days. I went through all the previous issues but yet couldn't figure out anything specifically useful. Urgent help is needed. Thanks 👍

**Comment by gilbarbara** [comment]
The stackblitz example isn't using this library, so I'm closing this

**Comment by s-pcode** [comment]
sorry my bad.
