### ISSUE TITLE
color of arrow

### ISSUE THREAD

**Issue by lorof** [gilbarbara/react-joyride#798]
can't change color of floater arrow

```jsx
<Joyride
  run
  showSkipButton
  continuous
  styles={{
    overlay: {
      background: 'transparent',
    },
  }}
  floaterProps={{
    styles: {
      arrow: {
        color: 'black',
      },
    },
  }}
/>

```

**Comment by NickyTope** [comment]
I also need to change the color of the arrow, the doco here: https://docs.react-joyride.com/styling suggest I should use `options.arrowColor` which doesn't work, neither does the floaterProps approach above...

The pull request above seems to have been closed without merging, can this please be addressed ???

in the meantime, I am using this in css:
```
.__floater .__floater__arrow svg polygon {
  fill: var(--boards-darker-blue) !important;
}
```

**Comment by NickyTope** [comment]
ok, I just found that I was already overriding the arrow color on each step which is why it wasn't working as a prop on the main component `step.styles.options.arrowColor` indeed works fine.
