### ISSUE TITLE
show all beacons at once

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-joyride#8]

**Comment by phun-ky** [comment]
@gilbarbara I am actually in need of this kind of feature, what was the reasoning behind `wontfix` ?

**Comment by gilbarbara** [comment]
If all steps are showing at once, it's not a tour, just a bunch of tooltips...
You can achieve that with [react-tooltips](https://github.com/gilbarbara/react-tooltips)

**Comment by mplungjan** [comment]
But if we only want to load your fabulous tool?

**Comment by gilbarbara** [comment]
@mplungjan 
This will never be added since this module is about sequential tours...
You can achieve the exact same results using multiple tooltips.

**Comment by mplungjan** [comment]
Except the user would not take a tour then
