### ISSUE TITLE
Changing href on skip/next anchors

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#81]
Loving Joyride so far! Question on the tooltip buttons: They use `href="#"` which is a problem in my app's implementation, as our root app is Angular and that takes the user to the homepage of the app. Is there any way to change the `href`?

Also, for semantic reasons, any reason why this are anchor tags and not buttons?

Thanks!

**Comment by stinoga** [comment]
Adding the target attr seems to be a good workaround for the time being. @gilbarbara what do you think?

**Comment by gilbarbara** [comment]
hey.
Sorry, Angular?

Anyway, from [MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/a):
_self: Load the response into the same HTML4 frame (or HTML5 browsing context) as the current one. **This value is the default if the attribute is not specified.**

**Comment by stinoga** [comment]
Yeah, I know. We are porting our Angular app to React. 👷 

As far as `_self` goes, that keeps Angular from hijacking the `#`. You have to add it, even though it's the default value.
