### ISSUE TITLE
Misplaced position of the highlighting if using a mobile device and changing the orientation

### ISSUE THREAD

**Issue by mleister97** [gilbarbara/react-joyride#815]
## 🐛 Bug Report

Misplaced position of the highlighting if using a mobile device and changing the orientation.

## To Reproduce

Please checkout your official website https://react-joyride.com/
Highlighting step 2 is not working as expected on an iPad (iPad Air (4. Generation), iOS 14.4.1) after chaning the orientation of the device

## Video

https://user-images.githubusercontent.com/16700053/175545514-1705ec21-7ae7-4635-9e8e-ec647e0b3657.mp4

**Comment by gilbarbara** [comment]
hey @mleister97 

Couldn't replicate this behavior with Browserstack. The spotlight re-arranged itself to the correct position after rotating.

Feel free to submit a PR.

**Comment by mleister97** [comment]
Have you tried using the same iPad as mentioned in the description?

**Comment by krishgt60** [comment]
Even we are facing the same issue, so please can someone help me out with this, its bit urgent 

Thank you

**Comment by gilbarbara** [comment]
If someone else faces this problem, one could get the popper instance and update the position manually.

```tsx
function App() {
	const updatePosition = useRef<(() => void) | null>(null);

	return (
		<Joyride
	        floaterProps={{
	          getPopper: (popper, type) => {
	            if (type === 'floater') {
	              updatePosition.current = popper.instance.update;
	            }
	          },
	        }}
		/>
	);
}
```
