### ISSUE TITLE
Flickering when scrolling on iPad

### ISSUE THREAD

**Issue by mleister97** [gilbarbara/react-joyride#816]
## 🐛 Bug Report

Scrolling on page end on an iPad causes flickering

## To Reproduce

Please checkout your official website https://react-joyride.com/
Scrolling on page end on an iPad (iPad Air (4. Generation), iOS 14.4.1) causes flickering

## Video

https://user-images.githubusercontent.com/16700053/175561059-603b5867-5662-45f1-99ff-4478d973a6c6.mp4

**Comment by gilbarbara** [comment]
hey @mleister97 

Not sure how can this be "fixed"...
Feel free to submit a PR

**Comment by mleister97** [comment]
Also tried on an older iPad, did not experience the issue there (iPad Air iOS 12.4.8)
