### ISSUE TITLE
Cannot read properties of null (reading 'isConnected') in react-floater

### ISSUE THREAD

**Issue by johnhunter** [gilbarbara/react-joyride#829]
### Discussed in https://github.com/gilbarbara/react-joyride/discussions/820

<div type='discussions-op-text'>

<sup>Originally posted by **johnhunter** July 13, 2022</sup>

I'm seeing an occasional exception Cannot read properties of null (reading 'isConnected')

```
if (!this.floaterRef.isConnected) {
```
https://github.com/gilbarbara/react-floater/blob/v0.7.5/src/components/index.js#L274

I've been unable to reproduce but it is reported in my production environment.

</div>

**Comment by gilbarbara** [comment]
Fixed in 2.5.1
Thanks
