### ISSUE TITLE
peer dependencies

### ISSUE THREAD

**Issue by OleksiiKachan** [gilbarbara/react-joyride#835]
## 🐛 Bug Report

`prop-types` should not be a peer dependency. I don't use prop types in my project, but I do use `react-joyride`. Since `prop-types` is a peer dependency, I always get warning (for both joyride and floater btw) `has unmeet peer dependency`. You already have `prop-types` in dev dependencies. what is the reason of it being in peer dependencies?

## To Reproduce

have react project without `prop-types` and install `react-joyride`

## Expected behavior

Should install without unmet peer dependencies warning

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 35.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
  npmPackages:
    react-joyride: ^2.5.0 => 2.5.0 
```

**Comment by gilbarbara** [comment]
Updated in a2098985817a80e0818c9e7f3eff1bab417efd2b
