### ISSUE TITLE
_getElementDimensions called before position class is added

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#85]
I noticed that `_getElementDimensions` includes margins in it's calculation. This is good, however when the function runs it returns the incorrect position class. This causes issues if you have separate margins set for each position class.

I assume this is some sort of race case between setting the position class and `_getElementDimensions` being called.

This seems to happen differently at different browser widths.

**Comment by gilbarbara** [comment]
hey @stinoga 
Did it get fixed in the last version?

**Comment by gilbarbara** [comment]
fixed cdc8f7b67eb2e7e2f6174269e05fde5f006674de
