### ISSUE TITLE
Spotlight is not rendering properly

### ISSUE THREAD

**Issue by Lokprakash-babu** [gilbarbara/react-joyride#851]
## 🐛 Bug Report

If the background color of the body is not set to white explicitly, spot light is not being rendered. 

## To Reproduce

- Create a basic react app
- Install react joyride
- Configure React joyride for walkthrough

## Expected behavior

Spotlight should be displayed properly irrespective of the background color in the DOM. 

## Link to repl or repo

[codesandbox link](https://codesandbox.io/s/musing-edison-iy0mfq?file=/src/index.js)

Without bg color
```https://user-images.githubusercontent.com/60031382/193742722-ccb634bb-203a-4538-be2c-2db5d560d5b1.png```

With bg color
```https://user-images.githubusercontent.com/60031382/193742926-318e731a-b342-49d0-ac30-084250eb0825.png">```

**Comment by gilbarbara** [comment]
Hey @Lokprakash-babu 

This limitation has already been discussed in #411

It is the expected behavior since `mix-blend-mode` expects a background to work.
https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode

**Comment by Lokprakash-babu** [comment]
Hey @gilbarbara 
Can we capture this limitation somewhere in the doc, please? If it isn't done already. I am happy to raise a PR.
