### ISSUE TITLE
In chrome (mobile), user has to touch twice to press what's behind the overlay during spotlight

### ISSUE THREAD

**Issue by boompikachu** [gilbarbara/react-joyride#855]
## 🐛 Bug Report

When spotlight is active, the overlay will have a style `pointer-event: auto`; however, this will change to `pointer-event: none` when mouse is hovering the spotlight area. As for mobile, since there's no hovering, user has to press twice, one to hover on the spotlight and the other to click on the element. 

Note that iPhone Safari works

## To Reproduce
See https://codesandbox.io/s/github/gilbarbara/react-joyride-demo in controlled tab. 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/37561295/196588932-147772c2-3c9d-4960-9187-5fb0af2dc7dc.png">

Try clicking on the menu tab on the top left corner.

## Expected behavior

User should be able to press on the element once to trigger its action

## Link to repl or repo (highly encouraged)

See to reproduce section

**Comment by NedelevPhilip** [comment]
Have the same problem

**Comment by gilbarbara** [comment]
This is working as expected now. They probably fixed it.
Tested on Safari and Chrome mobile on an iPhone.
