### ISSUE TITLE
Using floaterProps.getPopper stops lifecycle events from triggering

### ISSUE THREAD

**Issue by a1994lex** [gilbarbara/react-joyride#875]
## 🐛 Bug Report

I am trying to use the `getPopper` attribute in `floaterProps` to determine the final placement of my tooltip as determined by `popperjs/@core`. When I provide the `getPopper` attribute in `floaterProps` for react-joyride, each step in my tour closes after the `next` button is clicked. It looks like the lifecycle events are not getting updated. 

## To Reproduce
Add the `getPopper` prop to the `Joyride` component: `<Joyride floaterProps={{ getPopper: () => {} }} ... />`

## Expected behavior
When advancing to the next step, the tour automatically opens the next tooltip, 
## Actual behavior 
With the prop `getPopper` added, the next tooltip does not open automatically when advancing to the next step.

## Link to code sandbox

https://codesandbox.io/s/affectionate-greider-3lhotn?from-embed

**Comment by gilbarbara** [comment]
Fixed in 2.7.2
Thanks
