### ISSUE TITLE
beaconComponent has the wrong type definition

### ISSUE THREAD

**Issue by dolanmiu** [gilbarbara/react-joyride#876]
## To Reproduce

1. Follow https://docs.react-joyride.com/custom-components to create a custom beacon (regular React component)
2. My custom beacon:
    ```tsx
    const CustomBeacon = (props) => {
        console.log(props);
        return (
            <div>Custom Beacon</div>
        );
    };

3. `Console` Output:
     ```ts
    {
        "aria-label": "Open the dialog",
        "title": "Open the dialog",
        "onClick": [Function],
        "onMouseOver": [Function]
    }
    ```
    ![Screenshot 2022-12-20 at 16 36 58](https://user-images.githubusercontent.com/2917613/208718538-40781e8c-be12-4bef-a7aa-f41cb3477b0a.png)

4. However, type definitions `BeaconRenderProps` is of:
    ```ts
    export interface BeaconRenderProps {
      continuous: boolean;
      index: number;
      isLastStep: boolean;
      setTooltipRef: () => void;
      size: number;
      step: Step;
    }
    ```
    https://github.com/gilbarbara/react-joyride/blob/main/types/index.d.ts#L112-L119
5. Types are wrong

## Expected behavior

I expect the types to be correct

**Comment by Davidjayan** [comment]
The issue doesn't seems to be fixed. Please reopen this issue. Still the types are incorrect in V2.9.2

**Comment by gilbarbara** [comment]
Hey @Davidjayan 

What's the error you're getting?
Which version of React/TypeScript?
