### ISSUE TITLE
Translation of next button when showStepsProgress is on (react-intl)

### ISSUE THREAD

**Issue by benzen** [gilbarbara/react-joyride#88]
For all the buttons in the tour message we can use react "FormattedMessage" to give a translated message instead of the default one. This is really great.

But because of the way the stepsProgress is appended to the "next" message, we can't use FormattedMessage for this button.

Their is a way to get arround this in react-intl but it's cubbersome to use. And on this lib, the change should be tiny.

Here is the part that need to change:
https://github.com/gilbarbara/react-joyride/blob/master/lib/scripts/Component.js#L681-L687

Instead of appending the progress, you should add it on an other element inside the button, this will keep the same api for everyone .

Atm we get this
![capture d ecran 2016-07-03 a 09 40 01](https://cloud.githubusercontent.com/assets/139909/16545736/28ebb3c6-4102-11e6-8f7f-3d751e8a4423.png)

Here is the way, I've builded my translations:
````jsx
const locale = {
  back: <FormattedMessage id='Back' defaultMessage="Back"/>, 
  close: <FormattedMessage id="Close" defaultMessage="Close"/>, 
  last: <FormattedMessage id="Last" defaultMessage="Last"/>, 
  next: <FormattedMessage id="Next" defaultMessage="Next"/>, 
  skip: <formattedMessage id="Skip" defaultMessage="Skip"/>,
}
````

Hope this will help

**Comment by gilbarbara** [comment]
Let me know if 493ec536ad0246f448b6507f7fe4197caba09c66 fixed.
It's on 1.4.1

**Comment by benzen** [comment]
Just made the update, the printed message is still the same

**Comment by gilbarbara** [comment]
Done! 1.4.2 coming soon.

**Comment by benzen** [comment]
Super nice!!  Thanks
