### ISSUE TITLE
(Safari): Fullscreen of iframe in the ReactJoyride dialog issue

### ISSUE THREAD

**Issue by dualisimo** [gilbarbara/react-joyride#887]
## 🐛 Bug Report

When it is placed iframe (f.e. vimeo) within RJR dialog and this iframe has the fullscreen option, after opening video in the fullscreen mode it is not visible on the screen.

## To Reproduce

1. Place iframe with video and fullscreen option enabled to the RJR dialog. 
2. Open safari and play this video  
3. Open video in the fullscreen mode

## Expected behavior

Usual view as in Chrome or FireFox.

**Comment by gilbarbara** [comment]
Hey @dualisimo 

Please provide a codesandbox minimal reproducible link

**Comment by dualisimo** [comment]
Unfortunately, Code sandbox is blocking fullscreen option in the iframes. (╯°□°)╯︵ ┻━┻

**Comment by gilbarbara** [comment]
Try opening the preview in a new window.
But I need some clarification. When the tooltip loads, would you like the video to render fullscreen, hiding the tooltip itself?

**Comment by dualisimo** [comment]
OMG, its shame, I didnt know about new window option. It works! Thank you.

[Here](https://codesandbox.io/s/boring-chihiro-z34y8b) is a code sandbox link and please:

1. open it in Safari and in the new window mode.
2. open RJR demo by clicking on Start button
3. play video and open it in the full screen mode

you should see the issue then :)

Thanks

**Comment by gilbarbara** [comment]
The full screen is not working on Chrome/Firefox/Safari for that codesandbox. It display some errors about sandbox environment. 

But anyway, this is something this library has no control and it doesn't have any specific code for browser vendors, so if the video isn't working in Safari, probably is a bug with the browser itself.

Good luck!

**Comment by dualisimo** [comment]
I can't agree. Full-screen video mode works on a safari within an iframe in all ways which I tried except RJR dialog. So for this bug is 100% responsible RJR package.

**Comment by gilbarbara** [comment]
Ok.
Feel free to submit a PR. This library is open-source, after all.
