### ISSUE TITLE
continuous make next tooltip position weirdly  

### ISSUE THREAD

**Issue by jt6677** [gilbarbara/react-joyride#889]
## 🐛 Bug Report
"react": "^18.2.0",
"react-joyride": "^2.5.3",

<Joyride continuous/> with continuous, the next will fail to lock on the element. The window would appear on the bottom. If continuous is disabled, the next will lock on the element properly. 

#Get round:

  setState({  run: false,})
   setTimeout(() => { setState({  run: true, })  }, 100)
      setState({ stepIndex: index + 1 })

turn the run off then on then go to the next, this will somehow make it lock on properly.

**Comment by gilbarbara** [comment]
@jt6677 

Please provide a https://codesandbox.io/ demo or similar with a minimal reproducible example.
