### ISSUE TITLE
Beacon does not stick to Component when scrolling up and down

### ISSUE THREAD

**Issue by djleon2001** [gilbarbara/react-joyride#89]
Great job with these library.

I have a problem with vertical scroll, Beacon should stay and scroll (move) with the element to which they are appended. 

Beacons seem to use absolute position , so, if you move the scroll up and down or resize the window (changing the size of the vertical scroll ) they beacon does not position itself in the correct relative vertical position, it is actually  positioned besides another component, I think it could be good the position to be either relative to the component  or recalculated.

**Comment by gilbarbara** [comment]
which version? Try 1.4.4

**Comment by djleon2001** [comment]
I am using v1.4.4

**Comment by gilbarbara** [comment]
Does the demo works as expect?
Do you have a public example?

**Comment by djleon2001** [comment]
The demo works correctly, I did not notice that before.

I am using Foundation's Grid for my layout.  I believe is something from my side, I will do some more research and post my findings here. Thank you.

**Comment by djleon2001** [comment]
A temporary solution in my case is the following :
`<body style="transform: translateY(0px) !important;">`

I will investigate to find the root cause of this problem in my environment  and post my findings here. Thank you.

**Comment by gilbarbara** [comment]
I don't the grid would break the viewport arrangement but I never tested with it.
Let me know if you find anything else!

cheers
