### ISSUE TITLE
"Cannot find module" error

### ISSUE THREAD

**Issue by nickbae91** [gilbarbara/react-joyride#90]
Hi,

So I just upgraded from 1.3.6 to 1.4.4 and am getting this error:

Error: Cannot find module 'core-decorators/lib/autobind' from 'C:\Users\user\Documents\GitHub\SagePath\node_modules\react-joyride\lib\scripts'

I changed the implementation of the code to replace the deprecations for the callbacks to the new methodology, and still this shows up. It worked perfectly fine before the update. Any guesses as to why this is occurring?

**Comment by Keats** [comment]
We have the same issue, could it some node 5 thing? I noticed it was the requirement in `package.json` and we are on node4

**Comment by gilbarbara** [comment]
I'll take a look tonight.

**Comment by ConstantineShkel** [comment]
Same issue with node 6

**Comment by gilbarbara** [comment]
I was loading it in the devDependencies.. But I changed it to a simpler module anyway. fixed in 1.4.5
Sorry!
