### ISSUE TITLE
Warning message about outdated popper.js dependency

### ISSUE THREAD

**Issue by dimassibassem** [gilbarbara/react-joyride#901]
## Description 
I am seeing a warning message in my React application when using the "react-joyride" package. The warning message is as follows:

```bash
warning react-joyride > react-floater > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
```

I am already using the latest version of "react-joyride" 2.5.3, but the warning message still appears. From my understanding, this is because "react-joyride" depends on an outdated version of "popper.js" (v1.16.1), which is no longer maintained.

Is there a plan to update the dependency on "popper.js" to use "@popperjs/core" instead? If so, when can we expect this change to be made? If not, what other steps can I take to resolve this issue?

Thank you for your help in resolving this issue. Let me know if you need any additional information.

## Environment:

```bash
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 772.72 MB / 15.86 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react-joyride: ^2.5.3 => 2.5.3

```

**Comment by gilbarbara** [comment]
Hey @dimassibassem 

This is just a warning and doesn't impact the library's functionality.
