### ISSUE TITLE
steps field is giving error in react-joyride

### ISSUE THREAD

**Issue by Sahani18** [gilbarbara/react-joyride#910]
The expected type comes from property 'steps' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReactJoyride> & Readonly<Props> & Readonly<{ children?: ReactNode; }>'

**Comment by gilbarbara** [comment]
Hey @Sahani18 

> Issues without a reproduction link are likely to stall.

Can you provide a codesandbox with an example?

**Comment by Sahani18** [comment]
https://codeshare.io/YLQeYE

There is a red swigly line under steps but things are working properly. I'm afraid it may break in production

**Comment by gilbarbara** [comment]
You are using `top-left` as a placement for a step, but that's not valid.
Check the [docs](https://docs.react-joyride.com/step) for the available options

**Comment by Sahani18** [comment]
Fixed that but still same issue 

<img width="551" alt="Screenshot (238)" src="https://github.com/gilbarbara/react-joyride/assets/72247207/b195fb20-edb5-4fba-9b9b-211f5c1d2e60">

**Comment by gilbarbara** [comment]
You need to type your steps...
Import the `Step` from this package, and set your step variable.

`const step: Array<Step> = ...`

Anyway, this was never a problem with the library. but misconfigured TS code. Closing it.
