### ISSUE TITLE
This bit of code does not adhere to the "disabledScroll" false flag:

### ISSUE THREAD

**Issue by dweng0** [gilbarbara/react-joyride#913]
## 🐛 Bug Report

For the life of me, i was trying to work out how my parent container, (with overlfow auto set) was not scrolling, then i noticed this little nugget being injected into the element:
![image](https://github.com/gilbarbara/react-joyride/assets/5268627/a3ddf8b5-19e7-4356-b65c-76bd72f0eba3)
My code doesn't set that anywhere, so i did a search in the react-joyride code base and found it [here](https://github.com/gilbarbara/react-joyride/blob/e69620a3c56bf26f34e5c81fcecde921395cce64/src/modules/dom.js#L99)

## To Reproduce
Looking at the code, all you need to do is have a parent with scroll, the [code](https://github.com/gilbarbara/react-joyride/blob/e69620a3c56bf26f34e5c81fcecde921395cce64/src/modules/dom.js#L99) 
``` typescript
   parent.style.overflow = 'initial';
```
Will override it to its initial values

## Expected behavior

The disableScroll flag in the joyride config should update this so it doesn't inject initial values, unless this is being done to prevent/fix another issue.

**Comment by gilbarbara** [comment]
Hey @dweng0 

> Please provide a https://codesandbox.io/ demo or similar.
> Issues without a reproduction link are likely to stall.
