### ISSUE TITLE
Popper renders before scrolling starts, messes up arrow placement, is there an event that fires after scrolling ect has finished?

### ISSUE THREAD

**Issue by dweng0** [gilbarbara/react-joyride#915]
## 🐛 Bug Report
Hi all, title says it all really, the scroll to item funcitonality seems to happen during/after the popper has rendered, meaning that the logic for arrow placement occurs before its correctly placed. 

My question is, is there an "after scroll" event or something similar that can be used to render the popper component? (or have it wait until the event has triggered? See video example).

[Screencast from 13-06-23 11:32:29.webm](https://github.com/gilbarbara/react-joyride/assets/5268627/5ec09881-6f63-432b-85fa-5d21cd356132)

**Comment by gilbarbara** [comment]
Hey @dweng0 

It's hard to know what is happening in your app without being able to test it.
Does the `body` fill the whole scroll height? Try adding `min-height: 100vh` to it. Or set the `disableScrollParentFix` prop.

If it still isn't working: 

> Please provide a https://codesandbox.io/ demo or similar.
> Issues without a reproduction link are likely to stall.
