### ISSUE TITLE
IE10 Out of stack space issue

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#93]
With the upgrade to the latest version, I'm getting an "Out of stack space" error in IE10. This breaks the page, and you can see it on the demo page in IE10:

http://gilbarbara.github.io/react-joyride/

**Comment by gilbarbara** [comment]
I hate IE! :)
Fixed in 1.4.6 with a few other IE improvements.

**Comment by stinoga** [comment]
@gilbarbara Thanks!!!
