### ISSUE TITLE
Beacon is showing above the other component as showing in the picture

### ISSUE THREAD

**Issue by zaid-ahmed-shark** [gilbarbara/react-joyride#935]
## 🐛 Bug Report

Beacon is showing above the other component as showing in the picture

## To Reproduce
<img width="1912" alt="Screenshot 2023-08-25 at 5 20 15 PM" src="https://github.com/gilbarbara/react-joyride/assets/72867253/90265fab-0cfc-4570-a987-dbe09c0cf349">

## Expected behavior
When scrolling the beacon component comes above html element.

## Link to repl or repo (highly encouraged)

Please provide a https://codesandbox.io/ demo or similar.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash

```

**Comment by gilbarbara** [comment]
Hey @zaid-ahmed-shark 

That's the expected behavior in the demo. If you want the "fixed" element to show above the beacon, just change the z-index to be higher than the beacon...
