### ISSUE TITLE
upgrade to react-floater 0.8.2

### ISSUE THREAD

**Issue by sam-mfb** [gilbarbara/react-joyride#937]
## 🐛 Bug Report

Package depends on react-floater 0.7.6 which relies on a deprecated version of popper (1.x.x)

This would be fixed by upgrading to the latest version of react-floater, which is 0.8.2 and users popper 2

**Comment by gilbarbara** [comment]
Hey @sam-mfb 

The react-popper@0.8.x isn't compatible with this library yet. And popper v2 is already deprecated...
Anyway, deprecated versions aren't bugs.
