### ISSUE TITLE
`callback` is trigged with `type: finished` on initial `start()`

### ISSUE THREAD

**Issue by kodell** [gilbarbara/react-joyride#94]
When calling `refs.joyride.start()` with a `callback` prop set, the callback function is invoked immediately with a `{type: 'finished'}` object.

This seems to be caused by `toggleToolTip` being called with an undefined `index` in `start()`. When `this.props.steps[index]` is [checked later](https://github.com/gilbarbara/react-joyride/blob/master/src/scripts/Joyride.jsx#L551) it is always falsey, causing a "finished" type to be sent immediately.

**Comment by gilbarbara** [comment]
You have this setup in the demo..
Are you passing a boolean to `start`? Do you have steps set when calling it?

**Comment by brikou** [comment]
I'm having the exact same issue. @kodell Did you find any solution?
