### ISSUE TITLE
Global is not defined

### ISSUE THREAD

**Issue by shiranZe** [gilbarbara/react-joyride#940]
## 🐛 Bug Report

Hello,
I've been using the react-joyride library in my project, and it relies on the `react-floater` package, which uses the `global` object. However, my project is using Vite, which doesn't define a `global` obkect in the window (unlike Webpack), this leads to this error:`(uncaught exception)ReferenceError: global is not defined`. To address this issue, I've had to enable certain [polyfills](https://github.com/react-simple-code-editor/react-simple-code-editor/issues/86#issuecomment-1450137826), but these have caused build failures.

I've noticed that there's an [update](https://github.com/gilbarbara/react-floater/issues/83) available for the react-floater package. Would it be possible to update the dependacy version? Such an update would elp ensure compatibility with Vite projects.

**Comment by gilbarbara** [comment]
Hey @shiranZe 

The react-floater 0.8.x isn't compatible with react-joyride yet.
Defining `global` shouldn't break the build. What errors are you getting?

**Comment by gilbarbara** [comment]
Duplicate #772

**Comment by BennyAlex** [comment]
@gilbarbara 
Please reopen this. The libary uses a global variable, that is not defined in every environment, so it should be using a fallback here.
Can you please check it again?

I cant use joyride with vite. It will break. Even with the 'fix' from the other comments, the build will fail then.

**Comment by gilbarbara** [comment]
@BennyAlex Fixed in 2.7.1
