### ISSUE TITLE
Skip buttons option is not honored

### ISSUE THREAD

**Issue by benzen** [gilbarbara/react-joyride#95]
Is here my config for the tour:
 
      <Joyride 
        ref={(c)=> this.joyride = c}
        locale={locale}
        steps={tourSteps}
        type="continuous"
        showStepsProgress={true}
        showSkipButton={true}
        callback={onTourEnd}
        />

I don't have the skip button visible. Is this due to my particular combination of buttons ?

**Comment by benzen** [comment]
If the field locale.skipButton is a React element (eg <FormattedMessage>), it won't be shown.

**Comment by gilbarbara** [comment]
how many steps? I disabled the skip button in the last step (or single step) since it will end the tour when closed anyway.

**Comment by gilbarbara** [comment]
I've reverted that modification. Try 1.4.6

**Comment by benzen** [comment]
Just for the record, it's a 6 steps tour.

**Comment by benzen** [comment]
Still the same behavior with 1.4.6

**Comment by gilbarbara** [comment]
humm, do you a public demo? Not much I could to without seeing some code

**Comment by benzen** [comment]
Sure here is my locales definitions:

````
const locale = {
  back: <FormattedMessage id='Back' defaultMessage="Back"/>, 
  close: <FormattedMessage id="Close" defaultMessage="Close"/>, 
  last: <FormattedMessage id="Last" defaultMessage="Last"/>, 
  next: <FormattedMessage id="Next" defaultMessage="Next"/>, 
  skip: <formattedMessage id="Skip" defaultMessage="Skip"/>,
}
`````

 And the tour is configured just as decribed at the top.
It's react-intl formattedMessage

**Comment by gilbarbara** [comment]
The rest of the buttons are working? Why only the skip's formattedMessage is in lowercase?
Does it print anything if you add it directly to your component?

**Comment by benzen** [comment]
Ohh you're right, thanks
Now react doesn't warn if you use an unkown html component or attribute.
If the first letter is lowercase, than it assume it's a html element, without warning.

**Comment by gilbarbara** [comment]
humpf..
ESLint is your friend.
