### ISSUE TITLE
Unsafe call to 'getBoundingClientRect' 

### ISSUE THREAD

**Issue by benzen** [gilbarbara/react-joyride#96]
If i start a tour with targets that are not always present, react-joyride will produce:

    TypeError: Cannot read property 'getBoundingClientRect' of null

Which can be prevented by checking for safe navigation

**Comment by gilbarbara** [comment]
from the readme: `Only start the tour after all target elements (or at least the first step) are rendered in the page.`
Anyway, feel free to submit a PR.

**Comment by gilbarbara** [comment]
Hey,
Fixed in cdc8f7b67eb2e7e2f6174269e05fde5f006674de
