### ISSUE TITLE
error TS2309: An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by vsbharath** [gilbarbara/react-joyride#978]
## 🐛 Bug Report

After Upgrading to latest react and react-joyride. Seeing issues while tunning yarn tsc 

node_modules/react-joyride/dist/index.d.ts:295:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

295 export = Joyride

## To Reproduce

Upgrade React to latest

**Comment by vsbharath** [comment]
Using    
 "@types/react": "^18.2.42",
    "@types/react-dom": "^18.2.17"

**Comment by vsbharath** [comment]
@gilbarbara Can you please help here ?

**Comment by gilbarbara** [comment]
Hey @vsbharath 

> Please provide a https://codesandbox.io/ demo or similar.
Issues without a reproduction link are likely to stall.

**Comment by vsbharath** [comment]
here are the version that I'm using 
"react-joyride": "2.7.0",
"react": "18.2.0",

Even upgrading to latest 2.7.0 running tsc is failing for react-joyride

**Comment by vsbharath** [comment]
Is see in react-joyride/dist/index.d.ts

two exports with the same file 

and Joyride as decalred as default and not sure why it is generated another export = JoyRide at the end of the file. After removing this line from node_modules it worked. Can you please help how this file is generated?

**Comment by matthiasschwarz** [comment]
I have the same issue when using versions above 2.5.5. 
I downgraded the library to version 2.5.5 and the build error was gone.

**Comment by matthiasschwarz** [comment]
After some investigation i found out that the issue comes from using fix-tsup-cjs in the build process which creates the duplicate export.
Is the use of fix-tsup-cjs necessary?

**Comment by gilbarbara** [comment]
Does setting "skipLibCheck" to true in your tsconfig fixes the problem?

**Comment by vsbharath** [comment]
No, skipLibCheck is not fixing the problem as the library it is being
called from other files that are included under tsc config.
If I just remove the duplicate line generated from the generated file. it
works.


Thanks,
Bharath Chadarajupalli



<https://smart.salesforce.com/sig/vchadarajupalli//us_mb/default/link.html>

**Comment by gilbarbara** [comment]
Weird.
Anyway, I already have a fix for this in #979 
Just fixing some scroll issues and I'll merge it soon.

**Comment by gilbarbara** [comment]
@vsbharath @matthiasschwarz 
Can you try this version and report back?
`npm i react-joyride@next`

Thanks

**Comment by matthiasschwarz** [comment]
Issue is resolved for me with version 2.7.2.
Thanks
