### ISSUE TITLE
'use strict' directive throwing readonly errors in tests

### ISSUE THREAD

**Issue by ryanseddon** [gilbarbara/react-joyride#98]
We have a test that stubs `component.refs.joyride.reset` this worked fine in 1.3.6 but from 1.4.4 when you switched to ES6 it adds 'use strict' which fails the tests due to making them readonly.

**Comment by gilbarbara** [comment]
I don't have control on the transpiling process since it uses babel like so many libraries.
Maybe you could mock the component differently?
Anyway I can't help much in this situation..
