### ISSUE TITLE
RangeError: Maximum call stack size exceeded after build using the vite bundler

### ISSUE THREAD

**Issue by quarterpound** [gilbarbara/react-joyride#981]
## 🐛 Bug Report

RangeError: Maximum call stack size exceeded after build using the vite bundler

## To Reproduce

Build Vite app with React Joyride and there will be an error on production

## Expected behavior

There should not be an error in production

## Link to repl or repo (highly encouraged)

The issue only happens after building 

## Run `npx envinfo --system --binaries --npmPackages react-joyride`

Paste the results here:

```bash


  System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M2
    Memory: 123.39 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.8.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  npmPackages:
    react-joyride: ^2.7.0 => 2.7.0 


```

Full error:

```
RangeError: Maximum call stack size exceeded
    at ba (index-4c91e0f5.js:2381:146765)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
    at ba (index-4c91e0f5.js:2381:147525)
```

**Comment by gilbarbara** [comment]
I just built and ran the demo app without any problems...

**Comment by aliteqqed** [comment]
I am having the same issue when building on vite

**Comment by gilbarbara** [comment]
Hey @aliteqqed 
Can you provide a minimal reproducible example? Stackblitz or a repo.

**Comment by iantrudell** [comment]
Minimal Reproducible Example: https://codesandbox.io/p/devbox/still-microservice-krd9zm?workspaceId=ws_MPs8vpSjS29og7c1MNtz6i
