### ISSUE TITLE
Version 1.4.6 breaks server-side rendering

### ISSUE THREAD

**Issue by emilecantin** [gilbarbara/react-joyride#99]
I use react-joyride in a project with server-side rendering, and, while I don't actually call any react-joyride code on the server, it still gets `import`ed.

Version 1.4.6 (more specifically, commit 9640e193) breaks server-side rendering because lib/scripts/utils.js executes code referencing `window` when `import`ed.

Would it be possible to move these inside a function, or at least make sure they only execute valid server-side code when `import`ed?

**Comment by gilbarbara** [comment]
I fixed that in 03011fa403595758d65a6cd48a00c1ecc3d0a58b
Try 1.4.7 please
