### ISSUE TITLE
Tooltip doesn't show up if there is no step with target: "body"

### ISSUE THREAD

**Issue by DaanyWaay** [gilbarbara/react-joyride#990]
Simply go to the official demo page: https://codesandbox.io/s/github/gilbarbara/react-joyride-demo/tree/main
and remove the first step with target: "body".
Now when you click the Start button the tooltip has visibility set to none and opacity set to 0.

**Comment by gilbarbara** [comment]
Hey @DaanyWaay 

It shows the red pulsating beacon instead. You can click it to open the tooltip or set `disableBeacon` on the step...
